### ISSUE TITLE
Request textDocument/semanticTokens/full/etc. failed 

### ISSUE THREAD

**Issue by 497e0bdf29873** [rust-lang/rust-analyzer#12663] opened 2022-07-01 08:54 UTC
Similar to https://github.com/rust-lang/rust-analyzer/issues/12236, the constant crashes are back. 

```
thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/chalk-ir-0.82.0/src/lib.rs:1447:27
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::impls_for_trait
   4: chalk_solve::clauses::push_program_clauses_for_associated_type_values_in_impls_of
   5: chalk_recursive::solve::SolveIteration::solve_iteration
   6: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
   7: chalk_recursive::fulfill::Fulfill<I,Solver>::prove
   8: chalk_recursive::fulfill::Fulfill<I,Solver>::solve
   9: chalk_recursive::solve::SolveIteration::solve_iteration
  10: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  11: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  12: <hir_ty::db::TraitSolveQueryQuery as salsa::plumbing::QueryFunction>::execute
  13: salsa::runtime::Runtime::execute_query_implementation
  14: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  17: salsa::QueryTable<Q>::get
  18: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  19: hir_ty::db::trait_solve_wait
  20: <DB as hir_ty::db::HirDatabase>::trait_solve
  21: hir_ty::infer::unify::InferenceTable::register_obligation_in_env
  22: hir_ty::infer::unify::InferenceTable::normalize_projection_ty
  23: <hir_ty::fold_tys_and_consts::TyFolder<F> as chalk_ir::fold::Folder<hir_ty::interner::Interner>>::fold_ty
  24: hir_ty::infer::InferenceContext::make_ty_with_mode
  25: hir_ty::infer::infer_query
  26: salsa::runtime::Runtime::execute_query_implementation
  27: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  28: salsa::derived::slot::Slot<Q,MP>::read
  29: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  30: salsa::QueryTable<Q>::get
  31: <DB as hir_ty::db::HirDatabase>::infer_query
  32: hir_ty::db::infer_wait
  33: hir::DefWithBody::diagnostics
  34: hir::Module::diagnostics
  35: ide_diagnostics::diagnostics
  36: std::panicking::try
  37: ide::Analysis::assists_with_fixes
  38: rust_analyzer::handlers::handle_code_action
  39: std::panicking::try
  40: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)

rust-analyzer version: 0.0.0 (b74e96f50 2022-06-26)

**rustc version**: (eg. output of `rustc -V`)

rustc 1.64.0-nightly (7425fb293 2022-06-30)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

**Comment by lnicola** [comment] 2022-07-01 08:57
Are you using GATs? Probably a dupe of #12193.

**Comment by lnicola** [comment] 2022-07-01 09:08
My guess is they're related. But we can leave this open until #12193 gets fixed.

**Comment by Veykril** [comment] 2023-02-08 12:22
This should be fixed

**Closed by Veykril** 2023-02-08 12:22 UTC
Labels: A-ty, S-unactionable, C-bug
