### ISSUE TITLE
Don't Auto-Import the BorrowMut Trait

### ISSUE THREAD

**Issue by joeyame** [rust-lang/rust-analyzer#13826] opened 2022-12-23 03:36 UTC
See https://github.com/rust-lang/rust/issues/39232

This is a huge roadblock to newcomers and intermediate people who end up having to work with Rc<RefCell>. It has wasted countless hours of mine as I research how to access X from Rc<RefCell<X>> and every time I used the .borrow_mut() function, as all the guides said, the returned object was just another Rc<RefCell<X>>.

I can't express how infuriating this has been in my Rust journey.

Today I stumbled across this issue again, and after over an hour of trying to debug I stumbled upon the issue linked at the top of this text. Sure enough, BorrowMut was there. I never added it, and I'm not sure what triggered it. Now that I know about this I'll be more mindful in the future, but it is incredibly difficult for inexperienced people to debug this. What do you search? 

I've encountered the same problem on multiple occasions and only now do I know what is causing it.

I think if someone needs the BorrowMut trait, they are experienced enough to write their own import. If someone doesn't need it, they might never notice it pop up, and what a huge turn-off that is for someone trying out a new language.

**Comment by flodiebold** [comment] 2022-12-23 11:43
Duplicate of #13786

**Closed by flodiebold** 2022-12-23 11:43 UTC
