### ISSUE TITLE
cfg_attr suppresses Go To Definition

### ISSUE THREAD

**Issue by krishna-selectstar** [rust-lang/rust-analyzer#11853] opened 2022-03-30 15:07 UTC
**rust-analyzer version**: rust-analyzer version: bc08b8eff 2022-03-28 stable

**rustc version**: rustc 1.58.1 (db9d1b20b 2022-01-20)

**relevant settings**: `Cargo: All Features` is false

https://user-images.githubusercontent.com/79652693/160867319-5355a2b8-0dc7-44c0-ada1-4a887a8c7d0e.mov

<img width="650" alt="image" src="https://user-images.githubusercontent.com/79652693/160867547-913f20fb-e7fd-4327-b3fa-becf4a3cc0bd.png">

If I remove the `#[cfg_attr(feature = "burn", flamer::flame)]` then everything works as normal.
NOTE: the `burn` feature is off by default

**Comment by krishna-selectstar** [comment] 2022-03-30 15:09
I tested this out and it was working fine for rust-analyzer version: 009e6ceb1 2021-09-27 stable

**Comment by krishna-selectstar** [comment] 2022-03-30 15:12
Go To Reference also doesn't work if the `cfg_attr` is precent (but does on older versions of RA)

**Comment by flodiebold** [comment] 2022-04-03 10:43
Can you provide an example project?

**Comment by arnodb** [comment] 2022-08-16 08:18
I've just bumped on that while investigating a similar issue. I'm not sure it's the same but here is the full test case:

Setup:
* `neovim` + `coc` + `coc-rust-analyzer`
* `rustc 1.63.0 (4b91a6ea7 2022-08-08)`
* `rust-analyzer 0.3.1170-standalone (b6d59f2bb 2022-08-14)`

`main.rs` (`cargo init hello_world` plus some global attributes):

```
#![cfg(not(test))]
#![warn(clippy::unwrap_used)]

pub mod foo;

fn main() {
    println!("Hello, world!");
}
```

`foo.rs`:

```
fn foo() {
    println!("hello foo!");
}
```

If I try to go to the definition of `mod foo`, it doesn't work unless I comment out the `cfg` line.

**Comment by flodiebold** [comment] 2022-08-16 15:11
That's working as intended. Rust-analyzer sets `cfg(test)` by default, because otherwise you wouldn't get IDE support inside `#[cfg(test)]` modules (which are much more common than `cfg(not(test))`). If you have a `cfg(not(test))` crate, you currently have to use the `rust-analyzer.cargo.unsetTest` setting.

**Comment by arnodb** [comment] 2022-08-16 15:19
But `cfg(not(test))` applies to `warn(clippy::unwrap_used)`, not `pub mod foo;`.

Make `foo` public, call it, compile without the test configuration and run the program to confirm that.

**Comment by arnodb** [comment] 2022-08-16 18:48
Right, my mistake. Forget it :)

**Comment by Veykril** [comment] 2023-09-16 14:47
As this was not reproducable for us I'll go close it

**Closed by Veykril** 2023-09-16 14:47 UTC
Labels: S-unactionable, C-support
