### ISSUE TITLE
Request textDocument/inlayHint failed. request handler panicked: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by Tnze** [rust-lang/rust-analyzer#14793] opened 2023-05-13 03:29 UTC
**rust-analyzer version**: 0.3.1506-standalone (833d5301d 2023-05-07)

**rustc version**: rustc 1.71.0-nightly (2a8221dbd 2023-05-11)

**relevant settings**: N/A

**output**:
```
Panic context:
> 
version: 0.3.1506-standalone (833d5301d 2023-05-07)
request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/c%3A/Projects/tauri/ffxiv-crafting-assistant/src-tauri/src/main.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 308,
            character: 38,
        },
        end: Position {
            line: 309,
            character: 40,
        },
    },
    context: CodeActionContext {
        diagnostics: [
            Diagnostic {
                range: Range {
                    start: Position {
                        line: 305,
                        character: 15,
                    },
                    end: Position {
                        line: 312,
                        character: 5,
                    },
                },
                severity: Some(
                    Hint,
                ),
                code: Some(
                    String(
                        "E0308",
                    ),
                ),
                code_description: Some(
                    CodeDescription {
                        href: Url {
                            scheme: "https",
                            cannot_be_a_base: false,
                            username: "",
                            password: None,
                            host: Some(
                                Domain(
                                    "doc.rust-lang.org",
                                ),
                            ),
                            port: None,
                            path: "/error-index.html",
                            query: None,
                            fragment: Some(
                                "E0308",
                            ),
                        },
                    },
                ),
                source: Some(
                    "rustc",
                ),
                message: "this block is missing a tail expression",
                related_information: Some(
                    [
                        DiagnosticRelatedInformation {
                            location: Location {
                                uri: Url {
                                    scheme: "file",
                                    cannot_be_a_base: false,
                                    username: "",
                                    password: None,
                                    host: None,
                                    port: None,
                                    path: "/c%3A/Projects/tauri/ffxiv-crafting-assistant/src-tauri/src/main.rs",
                                    query: None,
                                    fragment: None,
                                },
                                range: Range {
                                    start: Position {
                                        line: 323,
                                        character: 8,
                                    },
                                    end: Position {
                                        line: 323,
                                        character: 12,
                                    },
                                },
                            },
                            message: "original diagnostic",
                        },
                    ],
                ),
                tags: None,
                data: None,
            },
        ],
        only: None,
        trigger_kind: Some(
            Automatic,
        ),
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', crates\hir-expand\src\ast_id_map.rs:141:58
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\panicking.rs:579
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\panicking.rs:64
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\panicking.rs:114
   3: hir_expand::InFile<hir_expand::ast_id_map::FileAstId<N>>::to_node
   4: hir_expand::hygiene::HygieneFrame::new
   5: hir_def::item_tree::lower::Ctx::new
   6: hir_def::item_tree::ItemTree::file_item_tree_query
   7: salsa::runtime::Runtime::execute_query_implementation
   8: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_def::db::TraitAliasDataQuery>>
   9: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  10: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  11: hir_def::db::DefDatabaseGroupStorage__::maybe_changed_since
  12: <ide_db::RootDatabase as salsa::plumbing::DatabaseOps>::maybe_changed_since
  13: salsa::derived::slot::MemoRevisions::validate_memoized_value
  14: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_def::db::TraitAliasDataQuery>>
  15: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  17: hir_def::db::DefDatabaseGroupStorage__::maybe_changed_since
  18: <ide_db::RootDatabase as salsa::plumbing::DatabaseOps>::maybe_changed_since
  19: salsa::derived::slot::MemoRevisions::validate_memoized_value
  20: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  21: salsa::derived::slot::Slot<Q,MP>::read
  22: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  23: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate
  24: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  25: hir_ty::method_resolution::TraitImpls::trait_impls_in_deps_query
  26: salsa::runtime::Runtime::execute_query_implementation
  27: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  28: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  29: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  30: hir_ty::db::HirDatabaseGroupStorage__::maybe_changed_since
  31: <ide_db::RootDatabase as salsa::plumbing::DatabaseOps>::maybe_changed_since
  32: salsa::derived::slot::MemoRevisions::validate_memoized_value
  33: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  34: salsa::derived::slot::Slot<Q,MP>::read
  35: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  36: salsa::QueryTable<Q>::get
  37: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  38: hir_ty::db::trait_solve_wait
  39: <DB as hir_ty::db::HirDatabase>::trait_solve
  40: hir_ty::infer::unify::InferenceTable::try_obligation
  41: hir_ty::autoderef::deref_by_trait
  42: hir_ty::autoderef::autoderef_step
  43: <hir_ty::autoderef::Autoderef as core::iter::traits::iterator::Iterator>::next
  44: hir_ty::method_resolution::generic_implements_goal
  45: hir_ty::method_resolution::iterate_method_candidates_dyn
  46: indexmap::map::IndexMap<K,V,S>::insert
  47: indexmap::map::IndexMap<K,V,S>::insert
  48: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_assignee_expr
  49: indexmap::map::IndexMap<K,V,S>::insert
  50: indexmap::map::IndexMap<K,V,S>::insert
  51: hir_ty::infer::infer_query
  52: salsa::runtime::Runtime::execute_query_implementation
  53: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  54: salsa::derived::slot::Slot<Q,MP>::read
  55: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  56: <DB as hir_ty::db::HirDatabase>::infer_query
  57: hir_ty::db::infer_wait
  58: <DB as hir_ty::db::HirDatabase>::infer
  59: hir::DefWithBody::diagnostics
  60: hir::ModuleDef::diagnostics
  61: hir::Module::diagnostics
  62: ide_diagnostics::diagnostics
  63: std::panicking::try
  64: rust_analyzer::handlers::request::handle_code_action
  65: std::panicking::try
  66: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 0.3.1506-standalone (833d5301d 2023-05-07)
request: textDocument/inlayHint InlayHintParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/c%3A/Projects/tauri/ffxiv-crafting-assistant/src-tauri/src/main.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 234,
            character: 0,
        },
        end: Position {
            line: 391,
            character: 5,
        },
    },
}

thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', crates\hir-expand\src\ast_id_map.rs:141:58
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\panicking.rs:579
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\panicking.rs:64
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\panicking.rs:114
   3: hir_expand::InFile<hir_expand::ast_id_map::FileAstId<N>>::to_node
   4: hir_expand::hygiene::HygieneFrame::new
   5: hir_def::item_tree::lower::Ctx::new
   6: hir_def::item_tree::ItemTree::file_item_tree_query
   7: salsa::runtime::Runtime::execute_query_implementation
   8: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_def::db::TraitAliasDataQuery>>
   9: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  10: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  11: hir_def::db::DefDatabaseGroupStorage__::maybe_changed_since
  12: <ide_db::RootDatabase as salsa::plumbing::DatabaseOps>::maybe_changed_since
  13: salsa::derived::slot::MemoRevisions::validate_memoized_value
  14: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_def::db::TraitAliasDataQuery>>
  15: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  17: hir_def::db::DefDatabaseGroupStorage__::maybe_changed_since
  18: <ide_db::RootDatabase as salsa::plumbing::DatabaseOps>::maybe_changed_since
  19: salsa::derived::slot::MemoRevisions::validate_memoized_value
  20: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  21: salsa::derived::slot::Slot<Q,MP>::read
  22: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  23: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate
  24: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  25: hir_ty::method_resolution::TraitImpls::trait_impls_in_deps_query
  26: salsa::runtime::Runtime::execute_query_implementation
  27: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  28: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  29: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  30: hir_ty::db::HirDatabaseGroupStorage__::maybe_changed_since
  31: <ide_db::RootDatabase as salsa::plumbing::DatabaseOps>::maybe_changed_since
  32: salsa::derived::slot::MemoRevisions::validate_memoized_value
  33: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  34: salsa::derived::slot::Slot<Q,MP>::read
  35: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  36: salsa::QueryTable<Q>::get
  37: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  38: hir_ty::db::trait_solve_wait
  39: <DB as hir_ty::db::HirDatabase>::trait_solve
  40: hir_ty::infer::unify::InferenceTable::try_obligation
  41: hir_ty::autoderef::deref_by_trait
  42: hir_ty::autoderef::autoderef_step
  43: <hir_ty::autoderef::Autoderef as core::iter::traits::iterator::Iterator>::next
  44: hir_ty::method_resolution::generic_implements_goal
  45: hir_ty::method_resolution::iterate_method_candidates_dyn
  46: indexmap::map::IndexMap<K,V,S>::insert
  47: indexmap::map::IndexMap<K,V,S>::insert
  48: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_assignee_expr
  49: indexmap::map::IndexMap<K,V,S>::insert
  50: indexmap::map::IndexMap<K,V,S>::insert
  51: indexmap::map::IndexMap<K,V,S>::insert
  52: indexmap::map::IndexMap<K,V,S>::insert
  53: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_assignee_expr
  54: indexmap::map::IndexMap<K,V,S>::insert
  55: indexmap::map::IndexMap<K,V,S>::insert
  56: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_assignee_expr
  57: indexmap::map::IndexMap<K,V,S>::insert
  58: indexmap::map::IndexMap<K,V,S>::insert
  59: hir_ty::infer::infer_query
  60: salsa::runtime::Runtime::execute_query_implementation
  61: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  62: salsa::derived::slot::Slot<Q,MP>::read
  63: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  64: <DB as hir_ty::db::HirDatabase>::infer_query
  65: hir_ty::db::infer_wait
  66: <DB as hir_ty::db::HirDatabase>::infer
  67: hir::source_analyzer::SourceAnalyzer::new_for_body
  68: hir::semantics::SemanticsImpl::analyze_impl
  69: ide::inlay_hints::bind_pat::hints
  70: ide::inlay_hints::hints
  71: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  72: ide::inlay_hints::inlay_hints
  73: std::panicking::try
  74: rust_analyzer::handlers::request::handle_inlay_hints
  75: std::panicking::try
  76: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 11:22:25] Request textDocument/inlayHint failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
```

**Comment by Tnze** [comment] 2023-05-13 03:32
![image](https://github.com/rust-lang/rust-analyzer/assets/19628575/5bcc81ea-9aca-4753-9d12-3871197f96e6)

**Comment by MariaSolOs** [comment] 2023-05-20 02:46
I've also been experiencing this quite a bit lately...
While the root cause gets fixed, is there a setting to disable the notification? I know that this might be a serious crash but I do find the popup quite disruptive.

**Comment by JackTan25** [comment] 2023-07-18 12:18
how to solve this problem??

**Comment by shoichi1023** [comment] 2023-07-20 04:20
I tried downgrade this, under v0.3.1583.
that problem is resolved.

**Comment by lnicola** [comment] 2023-07-20 09:23
Is anyone seeing this on a public codebase?

**Comment by lnicola** [comment] 2023-07-20 09:25
This seems similar to #14709, but that's older than 0.3.1583.

**Comment by Veykril** [comment] 2023-08-08 20:18
Closing as this is unactionable without a reproducer

**Closed by Veykril** 2023-08-08 20:18 UTC
Labels: C-bug, I-panic
