### ISSUE TITLE
Add function to manage dependencies with Cargo.toml

### ISSUE THREAD

**Issue by shenghui0779** [rust-lang/rust-analyzer#14321] opened 2023-03-11 00:47 UTC
Like [crates](https://marketplace.visualstudio.com/items?itemName=serayuzgur.crates)

**Comment by lnicola** [comment] 2023-03-11 06:56
Dupe of #13532. In the meanwhile, that extension is pretty good, and there's nothing wrong with using it.

**Closed by lnicola** 2023-03-11 06:56 UTC
Labels: C-feature, S-needs-toml
