### ISSUE TITLE
Use macro to prompt unexpected tokens

### ISSUE THREAD

**Issue by rendaoer** [rust-lang/rust-analyzer#17977] opened 2024-08-27 17:11 UTC
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
2024-08-06 and 2024-08-26

**rustc version**: (eg. output of `rustc -V`)
rustc 1.80.1 (3f5fd8dd4 2024-08-06)

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable)
zed and VS Code (Editor that automatically updates Rust-Analyzer)
use cargo add bevy;
Write a structure or enumeration that uses the Reflect macro

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))
When using the Bevy game library, using the Reflec macro will prompt "unexpected tokens"

**code snippet to reproduce**: 
<img width="492" alt="image" src="https://github.com/user-attachments/assets/390ae93a-b9d7-474b-a659-5cfffa74c8b5">

**Comment by rendaoer** [comment] 2024-08-27 17:13
This is an issue created by the Bevy repository
https://github.com/bevyengine/bevy/issues/14935

**Comment by alice-i-cecile** [comment] 2024-08-27 17:22
I've encountered this issue as well: it's a recent regression. Cargo builds and runs the code without issue.

**Comment by Veykril** [comment] 2024-08-27 17:23
There should be another extension update out that fixes this (released today)

**Comment by lnicola** [comment] 2024-08-27 17:24
Duplicate of #17968, the fix is in v0.3.2089.

**Closed by lnicola** 2024-08-27 17:24 UTC
Labels: C-bug
