### ISSUE TITLE
rustdoc on re-exported type is not shown on hover

### ISSUE THREAD

**Issue by xxchan** [rust-lang/rust-analyzer#15354] opened 2023-07-29 17:55 UTC
**rust-analyzer version**: rust-analyzer version: 0.4.1604-standalone (f442c4aad 2023-07-28)

**rustc version**: rustc 1.73.0-nightly (0e8e857b1 2023-07-16)

e.g., `wasmtime::Trap` is shown in rustdoc, but not shown on hover.

<img width="468" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/37948597/83ab2cf0-933a-445e-9e13-4ba1a5c66f30">

https://docs.rs/wasmtime/latest/wasmtime/enum.Trap.html

The doc is on the re-export, but not original type.

<img width="1050" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/37948597/48d6e53a-6341-4c0e-a93a-b104dbf9056d">

**Comment by Veykril** [comment] 2023-07-30 11:00
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/14079

**Closed by Veykril** 2023-07-30 11:00 UTC
Labels: C-bug
