### ISSUE TITLE
rust-analyzer: proc macro `main` not expanded: failed to write request: Broken pipe (os error 32)

### ISSUE THREAD

**Issue by coder3101** [rust-lang/rust-analyzer#15009] opened 2023-06-08 07:56 UTC
<img width="1372" alt="Screenshot 2023-06-08 at 1 24 40 PM" src="https://github.com/rust-lang/rust-analyzer/assets/22212259/6f5ff5ef-8cf5-4e14-a564-c5feffd8a540">

If I switch to nightly release 31-05-2023 this issue disappear whereas in 06-06-2023 and above nightly this issue is being observed.

**Comment by lnicola** [comment] 2023-06-08 07:57
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/14991.

**Closed as completed by lnicola** 2023-06-08 07:57 UTC
