### ISSUE TITLE
Feature request: when auto importing, propagate feature gates to the use statement

### ISSUE THREAD

**Issue by kangalio** [rust-lang/rust-analyzer#13469] opened 2022-10-23 02:41 UTC
Example:
```rust
#[cfg(feature = "collector")]
fn modal(builder: CreateQuickModal /* unimported */) {}
```
After auto-import via Quick Fix or autocomplete:
```rust
#[cfg(feature = "collector")]
use crate::builder::CreateQuickModal;

#[cfg(feature = "collector")]
fn modal(builder: CreateQuickModal) {}
```

**Comment by lnicola** [comment] 2024-02-26 20:53
Pretty much a duplicate of #9391.

**Closed by lnicola** 2024-02-26 20:53 UTC
Labels: C-feature
