### ISSUE TITLE
Don't add call parenthesis when auto-completing a callback function

### ISSUE THREAD

**Issue by heksesang** [rust-lang/rust-analyzer#18380] opened 2024-10-23 11:05 UTC
Assuming I have this code, the auto-complete doesn't do what I'd want from it when I try to auto-complete the input to `map`:
```rust
fn foo(n: i32) -> i32 {
  todo!()
}

fn main() {
  let opt = Some(1).map(f);
}
```

**Actual:**
```rust
fn foo(n: i32) -> i32 {
  todo!()
}

fn main() {
  let opt = Some(1).map(foo(n));
}
```
**Expected:**
```rust
fn foo(n: i32) -> i32 {
  todo!()
}

fn main() {
  let opt = Some(1).map(foo);
}
```

It's really annoying having to remove the call parenthesis every time I try to pass a function as a callback. It should only add them when it's not being inserted into a callback position.

**Comment by Veykril** [comment] 2024-10-23 12:14
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/3148

**Closed by Veykril** 2024-10-23 12:14 UTC
