### ISSUE TITLE
`async-trait` causes `self` to be incorrectly returned.

### ISSUE THREAD

**Issue by Milo123459** [rust-lang/rust-analyzer#16528] opened 2024-02-10 16:19 UTC
**rust-analyzer version**: 0.3.1831

**rustc version**:
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: aarch64-apple-darwin
release: 1.76.0
LLVM version: 17.0.6

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

When the async-trait derive macro is used, getting &self is now incorrectly reported as the wrong semantic token type.
For example: when using async-trait, looking at the semantic token type of `&self` is:

<img width="451" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/50248166/d618ab4b-6bd9-4137-9b79-c4cf6d6e009d">

However, when async-trait is not being used, when accessing `&self`, it is returned *correctly* as 

<img width="851" alt="image (1)" src="https://github.com/rust-lang/rust-analyzer/assets/50248166/6d6197c0-b964-4831-940b-229c10c2a816">

This is just an example of it, as semantic highlighting practically completely breaks whenever it is being used inside a macro.

**Comment by Veykril** [comment] 2024-02-10 16:28
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/16148

**Closed by Veykril** 2024-02-10 16:28 UTC
Labels: C-bug
