### ISSUE TITLE
Error NO_RESULT_CALLBACK_FOUND with Neovim's native LSP

### ISSUE THREAD

**Issue by dtomvan** [rust-lang/rust-analyzer#12482] opened 2022-06-06 21:15 UTC
**rust-analyzer version**: rust-analyzer ad6810e90 2022-06-06 stable

**rustc version**: rustc 1.62.0-nightly (f4a7ce997 2022-04-08)

**neovim version**: NVIM v0.8.0-dev 37ee800b519

**relevant settings**:
```
CARGO_HOME=/home/tomvd/.local/share/cargo
RUSTUP_HOME=/home/tomvd/.local/share/rustup
```
Neovim LSP config is done with https://github.com/simrat39/rust-tools.nvim and https://github.com/williamboman/nvim-lsp-installer

Link to (very long) log: https://www.toptal.com/developers/hastebin/ihiguxinej.properties

Ref: neovim/neovim#15844
The above issue told me that the issue is with the language server, not with neovim itself.

**Comment by ten3roberts** [comment] 2022-06-07 08:51
Can confirm.

The issue persists without rust-tools

**Comment by ten3roberts** [comment] 2022-06-07 08:54
This issue is reprocucible with the default

```lua
require"lspconfig".rust_analyzer.setup {}
```

**Comment by flodiebold** [comment] 2022-06-07 11:08
https://github.com/neovim/nvim-lspconfig/issues/225 says the configs there are "best-effort" and unsupported. I don't see anything saying that it's a server issue. The log seems to just be a completion response. If there are some specific steps that lead to the error, it would help if you could name them, and see whether they lead to similar errors with other clients (VSCode, Emacs, ...). If the issue does not happen with older rust-analyzer versions, that would also be interesting. Otherwise I would suggest asking at `nvim-lspconfig` or `rust-tools.nvim`.

**Comment by dtomvan** [comment] 2022-06-07 14:38
Update: This doesn't occur on Emacs, so I think this issue is `nvim-lspconfig` specific. Using the normal (non-lsp-installer) version of rust-analyzer doesn't help. I did update from lspconfig version `84252b0` to `eb03999`, but downgrading back doesn't help either. I guess this issue just started appearing all of a sudden, which I find weird.

**Comment by dtomvan** [comment] 2022-06-07 14:55
Another update: (I'm sorry for the spam) The latest version (package in Arch Linux's `community` repo) I can find not to error is `rust-analyzer 2022-05-30`. I guess it is some breaking change in rust-analyzer, then.

**Comment by ten3roberts** [comment] 2022-06-07 18:00
I downgraded from the 2022-06-06 to 2022-05-30 and everything works perfectly.

**Comment by Kangaxx-0** [comment] 2022-06-07 19:19
Same issue after upgrading rust_analyzer with version 2022-06-06

**Comment by jonhoo** [comment] 2022-06-07 20:37
@flodiebold I'll give that a shot — stay tuned!

**Comment by jonhoo** [comment] 2022-06-07 20:51
e2da967578872756b81d32665dc85a5d9fe54f9c is the first bad commit

Here's one particularly short error I get a fair amount, if it helps:
```
LSP[rust_analyzer]: Error NO_RESULT_CALLBACK_FOUND: {
  id = 19,
  jsonrpc = "2.0",
  result = {
    isIncomplete = true,
    items = {}
  }
```

**Comment by Veykril** [comment] 2022-06-07 21:16
Hmm, I can only make an assumption here but I imagine that nvim discards requests of a certain kind it sent out if a newer one has been answered. That is if we have requests like `completion:id` the following might now be happening:

`nvim request completion:0`
`r-a starts processing`
`nvim request completion:1`
`r-a cancels completion:0 and requeues it, starts processing completion:1`
`r-a response completion:1`
`nvim acknowledges, discards all completion callbacks for ids <= 1`
`r-a response completion:0`
`nvim can't find a completion callback for id 0 and errors`

This is might seem odd for r-a to do, but to my knowledge the LSP permits this kind of processing.

Though again, this is a wild guess, I do not know how nvim's lsp implementation works, but if this is the case I would argue that this is an implementation error on nvim's side (even if we try to fix the ordering here which we might want to do).

**Comment by jonhoo** [comment] 2022-06-07 21:20
@justinmk would love your input here in trying to figure out if this is a rust-analyzer LSP bug, or a bug/missing feature on the neovim LSP side of things. Does what Veykril outlined above match the actual behavior of neovim?

**Comment by toothlesslizard** [comment] 2022-06-08 12:08
`:LspInstall@2022-05-30`

**Comment by Veykril** [comment] 2022-06-08 16:48
> How do other LSP clients handle this? Just ignore it?

There isn't really anything to ignore here, when a reply comes in a client should only mark the request that belongs to that reply as resolved. "Resolving" multiple requests from one reply and then expecting no replies for the other requests to come in won't work as per spec the server should reply to every request in some form.

**Comment by justinmk** [comment] 2022-06-08 16:56
I have reopened https://github.com/neovim/neovim/issues/15844 and pasted the helpful comments from here.

**Comment by JojiiOfficial** [comment] 2022-06-09 12:03
I'm getting this error on `2022-05-30` as well

**Comment by mfussenegger** [comment] 2022-06-10 10:55
> but I imagine that nvim discards requests of a certain kind it sent out if a newer one has been answered. 

Neovim doesn't do that. It clears callbacks only for a given id.
The [logs](https://gist.github.com/doupongzeng/4886b48e02fa22bc1a33262b067d158c) shared in https://github.com/neovim/neovim/issues/15844 indicate that the server is sending multiple responses with the same request id

**Comment by Veykril** [comment] 2022-06-10 11:06
We'll need to see some neovim logs for r-a here then, because there isn't really a way for r-a to send multiple responses for one request from what I can see.

**Comment by dtomvan** [comment] 2022-06-10 15:31
> We'll need to see some neovim logs for r-a here then, because there isn't really a way for r-a to send multiple responses for one request from what I can see (so I'd like to get proven wrong here then).

While trying to look for my lsp log `~/.cache/nvim/lsp.log` I couldn't find any logs after 2022-05-23. Which is weird, because I've tried to reproduce this issue 4 days ago, so I'd at least see some logs on 2022-06-06, right?

Anyways, if anyone knows where to find (the proper) logs for nvim LSP that would be appreciated.

**Comment by MultisampledNight** [comment] 2022-06-10 17:11
Hm, that actually are the proper logs (opened through `:LspLog`). Here's my relevant log if that's interesting in any way, for me it looks nonsensical: https://gist.github.com/MultisampledNight/7069f686b2d6b8755c5d6448a1f5d80d

**Comment by Veykril** [comment] 2022-06-11 23:18
Regarding logs, we'll need one that shows some more LSP calls prior to the error so we can tell what the server and client exchange that causes the problem.

**Comment by bobtwinkles** [comment] 2022-06-12 00:06
I grabbed some logs from the rust-analyzer side as well, see my comment here: https://github.com/neovim/neovim/issues/15844#issuecomment-1153023365

Those logs were with `RA_LOG=info,rust_analyzer=debug,ide_db=debug,hir_ty=error,chalk_recursive=error,salsa=error`

Poking through it with no real experience on r-a or the neovim LSP, my guess is that the problem is related to this line:
```
[DEBUG rust_analyzer::main_loop] will prime caches cause=restart after cancellation
```

If anyone wants to reproduce the problem and is familiar with Nix, I've been using [this tree](https://github.com/bobtwinkles/mcpnr/tree/994e043ab54a25d0e2afc791257e3436aad4b14c) to reproduce the problem. Add a line after [this one](https://github.com/bobtwinkles/mcpnr/blob/994e043ab54a25d0e2afc791257e3436aad4b14c/pnr/mcpnr-placement/src/gui.rs#L21) with the contents `ctx.` and wait for completion to trigger. I can also grab some more detailed logs if that would be helpful.

**Comment by Veykril** [comment] 2022-06-12 00:48
Hmm, so I think what might be happening here is that the client cancels the completion request, we acknowledge that but still return a response.

**Comment by Veykril** [comment] 2022-06-12 00:58
https://github.com/rust-lang/rust-analyzer/pull/12508 should fix this, we were resetting the cancelled state of requests when retrying them which made us reply for already cancelled requests again.

**Comment by Veykril** [comment] 2022-06-12 01:05
With that said @justinmk you can probably close the issue on the neovim side again as this was a fault on our part after all. Sorry for that!

**Closed** 2022-06-12 01:05 UTC
Labels: C-support

**Comment by bobtwinkles** [comment] 2022-06-12 01:12
I built a r-a based on the branch for #12508 and the problem appears fixed, thanks for the quick turnaround Veykril!

**Comment by garrettmaring** [comment] 2022-08-02 01:29
Don't forget to `:LspRestart` after updating
