### ISSUE TITLE
Incorrect type check of inner struct member

### ISSUE THREAD

**Issue by SephVelut** [rust-lang/rust-analyzer#11981] opened 2022-04-14 02:25 UTC
`rust-analyzer 46d7ee6 2022-04-11 dev`
`rustc 1.62.0-nightly (90ca44752 2022-04-11)`
CocVim

```rust
struct IndexedArray<'a, T, Idx: Copy + SliceIndex<[Idx]> + AddAssign>(&'a [T], Vec<Vec<Idx>>);
struct IndexedArrayIter<'a, T, Idx: Copy + SliceIndex<[Idx]> + AddAssign>(&'a IndexedArray<'a, T, Idx>, usize);

impl<'a, T, Idx: Copy + SliceIndex<[Idx], Output = Idx> + AddAssign + SliceIndex<[T]>> IntoIterator for &'a IndexedArray<'a, T, Idx> {
    type Item = &'a T;
    type IntoIter = IndexedArrayIter<'a, T, Idx>;
    fn into_iter(self) -> Self::IntoIter {
        IndexedArrayIter(self, 0usize)
    }
}

impl<'a, T, Idx: Copy + SliceIndex<[Idx], Output = Idx> + AddAssign + SliceIndex<[T]>> Iterator for IndexedArrayIter<'a, T, Idx> 
{
    type Item = &'a T;
    fn next(&mut self) -> Option<Self::Item> {
        let a: &[T] = self.0.0; //  [rust-analyzer type-mismatch] [E] expected &[T], found &IndexedArray<T, Idx>
    }
}
```

cargo check shows no errors. Indeed, self.0.0 should be of type &'a [T] not &IndexedArray. (self.0).0 fixes it.

**Comment by flodiebold** [comment] 2022-04-14 09:33
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/10560 / https://github.com/rust-lang/rust-analyzer/issues/1109.

**Closed by flodiebold** 2022-04-14 09:33 UTC
