### ISSUE TITLE
Incomplete Type Hover Information with Macro-Generated Types and Documentation

### ISSUE THREAD

**Issue by FuuuOverclocking** [rust-lang/rust-analyzer#15930] opened 2023-11-19 03:28 UTC
**rust-analyzer version**: 0.3.1730-standalone

**rustc version**: 1.73.0 (cc66ad468 2023-10-03)

The latter half of the type documentation disappears when hovering over types that are generated through macros.

To reproduce the bug, `cargo new` and

![image](https://github.com/rust-lang/rust-analyzer/assets/32507398/5e7d2d15-ca9b-4e77-a0fc-938e51fdc118)

Its source: (`~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/uint_macros.rs`)

```rust
macro_rules! uint_impl {
    (
        // ...
    ) => {
        // ...

        /// Returns the number of trailing ones in the binary representation
        /// of `self`.
        ///
        /// # Examples
        ///
        /// Basic usage:
        ///
        /// ```
        #[doc = concat!("let n = 0b1010111", stringify!($SelfT), ";")]
        ///
        /// assert_eq!(n.trailing_ones(), 3);
        /// ```
        #[stable(feature = "leading_trailing_ones", since = "1.46.0")]
        #[rustc_const_stable(feature = "leading_trailing_ones", since = "1.46.0")]
        #[must_use = "this returns the result of the operation, \
                      without modifying the original"]
        #[inline(always)]
        pub const fn trailing_ones(self) -> u32 {
            (!self).trailing_zeros()
        }
}
```

**Comment by lnicola** [comment] 2023-11-19 03:31
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/8092.

**Closed by lnicola** 2023-11-19 03:31 UTC
Labels: C-bug
