### ISSUE TITLE
thread 'Worker' panicked at 'Internal error, cycle detected:

### ISSUE THREAD

**Issue by shanliu** [rust-lang/rust-analyzer#14309] opened 2023-03-10 03:42 UTC
```
> impl_trait_query(ImplId(36596) -> ItemLoc { container: ModuleId { krate: CrateId(273), block: None, local_id: Idx::<ModuleData>(15) }, id: ItemTreeId { tree: TreeId { file: HirFileId(4908), block: None }, value: Idx::<Impl>(0) } } -> ImplData { target_trait: Some(TraitRef { path: Path { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("From"))] }, generic_args: Some([Some(GenericArgs { args: [Type(Array(Path(Path { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("u8"))] }, generic_args: None }), Path(Name(Text("KEY_LEN")))))], has_self_type: false, bindings: [], desugared_from_fn: false })]) } }), self_ty: Path(Path { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("Key"))] }, generic_args: None }), items: [FunctionId(FunctionId(80586))], is_negative: false, attribute_calls: None })

thread 'Worker' panicked at 'Internal error, cycle detected:

trait_impls_in_crate(CrateId(273))
impl_trait(ImplId(36596))
const_eval(ConstId(57732))
mir_body(ConstId(ConstId(57732)))
infer_query(ConstId(ConstId(57732)))
trait_solve_query((CrateId(273), Canonical { value: InEnvironment { environment: Env([]), goal: Implemented(Uint(Usize): TraitId(192)) }, binders: [] }))
trait_impls_in_deps(CrateId(273))
', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.17.0-pre.2\src\lib.rs:422:35
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\core\src\panicking.rs:64
   2: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate
   3: <hir_ty::db::TraitImplsInDepsQuery as salsa::plumbing::QueryFunction>::execute
   4: salsa::runtime::Runtime::execute_query_implementation
   5: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
   6: salsa::derived::slot::Slot<Q,MP>::read
   7: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   8: <DB as hir_ty::db::HirDatabase>::trait_impls_in_deps
   9: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::impls_for_trait
  10: chalk_solve::clauses::program_clauses_that_could_match
  11: chalk_recursive::solve::SolveIteration::solve_iteration
  12: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  13: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  14: <hir_ty::db::TraitSolveQueryQuery as salsa::plumbing::QueryFunction>::execute
  15: salsa::runtime::Runtime::execute_query_implementation
  16: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
  17: salsa::derived::slot::Slot<Q,MP>::read
  18: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  19: salsa::QueryTable<Q>::get
  20: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  21: hir_ty::db::trait_solve_wait
  22: <DB as hir_ty::db::HirDatabase>::trait_solve
  23: hir_ty::infer::unify::InferenceTable::register_obligation_in_env
  24: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_assignee_expr
  25: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_assignee_expr
  26: hashbrown::raw::RawTable<T,A>::find::{{closure}}
  27: hashbrown::raw::RawTable<T,A>::find::{{closure}}
  28: hir_ty::infer::infer_query
  29: salsa::runtime::Runtime::execute_query_implementation
  30: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
  31: salsa::derived::slot::Slot<Q,MP>::read
  32: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  33: <DB as hir_ty::db::HirDatabase>::infer_query
  34: hir_ty::db::infer_wait
  35: <DB as hir_ty::db::HirDatabase>::infer
  36: hir_ty::mir::lower::mir_body_query
  37: salsa::runtime::Runtime::execute_query_implementation
  38: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
  39: salsa::derived::slot::Slot<Q,MP>::read
  40: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  41: <DB as hir_ty::db::HirDatabase>::mir_body
  42: hir_ty::consteval::const_eval_query
  43: salsa::runtime::Runtime::execute_query_implementation
  44: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
  45: salsa::derived::slot::Slot<Q,MP>::read
  46: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  47: <DB as hir_ty::db::HirDatabase>::const_eval
  48: hir_ty::lower::TyLoweringContext::lower_ty_ext
  49: hir_ty::lower::TyLoweringContext::substs_from_path_segment
  50: hir_ty::lower::TyLoweringContext::substs_from_path_segment
  51: hir_ty::lower::impl_trait_query
  52: salsa::runtime::Runtime::execute_query_implementation
  53: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
  54: salsa::derived::slot::Slot<Q,MP>::read
  55: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  56: <DB as hir_ty::db::HirDatabase>::impl_trait
  57: hir_ty::method_resolution::TyFingerprint::for_trait_impl
  58: <hir_ty::db::TraitImplsInCrateQuery as salsa::plumbing::QueryFunction>::execute
  59: salsa::runtime::Runtime::execute_query_implementation
  60: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
  61: salsa::derived::slot::Slot<Q,MP>::read
  62: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  63: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate
  64: <hir_ty::db::TraitImplsInDepsQuery as salsa::plumbing::QueryFunction>::execute
  65: salsa::runtime::Runtime::execute_query_implementation
  66: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
  67: salsa::derived::slot::Slot<Q,MP>::read
  68: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  69: <DB as hir_ty::db::HirDatabase>::trait_impls_in_deps
  70: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::impls_for_trait
  71: chalk_solve::clauses::program_clauses_that_could_match
  72: chalk_recursive::solve::SolveIteration::solve_iteration
  73: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  74: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  75: <hir_ty::db::TraitSolveQueryQuery as salsa::plumbing::QueryFunction>::execute
  76: salsa::runtime::Runtime::execute_query_implementation
  77: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
  78: salsa::derived::slot::Slot<Q,MP>::read
  79: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  80: salsa::QueryTable<Q>::get
  81: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  82: hir_ty::db::trait_solve_wait
  83: <DB as hir_ty::db::HirDatabase>::trait_solve
  84: hir_ty::infer::coerce::<impl hir_ty::infer::unify::InferenceTable>::coerce_inner
  85: hir_ty::infer::coerce::<impl hir_ty::infer::unify::InferenceTable>::coerce
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 11:21:08 AM] Request textDocument/semanticTokens/full/delta failed.
  Message: request handler panicked: Internal error, cycle detected:

trait_impls_in_crate(CrateId(273))
impl_trait(ImplId(36596))
const_eval(ConstId(57732))
mir_body(ConstId(ConstId(57732)))
infer_query(ConstId(ConstId(57732)))
trait_solve_query((CrateId(273), Canonical { value: InEnvironment { environment: Env([]), goal: Implemented(Uint(Usize): TraitId(192)) }, binders: [] }))
trait_impls_in_deps(CrateId(273))

  Code: -32603 
```

**Comment by lnicola** [comment] 2023-03-10 06:11
Duplicate of #14305.

**Closed by lnicola** 2023-03-10 06:11 UTC
Labels: C-bug
