### ISSUE TITLE
Panic in flyimport with `serde_fix`

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#8728] opened 2021-05-04 18:20 UTC
Tested with RA at commit `a2349366b57d49dad7293ecd91620835236f980e`.

Clone https://github.com/lnicola/serde_fix, load the project (beware, it's dog slow to compile), open `fix50sp2/src/comp_id_stat_grp.rs`, go to line 55 and trigger auto-completion after `StatusValue::`.  I get:

```
Failed to lookup SOURCE_FILE@0..1650 in this Semantics.
Make sure to use only query nodes, derived from this instance of Semantics.
root node:   SOURCE_FILE@0..1650
known nodes: SOURCE_FILE@0..1650


', crates/hir/src/semantics.rs:635:stack backtrace:
13
   0: rust_begin_unwind
             at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:435:5
   2: hir::semantics::SemanticsImpl::find_file::{{closure}}
   3: hir::semantics::SemanticsImpl::find_file
   4: hir::semantics::SemanticsImpl::analyze_impl
   5: hir::semantics::SemanticsImpl::scope
   6: ide_db::helpers::import_assets::ImportAssets::search_for
   7: ide_db::helpers::import_assets::ImportAssets::search_for_imports
   8: ide_completion::completions::flyimport::import_on_the_fly
   9: ide_completion::completions
  10: std::panicking::try
  11: ide::Analysis::completions
  12: rust_analyzer::handlers::handle_completion
  13: <F as threadpool::FnBox>::call_box
```

Found in #8599, CC @nappa85 if you want to keep an eye on this.

---

There's also this (unrelated) really annoying `cargo` thing where `cargo check` rebuilds everything when started from RA vs. the terminal. I've seen others complain about it, but now I started seeing it myself.

**Comment by SomeoneToIgnore** [comment] 2021-05-04 19:02
<img width="677" alt="Screenshot 2021-05-04 at 22 01 03" src="https://user-images.githubusercontent.com/2690773/117055800-413ee180-ad24-11eb-8ed2-4b1c1ef6b114.png">

There aren't any flyimport completion options for me though?
When I complete any variant, it works for me without panics (rust-analyzer version: a0ec841bf 2021-05-04 nightly), albeit the list opens tremendously slow.

**Comment by lnicola** [comment] 2021-05-04 19:03
But do you get any panics?

**Comment by SomeoneToIgnore** [comment] 2021-05-04 19:05
I don't see any (the server log tab does not appear for me at all).

I've also tried to do the flyimport completion with `StatusValue::Connected.borrow()` to no avail also.

**Comment by SomeoneToIgnore** [comment] 2021-05-04 19:17
Ok, after reopening the project again the panic had appeared once when I've completed the enum variant, but not for any other consequent completions (no restarts this time), including the same enum variants.

**Comment by Veykril** [comment] 2023-02-08 10:30
As this is somewhat tricky to reproduce reliably and a lot has changed in the completions code I'll close this.

**Closed by Veykril** 2023-02-08 10:30 UTC
Labels: S-unactionable, C-bug

**Comment by lnicola** [comment] 2023-02-08 12:01
Yeah, seems fixed now.
