### ISSUE TITLE
`rust-analyzer` macro expansion gives incorrect result

### ISSUE THREAD

**Issue by mccolljr** [rust-lang/rust-analyzer#13075] opened 2022-08-21 13:27 UTC
**rust-analyzer version**: `rust-analyzer version: 0.3.1170-standalone (b6d59f2bb 2022-08-14)`

**rustc version**: `rustc 1.65.0-nightly (878aef79d 2022-08-20)`

**relevant settings**: There are `.cargo` and `rust-toolchain.toml` files in the repro repo

Here's a minimal reproduction: https://github.com/mccolljr/bug_repro/tree/bug_repro

In the `atsamd-hal` crate, there is a `bsp_pins!` macro which is used to define the `Pins` struct for a board support package.

The struct it generates has fields for each named pin described in the macro invocation. It looks like `rust-analyzer`'s expansion loses these fields. The `rustc` expansion contains them.

The relevant excerpts from the two expansions:

#### From `rust-analyzer`:
```
// Recursive expansion of bsp_pins! macro
// =======================================

#[doc = " BSP replacement for the HAL"]
#[doc = " [`Pins`](atsamd_hal::gpio::v2::Pins) type"]
#[doc = ""]
#[doc = " This type is intended to provide more meaningful names for the"]
#[doc = " given pins."]
pub struct Pins {
    port: Option<$crate::pac::PORT>,
}
impl Pins {
    #[doc = " Take ownership of the PAC [`PORT`] and split it into"]
    #[doc = " discrete [`Pin`]s."]
    #[doc = ""]


    [ ... REST OMITTED ... ]
```

#### From `cargo expand` (which uses `rustc`):
```
/// BSP replacement for the HAL
/// [`Pins`](atsamd_hal::gpio::v2::Pins) type
///
/// This type is intended to provide more meaningful names for the
/// given pins.
pub struct Pins {
    port: Option<::atsamd_hal::pac::PORT>,
    /**
This field can also be accessed using the [`pin_alias!`] macro with the following alternate names:
*/
    ///usb_dp,
    pub testpin: ::atsamd_hal::gpio::v2::Pin<
        ::atsamd_hal::gpio::v2::PA25,
        ::atsamd_hal::gpio::v2::Reset,
    >,
}
impl Pins {
    /// Take ownership of the PAC [`PORT`] and split it into
    /// discrete [`Pin`]s.

    [ ... REST OMITTED ... ]
```

I've been able to reproduce this with the pre-release version of `rust-analyzer` and both the nightly and stable versions of `rustc`

**Comment by mccolljr** [comment] 2022-08-21 13:38
I did some testing, and the last version of `rust-analyzer` that properly expanded this macro was:
`rust-analyzer version: 0.3.1162-standalone (634cfe3d7 2022-08-07)`

**Comment by mccolljr** [comment] 2022-09-01 17:52
To add some more color - the issue is less that calling "Expand Macro Recursively" returns the wrong result, and more that it seems the rust analyzer macro internals are missing the defined fields created via this macro, causing autocomplete to not show the correct fields for the `Pins` type.

**Comment by zicklag** [comment] 2023-08-20 00:23
I'm running into what is probably the same issue. I have a few macros that are pervasive in my codebase and under certain configurations the macro expansion by rust-analyzer is incorrect, causing auto-completion to fail for a large percentage of my dependent crates' code.

Here is a simple reproduction example, including the macro code that causes the issue for me. This isn't the only issue, the other one is caused by a more complex macro which I can give another example for if desired.

This screenshot shows an example of the inference not working:

![image](https://github.com/rust-lang/rust-analyzer/assets/25393315/e2815166-1126-4380-a432-580e19ed2ee4)

There should be a `&str` inlay showing that RA has correctly inferred the type.

It only happens under certain combinations, though, for example, if I comment out one of the fields:

![image](https://github.com/rust-lang/rust-analyzer/assets/25393315/0349a1a5-a895-45ee-8454-b2bf379918bb)

The macro is simple: https://github.com/zicklag/rust-analyzer-issue-example/blob/master/macros/src/lib.rs#L16-L89

I might be able to figure out what exact logic causes the mis-compilation.

The expand macro feature shows the macro compiling with an error:

```rust
// Recursive expansion of Deref macro
// ===================================

compile_error!("One field must be annotated with a #[deref] attribute");
```

While `cargo expand` shows the correct expansion:

```rust
impl ::std::ops::Deref for Example {
    type Target = String;
    fn deref(&self) -> &Self::Target {
        &self.s
    }
}
```

**Comment by zicklag** [comment] 2023-08-20 00:48
Aha! I think I figured out the cause.

With `cargo expand` if I take a struct attribute and call `attr.to_token_stream().to_string()`, I get:

    #[deref]

Which is correct.

If I expand it with Rust analyzer, though I get:

    # [deref]

Interestingly, they also have different debug representations, not just different display representations:

**cargo expand:**

```rust
TokenStream [
    Punct {
        ch: '#',
        spacing: Alone,
        span: #0 bytes(99..100),
    },
    Group {
        delimiter: Bracket,
        stream: TokenStream [
            Ident {
                ident: "deref",
                span: #0 bytes(101..106),
            },
        ],
        span: #0 bytes(100..107),
    },
]
```

**rust analyzer:**

```rust
TokenStream [
    Punct {
        ch: '#',
        spacing: Alone,
        span: 3,
    },
    Group {
        delimiter: Bracket,
        stream: TokenStream [
            Ident {
                ident: "deref",
                span: 5,
            },
        ],
        span: 4,
    },
]
```

It can probably be argued, and may even be mentioned somewhere I didn't notice, that you shouldn't depend on the debug or display implementations of `TokenStream` when writing macros. I should be able to work around this if it's the only issue.

**Comment by zicklag** [comment] 2023-08-20 01:15
I can verify that refactoring the macros to not depend on the `Display` implementation of `TokenStream` fixed my issue.

**Comment by Veykril** [comment] 2023-08-20 08:04
Spans are implementation defined so you can't really rely on their debug/display values. Definitely something that should be reflected in the rust docs.

**Comment by Veykril** [comment] 2023-08-20 08:08
Also note r-a showing `# [deref]` is expected, expansions don't contain any whitespace whatsoever and we have a very crude implementation that tries to insert whitespace in a few places to make it more readable on expansion.

**Comment by Veykril** [comment] 2023-08-20 08:46
I also just checked the initial repro again and that works fine now, so I'll close this

**Closed by Veykril** 2023-08-20 08:46 UTC
Labels: A-macro, S-actionable, C-bug
