### ISSUE TITLE
thread 'Worker' panicked at /src/index.crates.io-6f17d22bba15001f/rowan-0.15.15/src/cursor.rs:786:13

### ISSUE THREAD

**Issue by kzhui125** [rust-lang/rust-analyzer#16119] opened 2023-12-14 07:53 UTC
```
thread 'Worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rowan-0.15.15/src/cursor.rs:786:13:
Bad range: node range 0..1334, range 673..2075
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: rowan::cursor::SyntaxNode::covering_element
   3: syntax::algo::find_node_at_range
   4: ide_diagnostics::adjusted_display_range
   5: ide_diagnostics::handlers::type_mismatch::type_mismatch
   6: ide_diagnostics::diagnostics
   7: std::panicking::try
   8: ide::Analysis::assists_with_fixes
   9: rust_analyzer::handlers::request::handle_code_action
  10: std::panicking::try
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
```

**Comment by SludgePhD** [comment] 2023-12-15 01:58
I'm seeing the same panic, which causes every `codeLens` request to fail on every key press. I'm on `0.3.1766-standalone` and this started happening not too long ago, probably only on the last update.

**Comment by Veykril** [comment] 2023-12-15 11:00
The code lens one is fixed on the nightly release (next stable). I presume this one is caused by the same issue which should therefore also be fixed.

**Comment by Veykril** [comment] 2023-12-15 17:47
I'll close this, if it happens with tomorrows nightly release / monday's stable please open a new issue about it.

**Closed by Veykril** 2023-12-15 17:47 UTC
Labels: C-bug, I-panic

**Comment by SludgePhD** [comment] 2023-12-15 22:24
Switching to nightly has indeed resolved this, thanks!
