### ISSUE TITLE
Auto completion seems to break in function pointers

### ISSUE THREAD

**Issue by NickBotelho** [rust-lang/rust-analyzer#18268] opened 2024-10-08 17:53 UTC
(Using VS Code default settings for everything)

I am writing a medium sized project, and rust analyzer works great until I start declaring function pointers against large structs. The rust analyzer just loses its marbles, it cannot do auto completion or anything. Here is a really simplified version of what I am doing:

struct MyStruct {
    pub work: fn(x: i32, y: i32) -> i32
}

fn create() -> Vec<MyStruct> {
    vec![
        MyStruct{
            work: |x, y| {
                x + y
            }
        },
        MyStruct{
            work: |x, y| {
                x * y
            }
        }
    ]
}
I am creating a large vector of structs like above with function pointers. In my real project, I am totally unable to get suggestions against x or y or anything created inside the function pointer. Does anyone have some suggestions? Whether its a config on the rust analyzer or whether I should just use a different pattern?

In my project I try typing `x.` and then hitting "CRTL + SPACE" to force autocompletion and it just says "Loading..." and then nothing. If I type out the code itself without the help, it recognizes it alright and checks for errors. But its just really unfun to write without the assistance

![Image](https://github.com/user-attachments/assets/d282b45d-ebd8-49d0-9ad5-1a2b273fd994)
shows that when the code is typed out its fine. But I get no autocompletion help when try to type
![Image](https://github.com/user-attachments/assets/a8ed28be-6302-4fff-a1dc-883b629aa023)

**Comment by lnicola** [comment] 2024-10-08 18:02
Does it work better outside `vec![]`?

**Comment by ChayimFriedman2** [comment] 2024-10-08 18:11
Duplicate of #16624 and probably others.

The problem is that the macro matching fails because this is not a valid expression.

**Closed by ChayimFriedman2** 2024-10-08 18:11 UTC
Labels: A-completion, C-bug

**Comment by NickBotelho** [comment] 2024-10-08 18:28
Ah yeah taking it outside of the vec![] macro helps! Whats a good work around here? I'd like to avoid assigning 100+ configs to individual variables and then creating a vector after the fact if possible

**Comment by lnicola** [comment] 2024-10-08 18:32
> Whats a good work around here?

Type one character after the `.`.

**Comment by NickBotelho** [comment] 2024-10-08 18:56
> > Whats a good work around here?
> 
> Type one character after the `.`.

I dont follow

**Comment by lnicola** [comment] 2024-10-08 18:59
Type the first letter of the field or method you need, then press Ctrl-Space to trigger completion.

**Comment by NickBotelho** [comment] 2024-10-08 19:20
> Type the first letter of the field or method you need, then press Ctrl-Space to trigger completion.

that doesnt work inside the vec![] macro

**Comment by lnicola** [comment] 2024-10-08 19:23
It worked in my test, try a simpler case. It should work if the code compiles.

**Comment by NickBotelho** [comment] 2024-10-08 20:03
but see my original picture, thats what happens when I hit `.` and then CTRL SPACE so am I missing something?

**Comment by ChayimFriedman2** [comment] 2024-10-08 20:10
You need to type the first letter of the method then press Ctrl+Space as @lnicola said.

**Comment by ChayimFriedman2** [comment] 2024-10-08 20:37
Oh that's because it's still not a valid expression, because it is followed by other things. If you will type a semicolon and return to the `i` and type Ctrl+Space it should work.
