### ISSUE TITLE
Go to definition feature of rust analyzer not working in a macro

### ISSUE THREAD

**Issue by Prashant-Shekhar-Rao** [rust-lang/rust-analyzer#16072] opened 2023-12-09 18:29 UTC
![0c8a3b970cbd970e12aaf6d69d79f5958f1b0411_2_1035x210](https://github.com/rust-lang/rust-analyzer/assets/139104389/3701a1cf-2982-49e6-b66f-96e73a90dd57)

When I try to find the definition of ChaCha in state:ChaCha, I get no definitions found. This is from the rand_chacha 0.3.1 crate in chacha.rs file .

Is there some setting I can tweak to fix this or is it a know problem in rust analyzer?
output of "0.3.1756-standalone (e402c494b 2023-12-01)"

output of rustc 1.74.0 (79e9716c9 2023-11-13)

**Comment by Veykril** [comment] 2023-12-09 19:00
What `ChaCha` resolves to there depends on the macro invocation site, so we can't really reasonable make that work

**Comment by Prashant-Shekhar-Rao** [comment] 2023-12-10 02:32
Maybe some option can be added where it asks the user which location the macro is being called before showing the definition based on that or a helpful error message about why definition has not been found.

> What `ChaCha` resolves to there depends on the macro invocation site, so we can't really reasonable make that work

**Comment by flodiebold** [comment] 2023-12-10 09:44
Duplicate of #7890.

**Closed by flodiebold** 2023-12-10 09:44 UTC
Labels: C-bug
