### ISSUE TITLE
Triple slash (`///`) completion above functions is not working

### ISSUE THREAD

**Issue by fslongjin** [rust-lang/rust-analyzer#16631] opened 2024-02-22 06:44 UTC
**rust-analyzer version**:  0.4.1854

**rustc version**: (eg. output of `rustc -V`) rustc 1.76.0-nightly (a57770440 2023-11-16)

In Visual Studio Code (both the official and nightly versions with the latest version), using Rust Analyzer version `v0.4.1854 (pre-release)`, the triple slash (`///`) completion above functions is not working.

Expected output after a new line:

```rust
/// This is a function
/// 
fn func() {
}
```
 
Actual output:

```rust
/// This is a function

fn func() {
}
```
 
After adding a comment using `///` above a function or struct, then pressing Enter to move to a new line, it is unable to auto-complete the next `///`. Even after completely uninstalling (including extensions and configurations) and reinstalling VSCode, the issue persists. Downgrading to `v0.4.1816 (pre-release)` for Rust Analyzer solves the problem.

**Comment by Veykril** [comment] 2024-02-22 06:56
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/16602

**Closed by Veykril** 2024-02-22 06:56 UTC
Labels: C-bug
