### ISSUE TITLE
Feature Request: Better diagnostics for version control conflict marker in file

### ISSUE THREAD

**Issue by Ddystopia** [rust-lang/rust-analyzer#17446] opened 2024-06-18 08:54 UTC
Hello, clangd is having that feature and it is quite nice:

![image](https://github.com/rust-lang/rust-analyzer/assets/63151578/3d85d05c-b7bc-42a7-92c6-6f40215daa94)

With Rust, while also detecting a marker, it gives a lot of errors that are not helpful and create a messy feeling (nvim-lsp):

```
Diagnostics:
1. Syntax Error: expected an item [syntax-error]
2. Syntax Error: expected an item [syntax-error]
3. Syntax Error: expected an item [syntax-error]
4. Syntax Error: expected an item [syntax-error]
5. Syntax Error: expected an item [syntax-error]
6. Syntax Error: expected an item [syntax-error]
7. Syntax Error: expected an item [syntax-error]
8. Syntax Error: expected BANG [syntax-error]
9. Syntax Error: expected `{`, `[`, `(` [syntax-error]
10. Syntax Error: expected SEMICOLON [syntax-error]
11. encountered diff marker
    if you're having merge conflicts after pulling new code, the top section is the code you already had and the bottom section is the remote code
    if you're in the middle of a rebase, the top section is the code being rebased onto and the bottom section is the code coming from the current commit being rebased
    for an explanation on these markers from the `git` documentation, visit <https://git-scm.com/book/en/v2/Git-Tools-Advanced-Merging#_checking_out_conflicts>
```

**Comment by Veykril** [comment] 2024-06-18 11:52
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/7127

**Closed by Veykril** 2024-06-18 11:52 UTC
Labels: C-feature
