### ISSUE TITLE
Total failure after some time

### ISSUE THREAD

**Issue by szagi3891** [rust-lang/rust-analyzer#13203] opened 2022-09-07 11:58 UTC
**rust-analyzer version**: v0.3.1194

**rustc version**: rustc 1.65.0-nightly (78a891d36 2022-09-06)

```
[Error - 1:55:46 PM] Request textDocument/inlayHint failed.
  Message: Invalid offset
  Code: -32603 
```

When this message appears, the rust-analyser stops responding.

**Comment by lnicola** [comment] 2022-09-07 14:03
Does it happen on a specific project? Often? Is the code public?

**Comment by szagi3891** [comment] 2022-09-07 15:29
This problem started to occur yesterday (probably after updating to a newer version of rust-analyzer).
Unfortunately, I can't share the project because it's closed source code.
After starting VSC, after about 30 seconds, this problem occurs and rust-analyzer stops hinting.

**Comment by szagi3891** [comment] 2022-09-07 15:46
I switched to the "Pre-Release" version. It seems to work much better this version. It has not yet happened to me that the rust-analyser stopped responding.

**Comment by szagi3891** [comment] 2022-09-07 16:04
I have switched to the "Pre-Release" version. It seems to work much better this version. It has not yet happened to me that the rust-analyser stopped responding

**Comment by szagi3891** [comment] 2022-09-07 16:13
Only problem with this version is that it eats up almost 100% of my CPU.

**Comment by szagi3891** [comment] 2022-09-07 16:24
I have switched to version v0.3.1162 and this version behaves very stable.

**Comment by leolara** [comment] 2022-09-21 16:23
I got the same problem, version 0.3.1212

**Comment by leolara** [comment] 2022-09-21 16:26
I changed to pre-release version 0.4.1215 and it seems to be fine now

**Comment by jonas-schievink** [comment] 2023-01-30 17:38
Closing, as the pre-release back then seemed to have fixed the issue.

If it happens again, please file a new issue and include a way to reproduce the problem, or *any* other information we could use to track it down.

**Closed by jonas-schievink** 2023-01-30 17:38 UTC
Labels: S-unactionable, C-bug
