### ISSUE TITLE
NO_RESULT_CALLBACK_FOUND with rust-analyzer / neovim

### ISSUE THREAD

**Issue by sbromberger** [rust-lang/rust-analyzer#12507] opened 2022-06-11 23:31 UTC
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command) `rust-analyzer cf10a1ee3 2022-06-01 dev` - but this has been happening for the past few weeks.

**rustc version**: (eg. output of `rustc -V`) `rustc 1.61.0 (fe5b13d68 2022-05-18)` 

**relevant settings**: neovim nightly as of 2022-06-08 (but this has been happening since 0.7)

To reproduce:
```
cargo init --lib
nvim src/lib.rs
```
start editing. Within 3 seconds, the following text appears as paged screen output (output is truncated in this issue):

<details>
    <summary>Click to expand</summary>

```
LSP[rust_analyzer]: Error NO_RESULT_CALLBACK_FOUND: {
  id = 3,
  jsonrpc = "2.0",
  result = {
    isIncomplete = true,
    items = {}
  }
LSP[rust_analyzer]: Error NO_RESULT_CALLBACK_FOUND: {
  id = 2,
  jsonrpc = "2.0",
  result = {
    isIncomplete = true,
    items = { {
        additionalTextEdits = {},
        deprecated = false,
        filterText = "enum",
        kind = 14,
        label = "enum",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "enum",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        filterText = "mod",
        kind = 14,
        label = "mod",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "mod",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        filterText = "static",
        kind = 14,
        label = "static",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "static",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        filterText = "struct",
        kind = 14,
        label = "struct",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "struct",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        filterText = "trait",
        kind = 14,
        label = "trait",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "trait",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        filterText = "union",
        kind = 14,
        label = "union",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "union",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        filterText = "use",
        kind = 14,
        label = "use",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "use",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        filterText = "impl",
        kind = 14,
        label = "impl",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "impl",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        filterText = "pub(crate)",
        kind = 14,
        label = "pub(crate)",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "pub(crate)",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        filterText = "pub(super)",
        kind = 14,
        label = "pub(super)",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "pub(super)",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        filterText = "pub",
        kind = 14,
        label = "pub",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "pub",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        filterText = "extern",
        kind = 14,
        label = "extern",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "extern",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        filterText = "type",
        kind = 14,
        label = "type",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "type",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        filterText = "fn",
        kind = 14,
        label = "fn",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "fn",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        filterText = "unsafe",
        kind = 14,
        label = "unsafe",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "unsafe",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        filterText = "const",
        kind = 14,
        label = "const",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "const",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! eprint",
        documentation = {
          kind = "markdown",
          value = 'Prints to the standard error.\n\nEquivalent to the [`print!`] macro, except that output goes to\n[`io::std
err`] instead of [`io::stdout`]. See [`print!`] for\nexample usage.\n\nUse `eprint!` only for error and progress messages. Us
e `print!`\ninstead for the primary output of your program.\n\n[`io::stderr`]: crate::io::stderr\n[`io::stdout`]: crate::io::
stdout\n\n# Panics\n\nPanics if writing to `io::stderr` fails.\n\n# Examples\n\n```rust\neprint!("Error: Could not complete t
ask");\n```'
        },
        filterText = "eprint!",
        kind = 3,
        label = "eprint!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "eprint!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! panic",
        filterText = "panic!",
        kind = 3,
        label = "panic!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "panic!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! debug_assert_eq",
        documentation = {
          kind = "markdown",
          value = "Asserts that two expressions are equal to each other.\n\nOn panic, this macro will print the values of the
 expressions with their\ndebug representations.\n\nUnlike [`assert_eq!`], `debug_assert_eq!` statements are only enabled in n
on\noptimized builds by default. An optimized build will not execute\n`debug_assert_eq!` statements unless `-C debug-assertio
ns` is passed to the\ncompiler. This makes `debug_assert_eq!` useful for checks that are too\nexpensive to be present in a re
lease build but may be helpful during\ndevelopment. The result of expanding `debug_assert_eq!` is always type checked.\n\n# E
xamples\n\n```rust\nlet a = 3;\nlet b = 1 + 2;\ndebug_assert_eq!(a, b);\n```"
        },
        filterText = "debug_assert_eq!",
        kind = 3,
        label = "debug_assert_eq!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "debug_assert_eq!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! stringify",
        documentation = {
          kind = "markdown",
          value = "Stringifies its arguments.\n\nThis macro will yield an expression of type `&'static str` which is the\nstr
ingification of all the tokens passed to the macro. No restrictions\nare placed on the syntax of the macro invocation itself.
\n\nNote that the expanded results of the input tokens may change in the\nfuture. You should be careful if you rely on the ou
tput.\n\n# Examples\n\n```rust\nlet one_plus_one = stringify!(1 + 1);\nassert_eq!(one_plus_one, \"1 + 1\");\n```"
        },
        filterText = "stringify!",
        kind = 3,
        label = "stringify!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "stringify!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! concat",
        documentation = {
          kind = "markdown",
          value = "Concatenates literals into a static string slice.\n\nThis macro takes any number of comma-separated litera
ls, yielding an\nexpression of type `&'static str` which represents all of the literals\nconcatenated left-to-right.\n\nInteg
er and floating point literals are stringified in order to be\nconcatenated.\n\n# Examples\n\n```rust\nlet s = concat!(\"test
\", 10, 'b', true);\nassert_eq!(s, \"test10btrue\");\n```"
        },
        filterText = "concat!",
        kind = 3,
        label = "concat!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "concat!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! format",
        documentation = {
          kind = "markdown",
          value = 'Creates a `String` using interpolation of runtime expressions.\n\nThe first argument `format!` receives is
 a format string. This must be a string\nliteral. The power of the formatting string is in the `{}`s contained.\n\nAdditional
 parameters passed to `format!` replace the `{}`s within the\nformatting string in the order given unless named or positional
 parameters\nare used; see [`std::fmt`] for more information.\n\nA common use for `format!` is concatenation and interpolatio
n of strings.\nThe same convention is used with [`print!`] and [`write!`] macros,\ndepending on the intended destination of t
he string.\n\nTo convert a single value to a string, use the [`to_string`] method. This\nwill use the [`Display`] formatting 
trait.\n\n[`std::fmt`]: ../std/fmt/index.html\n[`print!`]: ../std/macro.print.html\n[`write!`]: core::write\n[`to_string`]: crate::string::ToString\n[`Display`]: core::fmt::Display\n\n# Panics\n\n`format!` panics if a formatting trait implementation 
returns an error.\nThis indicates an incorrect implementation\nsince `fmt::Write for String` never returns an error itself.\n
\n# Examples\n\n```rust\nformat!("test");\nformat!("hello {}", "world!");\nformat!("x = {}, y = {y}", 10, y = 30);\n```'
        },
        filterText = "format!",
        kind = 3,
        label = "format!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "format!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! log_syntax",
        documentation = {
          kind = "markdown",
          value = "Prints passed tokens into the standard output."
        },
        filterText = "log_syntax!",
        kind = 3,
        label = "log_syntax!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "log_syntax!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! include_str",
        documentation = {
          kind = "markdown",
          value = "Includes a UTF-8 encoded file as a string.\n\nThe file is located relative to the current file (similarly 
to how\nmodules are found). The provided path is interpreted in a platform-specific\nway at compile time. So, for instance, a
n invocation with a Windows path\ncontaining backslashes `\\` would not compile correctly on Unix.\n\nThis macro will yield a
n expression of type `&'static str` which is the\ncontents of the file.\n\n# Examples\n\nAssume there are two files in the sa
me directory with the following\ncontents:\n\nFile 'spanish.in':\n\n```text\nadiós\n```\n\nFile 'main.rs':\n\n```rust\nfn mai
n() {\n    let my_str = include_str!(\"spanish.in\");\n    assert_eq!(my_str, \"adiós\\n\");\n    print!(\"{my_str}\");\n}\n`
``\n\nCompiling 'main.rs' and running the resulting binary will print \"adiós\"."
        },
        filterText = "include_str!",
        kind = 3,
        label = "include_str!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "include_str!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! assert_ne",
        documentation = {
          kind = "markdown",
          value = 'Asserts that two expressions are not equal to each other (using [`PartialEq`]).\n\nOn panic, this macro wi
ll print the values of the expressions with their\ndebug representations.\n\nLike [`assert!`], this macro has a second form, 
where a custom\npanic message can be provided.\n\n# Examples\n\n```rust\nlet a = 3;\nlet b = 2;\nassert_ne!(a, b);\n\nassert_
ne!(a, b, "we are testing that the values are not equal");\n```'
        },
        filterText = "assert_ne!",
        kind = 3,
        label = "assert_ne!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "assert_ne!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! dbg",
        documentation = {
          kind = "markdown",
          value = "Prints and returns the value of a given expression for quick and dirty\ndebugging.\n\nAn example:\n\n```ru
st\nlet a = 2;\nlet b = dbg!(a * 2) + 1;\n//      ^-- prints: [src/main.rs:2] a * 2 = 4\nassert_eq!(b, 5);\n```\n\nThe macro 
works by using the `Debug` implementation of the type of\nthe given expression to print the value to [stderr] along with the\
nsource location of the macro invocation as well as the source code\nof the expression.\n\nInvoking the macro on an expressio
n moves and takes ownership of it\nbefore returning the evaluated expression unchanged. If the type\nof the expression does n
ot implement `Copy` and you don't want\nto give up ownership, you can instead borrow with `dbg!(&expr)`\nfor some expression 
`expr`.\n\nThe `dbg!` macro works exactly the same in release builds.\nThis is useful when debugging issues that only occur i
n release\nbuilds or when debugging in release mode is significantly faster.\n\nNote that the macro is intended as a debuggin
g tool and therefore you\nshould avoid having uses of it in version control for long periods\n(other than in tests and simila
r).\nDebug output from production code is better done with other facilities\nsuch as the [`debug!`] macro from the [`log`] cr
ate.\n\n# Stability\n\nThe exact output printed by this macro should not be relied upon\nand is subject to future changes.\n\n# Panics\n\nPanics if writing to `io::stderr` fails.\n\n# Further examples\n\nWith a method call:\n\n```rust\nfn foo(n: usiz
e) {\n    if let Some(_) = dbg!(n.checked_sub(4)) {\n        // ...\n    }\n}\n\nfoo(3)\n```\n\nThis prints to [stderr]:\n\n`
``text,ignore\n[src/main.rs:4] n.checked_sub(4) = None\n```\n\nNaive factorial implementation:\n\n```rust\nfn factorial(n: u3
2) -> u32 {\n    if dbg!(n <= 1) {\n        dbg!(1)\n    } else {\n        dbg!(n * factorial(n - 1))\n    }\n}\n\ndbg!(facto
rial(4));\n```\n\nThis prints to [stderr]:\n\n```text,ignore\n[src/main.rs:3] n <= 1 = false\n[src/main.rs:3] n <= 1 = false\
n[src/main.rs:3] n <= 1 = false\n[src/main.rs:3] n <= 1 = true\n[src/main.rs:4] 1 = 1\n[src/main.rs:5] n * factorial(n - 1) =
 2\n[src/main.rs:5] n * factorial(n - 1) = 6\n[src/main.rs:5] n * factorial(n - 1) = 24\n[src/main.rs:11] factorial(4) = 24\n
```\n\nThe `dbg!(..)` macro moves the input:\n\n```rust\n/// A wrapper around `usize` which importantly is not Copyable.\n#[d
erive(Debug)]\nstruct NoCopy(usize);\n\nlet a = NoCopy(42);\nlet _ = dbg!(a); // <-- `a` is moved here.\nlet _ = dbg!(a); // 
<-- `a` is moved again; error!\n```\n\nYou can also use `dbg!()` without a value to just print the\nfile and line whenever it
's reached.\n\nFinally, if you want to `dbg!(..)` multiple values, it will treat them as\na tuple (and return it, too):\n\n``
`rust\nassert_eq!(dbg!(1usize, 2u32), (1, 2));\n```\n\nHowever, a single argument with a trailing comma will still not be tre
ated\nas a tuple, following the convention of ignoring trailing commas in macro\ninvocations. You can use a 1-tuple directly 
if you need one:\n\n```rust\nassert_eq!(1, dbg!(1u32,)); // trailing comma ignored\nassert_eq!((1,), dbg!((1u32,))); // 1-tup
le\n```\n\n[stderr]: https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)\n[`debug!`]: https://docs.rs/log/
*/log/macro.debug.html\n[`log`]: https://crates.io/crates/log"
        },
        filterText = "dbg!",
        kind = 3,
        label = "dbg!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "dbg!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! vec",
        documentation = {
          kind = "markdown",
          value = "Creates a [`Vec`] containing the arguments.\n\n`vec!` allows `Vec`s to be defined with the same syntax asarray expressions.\nThere are two forms of this macro:\n\n- Create a [`Vec`] containing a given list of elements:\n\n```rust\
nlet v = vec![1, 2, 3];\nassert_eq!(v[0], 1);\nassert_eq!(v[1], 2);\nassert_eq!(v[2], 3);\n```\n\n- Create a [`Vec`] from a g
iven element and size:\n\n```rust\nlet v = vec![1; 3];\nassert_eq!(v, [1, 1, 1]);\n```\n\nNote that unlike array expressions 
this syntax supports all elements\nwhich implement [`Clone`] and the number of elements doesn't have to be\na constant.\n\nTh
is will use `clone` to duplicate an expression, so one should be careful\nusing this with types having a nonstandard `Clone` 
implementation. For\nexample, `vec![Rc::new(1); 5]` will create a vector of five references\nto the same boxed integer value,
 not five references pointing to independently\nboxed integers.\n\nAlso, note that `vec![expr; 0]` is allowed, and produces a
n empty vector.\nThis will still evaluate `expr`, however, and immediately drop the resulting value, so\nbe mindful of side e
ffects.\n\n[`Vec`]: crate::vec::Vec"
        },
        filterText = "vec!",
        kind = 3,
        label = "vec!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "vec!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! include",
        documentation = {
          kind = "markdown",
          value = "Parses a file as an expression or an item according to the context.\n\nThe file is located relative to the
 current file (similarly to how\nmodules are found). The provided path is interpreted in a platform-specific\nway at compile 
time. So, for instance, an invocation with a Windows path\ncontaining backslashes `\\` would not compile correctly on Unix.\n
\nUsing this macro is often a bad idea, because if the file is\nparsed as an expression, it is going to be placed in the\nsur
rounding code unhygienically. This could result in variables\nor functions being different from what the file expected if\nth
ere are variables or functions that have the same name in\nthe current file.\n\n# Examples\n\nAssume there are two files in t
he same directory with the following\ncontents:\n\nFile 'monkeys.in':\n\n```rust\n['🙈', '🙊', '🙉']\n    .iter()\n    .cycle
()\n    .take(6)\n    .collect::<String>()\n```\n\nFile 'main.rs':\n\n```rust\nfn main() {\n    let my_string = include!(\"monkeys.in\");\n    assert_eq!(\"🙈🙊🙉🙈🙊🙉\", my_string);\n    println!(\"{my_string}\");\n}\n```\n\nCompiling 'main.rs' and
 running the resulting binary will print\n\"🙈🙊🙉🙈🙊🙉\"."
        },
        filterText = "include!",
        kind = 3,
        label = "include!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "include!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! print",
        documentation = {
          kind = "markdown",
          value = 'Prints to the standard output.\n\nEquivalent to the [`println!`] macro except that a newline is not printe
d at\nthe end of the message.\n\nNote that stdout is frequently line-buffered by default so it may be\nnecessary to use [`io:
:stdout().flush()`][flush] to ensure the output is emitted\nimmediately.\n\nUse `print!` only for the primary output of your 
program. Use\n[`eprint!`] instead to print error and progress messages.\n\n[flush]: crate::io::Write::flush\n\n# Panics\n\nPa
nics if writing to `io::stdout()` fails.\n\n# Examples\n\n```rust\nuse std::io::{self, Write};\n\nprint!("this ");\nprint!("w
ill ");\nprint!("be ");\nprint!("on ");\nprint!("the ");\nprint!("same ");\nprint!("line ");\n\nio::stdout().flush().unwrap()
;\n\nprint!("this string has a newline, why not choose println! instead?\\n");\n\nio::stdout().flush().unwrap();\n```'
        },
        filterText = "print!",
        kind = 3,
        label = "print!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "print!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! concat_idents",
        documentation = {
          kind = "markdown",
          value = 'Concatenates identifiers into one identifier.\n\nThis macro takes any number of comma-separated identifier
s, and\nconcatenates them all into one, yielding an expression which is a new\nidentifier. Note that hygiene makes it such th
at this macro cannot\ncapture local variables. Also, as a general rule, macros are only\nallowed in item, statement or expres
sion position. That means while\nyou may use this macro for referring to existing variables, functions or\nmodules etc, you c
annot define a new one with it.\n\n# Examples\n\n```rust\n#![feature(concat_idents)]\n\nfn foobar() -> u32 { 23 }\n\nlet f = 
concat_idents!(foo, bar);\nprintln!("{}", f());\n\n// fn concat_idents!(new, fun, name) { } // not usable in this way!\n```'
        },
        filterText = "concat_idents!",
        kind = 3,
        label = "concat_idents!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "concat_idents!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! write",
        documentation = {
          kind = "markdown",
          value = "Writes formatted data into a buffer.\n\nThis macro accepts a 'writer', a format string, and a list of argu
ments. Arguments will be\nformatted according to the specified format string and the result will be passed to the writer.\nTh
e writer may be any value with a `write_fmt` method; generally this comes from an\nimplementation of either the [`fmt::Write`
] or the [`io::Write`] trait. The macro\nreturns whatever the `write_fmt` method returns; commonly a [`fmt::Result`], or an\n
[`io::Result`].\n\nSee [`std::fmt`] for more information on the format string syntax.\n\n[`std::fmt`]: ../std/fmt/index.html\
n[`fmt::Write`]: crate::fmt::Write\n[`io::Write`]: ../std/io/trait.Write.html\n[`fmt::Result`]: crate::fmt::Result\n[`io::Res
ult`]: ../std/io/type.Result.html\n\n# Examples\n\n```rust\nuse std::io::Write;\n\nfn main() -> std::io::Result<()> {\n    le
t mut w = Vec::new();\n    write!(&mut w, \"test\")?;\n    write!(&mut w, \"formatted {}\", \"arguments\")?;\n\n    assert_eq
!(w, b\"testformatted arguments\");\n    Ok(())\n}\n```\n\nA module can import both `std::fmt::Write` and `std::io::Write` an
d call `write!` on objects\nimplementing either, as objects do not typically implement both. However, the module must\nimport
 the traits qualified so their names do not conflict:\n\n```rust\nuse std::fmt::Write as FmtWrite;\nuse std::io::Write as IoW
rite;\n\nfn main() -> Result<(), Box<dyn std::error::Error>> {\n    let mut s = String::new();\n    let mut v = Vec::new();\n
\n    write!(&mut s, \"{} {}\", \"abc\", 123)?; // uses fmt::Write::write_fmt\n    write!(&mut v, \"s = {:?}\", s)?; // uses 
io::Write::write_fmt\n    assert_eq!(v, b\"s = \\\"abc 123\\\"\");\n    Ok(())\n}\n```\n\nNote: This macro can be used in `no
_std` setups as well.\nIn a `no_std` setup you are responsible for the implementation details of the components.\n\n```rust\n
use core::fmt::Write;\n\nstruct Example;\n\nimpl Write for Example {\n    fn write_str(&mut self, _s: &str) -> core::fmt::Res
ult {\n         unimplemented!();\n    }\n}\n\nlet mut m = Example{};\nwrite!(&mut m, \"Hello World\").expect(\"Not written\"
);\n```"
        },
        filterText = "write!",
        kind = 3,
        label = "write!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "write!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! line",
        documentation = {
          kind = "markdown",
          value = 'Expands to the line number on which it was invoked.\n\nWith [`column!`] and [`file!`], these macros provid
e debugging information for\ndevelopers about the location within the source.\n\nThe expanded expression has type `u32` and i
s 1-based, so the first line\nin each file evaluates to 1, the second to 2, etc. This is consistent\nwith error messages by c
ommon compilers or popular editors.\nThe returned line is *not necessarily* the line of the `line!` invocation itself,\nbut r
ather the first macro invocation leading up to the invocation\nof the `line!` macro.\n\n# Examples\n\n```rust\nlet current_li
ne = line!();\nprintln!("defined on line: {current_line}");\n```'
        },
        filterText = "line!",
        kind = 3,
        label = "line!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "line!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! env",
        documentation = {
          kind = "markdown",
          value = "Inspects an environment variable at compile time.\n\nThis macro will expand to the value of the named envi
ronment variable at\ncompile time, yielding an expression of type `&'static str`.\n\nIf the environment variable is not defin
ed, then a compilation error\nwill be emitted. To not emit a compile error, use the [`option_env!`]\nmacro instead.\n\n# Exam
ples\n\n```rust\nlet path: &'static str = env!(\"PATH\");\nprintln!(\"the $PATH variable at the time of compiling was: {path}\");\n```\n\nYou can customize the error message by passing a string as the second\nparameter:\n\n```rust\nlet doc: &'static 
str = env!(\"documentation\", \"what's that?!\");\n```\n\nIf the `documentation` environment variable is not defined, you'll 
get\nthe following error:\n\n```text\nerror: what's that?!\n```"
        },
        filterText = "env!",
        kind = 3,
        label = "env!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "env!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! debug_assert",
        documentation = {
          kind = "markdown",
          value = "Asserts that a boolean expression is `true` at runtime.\n\nThis will invoke the [`panic!`] macro if the pr
ovided expression cannot be\nevaluated to `true` at runtime.\n\nLike [`assert!`], this macro also has a second version, where
 a custom panic\nmessage can be provided.\n\n# Uses\n\nUnlike [`assert!`], `debug_assert!` statements are only enabled in non
\noptimized builds by default. An optimized build will not execute\n`debug_assert!` statements unless `-C debug-assertions` i
s passed to the\ncompiler. This makes `debug_assert!` useful for checks that are too\nexpensive to be present in a release bu
ild but may be helpful during\ndevelopment. The result of expanding `debug_assert!` is always type checked.\n\nAn unchecked a
ssertion allows a program in an inconsistent state to keep\nrunning, which might have unexpected consequences but does not in
troduce\nunsafety as long as this only happens in safe code. The performance cost\nof assertions, however, is not measurable 
in general. Replacing [`assert!`]\nwith `debug_assert!` is thus only encouraged after thorough profiling, and\nmore important
ly, only in safe code!\n\n# Examples\n\n```rust\n// the panic message for these assertions is the stringified value of the\n/
/ expression given.\ndebug_assert!(true);\n\nfn some_expensive_computation() -> bool { true } // a very simple function\ndebu
g_assert!(some_expensive_computation());\n\n// assert with a custom message\nlet x = true;\ndebug_assert!(x, \"x wasn't true!
\");\n\nlet a = 3; let b = 27;\ndebug_assert!(a + b == 30, \"a = {}, b = {}\", a, b);\n```"
        },
        filterText = "debug_assert!",
        kind = 3,
        label = "debug_assert!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "debug_assert!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
            }
          }
        }
      }, {
        additionalTextEdits = {},
        deprecated = false,
        detail = "macro_rules! const_format_args",
        documentation = {
          kind = "markdown",
          value = "Same as [`format_args`], but can be used in some const contexts.\n\nThis macro is used by the panic macros
 for the `const_panic` feature.\n\nThis macro will be removed once `format_args` is allowed in const contexts."
        },
        filterText = "const_format_args!",
        kind = 3,
        label = "const_format_args!",
        preselect = true,
        sortText = "ffffffef",
        textEdit = {
          newText = "const_format_args!",
          range = {
            end = {
              character = 2,
              line = 0
            },
            start = {
              character = 0,
              line = 0
...
```
</details>

Related issue / comment on the neovim issues page: https://github.com/neovim/neovim/issues/15844#issuecomment-1153012889

**Comment by bobtwinkles** [comment] 2022-06-11 23:58
Probably a duplicate of https://github.com/rust-lang/rust-analyzer/issues/12482

**Comment by Veykril** [comment] 2022-06-12 00:04
yep,
Duplicate of #12482

**Closed by Veykril** 2022-06-12 00:04 UTC

**Comment by sbromberger** [comment] 2022-06-12 00:09
I swear I searched the issues before posting. Sorry about that.
