### ISSUE TITLE
[Feature request] Enum variant size hint 

### ISSUE THREAD

**Issue by oxalica** [rust-lang/rust-analyzer#12972] opened 2022-08-08 12:10 UTC
It's quite common to write a enum with tons of variants, but have no idea which one bloats the whole enum size.
They are not always easy to estimate when taking padding and size optimization into count.

The type size can be platform dependent. But we could reuse the setting `rust-analyzer.cargo.target` and `rustc --print cfg` for the calculation.

**Comment by lnicola** [comment] 2022-08-08 12:18
Duplicate of #4091

**Closed by lnicola** 2022-08-08 12:18 UTC
