### ISSUE TITLE
Error showing cannot mutate immutable variable even though it complies

### ISSUE THREAD

**Issue by DE0CH** [rust-lang/rust-analyzer#17448] opened 2024-06-18 15:19 UTC
**rust-analyzer version**: rust-analyzer version: 0.3.2002-standalone [/home/codespace/.vscode-remote/extensions/rust-lang.rust-analyzer-0.3.2002-linux-x64/server/rust-analyzer]

**rustc version**: rustc 1.79.0 (129f3b996 2024-06-10)

**editor or extension**: VSCode. I uninstalled all other extensions and the bug is still there.

**relevant settings**: I am using the stock codespaces image (Ubuntu) `mcr.microsoft.com/devcontainers/universal:2`, with rust installed with the installation script.

**repository link (if public, optional)**: The original bug appeared [in my project here](https://github.com/DE0CH/TA_algs/blob/d948a88b09ba360723911eea9336a2e4e5a35808/ta_algs/src/common.rs#L261), but I have a minimal reproducable example below

**code snippet to reproduce**: 
```rust
use itertools::izip;

fn main() {
    let mut yp_sn = vec![0;5];
    let yp = vec![0;5];
    let x = vec![0;5];
    for (x, yp_sn, _yp) in izip!(x, yp_sn.iter_mut(), yp) {
        *yp_sn = x;
    }
}

```

rust analyzer shows that ``cannot mutate immutable variable `yp_sn` ``, but I can compile successfully with `cargo build`. If I add `mut yp_sn`, it shows a warning that the variable does not need to be mutable.

**Comment by roife** [comment] 2024-06-20 15:47
Duplicate of #11681

**Closed** 2024-06-20 15:52 UTC
Labels: A-ty, C-bug, A-hygiene
