### ISSUE TITLE
Peek implementations displays trimmed strings for impl with generics

### ISSUE THREAD

**Issue by SomeoneToIgnore** [rust-lang/rust-analyzer#5781] opened 2020-08-17 09:29 UTC
Go to `std::time::Duration` declaration, peek implementations (or use the implenentations lens) to open a pop-up with the implementations.
Notice some of them are trimmed:

`u32> for Duration`
instead of
`Mul<u32> for Duration`

while there's clearly enough space to display the full string:

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/2690773/90380342-9e0a4700-e084-11ea-945e-e08f28ac92b8.png">

We might also consider adding `impl` to all impls, for consistency with the first item, `impl Duration`.

**Comment by Veetaha** [comment] 2020-08-25 20:52
I think there was a regression somewhere. I've been seeing this bug for a while...
cc @kjeremy

**Comment by Veykril** [comment] 2021-06-11 11:08
This seems to be a VSCode problem, the ranges we send seem to be correct so it looks like its just truncating the line of the target ident early.

**Comment by Veykril** [comment] 2023-02-02 17:20
Closing as VSCode is in charge of the rendering there, not much we can do about

**Closed by Veykril** 2023-02-02 17:20 UTC
Labels: A-vscode, S-actionable
