### ISSUE TITLE
Cannot set rustcSource to rustc-dev rustup package

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-analyzer#7589] opened 2021-02-07 13:18 UTC
In an attempt to get rust-analyzer to work better for working on Miri (which imports rustc-private crates), I tried setting `rust-analyzer.rustcSource` to `/home/r/.rustup/toolchains/miri/lib/rustlib/rustc-src/rust/compiler/`, where the `rustc-dev` rustup package puts the sources. However, that does not work -- I am getting an error saying "the manifest path must be a path to a Cargo.toml file".

Is there any way to make rust-analyzer use the sources included in the rustc-dev package?

**Comment by bjorn3** [comment] 2021-02-07 13:31
I think you need to point to `/home/r/.rustup/toolchains/miri/lib/rustlib/rustc-src/rust/Cargo.toml`.

**Comment by RalfJung** [comment] 2021-02-07 13:45
But in that directory thereÄs only the lib source, not the compiler source.

**Comment by RalfJung** [comment] 2021-02-07 13:45
There's no such file:
```
$ ls /home/r/.rustup/toolchains/miri/lib/rustlib/rustc-src/rust/
Cargo.lock  compiler
```

**Comment by bjorn3** [comment] 2021-02-07 13:46
Maybe try the `Cargo.toml` of `rustc_driver`?

**Comment by flodiebold** [comment] 2021-02-07 13:49
I would assume you need an actual checkout of rustc.

**Comment by RalfJung** [comment] 2021-02-07 13:58
> I would assume you need an actual checkout of rustc.

That would be rather unpractical -- the crates it is linking against are installed via rustup, so to make sure the source matches, that should also be taken from rustup.

The `rustc-dev` package can probably be extended with some more files if that helps.

**Comment by RalfJung** [comment] 2021-02-07 14:01
> Maybe try the `Cargo.toml` of `rustc_driver`?

No that does not work either:
```
rust-analyzer failed to load workspace: Failed to read Cargo metadata for Rust sources: Failed to run `cargo metadata --manifest-path /home/r/.rustup/toolchains/miri/lib/rustlib/rustc-src/rust/compiler/rustc_driver/Cargo.toml` in `/home/r/.rustup/toolchains/miri/lib/rustlib/rustc-src/rust/compiler/rustc_driver`: `cargo metadata` exited with an error:     Updating crates.io index
error: failed to get `build_helper` as a dependency of package `rustc_llvm v0.0.0 (/home/r/.rustup/toolchains/miri/lib/rustlib/rustc-src/rust/compiler/rustc_llvm)`
    ... which is depended on by `rustc_codegen_llvm v0.0.0 (/home/r/.rustup/toolchains/miri/lib/rustlib/rustc-src/rust/compiler/rustc_codegen_llvm)`
    ... which is depended on by `rustc_interface v0.0.0 (/home/r/.rustup/toolchains/miri/lib/rustlib/rustc-src/rust/compiler/rustc_interface)`
    ... which is depended on by `rustc_driver v0.0.0 (/home/r/.rustup/toolchains/miri/lib/rustlib/rustc-src/rust/compiler/rustc_driver)`

Caused by:
  failed to load source for dependency `build_helper`

Caused by:
  Unable to update /home/r/.rustup/toolchains/miri/lib/rustlib/rustc-src/rust/src/build_helper

Caused by:
  failed to read `/home/r/.rustup/toolchains/miri/lib/rustlib/rustc-src/rust/src/build_helper/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

**Comment by bnjbvr** [comment] 2021-02-11 16:37
I've found what the root cause of this particular issue is: the `src/build_helper` directory is missing from the distributed sources. If you manualloy copy it from the Rustc src to `~/.rustup/toolchains/{toolchain}/lib/rustlib/rustc-src/rust/src/build_helper`, it works just fine! I'll open a PR for adding this directory when distributing rustc.

**Comment by lnicola** [comment] 2021-02-20 11:21
@bnjbvr can this be closed now?

**Comment by RalfJung** [comment] 2021-02-20 17:41
With the latest rustc, pointing to `/home/r/.rustup/toolchains/miri/lib/rustlib/rustc-src/rust/compiler/rustc_driver/Cargo.toml` seems to do something -- I now get more auto-completion than before.

However, it seems rather strange that I would have to pick one of the many compiler crates. Why rustc_driver? At the very least, the docstring for `rustcSource` should explicitly say "set this to the Cargo.toml of rustc_driver", or so.

**Comment by Veykril** [comment] 2024-04-07 16:05
Pointing it to `<sysroot>/lib/rustlib/rustc-src/rust/compiler/rustc/Cargo.toml` should work nowadays (that's what we try to lookup by default), so I believe this can be closed? (I'll close it, re-open if you think otherwise)

**Closed by Veykril** 2024-04-07 16:05 UTC
Labels: C-support
