### ISSUE TITLE
Clippy as command leads to no diagnostics

### ISSUE THREAD

**Issue by augustocdias** [rust-lang/rust-analyzer#9768] opened 2021-08-03 09:54 UTC
If I set the setting `rust-analyzer.checkOnSave.command` to `clippy` I'm getting no diagnostics (on multi project workspaces) since last week's rust-analyzer update. Is this an issue with coc or rust-analyzer?

I could reproduce the issue on VSCode and NeoVim+Coc (https://github.com/fannheyward/coc-rust-analyzer/issues/833)

**Comment by equal-l2** [comment] 2021-08-28 19:36
Any updates here?

**Comment by Leandros** [comment] 2022-02-15 10:54
Same issue here, I get no diagnostics on a workspace project. Running `cargo clippy` manually works.

**Comment by tami5** [comment] 2022-04-25 23:49
Same issue

**Comment by Veykril** [comment] 2022-04-26 09:15
This needs a reproducer for us to be actionable, or at least some logs.

**Comment by fdelacruz** [comment] 2022-06-27 14:42
Any updates on this issue?

**Comment by Leandros** [comment] 2022-09-06 19:04
I can reproduce it easily. How can I get you some logs?

**Comment by Veykril** [comment] 2022-09-07 11:35
On VSCode you can get the logs here ![grafik](https://user-images.githubusercontent.com/3757771/188868940-7529f51c-e9ca-4c06-8abb-43a3dbf86f41.png)

**Comment by Veykril** [comment] 2023-09-16 14:29
Are people still running into this? We'd need to see a repro this reproduces on

**Comment by pattop** [comment] 2023-10-05 00:45
Still happens for me.

**Comment by lnicola** [comment] 2024-07-22 15:48
Closing, since there's not enough information to do anything about it.

**Closed by lnicola** 2024-07-22 15:48 UTC
Labels: S-unactionable, C-support
