### ISSUE TITLE
exceptionally high cpu usage

### ISSUE THREAD

**Issue by Milo123459** [rust-lang/rust-analyzer#17383] opened 2024-06-10 20:04 UTC
**rust-analyzer version**: rust-analyzer version: 0.3.1992-standalone (b427d460e 2024-06-09) [/Users/milo5/.vscode/extensions/rust-lang.rust-analyzer-0.3.1992-darwin-arm64/server/rust-analyzer]

**rustc version**: (rustc 1.78.0 (9b00956e5 2024-04-29)

**editor or extension**: vscode, rust-analyzer

**relevant settings**:     "rust-analyzer.cargo.allFeatures": true,
    "rust-analyzer.checkOnSave.command": "clippy",
    "rust-analyzer.inlayHints.lifetimeElisionHints.useParameterNames": true,
    "rust-analyzer.inlayHints.lifetimeElisionHints": "always",

**repository link (if public, optional)**: n/a

**code snippet to reproduce**: 
n/a

running on a regular project causes 900% CPU usage which never drops, and it never actually provides information to me (ie, everything says Loading). I've had to downgrade to continue working.

another thing, telling rust analyzer to stop the server or restart doesn't work, saying it took too long to respond.

**Comment by lnicola** [comment] 2024-06-10 20:44
Duplicate of #17378.

**Closed by lnicola** 2024-06-10 20:44 UTC
Labels: C-bug
