### ISSUE TITLE
Implementing trait as returning self causes return type to become {unknown}

### ISSUE THREAD

**Issue by TetroGem** [rust-lang/rust-analyzer#16798] opened 2024-03-10 04:15 UTC
**rust-analyzer version**: 0.4.1875-standalone (574e23ec5 2024-03-09)

**rustc version**: 1.77.0-nightly (d78329b92 2024-01-13)

**relevant settings**: n/a

**repository link (if public, optional)**: n/a

**code snippet to reproduce**: 
```rust
pub trait GetRef<T> {
    fn get(&self) -> &T;
}

impl<T> GetRef<T> for T {
    fn get(&self) -> &T {
        self
    }
}

fn print_u8(inner: impl GetRef<u8>) {
    let x = inner.get(); // ra says --> x: &{unknown}
    println!("Got: {}", x);
}

fn main() {
    print_u8(100);
}
```

This program, though RA says a type is unknown, compiles successfully and outputs the expected values:
```
Got: 100
```
Implementing `get` in a way that does not return `self` appears to fix the problem.

Edit: found an even more minimal reproducible example which changes what the bug appears to be, edited the title & code sample accordingly

**Comment by flodiebold** [comment] 2024-03-10 07:57
Duplicate of #5514

**Closed by flodiebold** 2024-03-10 07:57 UTC
Labels: C-bug
