### ISSUE TITLE
False positive diagnostic due to incorrect trait resolution

### ISSUE THREAD

**Issue by bonsairobo** [rust-lang/rust-analyzer#10060] opened 2021-08-28 03:17 UTC
I'm using `v0.2.718` of the visual studio code plugin.

I have a project here: https://github.com/bonsairobo/building-blocks

And in the file `building-blocks/crates/building_blocks_storage/src/chunk_tree.rs` I get a false positive error "expected 1 argument, found 2" here:

<img width="433" alt="Screen Shot 2021-08-27 at 8 14 13 PM" src="https://user-images.githubusercontent.com/3229981/131204579-eaec66ba-3bd6-4c35-8675-bfae1a8bf829.png">

The code compiles fine when I run the tests: `cargo test --all`

I suspect that rust analyzer thinks that `lod0` implements `Iterator`, but really it implements the `ForEach` trait from my crate.

**Comment by jbuckmccready** [comment] 2021-11-15 21:10
I am running into this same issue of incorrect trait resolution due to the same name on method. The concrete types implementing the traits and the traits themselves are completely separate (but both are imported into the same file). E.g., type `A` implements `TraitA` with method `print` and type `B` implements `TraitB` with method `print` and it shows an error due to resolving to `TraitA::print` when it should resolve to `TraitB::print`.

I tried to create a really simple minimal example but it doesn't seem to give the false positive in such cases - I think it may require the use of generics, the use of `Self` as a type parameter, and/or multiple crates to reproduce minimally.

**Comment by lowr** [comment] 2023-05-06 06:51
Tested and confirmed we can resolve the trait method correctly today. Closing, but feel free to file a new issue if you still have similar problems!

**Closed by lowr** 2023-05-06 06:51 UTC
Labels: A-ty, S-actionable
