### ISSUE TITLE
rustdoc text not appearing

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/rust-analyzer#18442] opened 2024-10-30 13:14 UTC
![Image](https://github.com/user-attachments/assets/378b905a-4264-46bc-ac98-c5081472d725)
https://doc.rust-lang.org/nightly/std/primitive.i32.html#method.saturating_neg

The example text for saturating_neg is not appearing.
Version: `rust-analyzer 1 (9323b53858 2024-10-20)`
rustc version: rustc 1.84.0-nightly (df4ca44d3 2024-10-27)
Using neovim.

Other examples in other functions work fine. I don't know if this is an issue with rustdoc or r-a.

**Comment by lnicola** [comment] 2024-10-30 13:21
Duplicate of #8092.

**Closed by lnicola** 2024-10-30 13:21 UTC
Labels: C-bug
