### ISSUE TITLE
Syntax highlighting issue ("templates/**/*")

### ISSUE THREAD

**Issue by vblinden** [rust-lang/rust-analyzer#15091] opened 2023-06-19 15:12 UTC
**rust-analyzer version**: rust-analyzer version: 0.3.1557-standalone (cd3bf9fe5 2023-06-18)
**rustc version**: rustc 1.70.0 (90c541806 2023-05-31)

Hi, 

I'm running into an issue where syntax highlighting is not correctly working for `"templates/**/*"`. Somehow the editor thinks this is a comment and makes everything greyed out (because of `/**`). 

This is inside a string so it shouldn't be considered a comment.

Some screenshots:

![image](https://github.com/rust-lang/rust-analyzer/assets/1420356/d3bf666a-f4f6-4b2e-ba3d-ac33c9602a0d)

![image](https://github.com/rust-lang/rust-analyzer/assets/1420356/8818f56b-1a2b-4d81-8423-9cdecb250296)

**Comment by lnicola** [comment] 2023-06-20 08:11
Does it look fine if you use `Tera::new("templates/**/*").unwrap()`, as you probably should?

**Comment by vblinden** [comment] 2023-06-20 08:16
It does not matter. If I try other themes, the syntax highlighting issue remains.

![image](https://github.com/rust-lang/rust-analyzer/assets/1420356/c173c891-1909-4488-a0d2-9fe929fc25ae)

![image](https://github.com/rust-lang/rust-analyzer/assets/1420356/51de2d8b-c42d-4eec-9e92-88bbc1e94b67)

**Comment by lnicola** [comment] 2023-06-20 08:17
Which theme is that? Can you also show your extension list?

**Comment by vblinden** [comment] 2023-06-20 08:21
The theme is GitHub Dark (but any will do). 

Extension list:
```
aaron-bond.better-comments
alefragnani.project-manager
BeardedBear.beardedicons
BeardedBear.beardedtheme
bierner.lit-html
bierner.markdown-mermaid
bmewburn.vscode-intelephense-client
bradlc.vscode-tailwindcss
BriteSnow.vscode-toggle-quotes
bungcip.better-toml
christian-kohler.npm-intellisense
dbaeumer.vscode-eslint
donjayamanne.githistory
eamodio.gitlens
EditorConfig.EditorConfig
esbenp.prettier-vscode
GitHub.copilot
GitHub.copilot-chat
GitHub.github-vscode-theme
golang.go
junstyle.php-cs-fixer
karunamurti.tera
MehediDracula.php-namespace-resolver
mikestead.dotenv
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode-remote.vscode-remote-extensionpack
ms-vscode.live-server
ms-vscode.remote-explorer
ms-vscode.remote-server
ms-vsliveshare.vsliveshare
Natizyskunk.sftp
onecentlin.laravel-blade
persoderlind.vscode-phpcbf
Prisma.prisma
redhat.vscode-yaml
rust-lang.rust-analyzer
streetsidesoftware.code-spell-checker
streetsidesoftware.code-spell-checker-dutch
usernamehw.errorlens
vadimcn.vscode-lldb
VisualStudioExptTeam.intellicode-api-usage-examples
VisualStudioExptTeam.vscodeintellicode
vscodevim.vim
whatwedo.twig
yoavbls.pretty-ts-errors
zhuangtongfa.material-theme
```
The error will be triggered by just this:
```rust
let foo = "/**";
```

If I disable all extensions, it works correctly. If I enable only rust analyzer, it fails

**Comment by Veykril** [comment] 2023-06-20 08:25
`concat` is an eager macro so thats most likely whats breaking things here. Odd that this completely messed with everything after the call though and justthe call ..

**Comment by lnicola** [comment] 2023-06-20 08:28
No, it's not `concat!`, I think it's a recent regression.

**Comment by Veykril** [comment] 2023-06-20 08:33
Oh sorry I didn't check the later replies. Might be doc comment markdown injection messing up somehow?

**Comment by lnicola** [comment] 2023-06-20 08:33
I can reproduce this:

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/de77933b-1340-42fd-9fc6-0e103ee5b566)

but only right after load. If I wait a little, I see:

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/a12a25e9-e58e-431f-bc14-74d69ae25191)

This is because my test project has `bevy` as a dependency, which makes us take 15-30 seconds (!) for the initial diagnostics and syntax highlighting.

I also thought it was the Markdown PR or the `aaron-bond.better-comments`, but those seem unrelated.

**Comment by vblinden** [comment] 2023-06-20 08:42
If I use a freshly created Cargo project (and another theme (Light (Visual Studio)). And only enable rust-analyzer extension:
      
![image](https://github.com/rust-lang/rust-analyzer/assets/1420356/bf28ee91-84af-47fa-929a-6f15cb08cd50)
^ it stays like this forever.

If I then disable rust-analyzer:
![image](https://github.com/rust-lang/rust-analyzer/assets/1420356/caca0995-1968-43b7-ad52-9e5dbc85dca9)

The syntax highlighting is fixed, but I am sad I don't have rust-analyzer 😄

**Comment by Veykril** [comment] 2023-06-20 08:45
So this is either semantic highlighting causing this (which I doubt it is) or the markdown injection is doing wrong things (which I am more inclined to believe).

**Comment by Veykril** [comment] 2023-06-20 09:11
This is the markdown injection causing problems, note how the semicolon is tagged with markdown
![image](https://github.com/rust-lang/rust-analyzer/assets/3757771/40c9de01-e47a-446b-8d6f-1611aad24569)

**Comment by tuxmark5** [comment] 2023-06-20 11:34
I have a similar issue where comments like /******/ cause anything that follows to have broken syntax highlighting. This started happening today:

![image](https://github.com/rust-lang/rust-analyzer/assets/506439/c25cf042-c8c5-4e3d-9bb4-4406fe998b3e)

**Comment by Veykril** [comment] 2023-06-20 12:00
That one is expected, as doc comments are now treated as markdown, parens, braces and bracktes will benefit from the rainbow bracket highlighting

**Comment by tuxmark5** [comment] 2023-06-20 13:07
@Veykril How can it be expected if the code below the comment isn't part of that comment? The comment in the screenshot both starts and terminates in line 10. The lines 11 to 30+ shouldn't be affected.

**Comment by Veykril** [comment] 2023-06-20 14:23
Oh apologies, I didn't see the closing `/` 🤦‍♂️ 
That is the same issue as described here, its also the markdown injection

**Comment by OliverNChalk** [comment] 2023-06-20 16:19
Can confirm a recent update broke syntax highlighting in all files that contain this non-standard (but valid) header comments:
![image](https://github.com/rust-lang/rust-analyzer/assets/11343499/0b8097c2-a214-4d2a-95fa-aa8e680ab842)

This is the minimal repro version:
![image](https://github.com/rust-lang/rust-analyzer/assets/11343499/1eda0d7f-fe02-4e2b-b56a-08c5c8c2473c)

**Comment by OliverNChalk** [comment] 2023-06-21 15:06
For those affected by this using VSCode or derivative, you can rollback to the previous version:
![image](https://github.com/rust-lang/rust-analyzer/assets/11343499/87cd9f16-7ad2-40c7-af16-72f3350e2ecb)

![image](https://github.com/rust-lang/rust-analyzer/assets/11343499/2765b5f5-6c2f-4328-a09f-716c77d8a4ed)

**Closed** 2023-06-21 17:26 UTC
Labels: C-bug, A-highlighting
