### ISSUE TITLE
rust-analyzer confusion while resolving function attributes with Traits, wrong type inference

### ISSUE THREAD

**Issue by BarbossHack** [rust-lang/rust-analyzer#15286] opened 2023-07-15 10:19 UTC
**rust-analyzer version**: 0.3.1583-standalone (from vscode)
**rustc version**: rustc 1.71.0 (8ede3aae2 2023-07-12)
**relevant settings**: no vscode settings nor cargo env or something else
**os**: fedora 38

Hi,

Since the last version I experienced a bug, that I will try to explain here.

First, this is not a bug in **sha2** nor **aes_gcm** crates (both from RustCrypto), as `cargo check` work as expected, and there were no updates in theses crates since one month.

### Steps to reproduce

1. `cargo init trait_bug`
2. `code trait_bug`
3. `cargo add sha2`
4. `cargo add aes_gcm` (we don't need this one, but it uses the same Trait as in sha2, KeyInit, which is where the confusion is)
5. add the following code in main.rs : 

```rust
use aes_gcm::KeyInit;
use sha2::{Digest, Sha224};

fn main() {
    println!("Hello, world! {}", hash_me("test"));
}

pub fn hash_me(key: &str) -> String {
    let mut hasher = Sha224::new();
    hasher.update(key);
    format!("{:x}", hasher.finalize())
}
```
note that `use aes_gcm::KeyInit;` will be marked as "unused import" by rust-analyzer, and it's normal, we don't use it
6. `cargo run` (success)
7. ctrl+shift+P -> `reload windows` (to be sure that rust-analyzer will fully re-run)
8. Now, we can see that rust-analyzer tells that `Sha224::new()` expects 1 argument, and it's wrong, it does not need any argument (try `cargo check` => success)
![image](https://github.com/rust-lang/rust-analyzer/assets/49869902/e66f2065-f2f3-4fb5-ad56-3fef1bb9833c)
9. Now, try to add `key` argument (as rust-analyzer tells us to do so) and do not reload... it will now tell that it expect 0 argument (yeah, that should be like that !), and now `cargo check` will fail as we provide an argument and we should not
![image](https://github.com/rust-lang/rust-analyzer/assets/49869902/2f3997f2-a460-4085-8f60-0e36fd0efa2c)
10. Now, try to remove the `use aes_gcm::KeyInit;`, remove the unneeded `key` argument, and `reload windows`, and all will be fine (except that there won't be any type inference anymore for `hasher`)
![image](https://github.com/rust-lang/rust-analyzer/assets/49869902/c1df58cf-f188-4907-b2e5-a3460ccf61ef)

### Hints

When we have `use aes_gcm::KeyInit;` and no `key` argument, and we inspect (ctrl+clic) on `::new()`, it opens [this file](https://github.com/RustCrypto/traits/blob/962dabad2c0a316a018b0a1dcbc399aa9408ac9e/digest/src/core_api/wrapper.rs#L74) but it should open [this one](https://github.com/RustCrypto/traits/blob/962dabad2c0a316a018b0a1dcbc399aa9408ac9e/digest/src/digest.rs#L17).

Thank you :+1:

**Comment by lnicola** [comment] 2023-07-15 17:29
Duplicate of #15242.

**Closed by lnicola** 2023-07-15 17:29 UTC
Labels: C-bug

**Comment by BarbossHack** [comment] 2023-07-15 19:46
> Duplicate of #15242.

Indeed, sry, hope it helped
