### ISSUE TITLE
Refactoring::Renaming - Reproducible bug that misses renaming

### ISSUE THREAD

**Issue by PepeOnzima** [rust-lang/rust-analyzer#13881] opened 2023-01-02 20:33 UTC
Consider the following code:

```
let secret_number= rand::thread_rng().gen_range(1..=10);
println!("The secret number is: {}", secret_number);
println!("The secret number is: {secret_number}");
```
    
if I hit F2 or rename in contextual menu, the extension will properly rename the second line, but  not the 3rd.

The extension should rename all valid occurrences of the variable, including line 3 in this example.

**Comment by lnicola** [comment] 2023-01-02 20:49
Duplicate of #11296.

**Closed by lnicola** 2023-01-02 20:49 UTC
