### ISSUE TITLE
Identifier-only completion when passing function as `impl Fn` argument

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust-analyzer#16138] opened 2023-12-16 19:18 UTC
The following example demonstrates the problem:

```Rust
fn takes_plain_fn(f: fn(i32) -> i32) {

}

fn takes_fn_trait(f: impl Fn(i32) -> i32) {

}

fn takes_generic_fn<F: Fn(i32) -> i32>(f: F) {

}

fn i_am_an_fn(arg: i32) -> i32 {
    todo!()
}

fn main() {
    takes_plain_fn(i_am_an_fn); // Good: Only the name is completed
    takes_fn_trait(i_am_an_fn(arg)); // Bad: A function call expression is completed
    takes_generic_fn(i_am_an_fn(arg)); // Bad: A function call expression is completed
}

```

For `takes_plain_fn`, only the function identifier is completed, as expected.
For `takes_fn_trait`, a whole function call expression is completed. Same with `takes_generic_fn`.

Is it possible to implement the same identifier-only completion behavior for `impl Fn`, or are there technical barriers?

**Comment by flodiebold** [comment] 2023-12-16 22:09
Duplicate of #3148. There is indeed a technical barrier, which I explained [here](https://github.com/rust-lang/rust-analyzer/issues/8676#issuecomment-872828070).

**Closed by flodiebold** 2023-12-16 22:09 UTC
Labels: C-feature
