### ISSUE TITLE
"cargo task detection didn't contribute a task for the following configuration"

### ISSUE THREAD

**Issue by mvanthoor** [rust-lang/rust-analyzer#3983] opened 2020-04-15 15:15 UTC
Hi :) Maybe someone can help with this issue. I've been using / testing Rust Analyzer for 10 days or so without issues, but since yesterday, something is wrong.

I've received two updates in two days: VS Code updated to 1.44.1, and Rust Analyzer updated to 0.2.135. Since then, the following error pops up when trying to debug a program by pressing F5:

"cargo task detection didn't contribute a task for the following configuration"

When I view the output, it shows me the pre-launch task that runs "cargo build". When I remove this task, I get the error that the pre-launch task isn't found (obviously), and the dialog to create it from a template. This creates the exact same task as I've been using since switching to Rust Analyzer.

However, the build *does* work, and the debugging also works. It seems I'm getting an error even though nothing is wrong.

If I remove Rust Analyzer in VSCode 1.44.1 and re-install RLS (and its pre-launch build task, because they're not the same), the error goes away.

**Comment by mvanthoor** [comment] 2020-04-17 15:54
Hi :)

I hope this information helps a little bit.

- Updated to Visual Studio Code 1.44.2 on 17-04-2020 (latest).
- Disabled every extension, restarted VSCode: problem still there.
- Switched to Nightly build for Rust Analyzer: problem still there.

As soon as I remove (or disable) Rust Analyzer and swtich back to RLS, the error message doesn't pop up. I do not get this message with other tasks either; only when trying to run "rust: cargo build" as a prelaunch task for debugging.

If you need me to test something somehow, I'll be happy to do so. I like this extension and server for the speed and better completion as compared to RLS :)

**Comment by mvanthoor** [comment] 2020-04-21 20:43
This issue can be closed; the problem is fixed. When having RLS installed and you want to build your program before debugging, you need a pre-launch task. RLS creates such a task, with the following name:

"rust: cargo build"

When you then remove RLS and install Rust Analyzer, this task doesn't work. After removing the task and then debugging, a prompt appears that "rust: cargo build" cannot be found. (Obviously; it was just deleted.) You can recreate the task from that prompt. With Rust Analyzer installed, a new pre-launch task is then created, with the name:

"Rust: cargo build"

Difference: capital R. When you want to debug, you therefore still get the error that "rust: cargo build" can't be found. If you change the name to have a capital R to match the prelaunch task name, the error "There were task errors" appears, stating that "cargo task detection didn't contribute a task for the following configuration", for which this issue was opened.

**Solution**
- Keep the prelaunch task name with the capital R: "Rust: cargo build"
- If you have still have them, remove both versions from task.json. There should be NO task which somehow matches "Rust: cargo build" in task.json. Then the build and debug session works as expected. It seems that Rust Analyzer provides its own prelaunch task internally, and it doesn't have to exist in tasks.json.

**Comment by mvanthoor** [comment] 2020-04-21 21:49
Solution posted in comments.

**Comment by jcdickinson** [comment] 2020-04-22 18:15
@matklad please re-open this, or I can log a new issue if you prefer. While there is a workaround, the current behavior isn't consistent with RLS (or any other VSCode) plugin and build task customization is currently impossible. For example, I would like to use this configuration (as Code-LLDB+DWARF extension is *vastly* superior to the C++ extension for Rust debugging):

```json
	{
		"type": "cargo",
		"command": "build",
		"args": [
			"--target",
			"x86_64-pc-windows-gnu"
		],
		"problemMatcher": [
			"$rustc"
		],
		"group": {
			"kind": "build",
			"isDefault": true
		},
		"label": "rust: cargo build"
	}
```

This configuration is ignored and an `msvc` binary is built. Ideally, customizing the build task for tests should also be possible - I could maintain a "build megaissue" if you'd like.

I've got some free time coming up, and have some open PRs, but I could look into fixing this after all of that.

**Comment by mvanthoor** [comment] 2020-04-22 18:41
Because of the comment of jcdickinson above, I have reopened this issue. I'd like to try code-lld+dwarf myself; didn't know about it. (I use the MS C++ extension with GDB, and manually installed pretty printers, on binaries compiled with thr gnu toolchain on windows. This works for most types, but not all of them.)

**Comment by jcdickinson** [comment] 2020-04-22 19:13
> @mvanthoor: I'd like to try code-lld+dwarf myself; didn't know about it.

It's a bit off-topic for this issue, but [this repo](https://github.com/jcdickinson/racemus) demonstrates how to use it right now. You'll need to look at "tasks.json", "launch.json" and steps 1, 2.ii from the readme.

The main difference is that the locals/variables window in VSCode is much more usable: variables usually have meaningful names (not always) and more often have live values. There are some minor and subjective improvements when it comes to stepping through code (especially where stdlib is concerned). Hope this helps.

**Comment by bjorn3** [comment] 2020-04-22 19:15
Wrong repo linked?

**Comment by mvanthoor** [comment] 2020-04-22 19:21
@jcdickinson Thanks, I'll have a look at it.

However, variables are fine now (with their normal names and live values), apart from some special types such as smart pointers. Maybe lldb is still better, after this issue is resolved.

**Comment by matklad** [comment] 2020-04-22 21:35
I probably won't have time to look into this right now, but I want to link https://github.com/microsoft/language-server-protocol/issues/944 which should be a better approach to the whole task thing than the current set of static tasks.

**Comment by jmevel** [comment] 2022-05-07 09:20
It seems this issue is back now on the latest VS Code as well as latest Cargo.
I made a [minimal reproduction repository](https://github.com/jmevel/vscode-cargo-task-bug) so you guys can try it.

Nothing fency, all I did was to create a new virgin hello world and add the simplest possible `Tasks.json` file which is using the `cargo` command.

Should we re-open this issue or I can create a new one if you guys think it's better?

**Comment by JPGygax68** [comment] 2022-11-03 09:30
Just had this issue pop up out of nowhere this morning (Oct 3 2022). Seriously annoying, found no workaround yet.

**Comment by JPGygax68** [comment] 2022-11-03 09:54
I made it work using the following `tasks.json`: 
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "process",
            "command": "cargo",
            "args": [
                "build"
            ],
            "problemMatcher": [
                "$rustc"
            ],
            "group": "build",
            "label": "cargo_build",
            "options": {
                "cwd": "${workspaceRoot}"
            }
        }
    ]
}
```
It appears any task of type "cargo" is now ignored. The following was working perfectly yesterday:
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cargo",
			"command": "cargo build",
			"problemMatcher": [
				"$rustc"
			],
			"group": "build",
			"label": "cargo_build",
			"options": {
				"cwd": "${workspaceRoot}"
			}
		}
	]
}
```
I removed all my extensions and reinstalled only C/C++ for Visual Studio and rust-analyzer. It did not help.

**Comment by jmevel** [comment] 2022-11-03 11:25
@jcdickinson could we please reopen this issue?

**Comment by jcdickinson** [comment] 2022-11-03 14:06
I am unable to open. Maybe a contributor has to.

**Comment by StewMcc** [comment] 2024-03-22 00:34
This appears to repro again on 0.4.1889 (pre-release) but not v0.3.1885. 

The workaround from @JPGygax68 still works. But seems odd it broke again between these to versions. Regression of some sort?

**Comment by yorickdewid** [comment] 2024-03-25 11:19
Has there been any progress since? The problem still exists

**Comment by PianoPrinter** [comment] 2024-03-25 11:40
Just updated to latest RA, I got this issue too. Had no problem yesterday on previous version.

(rust-analyzer version: 0.3.1896-standalone (6f6b03f9d 2024-03-24)

**Comment by yorickdewid** [comment] 2024-03-25 11:54
Just updated to v0.3.1896 when the problem appeared

**Comment by ipotseluev** [comment] 2024-03-26 13:28
I managed to workaround the issue by installing RA v0.4.1840. Probably it's not the latest good version.

**Comment by pm100** [comment] 2024-03-27 16:31
i switched to 0.4.1899 and still have the same problem.

**Comment by Dobby007** [comment] 2024-03-27 20:00
v0.3.1896 - the issue can be reproduced

**Comment by Tryum** [comment] 2024-03-28 08:38
Rolled back to v0.3.1885 and it fixed the issue.

**Comment by coolCucumber-cat** [comment] 2024-03-28 15:16
I also rolled back to RA v0.3.1885 and it works now. Nothing else I did seemd to work.

**Comment by pkoevesdi** [comment] 2024-03-28 19:24
I can confirm: rolling back to RA v0.3.1885 makes it work again. I deleted my task and ran "Configure Default Task", and it produced this, which works:
```
{
	"tasks": [
		{
			"type": "cargo",
			"command": "build",
			"problemMatcher": [
				"$rustc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"label": "rust: cargo build"
		}
	]
}
```

**Comment by va1ha11a** [comment] 2024-03-31 02:54
all my cargo tasks recently failing, I also confirm rollback to RA v0.3.1885 works

**Comment by mhnap** [comment] 2024-04-04 20:21
Does anybody know the root cause of this issue? Is it a bug or `tasks.json` should be updated to a new structure? Still have this issue on the latest `v0.3.1906` with the following task:
```json
{
	"label": "check",
	"type": "cargo",
	"command": "check",
	"problemMatcher": [
		"$rustc"
	],
	"group": {
		"kind": "build",
		"isDefault": true
	},
	"dependsOn": [
		"clear terminal"
	]
}
```
The same issue appears on `v0.3.1896`, but not on `v0.3.1885`.

**Comment by sazzer** [comment] 2024-04-04 22:34
I've got this happening as well, using `rust-analyzer-0.3.1906-darwin-arm64`. I've not tried rolling back to an older version yet, but it's been annoying me for a week or so now... :(

**Comment by patowen** [comment] 2024-04-05 04:17
I'm not following rust-analyzer that closely, so I may be far off, but this has affected me as well. I'm hopeful that #16943 and #16949 cover the issue we're having, in which case it should hopefully be fixed in the next version due to #16970 (which just missed last Monday's release).

**Comment by coolCucumber-cat** [comment] 2024-04-05 07:49
It now works as of 0.4.1907, so switch to prerelease until probably Monday, when it will be merged into stable

**Comment by coolCucumber-cat** [comment] 2024-04-10 07:36
I can confirm that it works in the newest stable release. If everyone here confirms it also works for them, then we can close this issue.

**Comment by sazzer** [comment] 2024-04-10 08:31
Looks like it's working for me on the release version now too :)

**Comment by pkoevesdi** [comment] 2024-04-10 15:40
"Working" from me too. Thank You for fixing it!

**Closed** 2024-04-10 15:40 UTC
Labels: E-unknown, A-vscode, C-enhancement

**Comment by coolCucumber-cat** [comment] 2024-06-20 08:48
It seems to not be working again on v0.3.2003. However it did work on v0.3.1995 and it is also fixed on prerelease v0.4.2005.

Does anyone know when it will be fixed on stable? I don't want to use older versions or use unstable versions.

**Comment by Veykril** [comment] 2024-06-20 08:54
Next monday

**Comment by yorickdewid** [comment] 2024-06-20 09:04
Same here

**Comment by coolCucumber-cat** [comment] 2024-06-20 09:15
Just to clarify, Monday the 24th?

**Comment by Veykril** [comment] 2024-06-20 09:34
yes
