### ISSUE TITLE
r-a ignores `#[doc=concat!(...)]` lines

### ISSUE THREAD

**Issue by digama0** [rust-lang/rust-analyzer#13337] opened 2022-10-02 23:53 UTC
```rust
/// Line 1
#[doc = concat!("Line", " 2")]
/// Line 3
pub const X: u8 = 0;
const _: u8 = X;
           // ^ hover doc: Line 1 Line 3
```
Rust analyzer currently seems to ignore macros in `#[doc=...]`, leading to broken docs for e.g. `u32::saturating_add()`.

**rust-analyzer version**: `0.4.1225-standalone`

**rustc version**: `rustc 1.63.0 (4b91a6ea7 2022-08-08)`

**Comment by HKalbasi** [comment] 2022-10-03 03:47
Duplicate of #8092

**Closed** 2022-10-03 04:29 UTC
