### ISSUE TITLE
Diagnostic shows error on code that can be compiled

### ISSUE THREAD

**Issue by Martinits** [rust-lang/rust-analyzer#15935] opened 2023-11-20 06:26 UTC
For the following code with dependency `sha3 = "0.10.8"`:
```rust
use sha3::{Digest, Sha3_256, digest::crypto_common::KeyInit};
fn main() {
    let mut hasher = Sha3_256::new();
    hasher.update(b"abc");
    hasher.finalize();
}
```
can be compiled with no error, but the LSP shows an error about wrong arguments about `Sha3_256::new()`.
The `KeyInit` trait import brings  a new `new` function of one argument to `Sha3_256`, and `Sha3_256` has a `new` implementation with no args originally (in trait `Digest`). Compiler chooses the correct `new` but LSP doesn't. Without the `KeyInit` import, no diagnostic error.
P.S. I import `KeyInit` because required in other code I omitted.

**rust-analyzer version**: 1.74.0
**rustc version**: 1.74.0

**Comment by lnicola** [comment] 2023-11-20 08:09
Duplicate of #15720 and probably others.

**Closed by lnicola** 2023-11-20 08:09 UTC
Labels: C-bug
