### ISSUE TITLE
The generate import action places the import in a wrong place for cfg-d inherent functions

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust-analyzer#12595] opened 2022-06-20 15:59 UTC
Consider initial code such as this:

```rust
struct Engine;

impl Engine {
    #[cfg(feature = "banana")]
    pub fn new() -> Self {
        todo!()
    }
}
```

I have added a parameter referencing a valid, unimported type:

```rust
#[cfg(feature = "banana")]
pub fn new(banana: Banana) -> Self {
    todo!()
}
```

And then I used the r-a action to generate the `use` for `Banana`, which produced code such as

```rust
#[cfg(feature = "banana")]
pub fn new(banana: Banana) -> Self {
    use somecrate::Banana;

    todo!()
}
```

this will not make the `Banana` in the argument list resolvable either way, so r-a should either not suggest to produce an `use` at all, or maybe generate something like this instead:

```rust
#[cfg(feature = "banana")]
use somecrate::Banana;

impl Engine {
    #[cfg(feature = "banana")]
    pub fn new(banana: Banana) -> Self {
        todo!()
    }
}
```

This does work alright if the `cfg` is not there.

---

Version: r-a is pretty old at this point, but I wasn’t able to upgrade due to nixpkgs woes recently. For those of you using nixpkgs, `/nix/store/7kk1ni8w2ibdj1diipn3891qw9p93scf-rust-analyzer-2022-05-17`.

**Comment by nagisa** [comment] 2022-06-20 16:00
Let me know if this isn’t trivially reproducible, I’ll try to minimize the codebase itself in that case.

**Comment by flodiebold** [comment] 2022-06-20 16:01
Duplicate of #9391.

**Closed by flodiebold** 2022-06-20 16:01 UTC
