### ISSUE TITLE
Make panic error shown on code optional.

### ISSUE THREAD

**Issue by adrianos42** [rust-lang/rust-analyzer#14977] opened 2023-06-04 19:08 UTC
It would be interesting to have an option not to show runtime errors as an error in the code.

**Comment by HKalbasi** [comment] 2023-06-04 20:43
Duplicate of #14193

Note that server panics are always considered a bug, so you can also report that with a stack trace and optionally a repro.

**Comment by adrianos42** [comment] 2023-06-04 21:18
Sorry if I didn't specify. Apparently it's related to this new feature: [14749](https://github.com/rust-lang/rust-analyzer/pull/14749). It was introduced in the 0.3.1506 version, changelog number 180.

**Comment by HKalbasi** [comment] 2023-06-04 21:26
Ah, sorry I misunderstood the issue.

**Comment by apollo-sturdy** [comment] 2023-06-06 10:43
+1. Since this update I am often confused to see red text in my file names and assume I have a compilation error, and instead just find that it is an error from a very old test run that has since been fixed. Is there already a way to clear these errors?

**Comment by tooltitude-support** [comment] 2023-06-19 22:54
It would also be nice to indicate that it's rust-analyzers' error message. The source is shown as panic which is not very easy to understand.

**Comment by dnut** [comment] 2023-06-30 20:14
The utility of this feature is not worth the violation of what we usually take for granted about "problem" highlighting. Problem highlighting serves some important roles, such as:
1. Telling you that something is *definitely invalid* and can *never* run without error.
2. Accurately represents the code exactly as it is written *right now*.
3. Providing immediate feedback about code that you just typed, within the context where you are working, so you don't need to jump to another context and compile or run the code from scratch.

All three of these principles are violated by this feature.

1. Your code might be perfectly fine, and the panic was triggered by something unrelated to your code.
2. As soon as you change the code, the problem is no longer valid. It may not even be possible for your code to panic in that location. Yet, the error *never* goes away, until you run the code without any errors, which is not always practical.
3. You will be looking at the terminal output regardless to understand the error. In that context, you can click on the stack trace to bring you to the exact location of the error. 

When something I trust refuses to stop demanding my attention, it's hard to concentrate. I trust it and take it seriously because it usually means there is *definitely* something wrong with my code. I may some learn to ignore these problems after I get desensitized to perpetual red herrings. That would be unfortunate.

I can imagine a variant of this feature that would be acceptable. It should...
- be easy to completely disable.
- immediately disappear as soon as any code files are written to.
- not be a "problem" that looks like a compiler error. It should have a completely different appearance that is less alarming.

As long as the first criteria is not met, I don't think any feature like this should be in rust-analyzer at all.

**Closed** 2023-07-03 02:55 UTC
Labels: A-vscode, C-feature
