### ISSUE TITLE
rust-analyzer fails to provide autocompletion for methods of type wrapped in Into<T>

### ISSUE THREAD

**Issue by westernwontons** [rust-lang/rust-analyzer#13482] opened 2022-10-25 09:57 UTC
I have this function signature:
```rust
  pub fn set_name<'a, T>(&mut self, name: T) -> &mut Self
  where
    T: Into<Cow<'a, str>>
  {
    self.name = name.into().into_owned();
    self
  }

```

In VSCode, if I set `"unresolvedReference": "#d3d3d3d3",` in `"editor.semanticTokenColorCustomizations"`, I noticed that `.into_owned()` is grayed out, but this code works fine. I can confirm this, because this compiles:

<img width="593" alt="Screenshot 2022-10-25 at 12 47 52" src="https://user-images.githubusercontent.com/75550932/197742683-40ab8777-126b-46b3-9af5-8b870e64f7cf.png">

For example, if I have `Into<Cow<'a, str>>`, the Into trait's `into()` method shows up, but nothing after that. This video demonstrates this in practice:

https://user-images.githubusercontent.com/75550932/197743591-3b00762d-ccbd-4c9c-8a6a-e0fa053ef446.mov

**Comment by flodiebold** [comment] 2022-10-25 09:58
Duplicate of #5514

**Closed by flodiebold** 2022-10-25 09:58 UTC
