### ISSUE TITLE
Type inference problem with `Into` & `.to_string()`

### ISSUE THREAD

**Issue by adsick** [rust-lang/rust-analyzer#18230] opened 2024-10-02 17:40 UTC
When using `Into<String>` paired with `.to_string()` RA fails to infer the type of the variable between the calls.

**rust-analyzer version**: 
```
rust-analyzer version: 0.3.2129-standalone [/home/adsick/.vscode/extensions/rust-lang.rust-analyzer-0.3.2129-linux-x64/server/rust-analyzer]
```

**rustc version**: (eg. output of `rustc -V`)
`rustc 1.80.0 (051478957 2024-07-21)`

**editor or extension**: VSCode

**code snippet to reproduce**: 
```rust
pub fn test(s: impl Into<String>) -> String {
    let s = s.into();
    // type of s is not known to the rust analyzer here
    // try typing `s.` and you will see no completions

    let s = s.to_string();
    // here rust analyzer knows that s is a String
    s
}

```

It's not critical but a tiny bit annoying.

**Comment by flodiebold** [comment] 2024-10-03 05:53
Duplicate of #5514

**Closed by flodiebold** 2024-10-03 05:53 UTC
Labels: C-bug
