### ISSUE TITLE
VSCode: Error ranges are completely in the wrong place after some edits

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [rust-lang/rust-analyzer#12403] opened 2022-05-27 19:26 UTC
On Windows, after doing some editing and saving in a file the error ranges are completely wrong. Checking the RA logs shows that the JSON output from all commands (cargo check, cargo clippy) is correct in terms of line numbers etc., but the red and orange squiggles are shifted very far back in the file.

I suspect this has to do with treatment of newlines because of the following indications:
* It doesn't happen on Linux with exactly the same configuration, program versions and repository/file.
* The further back the code is in the file, the more the ranges are shifted as well. For example, errors around line 1800 in one file get shifted back about 200 lines, while ones in a file with only ~100 lines get shifted back only 1-2 lines.
* The size of the squiggle marking appears to be correct. Errors for entire blocks still cause large squiggles while errors for single calls still cause small squiggles.

**rust-analyzer version**: 7e95c14ea 2022-05-17 stable

**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)

**relevant settings**: I'm using a custom override check command which includes clippy checks, but it also happens with the default check command.

**Comment by lnicola** [comment] 2022-05-27 19:27
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/12293.

**Closed by lnicola** 2022-05-27 19:27 UTC
