### ISSUE TITLE
Renaming a symbol does not change references to that symbol in named parameters in `format!`-esque macros

### ISSUE THREAD

**Issue by alexander-novo** [rust-lang/rust-analyzer#12653] opened 2022-06-28 20:41 UTC
**rust-analyzer version**: rust-analyzer version: 0.0.0 (9eaf96c9e 2022-06-27)

**rustc version**: rustc 1.61.0 (fe5b13d68 2022-05-18)

**relevant settings**: N/A

As an example:

```Rust
let x = "blah";
println!("{x}");
```

Rust-analyzer correctly determines that `x` in the format string is a named parameter that isn't specified in the function arguments, but renaming symbol `x` doesn't change it in the string. However,  rust-analyzer then picks up that the identifier `x` doesn't exist anymore. If rust-analyzer is checking the named parameters for format strings and making sure they exist (and type check them to make sure they impl `Display`), I would expect it to also be able to rename it properly.

**Comment by flodiebold** [comment] 2022-06-29 07:52
Duplicate of #11260.

**Closed by flodiebold** 2022-06-29 07:52 UTC
