### ISSUE TITLE
hover panics v0.4.1625

### ISSUE THREAD

**Issue by evbo** [rust-lang/rust-analyzer#15468] opened 2023-08-16 16:00 UTC
> Panic context:
> 
version: 0.4.1624-standalone (2fbe69d11 2023-08-12)
request: textDocument/semanticTokens/range SemanticTokensRangeParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/workspace/operation.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 23,
            character: 0,
        },
        end: Position {
            line: 80,
            character: 41,
        },
    },
}

> impl_trait_query(ImplId(47249) -> ItemLoc { container: ModuleId { krate: Idx::<CrateData>(265), block: None, local_id: Idx::<ModuleData>(2) }, id: ItemTreeId { tree: TreeId { file: FileId(FileId(5592)), block: None }, value: Idx::<Impl>(0) } } -> ImplData { target_trait: None, self_ty: Path(Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("CrcTable"))] }, generic_args: None }), items: [FunctionId(FunctionId(41673))], is_negative: false, attribute_calls: None })

> impl_self_ty_query(ImplId(47249) -> ItemLoc { container: ModuleId { krate: Idx::<CrateData>(265), block: None, local_id: Idx::<ModuleData>(2) }, id: ItemTreeId { tree: TreeId { file: FileId(FileId(5592)), block: None }, value: Idx::<Impl>(0) } } -> ImplData { target_trait: None, self_ty: Path(Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("CrcTable"))] }, generic_args: None }), items: [FunctionId(FunctionId(41673))], is_negative: false, attribute_calls: None })

> DefMap Idx::<CrateData>(265) crate_name=Some(CrateDisplayName { crate_name: CrateName("aws_endpoint"), canonical_name: "aws-endpoint" }) block=None path=CrcTable

thread 'Worker' panicked at 'index out of bounds: the len is 1 but the index is 2', crates/hir-def/src/nameres/path_resolution.rs:424:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:162:5
   3: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro_single
   4: hir_def::resolver::ModuleItemMap::resolve_path_in_type_ns
   5: hir_def::resolver::Resolver::resolve_path_in_type_ns
   6: hir_ty::lower::TyLoweringContext::lower_ty_ext
   7: hir_ty::lower::impl_self_ty_query
   8: salsa::runtime::Runtime::execute_query_implementation
   9: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  10: salsa::derived::slot::Slot<Q,MP>::read
  11: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  12: salsa::QueryTable<Q>::get
  13: <DB as hir_ty::db::HirDatabase>::impl_self_ty
  14: hir_ty::lower::impl_trait_query
  15: salsa::runtime::Runtime::execute_query_implementation
  16: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  17: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  18: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  19: salsa::derived::slot::MemoRevisions::validate_memoized_value
  20: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  21: salsa::derived::slot::Slot<Q,MP>::read
  22: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  23: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate::__shim
  24: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  25: hir_ty::method_resolution::TraitImpls::trait_impls_in_deps_query
  26: salsa::runtime::Runtime::execute_query_implementation
  27: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  28: salsa::derived::slot::Slot<Q,MP>::read
  29: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  30: salsa::QueryTable<Q>::get
  31: <DB as hir_ty::db::HirDatabase>::trait_impls_in_deps
  32: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::impls_for_trait
  33: chalk_recursive::solve::SolveIterationHelpers::solve_from_clauses
  34: chalk_recursive::solve::SolveIteration::solve_iteration
  35: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  36: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  37: hir_ty::traits::trait_solve_query
  38: salsa::runtime::Runtime::execute_query_implementation
  39: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  40: salsa::derived::slot::Slot<Q,MP>::read
  41: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  42: salsa::QueryTable<Q>::get
  43: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  44: hir_ty::db::trait_solve_wait
  45: hir_ty::infer::unify::InferenceTable::try_obligation
  46: hir_ty::autoderef::deref_by_trait
  47: hir_ty::autoderef::autoderef_step
  48: <hir_ty::autoderef::Autoderef as core::iter::traits::iterator::Iterator>::next
  49: hir_ty::method_resolution::autoderef_method_receiver
  50: hir_ty::method_resolution::iterate_method_candidates_dyn
  51: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  52: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  53: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  54: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  55: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  56: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  57: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  58: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  59: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  60: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  61: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  62: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_return
  63: hir_ty::infer::infer_query
  64: salsa::runtime::Runtime::execute_query_implementation
  65: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  66: salsa::derived::slot::Slot<Q,MP>::read
  67: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  68: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  69: <DB as hir_ty::db::HirDatabase>::infer_query
  70: hir_ty::db::infer_wait
  71: <DB as hir_ty::db::HirDatabase>::infer
  72: hir::source_analyzer::SourceAnalyzer::new_for_body
  73: hir::semantics::SemanticsImpl::analyze_impl
  74: ide_db::defs::NameClass::classify
  75: ide::syntax_highlighting::highlight::name_like
  76: ide::syntax_highlighting::traverse
  77: ide::syntax_highlighting::highlight
  78: std::panicking::try
  79: rust_analyzer::handlers::request::handle_semantic_tokens_range
  80: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 1:45:00 PM] Request textDocument/semanticTokens/range failed.
  Message: request handler panicked: index out of bounds: the len is 1 but the index is 2
  Code: -32603 
Panic context:
> 
version: 0.4.1624-standalone (2fbe69d11 2023-08-12)
request: textDocument/hover HoverParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/workspace/main.rs",
            query: None,
            fragment: None,
        },
    },
    position: Position(
        Position {
            line: 9,
            character: 21,
        },
    ),
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
}

> impl_trait_query(ImplId(45890) -> ItemLoc { container: ModuleId { krate: Idx::<CrateData>(227), block: None, local_id: Idx::<ModuleData>(3) }, id: ItemTreeId { tree: TreeId { file: FileId(FileId(11550)), block: None }, value: Idx::<Impl>(0) } } -> ImplData { target_trait: Some(TraitRef { path: Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("ToTokenTree"))] }, generic_args: None } }), self_ty: Path(Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("Date"))] }, generic_args: None }), items: [FunctionId(FunctionId(30977))], is_negative: false, attribute_calls: None })

> impl_self_ty_query(ImplId(45890) -> ItemLoc { container: ModuleId { krate: Idx::<CrateData>(227), block: None, local_id: Idx::<ModuleData>(3) }, id: ItemTreeId { tree: TreeId { file: FileId(FileId(11550)), block: None }, value: Idx::<Impl>(0) } } -> ImplData { target_trait: Some(TraitRef { path: Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("ToTokenTree"))] }, generic_args: None } }), self_ty: Path(Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("Date"))] }, generic_args: None }), items: [FunctionId(FunctionId(30977))], is_negative: false, attribute_calls: None })

> DefMap Idx::<CrateData>(227) crate_name=Some(CrateDisplayName { crate_name: CrateName("atoi"), canonical_name: "atoi" }) block=None path=Date

thread 'Worker' panicked at 'index out of bounds: the len is 1 but the index is 3', crates/hir-def/src/nameres/path_resolution.rs:424:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:162:5
   3: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro_single
   4: hir_def::resolver::ModuleItemMap::resolve_path_in_type_ns
   5: hir_def::resolver::Resolver::resolve_path_in_type_ns
   6: hir_ty::lower::TyLoweringContext::lower_ty_ext
   7: hir_ty::lower::impl_self_ty_query
   8: salsa::runtime::Runtime::execute_query_implementation
   9: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  10: salsa::derived::slot::Slot<Q,MP>::read
  11: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  12: salsa::QueryTable<Q>::get
  13: <DB as hir_ty::db::HirDatabase>::impl_self_ty
  14: hir_ty::lower::impl_trait_query
  15: salsa::runtime::Runtime::execute_query_implementation
  16: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  17: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  18: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  19: salsa::derived::slot::MemoRevisions::validate_memoized_value
  20: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  21: salsa::derived::slot::Slot<Q,MP>::read
  22: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  23: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate::__shim
  24: hir::Impl::all_for_type
  25: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  26: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  27: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  28: ide::goto_implementation::goto_implementation
  29: salsa::Cancelled::catch
  30: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  31: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  32: rust_analyzer::handlers::request::handle_hover
  33: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 0.4.1624-standalone (2fbe69d11 2023-08-12)
request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/workspace/operation.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 0,
            character: 0,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
        trigger_kind: Some(
            Automatic,
        ),
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

> impl_trait_query(ImplId(19521) -> ItemLoc { container: ModuleId { krate: Idx::<CrateData>(667), block: None, local_id: Idx::<ModuleData>(8) }, id: ItemTreeId { tree: TreeId { file: FileId(FileId(11882)), block: None }, value: Idx::<Impl>(0) } } -> ImplData { target_trait: Some(TraitRef { path: Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("Sync"))] }, generic_args: None } }), self_ty: Path(Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("ScopedKey"))] }, generic_args: Some([Some(GenericArgs { args: [Type(Path(Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("T"))] }, generic_args: None }))], has_self_type: false, bindings: [], desugared_from_fn: false })]) }), items: [], is_negative: false, attribute_calls: None })

> impl_self_ty_query(ImplId(19521) -> ItemLoc { container: ModuleId { krate: Idx::<CrateData>(667), block: None, local_id: Idx::<ModuleData>(8) }, id: ItemTreeId { tree: TreeId { file: FileId(FileId(11882)), block: None }, value: Idx::<Impl>(0) } } -> ImplData { target_trait: Some(TraitRef { path: Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("Sync"))] }, generic_args: None } }), self_ty: Path(Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("ScopedKey"))] }, generic_args: Some([Some(GenericArgs { args: [Type(Path(Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("T"))] }, generic_args: None }))], has_self_type: false, bindings: [], desugared_from_fn: false })]) }), items: [], is_negative: false, attribute_calls: None })

> DefMap Idx::<CrateData>(667) crate_name=Some(CrateDisplayName { crate_name: CrateName("sha2"), canonical_name: "sha2" }) block=None path=ScopedKey

thread 'Worker' panicked at 'index out of bounds: the len is 7 but the index is 8', crates/hir-def/src/nameres/path_resolution.rs:424:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:162:5
   3: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro_single
   4: hir_def::resolver::ModuleItemMap::resolve_path_in_type_ns
   5: hir_def::resolver::Resolver::resolve_path_in_type_ns
   6: hir_ty::lower::TyLoweringContext::lower_ty_ext
   7: hir_ty::lower::impl_self_ty_query
   8: salsa::runtime::Runtime::execute_query_implementation
   9: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  10: salsa::derived::slot::Slot<Q,MP>::read
  11: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  12: salsa::QueryTable<Q>::get
  13: <DB as hir_ty::db::HirDatabase>::impl_self_ty
  14: hir_ty::lower::impl_trait_query
  15: salsa::runtime::Runtime::execute_query_implementation
  16: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  17: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  18: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  19: salsa::derived::slot::MemoRevisions::validate_memoized_value
  20: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  21: salsa::derived::slot::Slot<Q,MP>::read
  22: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  23: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate::__shim
  24: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  25: hir_ty::method_resolution::TraitImpls::trait_impls_in_deps_query
  26: salsa::runtime::Runtime::execute_query_implementation
  27: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  28: salsa::derived::slot::Slot<Q,MP>::read
  29: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  30: salsa::QueryTable<Q>::get
  31: <DB as hir_ty::db::HirDatabase>::trait_impls_in_deps
  32: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::impls_for_trait
  33: chalk_recursive::solve::SolveIterationHelpers::solve_from_clauses
  34: chalk_recursive::solve::SolveIteration::solve_iteration
  35: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  36: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  37: hir_ty::traits::trait_solve_query
  38: salsa::runtime::Runtime::execute_query_implementation
  39: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  40: salsa::derived::slot::Slot<Q,MP>::read
  41: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  42: salsa::QueryTable<Q>::get
  43: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  44: hir_ty::db::trait_solve_wait
  45: hir_ty::infer::coerce::<impl hir_ty::infer::unify::InferenceTable>::coerce_inner
  46: hir_ty::infer::coerce::<impl hir_ty::infer::unify::InferenceTable>::coerce
  47: hir_ty::infer::coerce::<impl hir_ty::infer::InferenceContext>::coerce
  48: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
  49: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  50: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  51: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  52: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  53: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_return
  54: hir_ty::infer::infer_query
  55: salsa::runtime::Runtime::execute_query_implementation
  56: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  57: salsa::derived::slot::Slot<Q,MP>::read
  58: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  59: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  60: <DB as hir_ty::db::HirDatabase>::infer_query
  61: hir_ty::db::infer_wait
  62: <DB as hir_ty::db::HirDatabase>::infer
  63: hir::DefWithBody::diagnostics
  64: hir::ModuleDef::diagnostics
  65: hir::Module::diagnostics
  66: ide_diagnostics::diagnostics
  67: std::panicking::try
  68: ide::Analysis::assists_with_fixes
  69: rust_analyzer::handlers::request::handle_code_action
  70: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 0.4.1624-standalone (2fbe69d11 2023-08-12)
request: textDocument/hover HoverParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/evan_richards/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs",
            query: None,
            fragment: None,
        },
    },
    position: Position(
        Position {
            line: 501,
            character: 9,
        },
    ),
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
}

> impl_trait_query(ImplId(45890) -> ItemLoc { container: ModuleId { krate: Idx::<CrateData>(227), block: None, local_id: Idx::<ModuleData>(3) }, id: ItemTreeId { tree: TreeId { file: FileId(FileId(11550)), block: None }, value: Idx::<Impl>(0) } } -> ImplData { target_trait: Some(TraitRef { path: Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("ToTokenTree"))] }, generic_args: None } }), self_ty: Path(Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("Date"))] }, generic_args: None }), items: [FunctionId(FunctionId(30977))], is_negative: false, attribute_calls: None })

> impl_self_ty_query(ImplId(45890) -> ItemLoc { container: ModuleId { krate: Idx::<CrateData>(227), block: None, local_id: Idx::<ModuleData>(3) }, id: ItemTreeId { tree: TreeId { file: FileId(FileId(11550)), block: None }, value: Idx::<Impl>(0) } } -> ImplData { target_trait: Some(TraitRef { path: Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("ToTokenTree"))] }, generic_args: None } }), self_ty: Path(Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("Date"))] }, generic_args: None }), items: [FunctionId(FunctionId(30977))], is_negative: false, attribute_calls: None })

> DefMap Idx::<CrateData>(227) crate_name=Some(CrateDisplayName { crate_name: CrateName("atoi"), canonical_name: "atoi" }) block=None path=Date

thread 'Worker' panicked at 'index out of bounds: the len is 1 but the index is 3', crates/hir-def/src/nameres/path_resolution.rs:424:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:162:5
   3: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro_single
   4: hir_def::resolver::ModuleItemMap::resolve_path_in_type_ns
   5: hir_def::resolver::Resolver::resolve_path_in_type_ns
   6: hir_ty::lower::TyLoweringContext::lower_ty_ext
   7: hir_ty::lower::impl_self_ty_query
   8: salsa::runtime::Runtime::execute_query_implementation
   9: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  10: salsa::derived::slot::Slot<Q,MP>::read
  11: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  12: salsa::QueryTable<Q>::get
  13: <DB as hir_ty::db::HirDatabase>::impl_self_ty
  14: hir_ty::lower::impl_trait_query
  15: salsa::runtime::Runtime::execute_query_implementation
  16: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  17: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  18: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  19: salsa::derived::slot::MemoRevisions::validate_memoized_value
  20: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  21: salsa::derived::slot::Slot<Q,MP>::read
  22: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  23: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate::__shim
  24: hir::Impl::all_for_type
  25: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  26: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  27: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  28: ide::goto_implementation::goto_implementation
  29: salsa::Cancelled::catch
  30: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  31: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  32: rust_analyzer::handlers::request::handle_hover
  33: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 3:55:53 PM] Request textDocument/hover failed.
  Message: request handler panicked: index out of bounds: the len is 1 but the index is 3
  Code: -32603

**Comment by evbo** [comment] 2023-08-19 17:15
Here is how the error alerts me in VS Code UI:

![image](https://github.com/rust-lang/rust-analyzer/assets/6313004/a6f20db9-011b-46b8-8304-1770ea6b474b)

**Comment by JojiiOfficial** [comment] 2023-09-02 16:20
I have the same issue (with a slightly changed line number) in 0.3.1641-standalone from 28.08.2023

**Comment by lnicola** [comment] 2023-09-09 17:14
Duplicate of #5366.

**Closed by lnicola** 2023-09-09 17:14 UTC
Labels: C-bug, I-panic
