### ISSUE TITLE
rust-analyzer's latest stable release in openvsx extension is 9 months ago

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [rust-lang/rust-analyzer#13263] opened 2022-09-19 19:26 UTC
i unable to nightly

**Comment by lnicola** [comment] 2022-09-19 19:27
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/11080, you need to download the VSIX from the GitHub releases page.

**Closed by lnicola** 2022-09-19 19:27 UTC
