### ISSUE TITLE
Resolve simple declarative macros in `#[doc = ...]`

### ISSUE THREAD

**Issue by not-my-profile** [rust-lang/rust-analyzer#15326] opened 2023-07-22 04:52 UTC
A common use case would be `#[doc = include_str!("../../README.md")]`. Such include calls currently do not appear to be resolved by rust-analyzer (hovering over the identifier doesn't show the documentation from the README).

It would be great if rust-analyzer could additionally resolve simple custom declarative macros in `#[doc = ...]`, e.g:

```rs
macro_rules! link {
    ($label:literal, $path:literal) => {
        concat!("[", $label, "](https://example.com/some/path", $path, ")")
    };
}

#[doc = link!("foo", "/bar.html")]
struct Foo;
```

**Comment by Veykril** [comment] 2023-07-30 10:54
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/8092

**Closed by Veykril** 2023-07-30 10:54 UTC
Labels: C-feature
