### ISSUE TITLE
Uses of `std::env!` macro underlined as error

### ISSUE THREAD

**Issue by CorinJG** [rust-lang/rust-analyzer#13751] opened 2022-12-09 22:33 UTC
If my code includes `env!("FOO")`, it is underlined in red and the diagnostic message says 'environment variable "FOO" not defined'. Surely it's not desirable as people often develop in an environment without the necessary compile time environment variables exported.

**rust-analyzer version**: 0.3.1309-standalone
**rustc version**: 1.65.0
**relevant settings**: n/a

**Comment by jhgg** [comment] 2022-12-16 10:13
This is a rustc error, caused by flycheck (check on save)  invoking  `cargo check`.

**Comment by huangjj27** [comment] 2022-12-26 13:33
Here is my solution to make it works: use [`zenv-cli`](https://github.com/numToStr/zenv#cli) to import a test/dev version environment:
```
{
    "rust-analyzer.cargo.buildScripts.overrideCommand": [
        "zenv",
        "-f",
        ".env/test.env",
        "cargo",
        "--",
        "check",
        "--quiet",
        "--workspace",
        "--message-format=json",
        "--all-targets"
    ],
    "rust-analyzer.checkOnSave.overrideCommand": [
        "zenv",
        "-f",
        ".env/test.env",
        "cargo",
        "--",
        "+nightly",
        "check",
        "--quiet",
        "--workspace",
        "--message-format=json",
        "--all-targets"
    ]
}
```

**Comment by jonas-schievink** [comment] 2023-01-26 17:27
Closing, since this is not our bug

**Closed by jonas-schievink** 2023-01-26 17:27 UTC
