### ISSUE TITLE
didn't kill cargo check process after exit

### ISSUE THREAD

**Issue by GopherJ** [rust-lang/rust-analyzer#9156] opened 2021-06-07 00:45 UTC
sometimes when I exit vim, and execute cargo check manually, things block there for a very long time (30seconds)

<img width="441" alt="image" src="https://user-images.githubusercontent.com/33961674/120945709-a8f5ab80-c76c-11eb-9bdf-93e3e23c8ba0.png">

**Comment by lnicola** [comment] 2021-06-07 08:42
Probably duplicate of #5258. Can you check the running processes to see what's running?

 - `rust-analyzer`
 - `cargo`
 - `rustc`

**Comment by Veykril** [comment] 2023-02-08 10:49
This should no longer happen I believe since we are using process groups now

**Closed by Veykril** 2023-02-08 10:49 UTC
Labels: S-unactionable, C-bug
