### ISSUE TITLE
Remove all unused imports within in selected range 

### ISSUE THREAD

**Issue by nielsle** [rust-lang/rust-analyzer#12587] opened 2022-06-20 09:25 UTC
I would love to be able to do the following in vscode

* Select 10 lines that include a use-declaration.
* Press ctrl-.
* Choose "Remove all unused imports in selected range"

**Comment by lnicola** [comment] 2022-06-20 09:39
Mostly duplicate of https://github.com/rust-lang/rust-analyzer/issues/5131.

**Closed by lnicola** 2022-06-20 09:39 UTC
