### ISSUE TITLE
The RA crashed into the 'proc-macro-srv-cli'

### ISSUE THREAD

**Issue by zerodegress** [rust-lang/rust-analyzer#14991] opened 2023-06-06 06:45 UTC
**rust-analyzer version**: rust-analyzer version: 0.3.1541-standalone (2f1b7cedc 2023-06-04)

**rustc version**: rustc 1.72.0-nightly (e6d4725c7 2023-06-05)

```
thread 'main' panicked at 'proc-macro-srv-cli requires the `sysroot-abi` feature to be enabled', crates\proc-macro-srv-cli\src/main.rs:23:5
stack backtrace:
   0: begin_panic_handler
             at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library\std\src/panicking.rs:593:5
   1: panic_fmt
             at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library\core\src/panicking.rs:67:14
   2: rust_analyzer_proc_macro_srv::main
```

looks like that.
i am using the crate bevy, and when i use some macros there comes the crash:
<img width="687" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/60560055/a69f89d9-cdfa-4143-9530-2ce0d5526e75">
looks like it is saying 'the pipe is closing',but i dont know how it means.
i tried to restart the RA event the computer but not working.

**Comment by lnicola** [comment] 2023-06-06 06:57
Can't reproduce in 0.3.1541. Do you have any settings like `rust-analyzer.server.path`?

**Comment by Veykril** [comment] 2023-06-06 06:58
That's using yesterdays nightly proc macro server, I wonder did something go wrong with the subtree sync?

**Comment by lnicola** [comment] 2023-06-06 07:00
Oh, right, I had the previous nightly. Oof.

**Comment by Veykril** [comment] 2023-06-06 07:09
```diff
-in-rust-tree = [
    "proc-macro-srv/sysroot-abi",
    "ide/in-rust-tree",
    "syntax/in-rust-tree",
]
+sysroot-abi = ["proc-macro-srv-cli/sysroot-abi"]
+in-rust-tree = ["sysroot-abi", "ide/in-rust-tree", "syntax/in-rust-tree"]
```

This is the only diff part that seems relevant, but this should work fine no? Only difference is the intermediate feature flag

**Comment by Veykril** [comment] 2023-06-06 07:11
@zerodegress you can get around this by downgrading your toolchain to a version from before yesterday for now

**Comment by lnicola** [comment] 2023-06-06 07:13
https://github.com/rust-lang/rust/blob/master/src/bootstrap/tool.rs#L707-L718

I think the proc macro server gets built with `proc-macro-srv/sysroot-abi`, but without `sysroot-abi`? But the panic is in `proc-macro-srv-cli`.

**Comment by Veykril** [comment] 2023-06-06 07:16
Ah, that explains it. `proc-macro-srv-cli` was previously a dependency of `proc-macro-srv` https://github.com/rust-lang/rust-analyzer/pull/14432/files#diff-90bc501a1b3268c21aa349b968f706e31ac022ddb76b05eb675ca44066eb1ecb

So no subtree problems, we just need to update the build step

**Comment by lnicola** [comment] 2023-06-09 03:51
Fixed in the `2023-06-08` nightly toolchain.

**Closed by lnicola** 2023-06-09 03:51 UTC
Labels: Broken Window, C-bug
