### ISSUE TITLE
Feature: Allow exclusion of specific crates/modules/(methods?) in completions

### ISSUE THREAD

**Issue by tgrushka** [rust-lang/rust-analyzer#18159] opened 2024-09-21 20:20 UTC
Hi, I'm a legally blind Rust developer and reducing the amount of clutter would make things easier for me -- probably for others as well. I'm sorry if this has already been requested, please refer to that issue if so, as I did search without success, and there are so many issues.

Crates like `colored_json` or any other crate that add "extension" methods on almost all objects can really clutter the completions list. Adding the setting: `"rust-analyzer.completion.limit": 10` really doesn't help much, as the limit of completions depends on the object. Therefore, I kindly request a new setting be added, for example:

```
    "rust-analyzer.completions.ignorePatterns": [
        "colored_json::",
        "borrow_mut()",
    ],
```

With a setting like this, we could ignore specific crates, modules, or even methods from showing up. I'm not set on the name/format, I would defer to the Rust experts on that.

Thanks for your consideration.

**Comment by ChayimFriedman2** [comment] 2024-09-21 21:38
Yes this was already asked, e.g. https://github.com/rust-lang/rust-analyzer/issues/17477 and others.

I do think this is something we ought to support though.

**Comment by Veykril** [comment] 2024-09-24 08:40
Closing as a duplicate of #17477

**Closed by Veykril** 2024-09-24 08:40 UTC
Labels: C-feature
