### ISSUE TITLE
[bug] LSP autocompletes with completely different completion from what was selected

### ISSUE THREAD

**Issue by TheBearodactyl** [rust-lang/rust-analyzer#18558] opened 2024-11-25 15:56 UTC
**rust-analyzer version**: 2024-11-25

**rustc version**: rustc 1.83.0-nightly (6b9676b45 2024-10-12)

**editor or extension**: Lunarvim/Neovim

**relevant settings**: No custom settings

**repository link (if public, optional)**: No repository needed

**code snippet to reproduce**:  No code needed

So pretty much, every time i try to autocomplete something, it autocompletes with a completely irrelevant autocompletion. this happens even if i type in just about the entire thing I'm trying to get it to complete before tab-entering it

(video for reference)

https://github.com/user-attachments/assets/e4fb03da-1e65-4bdf-bf78-b1f21a7a45bf

**Comment by ChayimFriedman2** [comment] 2024-11-25 16:20
Probably a duplicate of #18536. Can you check if the solution there works for you?

**Comment by TheBearodactyl** [comment] 2024-11-25 16:27
> Probably a duplicate of [#18536](https://github.com/rust-lang/rust-analyzer/issues/18536). Can you check if the solution there works for you?

sure

**Comment by flodiebold** [comment] 2024-11-26 10:37
Let's close this in favor of #18547, which is still open.

**Closed by flodiebold** 2024-11-26 10:37 UTC
Labels: C-bug
