### ISSUE TITLE
First-class function-aware completions

### ISSUE THREAD

**Issue by abread** [rust-lang/rust-analyzer#17683] opened 2024-07-24 13:44 UTC
rust-analyzer seems to always consider functions as things to be called. Concretely, when using default settings, functions are inserted with parenthesis even if the function exactly matches the type expected for that argument/field/etc.

e.g. when the cursor is after `map(` in this code, rust-analyzer should suggest `mapper` without parenthesis/snippets before suggesting `mapper` with them:
```rust
fn mapper(x: X) -> Y { /* ... */  }

fn f() -> Option<Y> {
    let option: Option<X> = /* ... */;
    option.map(/*mapper*/)
}
```

rust-analyzer should consider the type of the function and separately consider suggesting the function name and calling the function, ideally with awareness of the underlying types.
I'd expect this to also apply to enum variant constructors (whose internal representation may be different from functions/methods).

Disclaimer: I have no idea if this is viable nor how it fits into rust-analyzer
That said, this is a common pain point for me and I'm willing to learn and take a crack at implementing this (with some pointers) :)

**Comment by roife** [comment] 2024-07-24 17:43
I really want this feature as well! If the cursor is on the arg and its type matches the completion item's type, and the completion item is a variant constructor or a function/closure, we should complete only the name.

**Comment by Veykril** [comment] 2024-07-24 20:03
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/3148

**Closed by Veykril** 2024-07-24 20:03 UTC
Labels: A-completion, C-feature
