### ISSUE TITLE
VSCode: running debug on test trigger error 'Invalid 'cwd' value'

### ISSUE THREAD

**Issue by bespegit** [rust-lang/rust-analyzer#16023] opened 2023-12-05 10:39 UTC
![image](https://github.com/rust-lang/rust-analyzer/assets/151434406/26a2935c-63f6-490d-857a-d2b1762b19eb)
When I try to run a debugging on test i have a this error. I have installed a C/C++ extension and MSVC toolchain for debugging on Windows 10 x64. On Ubuntu with CodeLLDB extenson this problem is not caused.
Output from VSCode debug-terminal:
`Finished test [unoptimized + debuginfo] target(s) in 0.00s
Launching debug configuration:
{
  "type": "cppvsdbg",
  "request": "launch",
  "name": "test some_test",
  "program": "C:\\Users\\dev\\Desktop\\projects\\ra-test-debug\\target\\debug\\deps\\ra_test_debug-c7a9528420d6f394.exe",
  "args": [
    "some_test",
    "--exact",
    "--nocapture"
  ],
  "cwd": "C:\\Users\\dev\\Desktop\\projects\\ra-test-debug\\Cargo.toml",
  "sourceFileMap": {},
  "env": {
    "RUST_BACKTRACE": "short",
    ...
    "VSCODE_CWD": "C:\\Users\\dev\\Desktop\\projects\\ra-test-debug",
    ...
  }
}`

rust-analyzer version: 0.3.1756-standalone (e402c494b 2023-12-01)
rustc version: 1.76.0-nightly (2f8d81f9d 2023-11-21)
vscode version: 1.84.2 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e x64

**Comment by lnicola** [comment] 2023-12-05 11:04
Duplicate of #16010.

**Closed by lnicola** 2023-12-05 11:04 UTC
Labels: C-bug
