### ISSUE TITLE
rust-analyzer shows {unknown} types when it's not clear why it wouldn't be able to

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust-analyzer#15387] opened 2023-08-03 04:10 UTC
**rust-analyzer version**: 0.3.1607-standalone

**rustc version**: 1.71.0

In the following code:
```rust
pub fn foo<T, I: IntoIterator<Item=T>,J: IntoIterator<Item=T>>(i: I, j: J) -> impl Iterator {
    let mut a = i.into_iter();
    let mut b = j.into_iter();

    std::iter::from_fn(move || {
         match (a.next(), b.next()) {
            (Some(a), Some(b)) => Some((a, b)),
            _ => None,
         }
    })
}
```

Hovering at the end of `a.next()` shows `Option<{unknown}>` instead of `Option<T>`, likewise for `b.next()`. Hovering `a` in `Some(a)` shows `{unknown}` instead of `T`, etc.

I thought it could be related to `from_fn`, but in the following:
```rust
pub fn bar<T, I: IntoIterator<Item=T>>(i: I) -> impl Iterator {
    let mut a = i.into_iter();

    std::iter::from_fn(move || {
         match a.next() {
            Some(a) => Some(a),
            _ => None,
         }
    })
}
```
it works fine.

**Comment by flodiebold** [comment] 2023-08-04 10:32
Duplicate of #10653 (and probably a bunch of others)

**Closed by flodiebold** 2023-08-04 10:32 UTC
Labels: A-ty, C-bug
