### ISSUE TITLE
Quick fix  erroneously escapes curly braces

### ISSUE THREAD

**Issue by acycliczebra** [rust-lang/rust-analyzer#16626] opened 2024-02-21 08:20 UTC
When I use the quick fix feature, the autocomplete inserts an escape backslash to every curly brace character.

https://github.com/rust-lang/rust-analyzer/assets/23509613/a84674da-86c0-4633-864e-f860dba81c9b

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

rust-analyzer version: 0.3.1850-standalone (68c506fd6 2024-02-19)

*(It works when I rolled back to an older version, so it is likely a regression)*

**rustc version**: (eg. output of `rustc -V`)

rustc 1.76.0 (07dca489a 2024-02-04)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

None

**Comment by Skgland** [comment] 2024-02-21 08:37
I think this might be a duplicate of #16607

**Comment by Young-Flash** [comment] 2024-02-21 09:12
fixed in https://github.com/rust-lang/rust-analyzer/pull/16618

**Closed by Young-Flash** 2024-02-21 09:12 UTC
Labels: C-bug

**Comment by acycliczebra** [comment] 2024-02-21 09:20
> fixed in #16618

Should the fix not be in release?

**Comment by Young-Flash** [comment] 2024-02-21 09:33
check out [here](https://github.com/rust-lang/rust-analyzer/releases/tag/nightly)
