### ISSUE TITLE
Latest release bugs (v0.3.1506) missing unsafe errors : when using `bit_flags` and derive traits

### ISSUE THREAD

**Issue by hnyls2002** [rust-lang/rust-analyzer#14766] opened 2023-05-09 02:46 UTC
**rust-analyzer version**: rust-analyzer version: 0.3.1506-standalone

**rustc version**: rustc 1.64.0-nightly (f6f9d5e73 2022-08-04)

**relevant settings**: 

This is my cargo
```
[package]
name = "os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
bitflags = "1.2.1"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
xmas-elf = "0.7.0"

[features] 
default = ["larger_memory"]

# for larger memory to load app's elf file with debug symbols
larger_memory = []

# for loggers
NoneLog = []
Error = []
Warn = ["Error"]
Debug = ["Warn"]
Info = ["Debug"]
Trace = ["Info"]

[profile.release]
debug = true
```

Today when I open my vscode to check my repo, I found there are so many rust errors appears. They are all

`this operation is unsafe and requires an unsafe function or block`

which appear at 

```rust
bitflags! {
    pub struct PTEFlags : usize{
        const V = 1 << 0; // valid
        const R = 1 << 1; // readable
        const W = 1 << 2; // writable
        const X = 1 << 3; // executable
        const U = 1 << 4; // user
        const G = 1 << 5; // global
        const A = 1 << 6; // accessed
        const D = 1 << 7; // dirty
    }
}


```

```
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
```

This is the shoot cut 

![image](https://user-images.githubusercontent.com/95566987/236980636-4e2e4700-97c8-4efc-af48-3be9c8eef0ce.png)

![image](https://user-images.githubusercontent.com/95566987/236980725-febf87e5-37f8-433c-bcf6-56019e50bd29.png)

I don't know why...

**Comment by hnyls2002** [comment] 2023-05-09 02:49
The reporting errors are like these
![image](https://user-images.githubusercontent.com/95566987/236981332-813bb3a1-bdd9-4783-9533-0792f29b609d.png)

**Comment by hnyls2002** [comment] 2023-05-09 05:06
When I rollback my rust-analyzer version from `v0.3.1506` to `v0.3.1498`, this problem solved! 

I think this could be a bug for the latest version released yesterday, even `#[derive(Debug, Copy, Clone, Eq, PartialEq)]` will cause errors...

**Comment by HKalbasi** [comment] 2023-05-09 09:47
Which trait(s) causes the error? Can someone post the result of `Expand macro recursively` on that trait?

**Comment by hnyls2002** [comment] 2023-05-09 11:41
Sorry about my previous description about the macro, I just mixed up `lazy_static` with `bit_flags`, where the warnings show is actually the macro `bit_flags` but not `lazy_static`.

And I have checked the traits, I found when only `Debug`, `Copy`, `Clone`, there is no warning.

![image](https://github.com/rust-lang/rust-analyzer/assets/95566987/1a853f1c-afa4-45cf-ac06-dc5237864307)

It seems that `Eq`, `PartialEq`, `Ord`, `PartialOrd` four traits causes the warning, and on each block the number of warnings are multiples of four.

![image](https://github.com/rust-lang/rust-analyzer/assets/95566987/72f6eedf-e0ca-4829-a5fb-fa6de9d522f5)

Also, in the `lazy_static` macro, I clicked into it, and I also found that :

![image](https://github.com/rust-lang/rust-analyzer/assets/95566987/0e29400f-97d2-4027-bced-9617536137fa)

Maybe that's where the problems occur...

**Comment by HKalbasi** [comment] 2023-05-09 17:11
I can't reproduce this on `lazy_static` and `bit_flags` alone, and I'm not sure how to mix them. An standalone reproduction would help.

**Comment by Aeledfyr** [comment] 2023-05-10 01:12
I can reproduce this just using `slotmap`, in a very simple example:  
`Cargo.toml`:
```toml
[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
slotmap = "1.0.6"
```

`src/lib.rs`:
```rust
slotmap::new_key_type! { struct Abc; } // this operation is unsafe and requires an unsafe function or block
```

Expanding the macro shows this:
```rust
#[derive(Copy, Clone, Default, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]
#[repr(transparent)]
struct Abc($crate::KeyData);

impl From<$crate::KeyData> for Abc {
    fn from(k: $crate::KeyData) -> Self {
        Abc(k)
    }
}
unsafe impl $crate::Key for Abc {
    fn data(&self) -> $crate::KeyData {
        self.0
    }
}
```
So it seems that `rust-analyzer` is incorrectly detecting an `unsafe impl` as unsafe code that requires an `unsafe` block?

(I am using rust-analyzer 0.3.1506-standalone in vscode)

**Comment by hnyls2002** [comment] 2023-05-10 01:40
> I can't reproduce this on `lazy_static` and `bit_flags` alone, and I'm not sure how to mix them. An standalone reproduction would help.

Sorry to bother you, my English is not so good. When I mentioned *I mixed `lazy_static` and `bit_flah`*, I didn't mean that I mixed them in my code, but I just wrote the wrong name in this issue. ( The errors occur at `bit_flags`, and have nothing to do with `lazy_static` in my project)

**Comment by Veykril** [comment] 2023-05-10 06:03
This is indeed an issue with pre 1.69 rust versions, https://github.com/rust-lang/rust/pull/100719 we rely on the safe intrinsic attribute which was introduced in 1.69 it seems

**Comment by Aeledfyr** [comment] 2023-05-12 17:32
What version range of rust does rust-analyzer support?  If it's only the latest stable then I guess this can stay closed, but otherwise this issue should be reopened, as the underlying issue is still there.

**Comment by Veykril** [comment] 2023-05-12 18:14
We usually only target the last 2-3 stable releases specifically. Sometimes it's only the latest though. If you can't upgrade your rust version for whatever reason we usually recommend sticking to an older r-a version until you can.

**Comment by kylejlin** [comment] 2023-06-03 06:47
> When I rollback my rust-analyzer version from `v0.3.1506` to `v0.3.1498`, this problem solved!

This worked for me too! Thanks for your help.

**Comment by Veykril** [comment] 2024-07-19 14:41
Closing this as its now certainly out of support range

**Closed by Veykril** 2024-07-19 14:41 UTC
Labels: C-support
