### ISSUE TITLE
Proc-macro derivative::Derivative unresolved

### ISSUE THREAD

**Issue by edwin0cheng** [rust-lang/rust-analyzer#7459] opened 2021-01-27 08:14 UTC
![image](https://user-images.githubusercontent.com/1465785/105921725-3c70e000-6007-11eb-9b27-6f4afbf8e51f.png)
Not working for me unfortunately.

![image](https://user-images.githubusercontent.com/1465785/105921743-4266c100-6007-11eb-9c66-0eb7a3bd37a5.png)

Settings are on true

```
➜ rustc --version
rustc 1.51.0-nightly (da305a2b0 2021-01-05)
```

_Originally posted by @aaomidi in https://github.com/rust-analyzer/rust-analyzer/issues/6053#issuecomment-767905822_

**Comment by edwin0cheng** [comment] 2021-01-27 08:15
[Copy from original issue]

@aaomidi Confirm your bug in `rustc-stable`, 

maybe related to `cfg_attr(not(test)...)`  ?

https://github.com/mcarton/rust-derivative/blob/770c67484a872470ca782202e13fc70a35e2695b/src/lib.rs#L76-L80

```rust
#[cfg_attr(not(test), proc_macro_derive(Derivative, attributes(derivative)))]
pub fn derivative(input: TokenStream) -> TokenStream {
    let mut errors = proc_macro2::TokenStream::new();

    let mut output = match syn::parse::<syn::DeriveInput>(input) {
        Ok(parsed) => {
            ast::Input::from_ast(&parsed, &mut errors)
                .map(|mut input| derive_impls(&mut input, &mut errors))
                .unwrap_or_default()
        },
        Err(error) => {
            errors.extend(error.to_compile_error());
            Default::default()
        }
    };

    output.extend(errors);
    output.into()
}
```

**Comment by jonas-schievink** [comment] 2021-01-27 13:01
> maybe related to `cfg_attr(not(test)...)` ?

Yeah that's it. We always set `cfg(test)`.

**Comment by flodiebold** [comment] 2021-01-27 14:06
So, this is kind of related to #6117, #2414 and #7225.

**Comment by aaomidi** [comment] 2021-01-28 21:37
Confirmed the bug is in stable too. Although I'm not 100% sure how to make sure rust-analyzer is running with the stable toolchain. I just used rustup to change the default and hoped for the best.

**Comment by Rua** [comment] 2021-04-22 08:23
I'm running into this as well with `Derivative`, using rustc 1.52.0-beta.3, rust-analyzer version: 2021-04-12-92-g7570212a5.

**Comment by edwin0cheng** [comment] 2021-04-22 08:30
It will fix by the last item of #8486 :

*  correctly handle "duplicated" crates in the crate graph. I.e, when cfg(test) crate depends on itself without cfg(test).

**Comment by sbrocket** [comment] 2021-07-08 23:00
https://github.com/rust-analyzer/rust-analyzer/commit/8b77e2692cd97552b1b8d66eb51cec69695b3a5b appears to have fixed this with some manual intervention; you can now add `derivative` to `rust-analyzer.cargo.unsetTest` (and then reload the window or restart the RA server).

**Comment by cheako** [comment] 2021-08-29 01:43
I used `use derivative::*;` and it's better.

**Comment by sunilkr** [comment] 2022-02-13 13:31
I still have this issue with `use derivative::Derivative;`. `use derivative::*;` just removes the unresolved error, but docs on hover or any such feature of VSCode doesn't work. It compiles just fine though. Is there a plan to fix this? I am using default RA settings.

```
RA: 
Released on    2/10/2020, 14:54:28
Last updated   2/9/2022, 06:16:38
Identifier     matklad.rust-analyzer
```

```
$ rustc -V
rustc 1.56.1 (59eed8a2a 2021-11-01)
```

**Comment by flodiebold** [comment] 2022-02-13 13:52
@sunilkr Right now, you will need to use the `rust-analyzer.cargo.unsetTest` setting.

**Comment by lnicola** [comment] 2022-05-04 16:59
There is a workaround in the comment above.

**Comment by zeenix** [comment] 2022-05-04 17:02
> There is a workaround in the comment above.

Thanks but the workaround needs to be applied by each dev on their own. I got people looking at my crate's source (possibly contributing) and getting annoyed by my use of derivative.

**Comment by bjorn3** [comment] 2022-05-04 17:04
You can set it in the `.vscode/settings.json` file in your repository. Then it will apply to everyone opening your project.

**Comment by cyqsimon** [comment] 2022-05-28 02:35
Is this issue fixed now? I had a project that used the `use derivative::*;` workaround, but today when I checked, `use derivative::Derivative;` no longer seems to error on my Linux box. Can someone please help confirm/refute this finding?

**Comment by zeenix** [comment] 2022-05-29 12:52
@cyqsimon Yeah, I am unable to reproduce either.

**Comment by flodiebold** [comment] 2022-06-28 17:29
This is fixed now, unless you're using derivative as a path dependency.

**Closed by flodiebold** 2022-06-28 17:29 UTC
Labels: S-unactionable
