### ISSUE TITLE
Latest release version fails to clear previously marked errors after fixing them

### ISSUE THREAD

**Issue by michaeleisel** [rust-lang/rust-analyzer#17305] opened 2024-05-28 18:28 UTC
As of yesterday, when the latest version was released, my VSCode rust-analyzer extension would flag errors in red as expected, but then even after I fixed them, it would fail to remove the red squiggly lines and error message when I mouse over them. This makes the editor fairly unusable, so I downgraded a couple versions and the problem went away.

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
0.3.1975-standalone

**rustc version**: (eg. output of `rustc -V`)
rustc 1.80.0-nightly (7d83a4c13 2024-05-06)

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable)
VSCode

0.3.1975

**Comment by lnicola** [comment] 2024-05-28 18:48
Duplicate of #17300, should be fixed by #17302.

**Closed by lnicola** 2024-05-28 18:48 UTC
Labels: C-bug
