### ISSUE TITLE
Request textDocument/semanticTokens/full/delta failed.

### ISSUE THREAD

**Issue by cybersoulK** [rust-lang/rust-analyzer#15218] opened 2023-07-05 20:22 UTC
I have the following error often for 1 year:

> impl_self_ty_query(ImplId(13944) -> ItemLoc { container: ModuleId { krate: Idx::<CrateData>(140), block: None, local_id: Idx::<ModuleData>(1) }, id: ItemTreeId { tree: TreeId { file: FileId(FileId(275)), block: None }, value: Idx::<Impl>(8) } } -> ImplData { target_trait: None, self_ty: Path(Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("LogicalPosition"))] }, generic_args: Some([Some(GenericArgs { args: [Type(Path(Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("P"))] }, generic_args: None }))], has_self_type: false, bindings: [], desugared_from_fn: false })]) }), items: [FunctionId(FunctionId(52313))], is_negative: false, attribute_calls: None })

> DefMap Idx::<CrateData>(140) crate_name=Some(CrateDisplayName { crate_name: CrateName("smol_str"), canonical_name: "smol_str" }) block=None path=LogicalPosition

thread 'Worker' panicked at 'index out of bounds: the len is 1 but the index is 1', crates/hir-def/src/nameres/path_resolution.rs:424:33
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro_single
   4: hir_def::resolver::Resolver::resolve_path_in_type_ns
   5: hir_ty::lower::TyLoweringContext::lower_ty_ext
   6: hir_ty::lower::impl_self_ty_query
   7: salsa::runtime::Runtime::execute_query_implementation
   8: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   9: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  10: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  11: salsa::derived::slot::MemoRevisions::validate_memoized_value
  12: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  13: salsa::derived::slot::Slot<Q,MP>::read
  14: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  15: <DB as hir_ty::db::HirDatabase>::inherent_impls_in_crate::__shim
  16: hir_ty::method_resolution::incoherent_inherent_impl_crates
  17: salsa::runtime::Runtime::execute_query_implementation
  18: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  19: salsa::derived::slot::Slot<Q,MP>::read
  20: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  21: <DB as hir_ty::db::HirDatabase>::incoherent_inherent_impl_crates::__shim
  22: hir_ty::method_resolution::def_crates
  23: hir_ty::method_resolution::iterate_method_candidates_with_autoref::{{closure}}
  24: hir_ty::method_resolution::iterate_method_candidates_dyn
  25: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  26: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
  27: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  28: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  29: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  30: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  31: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_return
  32: hir_ty::infer::infer_query
  33: salsa::runtime::Runtime::execute_query_implementation
  34: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  35: salsa::derived::slot::Slot<Q,MP>::read
  36: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  37: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  38: <DB as hir_ty::db::HirDatabase>::infer_query
  39: hir_ty::db::infer_wait
  40: <DB as hir_ty::db::HirDatabase>::infer
  41: hir::DefWithBody::diagnostics
  42: hir::ModuleDef::diagnostics
  43: hir::Module::diagnostics
  44: ide_diagnostics::diagnostics
  45: std::panicking::try
  46: ide::Analysis::diagnostics
  47: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::update_diagnostics::{{closure}}::{{closure}}
  48: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  49: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'LspServer' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /Users/runner/work/rust-analyzer/rust-analyzer/crates/stdx/src/thread/pool.rs:86:35
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: stdx::thread::pool::Pool::spawn
   4: rust_analyzer::task_pool::TaskPool<T>::spawn
   5: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event
   6: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
   7: rust_analyzer::main_loop::main_loop
   8: rust_analyzer::run_server
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lsp-server-0.7.1/src/stdio.rs:26:37
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jod-thread-0.1.2/src/lib.rs:33:22
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: jod_thread::JoinHandle<T>::join
   4: stdx::thread::JoinHandle<T>::join
   5: rust_analyzer::with_extra_thread
   6: rust_analyzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Info  - 1:20:15 PM] Connection to server got closed. Server will restart.
true

**Comment by Veykril** [comment] 2023-07-06 05:34
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/10084

**Closed by Veykril** 2023-07-06 05:34 UTC
Labels: C-bug
