### ISSUE TITLE
Support for standalone .rs files without Cargo.toml

### ISSUE THREAD

**Issue by sohang3112** [rust-lang/rust-analyzer#15072] opened 2023-06-18 02:27 UTC
I want to try using Rust for short scripts (similar to scripting in Bash or Python). Creating a full-fledged Cargo project can be overkill for such tasks.

I can compile & run these standalone scripts using `rustc script.rs`. It would be nice if Rust Analzyer also supported such scripts (for example, showing the *Run* button above `fn main()` in VS Code).

**Comment by Veykril** [comment] 2023-07-12 05:18
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/14318

Also just to note, for `cargo script` support we'd also need to first see support for `cargo metadata` parsing cargo scripts

**Closed by Veykril** 2023-07-12 05:18 UTC
Labels: C-feature
