### ISSUE TITLE
rename doesn't work in some cases

### ISSUE THREAD

**Issue by adsick** [rust-lang/rust-analyzer#11262] opened 2022-01-12 10:40 UTC
example:
```rust
let price: Option<u128> = price.map(|price| price.0);
```
let's say we want to rename closure parameter 'price' using rename feature. For me it won't work as intended and I will get this: 
```rust
price: Option<u128> = price.map(|p| price.0);
```
where I wanted this:
```rust
price: Option<u128> = price.map(|p| p.0);
```
I use rename a lot and most time it works but I feel like this particular is a bug.

**rust-analyzer version**:
rust-analyzer version: 7d6fcbc0b 2021-12-06 stable

**rustc version**
rustc 1.56.1 (59eed8a2a 2021-11-01)

**Comment by Veykril** [comment] 2022-01-12 10:54
Renaming price in the closure, either the parameter or the usage in the body works fine for me
![Code_JQf4yBi6ig](https://user-images.githubusercontent.com/3757771/149127048-edc690ca-ab94-41f6-b4b1-e99c10cfb1ad.gif)

**Comment by adsick** [comment] 2022-01-12 10:58
Idk, maybe the context matters here

**Comment by HKalbasi** [comment] 2023-05-17 21:12
Closing since this can not be reproduced for a long time. Feel free to reopen if you find a reproducible example.

**Closed by HKalbasi** 2023-05-17 21:12 UTC
Labels: S-unactionable
