### ISSUE TITLE
Async job failed: protocol error: InternalError: request handler panicked: assertion failed: check\_disjoint\_and\_sort(indels)

### ISSUE THREAD

**Issue by dogunbound** [rust-lang/rust-analyzer#14256] opened 2023-03-05 22:19 UTC
[dogunbound@archlinux ~]$ rust-analyzer --version
rust-analyzer 1.67.1 (d5a82bb 2023-02-07)
[dogunbound@archlinux ~]$ rustc --version
rustc 1.67.1 (d5a82bbd2 2023-02-07)
[dogunbound@archlinux ~]$ 

https://github.com/dogunbound/PACRB/tree/068c7daa57bb4f5ae69d207293b601e329b14c7b

in file utils/src/resource_manager/asset.rs, using helix, I try to auto fill the crate imports with `<space>a`, and the error `Async job failed: protocol error: InternalError: request handler panicked: assertion failed: check\_disjoint\_and\_sort(indels)` shows up pretty reliably. I have no clue why it happens. I only know I can pretty reliably reproduce it whenever I type `<space>a` on line 6 to auto import `Meta`

**Comment by Krahos** [comment] 2024-03-15 10:27
I also sometimes get this error on Helix. It's super annoying and occurs when i try to use autocompletion. [Here](https://github.com/helix-editor/helix/discussions/8295) more details.

**Comment by Veykril** [comment] 2024-04-28 15:10
I can't reproduce OPs report, Krahos your issue is a different which should be fixed

**Comment by pascalkuthe** [comment] 2024-04-28 16:51
I can reproduce neither of those cases with the latest helix version and latest RA nightly build (altough @Krahos case is incomplete since the type definitions are missing but I tried and all of them seem to work for me). This can probably be closed

**Closed** 2024-04-28 17:07 UTC
Labels: S-unactionable, C-bug, I-panic
