### ISSUE TITLE
Bad inference

### ISSUE THREAD

**Issue by realtica** [rust-lang/rust-analyzer#18393] opened 2024-10-23 20:58 UTC
**rust-analyzer version**: v0.3.2154 (latest)

**rustc version**: 1.80.1

**editor or extension**: nvim v0.10

This code works perfectly (diesel) but the type inference is failing, and so the filter function (red) has "No information available".
 
![Image](https://github.com/user-attachments/assets/a9166721-36c6-410a-ba86-d75b7114bac9)

**Comment by flodiebold** [comment] 2024-10-25 06:36
Probably a duplicate of #14607, and not really actionable without (and probably even with) a code example.

**Closed by flodiebold** 2024-10-25 06:36 UTC
Labels: A-ty, C-bug
