### ISSUE TITLE
rust-analyzer v0.3.2180 in vscodium makes it impossible to 'see' the source code in order to fix it

### ISSUE THREAD

**Issue by qknight** [rust-lang/rust-analyzer#18510] opened 2024-11-14 16:39 UTC
I'm developing rust/leptos and using the `view!{...} `macro. Rust-analyzer works great and I can control-click types and the editor changes to the respective implementation of the type.

However, if I use a leptos [component ](https://book.leptos.dev/view/03_components.html) with wrong arguments, then it looks like this:

![Image](https://github.com/user-attachments/assets/9df9fe08-cd38-4f80-940c-b90131654d00)

And the font change is so overwhealming, I literally can't see the source code I'm supposed to fix anymore.

# what I tried so far

https://chatgpt.com/share/67362523-0d4c-800c-b2ae-527304d81320

What strikes me is that using:

  ```
  "editor.tokenColorCustomizations": {

      "textMateRules": [
        {
          "scope": [""],
          "settings": {
            "foreground": "#00ff99",
            "fontStyle": "italic bold underline strikethrough"
          }
        }
      ]
    },
```

I was not able to override "the section in question" BUT everything else! What 

![Image](https://github.com/user-attachments/assets/bb23ccf8-5467-462c-a4a5-2e558178cec5)

Also I'm sorry if this is the wrong issue tracker but the https://open-vsx.org/extension/rust-lang/rust-analyzer links to this GH instance and does not list another tracker.
# versions

* vscodium 1.88.1 release 24104
* rust-analyzer v0.3.2180 (according to the vscodium plugin information)

# the component

```
#[component]
fn ItemsList(
  unique_name: &'static str,
  lists_scroll_states: RwSignal<HashMap<&'static str, i32>>,
) -> impl IntoView {
  let scrollable_div_ref = create_node_ref::<Div>();

  view!{
    <div
    node_ref=scrollable_div_ref
    on:scroll=move |e| {
        if let Some(div) = scrollable_div_ref.get() {
            let scroll_top = div.scroll_top();
            lists_scroll_states
                .update(|data| {
                    data.insert(unique_name, scroll_top);
                });
        }
    }
    class="h-full h-dvh p-1 bg-green-50 rounded-lg mx-1 shadow overflow-y-auto"
  >
    <ul role="list" class="col-span-1 divide-y">
    xxx
    </ul>
    </div>
  }
}
```

**Comment by lnicola** [comment] 2024-11-14 17:15
The error message is from `rustc`, not us (it should show up in `cargo check`), but why does it show up as deprecated? Can you provide an example to test with?

**Comment by qknight** [comment] 2024-11-14 18:39
It shows up in `cargo check`, so your conclusion could be right. I tried to reproduce this with a normal rust macro but so far no luck.

I noticed that too many arguments doesn't trigger the harsh coloring:

![Image](https://github.com/user-attachments/assets/0076d60f-c3cf-41ae-afc7-bae0f233a37d)

This is very likely to do with leptos and how it processes the `view!{}` and **components**.

@gbj any ideas?

Personally I'd be fine with a way to disable the coloring for this in particular. If I just could read the code ... to fix it!

**Comment by qknight** [comment] 2024-11-14 18:54
The code for this project is at https://codeberg.org/slowtec/fairsync.git just in case there is an obvious problem with the directory/file structure for instance. I'll try to get a minimal example of the problem still.

**Comment by gbj** [comment] 2024-11-14 18:56
@qknight This issue does not have to do with rust-analyzer. Please feel free to open a discussion in the Leptos repo if you're looking for help with your project, or an issue in the Leptos repo if there's a way we can improve the error spans coming from the macro, but I don't think there's any action to be taken from rust-analyzer's end.

**Comment by lnicola** [comment] 2024-11-14 19:00
@gbj the error spans are one thing, but it looks like everything in the expansion of `view!` is marked as `#[deprecated]`. I played around in the fairsync repo, but couldn't reproduce it.

**Comment by lnicola** [comment] 2024-11-14 19:16
You can set `"editor.showDeprecated": false` to disable the strike-through on deprecated code. I don't think we can do anything else here, so I'll close this, but feel free to reopen.

**Closed by lnicola** 2024-11-14 19:16 UTC
Labels: C-support

**Comment by qknight** [comment] 2024-11-15 10:14
@lnicola "editor.showDeprecated": false, is exactly what i was looking for! thanks so much!!
