### ISSUE TITLE
Warnings when it shouldn't 

### ISSUE THREAD

**Issue by Migorithm** [rust-lang/rust-analyzer#15039] opened 2023-06-13 02:21 UTC
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

**rustc version**: (eg. output of `rustc -V`)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

## Version
- 3.1549

## Problem 
-  it warns when using derive Hash on enum and it is used in different type 

## Minimum Reproducible Example
```rust
#[derive(Eq,Hash,PartialEq)]
enum State{
    A,
    B,
    C
}

#[derive(Eq,Hash,PartialEq)]
struct User{
    state : State,
    name : String,
}

```

You will get scribbly line on derive part of User type.

**Comment by lnicola** [comment] 2023-06-13 03:32
What do the errors say, and what is your rustc version?

**Comment by Migorithm** [comment] 2023-06-13 04:19
@lnicola 

The error says: "expected &mut {unknown}, found &State"

And my current rustc version is 1.70.0.

**Comment by lnicola** [comment] 2023-06-13 04:21
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/14860 / https://github.com/rust-lang/rust-analyzer/issues/11681.

**Comment by lnicola** [comment] 2023-06-13 04:27
Actually, we can probably work around this.

**Closed** 2023-06-13 06:28 UTC
Labels: C-bug
