### ISSUE TITLE
Build index from command line?

### ISSUE THREAD

**Issue by ice1000** [rust-lang/rust-analyzer#14566] opened 2023-04-14 01:19 UTC
It would be nice if we can build the index before opening vscode from command line

**Comment by lnicola** [comment] 2023-04-14 04:49
There's no persistent index, but you can disable cache priming to get a faster start-up. RA can still be used during the cache priming, though.

**Comment by lnicola** [comment] 2023-04-14 06:11
Duplicate of #4712.

**Closed by lnicola** 2023-04-14 06:11 UTC
Labels: C-feature
