### ISSUE TITLE
`non_camel_case_types` warning can fire spuriously in macros, even when `#[allow]`ed in that module

### ISSUE THREAD

**Issue by SludgePhD** [rust-lang/rust-analyzer#17306] opened 2024-05-28 21:55 UTC
A module that contains a non-camel-case type will produce a warning even though `#![allow(bad_style)]` is present to silence the rustc warning. Adding `#![allow(non_camel_case_types)]` works around this, but rust-analyzer should respect lint groups.

**Comment by mathew-horner** [comment] 2024-05-29 00:55
Hmm, it works for me on `master` and stable. What version are you on?

**Comment by SludgePhD** [comment] 2024-05-29 11:09
Huh, yeah, the actual issue here is more subtle. It can be reproduced by looking at this file: https://github.com/SludgePhD/FeV/blob/dd16b90ee3a93ebc7a72f32ad145ef3b9b6cdde5/src/dlopen.rs

The issue I'm seeing can be (somewhat unreliably) reproduced by replacing the identifier `vaGetDisplayDRM` with `vaGetDisplayDR M` (ie. breaking it into two idents).

When doing that, rust-analyzer will occasionally emit a warning like "Type alias `vaGetDisplayDRM` should have CamelCase name, e.g. `VaGetDisplayDrm`" (sometimes even for the other function names in that module!).

It might be caused by everything going through a macro.

**Comment by Robbepop** [comment] 2024-07-23 09:49
I also experience this bug in my codebase for this PR: https://github.com/wasmi-labs/wasmi/pull/1009
Affected code is the type aliases that are not in `lib.rs` where the `allow` attributes are defined:
```rust
#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
```
Files:

- `memory.rs`: `type wasm_memory_pages_t = u32;`
- `table.rs`: `type wasm_table_size_t = u32;`
- `trap.rs`: `type wasm_message_t = wasm_name_t;`

Screenshot:

![image](https://github.com/user-attachments/assets/3da6620b-7559-4757-a4e8-95bfe6f969f8)

**Comment by lnicola** [comment] 2024-07-23 13:15
This is pretty much a dupe of #6541

**Comment by ChayimFriedman2** [comment] 2024-10-07 18:33
Closing since this should have been fixed. If you see this again, please report!

**Closed by ChayimFriedman2** 2024-10-07 18:33 UTC
Labels: A-diagnostics, C-bug
