### ISSUE TITLE
Autocomplete shouldn't add parens when a fn is expected

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/rust-analyzer#18202] opened 2024-09-27 16:52 UTC
```rs
    Some(" trim me ").map(str::tri)
```
I you press enter it will complete to 
```rs
    Some(" trim me ").map(str::trim(&self))
```
which is not at all what I want!

**Comment by Veykril** [comment] 2024-09-27 19:38
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/3148

**Closed by Veykril** 2024-09-27 19:38 UTC
Labels: C-bug
