### ISSUE TITLE
Extra backslashes when generating a trait method

### ISSUE THREAD

**Issue by JustinHuPrime** [rust-lang/rust-analyzer#16655] opened 2024-02-24 09:38 UTC
**rust-analyzer version**: `0.3.1850-standalone`

**rustc version**: `rustc 1.75.0 (82e1608df 2023-12-21)`

**relevant settings**: default settings

This is a regression from 0.3.1850 and 0.3.1839

When in 0.3.1850 (newer), asking RA to implement the missing members for a trait generates extra backslashes:

```rust
struct SomeStruct {
    field: i32,
}
impl Display for SomeStruct {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result \{
        todo!()
    \}
}
```

When in 0.3.1839 (older), asking RA to implement the same missing member generates the expected code without the extra backslashes:

```rust
struct SomeStruct {
    field: i32,
}
impl Display for SomeStruct {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        todo!()
    }
}
```

**Comment by l1nxy** [comment] 2024-02-24 09:40
fixed in https://github.com/rust-lang/rust-analyzer/pull/16618

**Comment by flodiebold** [comment] 2024-02-24 09:58
Duplicate of #16607

**Closed by flodiebold** 2024-02-24 09:58 UTC
Labels: C-bug
