### ISSUE TITLE
Error: Connection got disposed. ???

### ISSUE THREAD

**Issue by jcdc404** [rust-lang/rust-analyzer#11678] opened 2022-03-11 12:53 UTC
I am constantly getting this error, usually in connection with codeLens/resolve, but also with textDocument/hover and textDocument/documentSymbol recently. The system is unusable, I have also seen top report CPU usabe for rust-analyzer before and/or after lockup above 300%

version
rust-analyzer 5fae65dd2 2022-03-07 stable

analysis stats
Failed to create perf counter: Operation not permitted (os error 1)
Failed to create perf counter: Operation not permitted (os error 1)
Database loaded:     3.02s (metadata 688.58ms; build 195.69ms)
Failed to create perf counter: Operation not permitted (os error 1)
  crates: 1, mods: 11, decls: 169, fns: 122
Item Collection:     15.15s
Failed to create perf counter: Operation not permitted (os error 1)
  exprs: 5081, ??ty: 1 (0%), ?ty: 3 (0%), !ty: 2        
Inference:           7.33s
Total:               22.49s

**Comment by jcdc404** [comment] 2022-03-12 12:14
It's now unusable. 5 minutes working followed by 5 minutes waiting. My project is at a standstill, so I am abandoning VSCode and Rust-Analyzer until some resolution is found. I'll be using text files and cargo check at the command line.

**Comment by lnicola** [comment] 2022-03-12 12:39
Do you get any errors in the Rust Analzser Server Output channel?

**Comment by jcdc404** [comment] 2022-03-12 12:54
Yes, quite a few, but I can't see them because I have closed VSCode. Is there a log file I can open?

**Comment by lnicola** [comment] 2022-03-12 13:07
No. You can configure a log file, but Code doesn't make one.

**Comment by jcdc404** [comment] 2022-03-13 12:11
[Info  - 7:10:29 AM] Connection to server got closed. Server will restart.
[Error - 7:10:29 AM] Request codeLens/resolve failed.
Error: Connection got disposed.
	at Object.dispose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:32:4444)
	at Object.dispose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:37:11843)
	at dg.handleConnectionClosed (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:9891)
	at dg.handleConnectionClosed (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:69283)
	at t (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:9599)
	at jd.invoke (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:14370)
	at yi.fire (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:15139)
	at Pt (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:6:6361)
	at jd.invoke (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:14370)
	at yi.fire (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:15139)
	at ra.fireClose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:17394)
	at Socket.<anonymous> (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:18924)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)

**Comment by jcdc404** [comment] 2022-03-13 12:22
[Info  - 7:21:24 AM] Connection to server got closed. Server will restart.
[Error - 7:21:24 AM] Request codeLens/resolve failed.
Error: Connection got disposed.
	at Object.dispose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:32:4444)
	at Object.dispose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:37:11843)
	at dg.handleConnectionClosed (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:9891)
	at dg.handleConnectionClosed (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:69283)
	at t (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:9599)
	at jd.invoke (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:14370)
	at yi.fire (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:15139)
	at Pt (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:6:6361)
	at jd.invoke (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:14370)
	at yi.fire (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:15139)
	at ra.fireClose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:17394)
	at Socket.<anonymous> (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:18924)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 7:21:24 AM] Request codeLens/resolve failed.
Error: Connection got disposed.
	at Object.dispose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:32:4444)
	at Object.dispose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:37:11843)
	at dg.handleConnectionClosed (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:9891)
	at dg.handleConnectionClosed (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:69283)
	at t (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:9599)
	at jd.invoke (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:14370)
	at yi.fire (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:15139)
	at Pt (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:6:6361)
	at jd.invoke (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:14370)
	at yi.fire (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:15139)
	at ra.fireClose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:17394)
	at Socket.<anonymous> (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:18924)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)

**Comment by jcdc404** [comment] 2022-03-13 12:25
[Info  - 7:25:01 AM] Connection to server got closed. Server will restart.
[Error - 7:25:01 AM] Request codeLens/resolve failed.
Error: Connection got disposed.
	at Object.dispose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:32:4444)
	at Object.dispose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:37:11843)
	at dg.handleConnectionClosed (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:9891)
	at dg.handleConnectionClosed (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:69283)
	at t (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:9599)
	at jd.invoke (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:14370)
	at yi.fire (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:15139)
	at Pt (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:6:6361)
	at jd.invoke (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:14370)
	at yi.fire (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:15139)
	at ra.fireClose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:17394)
	at Socket.<anonymous> (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:18924)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 7:25:01 AM] Request codeLens/resolve failed.
Error: Connection got disposed.
	at Object.dispose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:32:4444)
	at Object.dispose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:37:11843)
	at dg.handleConnectionClosed (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:9891)
	at dg.handleConnectionClosed (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:69283)
	at t (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:9599)
	at jd.invoke (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:14370)
	at yi.fire (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:15139)
	at Pt (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:6:6361)
	at jd.invoke (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:14370)
	at yi.fire (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:15139)
	at ra.fireClose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:17394)
	at Socket.<anonymous> (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:18924)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 7:25:01 AM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:32:4444)
	at Object.dispose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:37:11843)
	at dg.handleConnectionClosed (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:9891)
	at dg.handleConnectionClosed (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:69283)
	at t (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:9599)
	at jd.invoke (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:14370)
	at yi.fire (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:15139)
	at Pt (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:6:6361)
	at jd.invoke (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:14370)
	at yi.fire (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:15139)
	at ra.fireClose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:17394)
	at Socket.<anonymous> (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:18924)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 7:25:01 AM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:32:4444)
	at Object.dispose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:37:11843)
	at dg.handleConnectionClosed (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:9891)
	at dg.handleConnectionClosed (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:69283)
	at t (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:39:9599)
	at jd.invoke (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:14370)
	at yi.fire (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:15139)
	at Pt (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:6:6361)
	at jd.invoke (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:14370)
	at yi.fire (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:15139)
	at ra.fireClose (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:17394)
	at Socket.<anonymous> (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.964/out/main.js:5:18924)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)

**Comment by lnicola** [comment] 2022-03-13 12:42
Try looking here:

![image](https://user-images.githubusercontent.com/308347/158059836-a3d5c007-cb07-40a0-8854-ff0474ea8890.png)

**Comment by lnicola** [comment] 2022-03-13 12:48
Are you using `async-trait` or did you enable the references or method reference code lenses (`rust-analyzer.lens.references`, `rust-analyzer.lens.methodReferences`)?

Your project seems pretty small, can you share it?

**Comment by jcdc404** [comment] 2022-03-13 13:28
I haven't done anything with the configurations. Unfortunately I cannot share it.

**Comment by lnicola** [comment] 2022-03-13 13:38
Can you check the Output channel I mentioned earlier? The errors you've posted aren't really useful.

**Comment by jcdc404** [comment] 2022-03-13 14:25
Those logs were from the Rust Analyzer Language Server. That's all I have unless there's another place I can look.

**Comment by jonas-schievink** [comment] 2023-01-31 15:58
I don't think there's anything we can do here without the actual server logs or source code to reproduce this. Hence, closing.

There are a few known instances where rust-analyzer can take 100% CPU, it is likely to be a duplicate of one of those.

**Closed by jonas-schievink** 2023-01-31 15:58 UTC
Labels: C-support

**Comment by YuXiangZhao** [comment] 2023-09-13 02:02
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: textDocument/hover HoverParams {
    text_document_position_params: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                host: None,
                port: None,
                path: "/home/lixiang/data/soft/RustDemo/basics/src/main.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 48,
            character: 29,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
}

thread '<unnamed>' panicked at 'Internal error, cycle detected:
