### ISSUE TITLE
thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by ViktorVoloshko** [rust-lang/rust-analyzer#15591] opened 2023-09-10 00:02 UTC
I can't reproduce the issue, but code was somewhat similar to this:
```Rust
struct Test {
    // fields here (int or float numbers only)
    string_slice: &'static str,
    // fields here (int or float numbers only)
}

fn main() {
    let string = String::from("test");

    let test = Test {
        // literals assigned to fields
        string_slice: string.as_ref(),
    };
}
```

After typing dot to access string's associated functions, I got error (and continued to get it after each symbol of as_ref()).

Logs (too long to post here): https://pastebin.com/gk27PEkr

**rust-analyzer version**: 0.3.1649-standalone (2df30e1e0 2023-09-03)

**rustc version**: rustc 1.72.0 (5680fa18f 2023-08-23)

**Comment by lnicola** [comment] 2023-09-10 07:01
```
thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\chalk-solve-0.92.0\src\clauses\builtin_traits\fn_family.rs:90:55
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:67
   2: core::panicking::panic
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:117
   3: chalk_solve::clauses::builtin_traits::fn_family::add_fn_trait_program_clauses
   4: chalk_solve::clauses::builder::ClauseBuilder<I>::push_binders
   5: chalk_solve::clauses::builtin_traits::add_builtin_program_clauses
   6: chalk_solve::clauses::program_clauses_that_could_match
   7: ZN15chalk_recursive9recursive301_$LT$impl$u20$chalk_recursive..fixed_point..SolverStuff$LT$chalk_ir..UCanonical$LT$chalk_ir..InEnvironment$LT$chalk_ir..Goal$LT$I$GT$$GT$$GT$$C$core..result..Result$LT$chalk_solve..solve..Solution$LT$I$GT$$C$chalk_ir..NoSol
   8: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
   9: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  10: hir_ty::traits::solve::{{closure}}
  11: hir_ty::traits::trait_solve_query
  12: salsa::runtime::Runtime::execute_query_implementation
  13: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  14: salsa::derived::slot::Slot<Q,MP>::read
  15: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  16: salsa::QueryTable<Q>::get
  17: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  18: hir_ty::db::trait_solve_wait
  19: <DB as hir_ty::db::HirDatabase>::trait_solve
  20: hir_ty::method_resolution::iterate_method_candidates_dyn
  21: hir_ty::method_resolution::iterate_method_candidates_dyn
  22: hir::Type::iterate_path_candidates_dyn
  23: ide_completion::context::CompletionContext::iterate_path_candidates
  24: ide_completion::completions::expr::complete_expr_path
  25: ide_completion::completions::complete_name_ref
  26: ide_completion::completions
  27: std::panicking::try
  28: rust_analyzer::handlers::request::handle_completion
  29: std::panicking::try
  30: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Duplicate of #13531.

**Closed by lnicola** 2023-09-10 07:01 UTC
Labels: C-bug
