### ISSUE TITLE
Autocompleting Vec::as_slice pulls unstable SlicePattern trait unnecessarily

### ISSUE THREAD

**Issue by abreis** [rust-lang/rust-analyzer#9717] opened 2021-07-28 15:40 UTC
Lately I've noticed that autocompleting the `as_slice()` method on a Vec leads rust-analyzer to import `core::slice::SlicePattern`:

![image](https://user-images.githubusercontent.com/95046/127351483-b14e02ff-ad1b-4bbd-8c3f-7687d35378dd.png)

But `Vec::as_slice` exists outside of that trait. 

`SlicePattern` is also unstable, so importing it triggers the unstable feature error:

![image](https://user-images.githubusercontent.com/95046/127351500-454896e8-55a7-4737-bbc8-46564347ea9e.png)

... which is a bit of a headscratcher until one realizes what is happening.

**Comment by flodiebold** [comment] 2021-07-28 16:23
Hmm, I get both options, which would make this a duplicate of #3020.

**Comment by mahdi-frms** [comment] 2021-08-02 07:37
``` rust
fn main() {
    let s = &Struct;
    s.func();
}

struct Struct;

impl Struct {
    fn func(&self) {
        println!("khokh f");
    }
}

impl Trait for Struct {
    fn func(&self) {
        println!("gorkh f");
    }
}

trait Trait {
    fn func(&self) {
        println!("trait default");
    }
}

```

In this case I'm only suggested with ```func()``` not ```func() (as Trait)```. But why is that?

**Comment by mahdi-frms** [comment] 2021-08-02 07:42
Seems like it only does that when it has not imported it yet.

**Comment by Veykril** [comment] 2024-07-21 10:53
We no longer propose the unstable trait here

**Closed by Veykril** 2024-07-21 10:53 UTC
Labels: A-completion
