### ISSUE TITLE
False type-mismatch for derive(Hash) for structs with fields called "state"

### ISSUE THREAD

**Issue by valyagolev** [rust-lang/rust-analyzer#14860] opened 2023-05-20 20:19 UTC
As minimal reproduction as it gets: `cargo new --lib repro`, then:

```
#[derive(Hash)]
pub enum BgGameState {
    Over, // you can comment it out as well
}

#[derive(Hash)]
pub struct BgGame {
    pub state: BgGameState, // rename it, it will go away
}
```

<img width="791" alt="repro" src="https://github.com/rust-lang/rust-analyzer/assets/150242/a5f960a0-db01-426d-a122-15fdeda0b979">

**rust-analyzer version**: 0.4.1521-standalone, also some earlier versions

**rustc version**: tried with rustc 1.69.0 (84c898d65 2023-04-16), rustc 1.71.0-nightly (521f4dae1 2023-05-19), also some earlier versions

**relevant settings**: It's VS Code remote on my box, via SSH, but I've been running it without issues for many months

**Comment by valyagolev** [comment] 2023-05-20 20:21
Ohhh, I figured it out. If I rename "state", it goes away :-)

**Comment by HKalbasi** [comment] 2023-05-20 20:26
Yes this happens since state is used in the macro expansion code:
```Rust
impl core::hash::Hash for BgGame {
    fn hash<H: core::hash::Hasher>(&self, state: &mut H) {
        core::mem::discriminant(self).hash(state);
        match self {
            BgGame { state: state } => {
                               // ^^^ state shadows the state
                state.hash(state);
            }
        }
    }
}
```

**Comment by lowr** [comment] 2023-05-21 09:57
This should be resolved when we implement macro hygiene. Closing as a duplicate of #11681.

**Closed by lowr** 2023-05-21 09:57 UTC
Labels: A-macro, C-bug

**Comment by flodiebold** [comment] 2023-05-21 11:22
Maybe we could use a name that's less likely to collide until then?
