### ISSUE TITLE
Add `mut` when completing method that takes `&mut self`

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#12128] opened 2022-05-01 00:33 UTC
When accepting a completion for a method with a `&mut self` receiver, the completion could include a snippet that automatically makes the binding it's called on `mut`able, if that's required for the method call to compile.

**Comment by jhgg** [comment] 2022-05-01 03:32
Perhaps a dupe of #11084 ?

**Closed** 2022-05-01 18:22 UTC
Labels: A-completion, S-actionable, C-feature
