### ISSUE TITLE
Papercut: "Introduce variable" doesn't add semicolon after block

### ISSUE THREAD

**Issue by killercup** [rust-lang/rust-analyzer#504] opened 2019-01-12 13:23 UTC
When using "introduce variable" for a block, no trailing semicolon is added.

See last part of this gif:

![rust-analyzer-intro-var-for-block](https://user-images.githubusercontent.com/20063/51073720-8d5a4980-1675-11e9-904b-acb31ccf2952.gif)

 Might be a good beginner issue.

**Comment by matklad** [comment] 2019-01-12 13:34
The relevant code is here:

https://github.com/rust-analyzer/rust-analyzer/blob/e9e397e705ad0bec9775067b10109e35ebefc493/crates/ra_ide_api_light/src/assists/introduce_variable.rs#L29

I think that just pushing ‘;’ to the buff (and adding the corresponding test) should be enough?

**Comment by yerke** [comment] 2019-01-14 01:00
I want to take this issue.

@matklad Thanks for showing where to start. Turns out it's a bit more involved. Your suggested edit breaks 5 tests. I have found another approach that breaks only 1 test (`assists::introduce_variable::tests::test_introduce_var_expr_stmt`). Need to figure out what exactly is going there.

**Comment by gfreezy** [comment] 2019-01-24 14:10
seems the issue is resolved. we should close the issue.

**Closed as completed** 2019-01-24 14:15 UTC
Labels: good first issue, E-easy, E-has-instructions
