### ISSUE TITLE
Struct fields and function arguments not expanded on completion

### ISSUE THREAD

**Issue by dmitrii-ubskii** [rust-lang/rust-analyzer#18544] opened 2024-11-21 11:05 UTC
**rust-analyzer version**: rust-analyzer 0.0.0 (ba56d9b9b 2024-11-17) installed via Homebrew

**rustc version**: rustc 1.82.0 (f6e511eec 2024-10-15) installed via rustup

**editor or extension**: NeoVim using `neovim/nvim-lspconfig` and `hrsh7th/nvim-cmp` with `hrsh7th/cmp-nvim-lsp`

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
```lua
['rust-analyzer'] = {
    check = { command = "clippy" },
    completion = { privateEditable = { enable = true } },
    rustfmt = { extraArgs = { "+nightly" } },
    numThreads = 8,
}
```

**repository link (if public, optional)**: N/A

**code snippet to reproduce**: (`|` represents cursor position)
```rust
struct Type1 { field: u8 }
struct Type2 { field: u8 }
fn main() {
    let T|
}
```

When calling completion and selecting e.g. the item `Type1 {…}`, rust-analyzer inserts literal `Type1 {…}` where it previously would have correctly inserted `Type1 { field }`. Rust-analyzer 1.82.0 installed via rustup does not exhibit this behaviour, it expands correctly.

Note: I believe this was more easily reproducible on the 2024-11-04 version of RA, but I had updated in hope this had been fixed, and now I also get random symbols like `panic!` completed instead of the one I've selected (I'm guessing that's related to #18536).

**Comment by flodiebold** [comment] 2024-11-28 10:02
Duplicate of https://github.com/hrsh7th/cmp-nvim-lsp/issues/72 / https://github.com/rust-lang/rust-analyzer/issues/18547

**Closed by flodiebold** 2024-11-28 10:02 UTC
Labels: C-bug
