### ISSUE TITLE
Request codeLens/resolve failed.

### ISSUE THREAD

**Issue by PeterW-LWL** [rust-lang/rust-analyzer#14317] opened 2023-03-10 12:02 UTC
r-a is generating a lot of errors (on every cursor move/mouse move/scroll/typing) with the same error message "Request … failed.".

The project this is happening on is private.

Ref #14193

**rust-analyzer version**:  0.4.1430-standalone (14b9d182d 2023-03-09)  
rust-analyzer is installed by cloning the repo and using `cargo xtask install --server`

**rustc version**: rustc 1.70.0-nightly (39f2657d1 2023-03-09)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
```json
{
    // …
    "rust-analyzer.checkOnSave.command": "clippy",
    "rust-analyzer.diagnostics.experimental.enable": true,
    "rust-analyzer.lens.references.adt.enable": true,
    "rust-analyzer.lens.references.method.enable": true,
    "rust-analyzer.lens.references.trait.enable": true,
    "rust-analyzer.server.path": null,
    // …
}
```

**VSCode**: Version: 1.76.1 (Universal)  
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b  
Date: 2023-03-08T16:32:09.831Z  
Electron: 19.1.11  
Chromium: 102.0.5005.196  
Node.js: 16.14.2  
V8: 10.2.154.26-electron.0  
OS: Darwin arm64 21.6.0  
Sandboxed: No  

## Error example from VSCode output "Rust Analyzer Language Server" tab

```
Panic context:
> 
version: 0.4.1430-standalone (14b9d182d 2023-03-09)
request: codeLens/resolve CodeLens {
    range: Range {
        start: Position {
            line: 8,
            character: 20,
        },
        end: Position {
            line: 8,
            character: 26,
        },
    },
    command: None,
    data: Some(
        Object {
            "references": Object {
                "textDocument": Object {
                    "uri": String("file:///Users/HIDDEN_USER_NAME/Documents/Development/Rust/Projects/gitlab-trigger-rocket/src/trigger/issue.rs"),
                },
                "position": Object {
                    "line": Number(8),
                    "character": Number(20),
                },
            },
        },
    ),
}

> impl_trait_query(ImplId(27761) -> ItemLoc { container: ModuleId { krate: CrateId(144), block: None, local_id: Idx::<ModuleData>(15) }, id: ItemTreeId { tree: TreeId { file: HirFileId(1888), block: None }, value: Idx::<Impl>(0) } } -> ImplData { target_trait: Some(TraitRef { path: Path { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("From"))] }, generic_args: Some([Some(GenericArgs { args: [Type(Array(Path(Path { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("u8"))] }, generic_args: None }), Path(Name(Text("KEY_LEN")))))], has_self_type: false, bindings: [], desugared_from_fn: false })]) } }), self_ty: Path(Path { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("Key"))] }, generic_args: None }), items: [FunctionId(FunctionId(54226))], is_negative: false, attribute_calls: None })

thread 'Worker' panicked at 'Internal error, cycle detected:

trait_impls_in_crate(CrateId(144))
impl_trait(ImplId(27761))
const_eval(ConstId(4090))
mir_body(ConstId(ConstId(4090)))
infer_query(ConstId(ConstId(4090)))
trait_solve_query((CrateId(144), Canonical { value: InEnvironment { environment: Env([]), goal: Implemented(Uint(Usize): TraitId(192)) }, binders: [] }))
trait_impls_in_deps(CrateId(144))
', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.2/src/lib.rs:422:35
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate::__shim
   3: <hir_ty::db::TraitImplsInDepsQuery as salsa::plumbing::QueryFunction>::execute
   4: salsa::runtime::Runtime::execute_query_implementation
   5: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   6: salsa::derived::slot::Slot<Q,MP>::read
   7: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   8: <DB as hir_ty::db::HirDatabase>::trait_impls_in_deps::__shim
   9: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::impls_for_trait
  10: chalk_solve::clauses::program_clauses_that_could_match
  11: chalk_recursive::solve::SolveIteration::solve_iteration
  12: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  13: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  14: <hir_ty::db::TraitSolveQueryQuery as salsa::plumbing::QueryFunction>::execute
  15: salsa::runtime::Runtime::execute_query_implementation
  16: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  17: salsa::derived::slot::Slot<Q,MP>::read
  18: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  19: salsa::QueryTable<Q>::get
  20: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  21: hir_ty::db::trait_solve_wait
  22: <DB as hir_ty::db::HirDatabase>::trait_solve
  23: hir_ty::infer::unify::InferenceTable::register_obligation_in_env
  24: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::register_obligations_for_call
  25: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_overloadable_binop
  26: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  27: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  28: hir_ty::infer::infer_query
  29: salsa::runtime::Runtime::execute_query_implementation
  30: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  31: salsa::derived::slot::Slot<Q,MP>::read
  32: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  33: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  34: <DB as hir_ty::db::HirDatabase>::infer_query
  35: hir_ty::db::infer_wait
  36: <DB as hir_ty::db::HirDatabase>::infer
  37: hir_ty::mir::lower::mir_body_query
  38: salsa::runtime::Runtime::execute_query_implementation
  39: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  40: salsa::derived::slot::Slot<Q,MP>::read
  41: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  42: <DB as hir_ty::db::HirDatabase>::mir_body::__shim
  43: <DB as hir_ty::db::HirDatabase>::mir_body
  44: hir_ty::consteval::const_eval_query
  45: salsa::runtime::Runtime::execute_query_implementation
  46: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  47: salsa::derived::slot::Slot<Q,MP>::read
  48: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  49: <DB as hir_ty::db::HirDatabase>::const_eval::__shim
  50: hir_ty::lower::TyLoweringContext::lower_ty_ext
  51: hir_ty::lower::TyLoweringContext::substs_from_path_segment
  52: hir_ty::lower::TyLoweringContext::lower_trait_ref_from_path
  53: hir_ty::lower::impl_trait_query
  54: salsa::runtime::Runtime::execute_query_implementation
  55: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  56: salsa::derived::slot::Slot<Q,MP>::read
  57: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  58: <DB as hir_ty::db::HirDatabase>::impl_trait::__shim
  59: hir_ty::method_resolution::TraitImpls::collect_def_map
  60: <hir_ty::db::TraitImplsInCrateQuery as salsa::plumbing::QueryFunction>::execute
  61: salsa::runtime::Runtime::execute_query_implementation
  62: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  63: salsa::derived::slot::Slot<Q,MP>::read
  64: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  65: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate::__shim
  66: <hir_ty::db::TraitImplsInDepsQuery as salsa::plumbing::QueryFunction>::execute
  67: salsa::runtime::Runtime::execute_query_implementation
  68: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  69: salsa::derived::slot::Slot<Q,MP>::read
  70: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  71: <DB as hir_ty::db::HirDatabase>::trait_impls_in_deps::__shim
  72: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::impls_for_trait
  73: chalk_solve::clauses::program_clauses_that_could_match
  74: chalk_recursive::solve::SolveIteration::solve_iteration
  75: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  76: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  77: <hir_ty::db::TraitSolveQueryQuery as salsa::plumbing::QueryFunction>::execute
  78: salsa::runtime::Runtime::execute_query_implementation
  79: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  80: salsa::derived::slot::Slot<Q,MP>::read
  81: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  82: salsa::QueryTable<Q>::get
  83: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  84: hir_ty::db::trait_solve_wait
  85: <DB as hir_ty::db::HirDatabase>::trait_solve
  86: hir_ty::infer::unify::InferenceTable::try_obligation
  87: hir_ty::autoderef::autoderef_step
  88: hir_ty::autoderef::deref
  89: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  90: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 12:42:29] Request codeLens/resolve failed.
  Message: request handler panicked: Internal error, cycle detected:

trait_impls_in_crate(CrateId(144))
impl_trait(ImplId(27761))
const_eval(ConstId(4090))
mir_body(ConstId(ConstId(4090)))
infer_query(ConstId(ConstId(4090)))
trait_solve_query((CrateId(144), Canonical { value: InEnvironment { environment: Env([]), goal: Implemented(Uint(Usize): TraitId(192)) }, binders: [] }))
trait_impls_in_deps(CrateId(144))

  Code: -32603 
```

**Comment by lnicola** [comment] 2023-03-10 12:04
Dupe of https://github.com/rust-lang/rust-analyzer/issues/14305, try a pre-release build.

**Closed by lnicola** 2023-03-10 12:04 UTC
Labels: C-bug
