### ISSUE TITLE
[rust-analyzer vscode plugin] Weird "Roots scanned" never finishing since today's nightly update

### ISSUE THREAD

**Issue by StarStarJ** [rust-lang/rust-analyzer#16386] opened 2024-01-17 17:02 UTC
I use rust-analyzer plugin preview releases and since today i get:

![grafik](https://github.com/rust-lang/rust-analyzer/assets/77283933/a9bc9d80-0010-42cb-922b-34258ab63512)

I doesn't progress nor does it harm the editor in any way. It's just there... forever

#15636
sounds very related

I am also pretty sure it didn't happen before, and only since today, i use vscode + rust almost daily

I've 0 plan how to debug or what could help you.
Switchting to a non-prerelease fixes it

**rust-analyzer version**:  rust-analyzer version: 0.4.1809-standalone

**rustc version**: rustc 1.77.0-nightly (d78329b92 2024-01-13)

tested on 2 different machines

**Comment by lnicola** [comment] 2024-01-17 17:03
Duplicate of #16382

**Closed by lnicola** 2024-01-17 17:03 UTC
Labels: C-bug
