### ISSUE TITLE
Option to disable "double click to insert" on type inlay hint

### ISSUE THREAD

**Issue by Keavon** [rust-lang/rust-analyzer#17890] opened 2024-08-14 11:05 UTC
I often accidentally double-click the inlay hint for a type, which inserts it as text. I don't ever plan to use this feature, so I'd appreciate an option to disable it.

**Comment by lnicola** [comment] 2024-08-14 11:45
Duplicate of #15535, this [should](https://github.com/microsoft/vscode/issues/191868) be a VS Code setting.

**Closed by lnicola** 2024-08-14 11:45 UTC
Labels: C-feature

**Comment by Keavon** [comment] 2024-08-14 11:54
@lnicola Oh interesting, so the double clicking an inlay hint is functionality implemented by VS Code for all languages, and it's not something RA opts into? That's surprising, ok, thanks. But out of curiosity, how does VS Code even know that a particular inlay is valid code rather than just some other text which an extension might choose to display, causing an attempt to insert it into the file to make that file invalid?

**Comment by lnicola** [comment] 2024-08-14 12:04
> Oh interesting, so the double clicking an inlay hint is functionality implemented by VS Code for all languages, and it's not something RA opts into?

It's functionality described in the LSP, so it's not specific to VS Code. Other extensions work the same way, but some (like Python) don't show the hints by default:

![image](https://github.com/user-attachments/assets/6ef67131-5f5e-4236-bd17-c8592860a7a2)

![image](https://github.com/user-attachments/assets/6de59632-6078-4e25-9956-b1a0bd1d50a7)

I'm not aware of any extension that lets you disable these edits.

> how does VS Code even know that a particular inlay is valid code

It doesn't know, it just assumes that the clients send something that makes sense:

>  *Note* that edits are expected to change the document so that the inlay hint (or its nearest variant) is now part of the document and the inlay hint itself is now obsolete.

**Comment by Keavon** [comment] 2024-08-14 12:06
I see, thanks for the details. I'll direct my support towards https://github.com/microsoft/vscode/issues/191868 with a 👍.
