### ISSUE TITLE
New versions not available on OpenVSX (platform-specific VSIXes)

### ISSUE THREAD

**Issue by romainreignier** [rust-lang/rust-analyzer#11080] opened 2021-12-21 10:34 UTC
EDIT: see https://github.com/rust-analyzer/rust-analyzer/issues/11080#issuecomment-1010840901

---

**rust-analyzer version**: "Rust Analyzer: Show RA Version" command does nor exist, extension install dir: `matklad.rust-analyzer-0.2.867`

**rustc version**: `rustc 1.56.0 (09c42c458 2021-10-18)`

**OS Version**:  Ubuntu 18.04.6

**VS Code version**: I use VSCodium 1.63.2

Today, rust-analyzer updated itself and stop working with the error:

```
INFO [12/21/2021, 11:18:12 AM]: Using server binary at /home/user/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/server/rust-analyzer
ERROR [12/21/2021, 11:18:12 AM]: Bootstrap error [Error: Failed to execute /home/user/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/server/rust-analyzer --version
	at j0 (/home/user/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/out/main.js:109:4032)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async N0 (/home/user/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/out/main.js:109:1881)
	at async I0 (/home/user/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/out/main.js:108:3977)
	at async lC (/home/user/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/out/main.js:108:3808)
	at async Promise.all (index 0)
	at async v.$activate (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:100:20806)]
```

The file `/home/user/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/server/rust-analyzer` but cannot be executed, even manually:

```
$ /home/user/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/server/rust-analyzer --version
bash: /home/user/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/server/rust-analyzer: No such file or directory
```

While the file exists.

But `ldd` on it shows the missing `musl` lib:
```
ldd /home/user/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/server/rust-analyzer
        linux-vdso.so.1 (0x00007ffce3bfa000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5dc6a52000)
        libc.musl-x86_64.so.1 => not found
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5dc6661000)
        /lib/ld-musl-x86_64.so.1 => /lib64/ld-linux-x86-64.so.2 (0x00007f5dc8490000)
```

I had a VSCodium update yesterday so it might be related.

I have tried to uninstall the extension but it installs the same version.

**Comment by samueltardieu** [comment] 2021-12-21 10:38
A similar problem exists on ArchLinux.

**Comment by romainreignier** [comment] 2021-12-21 10:39
Reverting to 0.2.853 works. So this seems specific to latest 0.2.867 version.

**Comment by lnicola** [comment] 2021-12-21 10:40
@romainreignier what if you download https://github.com/rust-analyzer/rust-analyzer/releases/download/2021-12-20/rust-analyzer-linux-x64.vsix and install it using the `Install from VSIX` command?

**Comment by romainreignier** [comment] 2021-12-21 10:42
@lnicola It works!

**Comment by samueltardieu** [comment] 2021-12-21 10:43
Works for me too using the package provided by @lnicola which links musl statically.

**Comment by lnicola** [comment] 2021-12-21 10:43
@samueltardieu are you sure it links to `musl` and not `glibc`?

**Comment by romainreignier** [comment] 2021-12-21 10:44
I think it links to `glibc`:

```
 ldd ~/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/server/rust-analyzer
        linux-vdso.so.1 (0x00007ffd81e25000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fec466cf000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fec464b7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fec46298000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fec45efa000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fec45b09000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fec480ce000)
```

**Comment by samueltardieu** [comment] 2021-12-21 10:44
Yes, indeed, it links to glibc.

**Comment by lnicola** [comment] 2021-12-21 10:48
I think what happens is that:

 - VS Code 1.61 added support for platform-specific dependencies
 - downloading the server binaries from GitHub is a bit of a pain for us (sometimes the releases don't get published and updates fail, some users with proxies have problems, coordinating between the nightly and stable builds is a bit of a pain, it's a large surface for supply chain attacks and so on)
 - we implemented https://github.com/rust-analyzer/rust-analyzer/issues/10483 in https://github.com/rust-analyzer/rust-analyzer/pull/11053
 - VSCodium uses Open VSX
 - `rust-analyzer` gets published to Open VSX somehow (there's an open issue, but we don't have an account there and I don't know how it gets there)
 - either Open VSX or the publishing process there doesn't support platform-specific extensions
 - VSCodium users get a random version

I don't think we want to give up on this change, but I don't know any easy fix either.

**Comment by samueltardieu** [comment] 2021-12-21 10:53
Note that as far as I am concerned I use the open-source build of vscode on ArchLinux, but vscodium isn't mentioned anywhere:

```bash
$ paru -Qi code
Name            : code
Version         : 1.62.0-1
Description     : The Open Source build of Visual Studio Code (vscode) editor
Architecture    : x86_64
URL             : https://github.com/microsoft/vscode
Licenses        : MIT
Groups          : None
Provides        : vscode
Depends On      : electron13  libsecret  libx11  libxkbfile  ripgrep
Optional Deps   : bash-completion: Bash completions
                  zsh-completions: ZSH completitons
                  x11-ssh-askpass: SSH authentication
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 93.68 MiB
Packager        : Filipe Laíns <lains@archlinux.org>
Build Date      : Sun 07 Nov 2021 20:25:45 CET
Install Date    : Wed 24 Nov 2021 17:04:04 CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

How can I know if Open VSX is used? Neither "openvsx" or "open vsx" can be ripgrepped anywhere in the installed JS files (case insensitive).

**Comment by samueltardieu** [comment] 2021-12-21 10:55
vscode on ArchLinux is also using open-vsx:

```bash
$ jq .extensionsGallery < product.json
{
  "serviceUrl": "https://open-vsx.org/vscode/gallery",
  "itemUrl": "https://open-vsx.org/vscode/item"
}
```

**Comment by bjorn3** [comment] 2021-12-21 10:56
The vscode package registry is only allowed to be used by the vscode builds microsoft creates. These also contain a drm to make certain microsoft extensions work like the remote ssh, remote wsl and liveshare extensions. Any build from the source code in https://github.com/microsoft/vscode has to use an alternative package registry and isn't allowed to use these extensions.

**Comment by lnicola** [comment] 2021-12-21 10:58
I think we need to finally make an account on OVSX, and find someone to ping about the ovsx tool and backend.

**Comment by lnicola** [comment] 2021-12-21 11:10
https://github.com/eclipse/openvsx/issues/336

**Comment by lnicola** [comment] 2021-12-21 11:32
As a work-around, you can:

 - disable updates and update manually from a GitHub release every once in a while
 - use the non-free version of Code (on Arch, there's an AUR package for it, Ubuntu must have a snap)
 - install the language server separately (on Arch there's a `community` package) and set `rust-analyzer.server.path`

**Comment by lnicola** [comment] 2021-12-28 12:59
@najtin besides reverting https://github.com/rust-analyzer/rust-analyzer/issues/10483, there's not much we can do here. We could make a version with binaries for every platform, but currently we have no control over how things get published there.

I think this should be fixed on the Open VSX side. The maintainers there are aware of it.

**Comment by mrchip2k** [comment] 2022-01-01 11:31
Quickest way to "fix" it for me was installing an older version from within VSCodium (also, disable auto updates)
(rightclick extension > Install Another Version... > 0.2.853 worked for me)

**Comment by lukasjuhrich** [comment] 2022-01-04 14:56
> I think it links to `glibc`:
> 
> ```
>  ldd ~/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/server/rust-analyzer
>         linux-vdso.so.1 (0x00007ffd81e25000)
>         libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fec466cf000)
>         libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fec464b7000)
>         libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fec46298000)
>         libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fec45efa000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fec45b09000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007fec480ce000)
> ```

FYI, The artifact of `0.2.867` which I have (Open source version of vscode on arch, [`code v1.62.0-1`](https://archlinux.org/packages/community/x86_64/code/)) looks slightly different and links to `musl`:

```shell-session
➜  server ldd /home/lukas/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/server/rust-analyzer 
        linux-vdso.so.1 (0x00007ffc89fe5000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f38266f9000)
        libc.musl-x86_64.so.1 => not found
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f382652d000)
        /lib/ld-musl-x86_64.so.1 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f3827f87000)
➜  server md5sum rust-analyzer 
5b0abf5af15bb4f31c52048bd05a6044  rust-analyzer
```

**Comment by filiptronicek** [comment] 2022-01-10 11:30
For a quick status update: over at OpenVSX we are trying to remove the non-working versions to make the extension work at least, but are running into some issues on our end (see https://github.com/EclipseFdn/open-vsx.org/issues/814 & https://github.com/EclipseFdn/open-vsx.org/issues/816). I removed this extension from auto-publishing to OpenVSX (because of https://github.com/open-vsx/publish-extensions/issues/527) and hope to get the extension directly to OpenVSX back soon 🤞.

**Comment by lnicola** [comment] 2022-01-12 09:39
Update: OpenVSX has now removed the newer versions. Now if you install it from there you will get an older, working version. I'll update the issue title accordingly.

**Comment by akosyakov** [comment] 2022-01-26 09:51
A corresponding PR for OpenVSX: https://github.com/eclipse/openvsx/pull/406

**Comment by xsrvmy** [comment] 2022-03-01 14:52
There is a "no-server" vsix on the assets in releases. Would that version work for all platforms for the time being?

**Comment by lnicola** [comment] 2022-03-01 14:56
@xsrvmy that one has no server and no download support for it. The idea is to use it if you're on an unsupported platform like 32-bit or some BSD. For the time being, you can download the VSIX for your platform, but you won't get automatic updates.

**Comment by huguesBouvier** [comment] 2022-03-01 18:21
Had the same issue. The fix worked for me.

**Comment by filiptronicek** [comment] 2022-04-04 08:12
> A corresponding PR for OpenVSX: [eclipse/openvsx#406](https://github.com/eclipse/openvsx/pull/406)

Hello again everyone! I am pleased to announce that the blocking PR was merged about a half an hour ago.

## What's next?

The steps neccesary for publishing are as follows:

1. Create a claim ownership request in the https://github.com/EclipseFdn/open-vsx.org repo [[1](https://github.com/EclipseFdn/open-vsx.org/issues/new?assignees=&labels=namespace&template=claim-namespace-ownership.md&title=Claiming+namespace+%5Bname%5D)]
2. Sign up for OpenVSX and get the required access token by following https://github.com/eclipse/openvsx/wiki/Publishing-Extensions (steps 1-3)
3. Change the release workflow to allow publishing via `ovsx` - add the following two steps again, just replacing `npx vsce` with `npx ovsx` (also requires to change the name of the secret token, for example `OPENVSX_TOKEN` and adding it to your repository secrets).

https://github.com/rust-analyzer/rust-analyzer/blob/46d7ee68f26285db26b2640f2c07d6332380c756/.github/workflows/release.yaml#L249-L258

**Comment by lnicola** [comment] 2022-04-11 19:00
@filiptronicek question: do we need a more recent version of `ovsx` for the new platform arguments? The last published one is from January.

**Comment by filiptronicek** [comment] 2022-04-11 19:13
@lnicola thanks for noting the absent publish to NPM. It is indeed needed and I have let the team know, hopefully we'll see a publish in the next few days.

**Comment by Aloso** [comment] 2022-05-09 22:28
@filiptronicek has a new release been published? I just want to make sure this isn't forgotten.

**Comment by filiptronicek** [comment] 2022-05-10 06:09
@Aloso it for sure hasn't. There's some other issues we are tackling at the moment, but it's still something we are aware about and working towards.

**Comment by filiptronicek** [comment] 2022-05-10 06:34
The progress of the publish can be followed here: https://github.com/eclipse/openvsx/issues/450.

**Comment by WorldSEnder** [comment] 2022-06-07 00:34
> The progress of the publish can be followed here: [eclipse/openvsx#450](https://github.com/eclipse/openvsx/issues/450).

That issue is now closed, is there a new blocker I'm unaware of?

**Comment by lnicola** [comment] 2022-06-07 06:00
> That issue is now closed, is there a new blocker I'm unaware of?

Yes. We've moved namespaces (from `matklad` to `rust-lang`) on the official marketplace. We could publish it today on OpenVSX under `matklad`, but that would probably cause unnecessary confusion. I've asked someone from the infrastructure team to register the `rust-lang` namespace and give us an API token, hopefully they'll agree.

**Comment by lnicola** [comment] 2022-06-29 05:53
Update: we got the namespace/access token sorted out, but publishing appears to fail on the OVSX side: https://github.com/rust-lang/rust-analyzer/runs/7103624175?check_suite_focus=true#step:23:25.

**Comment by HKalbasi** [comment] 2022-07-01 08:16
@lnicola is it possible to publish it under `matklad` namespace until open-vsx fix that bug? Open-vsx side doesn't look very active.

**Comment by lnicola** [comment] 2022-07-01 08:17
@HKalbasi I doubt that will work, there's nothing special about either namespaces.

**Comment by lnicola** [comment] 2022-07-01 08:43
> From https://github.com/open-vsx/publish-extensions/issues/591 I thought the problem is related to changing the namespace.

I have no idea what the problem is, but this is practically a first publish attempt. It's not like on the Microsoft marketplace, where moving the extension to another namespace and broke the marketplace (and also `vsce`).

Maybe open-vsx.org doesn't like VSIXes built by `vsce`? But then how does auto-publishing work?

**Comment by filiptronicek** [comment] 2022-07-01 11:39
@lnicola I'm sorry for the troubles here. I have notified the team about the publishing issues again internally, I hope they will take a look soon. 

> Maybe open-vsx.org doesn't like VSIXes built by vsce?

Not at all! We use vsce to build the `vsix` files as well 🙂

Before the team takes a look, I suspect the problem being with the target-specific extension version. It's very unfortunate and we are pushing hard for its deploy on production, but although the code is merged and there, they still don't work on https://open-vsx.org [[1](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1483)]. I will comment here when it is deployed.

**Comment by lnicola** [comment] 2022-07-01 11:44
@filiptronicek I don't think so, since https://marketplace.visualstudio.com/items?itemName=REditorSupport.r has similar issues and it doesn't have platform-specific binaries; same for `ms-vscode.mock-debug`.

**Comment by filiptronicek** [comment] 2022-07-01 12:11
@lnicola the size limit is per-file, not per extension, so that shouldn't be the issue. 👀

**Comment by purkhusid** [comment] 2022-08-02 14:22
Has there been any progress on this?

**Comment by bjorn3** [comment] 2022-08-02 14:27
You might want to follow https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1483.

**Comment by lnicola** [comment] 2022-08-02 14:30
I'm not convinced that https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1483 helps, since that change was online for a couple of days, but our nightly publish action still failed.

So this is more or less implemented on our side, but I don't know what's up with OpenVSX.

**Comment by coffee-is-power** [comment] 2022-09-02 19:06
The extension is not setting the +x permission on the executable

**Comment by filiptronicek** [comment] 2022-10-14 13:47
Hey all! Good news, [https://open-vsx.org/](https://open-vsx.org/) has deployed the change with pre-releases and platform-specific releases, so this should be good to go 🎉

cc @lnicola

**Comment by coffee-is-power** [comment] 2022-10-14 14:09
YEEEEEESS

**Comment by lnicola** [comment] 2022-10-14 14:23
The good news is it's no longer returning an error right from the start. The bad news is that publishing doesn't seem to finish either:

![image](https://user-images.githubusercontent.com/308347/195870503-0e5fb2de-cdc3-438b-a5ab-49cf4671f015.png)

**Comment by lnicola** [comment] 2022-10-14 14:49
Still running, after almost 30 minutes.

@filiptronicek unrelated, but do you think it might be feasible to publish the extension "manually" (e.g. using curl) instead of going through the ovsx tool?

**Comment by lnicola** [comment] 2022-10-14 16:21
Killed after 2h:

![image](https://user-images.githubusercontent.com/308347/195894105-bd489cf6-c8cf-481c-b0f9-ce8c00d4e613.png)

I'm tempted to disable publishing since we can't let it run like this 8 times a week.

**Comment by filiptronicek** [comment] 2022-10-14 17:22
@lnicola sad to hear that the process is hanging 😕, @amvanbaren would you happen to know what might be causing this when only publishing a pre-baked extension file?

**Comment by filiptronicek** [comment] 2022-10-14 17:22
> @filiptronicek unrelated, but do you think it might be feasible to publish the extension "manually" (e.g. using curl) instead of going through the ovsx tool?

Yes! You can use `/api/-/publish` in the API - https://open-vsx.org/swagger-ui/#/registry-api/publishUsingPOST

**Comment by filiptronicek** [comment] 2022-10-14 19:36
Just tried publishing some other extensions, seems the timeout is happening there as well, forwarding it to the team internally, will get back.

**Comment by lnicola** [comment] 2022-10-15 11:38
@filiptronicek now it's back to returning 500.

**Comment by lnicola** [comment] 2022-11-02 18:09
rust-analyzer is now available on OpenVSX: https://open-vsx.org/extension/rust-lang/rust-analyzer.

That's only a pre-release version, you get an error if you try to install it, but you can still use the "Install Pre-Release Version" option to get it.

Thanks @amvanbaren and kineticSquid for the help!

**Closed by lnicola** 2022-11-02 18:09 UTC
