### ISSUE TITLE
go to definition in into goes to blanket implementation

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/rust-analyzer#17743] opened 2024-07-30 08:53 UTC
```rs
  struct S;

impl From<S> for String {
    fn from(value: S) -> Self {
        todo!()
    }
}

impl S {
    fn foo(self) -> String {
        self.into() // go to definition here goes to `impl<T, U> Into<U> for T
                    // which is not very useful
    }
}
```

**Comment by davidbarsky** [comment] 2024-07-30 16:37
Closing as a duplicate of https://github.com/rust-lang/rust-analyzer/issues/13394; I'd recommend reading the discussion there. I expect that moving to the new trait solver (hopefully by the end of the year...) would make this feature possible.

**Closed by davidbarsky** 2024-07-30 16:37 UTC
Labels: C-bug
