### ISSUE TITLE
Various E0308/E0107 errors in rustc code

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-analyzer#15332] opened 2023-07-24 12:34 UTC
RA recently started showing type errors in well-typed Rust code in the Rust compiler:

- [This](https://github.com/rust-lang/rust/blob/1c44af9b791c16557b5bf606707bb76df979134a/compiler/rustc_const_eval/src/interpret/step.rs#L185-L187)  triggers E0308 `expected &IndexSlice<{unknown}, Operand<'_>>, found &IndexVec<{unknown}, Operand<'_>>`
- [This](https://github.com/rust-lang/rust/blob/1c44af9b791c16557b5bf606707bb76df979134a/compiler/rustc_middle/src/mir/interpret/mod.rs#L320) triggers E0107 `expected 1 argument, found 0`
- [This](https://github.com/rust-lang/rust/blob/bccefd280755e52b60d721bb6e5ff2556180a57b/compiler/rustc_middle/src/ty/layout.rs#L327) (and similar code later that file) triggers E0308 `expected &LayoutError<'_>, found LayoutError<'_>`

**rust-analyzer version**: rust-analyzer version: 0.3.1599-standalone

**rustc version**: rustc bootstrap

**relevant settings**: 
```
    // user settings
    "rust-analyzer.lens.enable": false,
    "rust-analyzer.cachePriming.enable": false,
    "rust-analyzer.cargo.buildScripts.useRustcWrapper": false,
    "rust-analyzer.diagnostics.disabled": [
        "unlinked-file", // I guess for "normal" projects unlinked files are strange, for me they are common
        "unresolved-module", // https://github.com/rust-lang/rust-analyzer/issues/9173
        "type-mismatch", // https://github.com/rust-lang/rust-analyzer/issues/1109
    ],
    // workspace settings
    "rust-analyzer.rustc.source": "./Cargo.toml",
    "rust-analyzer.linkedProjects": [
        "./Cargo.toml",
        "./src/bootstrap/Cargo.toml"
    ],
    "rust-analyzer.checkOnSave.overrideCommand": [
        "./x.sh",
        "check",
        "--json-output",
        "library/std",
        "compiler/rustc",
        //"compiler/rustc_codegen_cranelift",
        "src/tools/miri",
    ],
    "rust-analyzer.rustfmt.overrideCommand": [
        "./build/host/rustfmt/bin/rustfmt",
        "--edition=2021",
    ],
    // These just make everything way too slow.
    "rust-analyzer.cargo.buildScripts.overrideCommand": ["false"],
    "rust-analyzer.cargo.buildScripts.enable": false,
    "rust-analyzer.procMacro.enable": false,
```

**Comment by Veykril** [comment] 2023-07-30 11:54
> - [This](https://github.com/rust-lang/rust/blob/1c44af9b791c16557b5bf606707bb76df979134a/compiler/rustc_const_eval/src/interpret/step.rs#L185-L187)  triggers E0308 `expected &IndexSlice<{unknown}, Operand<'_>>, found &IndexVec<{unknown}, Operand<'_>>`

This I can't reproduce

> - [This](https://github.com/rust-lang/rust/blob/1c44af9b791c16557b5bf606707bb76df979134a/compiler/rustc_middle/src/mir/interpret/mod.rs#L320) triggers E0107 `expected 1 argument, found 0`
We resolve `position` to `Iterator::position` here, we resolve it correctly if `decoder` is a `&D` instead of a `&mut D`, so it seems like our autoderef is failing here maybe?

> - [This](https://github.com/rust-lang/rust/blob/bccefd280755e52b60d721bb6e5ff2556180a57b/compiler/rustc_middle/src/ty/layout.rs#L327) (and similar code later that file) triggers E0308 `expected &LayoutError<'_>, found LayoutError<'_>`

This I can't reproduce

**Comment by RalfJung** [comment] 2023-07-30 13:18
Hm, is my RA outdated or so? I am still seeing both of the E0308 with current rustc master. I am using vscodium but I doubt that should make a difference. Enabling build scripts and proc macros made no difference.

**Comment by Veykril** [comment] 2023-07-30 13:39
Ah, nevermind I can reproduce those two if I disable proc-macro expansion. (So I suppose something else with proc-macros fails for you when you enable them).

For the issue in layout this makes sense, since the scrutinee of the match expression no longer resolves so the patterns infer by value instead. The `step.rs` one fails since the `FieldIdx` in the type no longer exists, so the coercion fails.

**Comment by RalfJung** [comment] 2023-07-30 14:43
Ah right, when I enable proc macros and build scripts, there is some "failed to build proc macro" popup for about 0.5s but it disappears too quickly to read the message.

**Comment by lowr** [comment] 2023-07-30 14:44
Rather than the concrete errors, I'm wondering why rust-analyzer even shows type-mismatches when `"type-mismatch"` is set in `"rust-analyzer.diagnostics.disabled"`. Has #14990 changed the way it works?

**Comment by RalfJung** [comment] 2023-07-30 15:14
I now have to add `E0308` and `E0107` to `diagnostics.disabled` to hide these.

**Comment by Veykril** [comment] 2024-08-05 12:43
I'll close this, only one of these remains and that one is a chalk bug (don't recall which there are too many)

**Closed as completed by Veykril** 2024-08-05 12:43 UTC
Labels: A-ty, C-bug, A-rustc
