### ISSUE TITLE
Type mismatch with `dyn` Trait

### ISSUE THREAD

**Issue by allan2** [rust-lang/rust-analyzer#14005] opened 2023-01-23 00:54 UTC
**rust-analyzer version**: 0.3.1369-standalone
**rustc version**: tried both 1.66.0-nightly and 1.64.0 stable

*lib.rs*
```rust
pub fn type_mismatch_ex() {
    let mut params = Vec::<&(dyn Sync)>::with_capacity(2);
    let nums = vec![1, 2];
    for n in &nums {
        params.push(n);
    }
}
```

![screenshot](https://user-images.githubusercontent.com/6740989/213949877-08bdce6d-75d8-4802-811b-66eca062e458.png)

I got this error in rust-analyzer but the code compiles.

Maybe related to PR #13112?

**Comment by lowr** [comment] 2023-01-23 08:35
Duplicate of #11847.

**Closed by lowr** 2023-01-23 08:35 UTC
