### ISSUE TITLE
Import type quick fix places `use` in the wrong place

### ISSUE THREAD

**Issue by y21** [rust-lang/rust-analyzer#12866] opened 2022-07-24 17:46 UTC
When trying to name a type that is not in scope, RA will suggest a quick fix to import it. Normally the import (`use path::to::Type;`) is placed somewhere in the enclosing module. However, when a function is marked with `#[cfg(anything)]` and a parameter names a type that's not in scope, RA tries to generate the `use` *inside* of the function body. 

https://user-images.githubusercontent.com/30553356/180659212-49687435-10f6-4781-9f3f-888a3ae49db0.mp4

I don't know what makes most sense for RA to generate in this case. Maybe `use path::to::Type;` in the same module (like it does normally) but with the same cfg attributes?

**rust-analyzer version**: rust-analyzer version: 0.3.1131-standalone (897a7ec4b 2022-07-17)

**rustc version**: rustc 1.64.0-nightly (93ffde6f0 2022-07-23)

**relevant settings**: `"rust-analyzer.cargo.features": "all"`

**Comment by flodiebold** [comment] 2022-07-24 22:04
Duplicate of #9391.

**Closed by flodiebold** 2022-07-24 22:04 UTC
