### ISSUE TITLE
ra have trouble to expand procedural macro of the `xflags` crate when doc comment is used

### ISSUE THREAD

**Issue by nerditation** [rust-lang/rust-analyzer#17137] opened 2024-04-25 12:21 UTC
**rust-analyzer version**:
> rust-analyzer version: 0.4.1935-standalone (73a427588 2024-04-24)

**rustc version**:
> rustc 1.79.0-nightly (ccfcd950b 2024-04-15)

**editor or extension**:
> vscode extension version: 0.4.1935 (pre-release)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
none

**code snippet to reproduce**: 
```rust
// cargo add xflags@0.3.2
xflags::xflags! {
    /// doc comment lines cause problems
    cmd example {
    }
}
fn main() {
    let _cli = Example::from_env_or_exit();
}
```

--------

### some notes:

- the code is perfectly good;

  - can run `cargo build` and `cargo run` 
  - also `cargo expand` shows correct output

- vscode command "expand macro recursively at caret" output is **EMPTY**;

- ra doesn't seem to report any errors, as far as I can see, even with `RA_LOG = info`

- the macro generated types won't appear in code completion candidate list;

- removing doc comment lines **"fixes"** the problem;

- changing doc comment lines into equivalent `#[doc = "..."]` attributes also "fixes" the problem,

  -  e.g. ra can expand and parse this code without any problem:

  ```rust
  xflags::xflags! {
      #[doc ="this has no problem at all"]
      cmd example {
      }
  }
  ```

**Comment by Veykril** [comment] 2024-04-26 07:48
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/16259

**Closed by Veykril** 2024-04-26 07:48 UTC
Labels: C-bug
