### ISSUE TITLE
Feature request: Run check or clippy without saving

### ISSUE THREAD

**Issue by danielhuang** [rust-lang/rust-analyzer#6591] opened 2020-11-19 18:49 UTC
This would be similar to the feature in IntelliJ Rust called "Run external linter to analyze code on the fly"

**Comment by havish10** [comment] 2020-11-19 18:50
Yes this would be a feature that I would love to see!

**Comment by YangJeffrey** [comment] 2020-11-19 18:53
please add this feature ❤️

**Comment by MaximilianHollis** [comment] 2020-11-19 18:59
This would really speed up development.

**Comment by lnicola** [comment] 2020-11-19 19:01
You can configure some editors (including Code) to auto-save the edited files. Not sharing on-the-fly diagnostics with the compiler is a known limitation.

**Comment by danielhuang** [comment] 2020-11-19 19:04
Enabling auto save does not appear to trigger checking

**Comment by havish10** [comment] 2020-11-21 20:24
This would be something that would make me switch from clion to vscode!

**Comment by havish10** [comment] 2020-11-21 20:25
this is the feature that's keeping me on intellij rust

**Comment by hf29h8sh321** [comment] 2020-11-25 17:48
This would be a great feature !

**Comment by hf29h8sh321** [comment] 2020-11-29 18:35
This would be a great feature !

**Comment by hf29h8sh321** [comment] 2020-12-01 19:59
This would be a great feature !

**Comment by bjorn3** [comment] 2020-12-01 20:21
It is impossible to present the rust-analyzer vfs to rustc without a custom rustc driver. Custom rustc drivers require nightly, while rust-analyzer supports stable.

**Comment by deontologician** [comment] 2020-12-09 00:19
I wonder how hard it would be to shim clippy lints into rust-analyzer diagnostics directly. clippy only runs on nightly, but maybe with some combination of codegen and some shim for the `hir` types it would be possible / not a ton of manual porting?

**Comment by bjorn3** [comment] 2020-12-09 06:48
Rustc and rust-analyzer use fundamentally incompatible ways of working. Rust-analyzer is as lazy as possible while rustc is pretty eager. This is the reason rust-analyzer is so much faster than rls. Trying to shoehorn clippy into rust-analyzer would require giving up on the speed of rust-analyzer.

**Comment by GopherJ** [comment] 2021-01-17 15:15
Another reason that we need this is:

> cargo check is soooooooooooooooooooooo fucking slow:)

**Comment by jonas-schievink** [comment] 2021-02-10 19:21
IntelliJ certainly does not implement its own rustc driver, right? How do they implement this feature? autosave + check-on-save?

**Comment by bjorn3** [comment] 2021-02-10 19:31
I assume they simply already reproduce more of the diagnostics rustc produces in their kotlin code. Other than that they simply run cargo check pretty much the same way as rust-analyzer it seems: https://github.com/intellij-rust/intellij-rust/blob/58079c90c737b5357aadc629fda79c5cc8790760/src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt#L328 They do save all files before running it though: https://github.com/intellij-rust/intellij-rust/blob/118d9d9005c8fa611df6837212c92707d4a09a18/src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt#L107

**Comment by jonas-schievink** [comment] 2021-02-18 13:44
I've confirmed that configuring VS Code as follows makes this work:

```json
{
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 1000,
    "rust-analyzer.checkOnSave.enable": true
}
```

Since this issue is not about RLS-like compilation using *unsaved* files, but about IntelliJ's feature, which works the same way, I'm closing this as fixed (or rather, responsibility of the client, and not something rust-analyzer can do server-side).

**Closed by jonas-schievink** 2021-02-18 13:44 UTC
Labels: S-unactionable, A-diagnostics

**Comment by asv1** [comment] 2021-03-04 09:32
One problem here, autosave cannot be set per language in vscode.

**Comment by Logarithmus** [comment] 2021-11-15 00:27
> Another reason that we need this is:
> 
> > cargo check is soooooooooooooooooooooo slow:)
> 
> which sometimes really drives me crazy that after saving I'll need to wait 10 seconds to be able to see diagnostics

@GopherJ you contradict yourself in this comment. I have to use `rust-analyzer` without `checkOnSave` because for many projects `cargo check` is really slow. So running `cargo check` continuosly would be constantly using 100% of CPU & drain your battery in an hour or so. How come you don't understand that?

> This would really speed up development.

@MaximilianHollis it will slow down development, because your computer will become unresponsive due to constant 100% CPU usage. I think we should work more on optimizing `rustc` (parallelizing this final single-threaded phase is crucial, as well as procedural macros optimizations), as well as reducing dependencies in the most popular crates. After all this hard work we may be able to run `cargo check` continuosly without needing NASA supercomputer.

**Comment by jonas-schievink** [comment] 2021-11-15 00:38
Don't start arguments in the issue tracker please

**Comment by jhonpedro** [comment] 2023-03-20 00:13
> One problem here, autosave cannot be set per language in vscode. Maybe add autosave delay for rust analyzer settings?

But you can do it per workspace, I think that this is a good workaround

**Comment by nikitavoloboev** [comment] 2023-05-11 12:09
Coming from https://github.com/rust-lang/rust-analyzer/issues/4185

Is this still not possible to do without this hack

```
{
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 1000,
    "rust-analyzer.checkOnSave.enable": true
}
```

Which I don't want to run as I run rust code with `cargo watch -q -- sh -c "tput reset && cargo run -q"`.

Anything one can do to help implement this needed feature?

**Comment by bjorn3** [comment] 2023-05-11 13:38
This needs a rustc change to support loading files from rust-analyzer's VFS instead of the disk.

**Comment by nikitavoloboev** [comment] 2023-05-11 15:14
> This needs a rustc change to support loading files from rust-analyzer's VFS instead of the disk

Is there an open issue in rustc about it or should we open it?

**Comment by nikitavoloboev** [comment] 2023-05-11 17:40
I want to be using https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens to see errors inline.

**Comment by Atemu** [comment] 2025-04-01 16:32
It's been a few years, what is the state of this?

I have gathered that rust-analyzer needs more direct access to what `cargo check` does internally in order to be able to run the checks on unsaved files and likely other desirable features such as caching etc.

Given that this issue is closed, is there anywhere else where progress on that is tracked?

**Comment by natanfudge** [comment] 2025-04-07 21:41
@bjorn3 
So lets make one
https://internals.rust-lang.org/t/allow-running-cargo-check-on-a-virtual-file-system-like-the-one-held-by-rust-analyzer/22709
