### ISSUE TITLE
Failure to Infer Complicated Types

### ISSUE THREAD

**Issue by HTGAzureX1212** [rust-lang/rust-analyzer#16296] opened 2024-01-07 03:36 UTC
**rust-analyzer version**: 0.4.1797-standalone (f595e60b6 2024-01-06)

`DATABASE_POOL` declaration:
```rs
pub type PostgresPool = Pool<PostgresConnectionManager<NoTls>>;
pub type DatabasePoolFuture = impl Future<Output = PostgresPool>;
pub static DATABASE_POOL: AsyncLazy<PostgresPool, DatabasePoolFuture> = AsyncLazy::new(async {
    let hartex_pgsql_url = env::var("HARTEX_NIGHTLY_PGSQL_URL").unwrap();

    let manager = PostgresConnectionManager::new_from_stringlike(hartex_pgsql_url, NoTls).unwrap();

    Pool::builder().build(manager).await.unwrap()
});
```

Rust Analyzer behaviour:
![image](https://github.com/rust-lang/rust-analyzer/assets/39023054/c745692a-d7a2-465b-ae82-fe0953b60d65)

RustRover behaviour:
![image](https://github.com/rust-lang/rust-analyzer/assets/39023054/b8dc5eb2-0993-4db8-bbff-2d92b48e1013)

**Comment by ShoyuVanilla** [comment] 2024-08-10 06:04
I think that this issue happend in here, right?
https://github.com/TeamHarTex/HarTex/blob/6794deb510fa9f96eb4d0c3b26b729a8f5326f40/rust-utilities/hartex-discord-utils/src/lib.rs#L61-L73

This is not happening in the current version of r-a somehow;
<img width="1682" alt="issue" src="https://github.com/user-attachments/assets/2b038758-f563-4b7c-96c1-041b591c5e0a">

but I think that the cause was type alias impl trait in L64;
```rust
pub type DatabasePoolFuture = impl Future<Output = PostgresPool>;
```

I guess the reason this has been fixed somehow is my ATPIT implementation in #16852 worked partly in some TAITs and I think that this issue can be marked as closed by implementing TAIT correctly.

**Closed** 2024-08-12 08:22 UTC
Labels: A-ty, C-bug
