### ISSUE TITLE
Incorrect type hint with itertools izip macro with 3+ arguments

### ISSUE THREAD

**Issue by pgimalac** [rust-lang/rust-analyzer#13526] opened 2022-11-01 22:53 UTC
**rust-analyzer version**: 0.3.1266-standalone

**rustc version**: rustc 1.64.0 (a55dd71d5 2022-09-19)

Any use of `itertools::izip!` with 3 or more arguments displays incorrect type for 3rd (and more) element (eg. here it display `i32` instead of `&str`). The incorrectly displayed type is the one of argument 2 (here `i32`).

Minimal example:
```rs
let _e = itertools::izip!(vec![0.1], vec![1], vec![""]).collect::<Vec<_>>();
```
![image](https://user-images.githubusercontent.com/23154723/199355406-20a68467-ce2c-4fdc-8044-2660a7cf458f.png)

I can still use the result of `izip` with the correct types and everything runs correctly so I guess the issue is on how rust-analyzer generates the types of macros and not on `itertools` / `rustc` 's side.

**Comment by lnicola** [comment] 2022-11-02 07:35
Duplicate of #11681.

**Closed by lnicola** 2022-11-02 07:35 UTC
