### ISSUE TITLE
Confused function aliases

### ISSUE THREAD

**Issue by harisraharjo** [rust-lang/rust-analyzer#12218] opened 2022-05-12 04:04 UTC
So I'm trying to create a dynamic matrix with [nalgebra](https://github.com/dimforge/nalgebra) like `let dm3 = DMatrix::from_fn(3, 3, |r, c| if r == c { 1.0 } else { 0.0 })`. This code is a copy from [this](https://github.com/dimforge/nalgebra/blob/dev/examples/matrix_construction.rs) official file. 
## Current Behaviour
Rust-analyzer is giving me [this](https://rust-analyzer.github.io/manual.html#mismatched-arg-count) error eventhough the `cargo check` command says it works just fine
## Expected Behaviour
Rust-analyzer should be able to know different types of function aliases and not show error 

**rust-analyzer version**: 5d5bbec9b 2022-05-09 stable
**rustc version**: 1.60.0 (7737e0b5c 2022-04-04)
**relevant settings**: `vscode {
Check On Save: Command = clippy
}`

**Comment by lnicola** [comment] 2022-05-12 06:30
Probably a dupe of #544.

**Closed by lnicola** 2022-05-12 06:30 UTC

**Comment by flodiebold** [comment] 2022-05-12 08:48
#5441, that is ;)
