### ISSUE TITLE
Hovering over an error in VS Code shows me the help instead of the error

### ISSUE THREAD

**Issue by mvtec-bergdolll** [rust-lang/rust-analyzer#13205] opened 2022-09-08 13:40 UTC
rust-analyzer version: 0.3.1194-standalone (67920f797 2022-09-04)

rustc 1.65.0-nightly (29e4a9ee0 2022-08-10)

When I hover over an error, more often than not it shows me literal pages worth of documentation before telling me what is wrong. That's annoying, I hover over the error squiggle because I want to know what is wrong.

Example:

![rust-analyzer-error-show](https://user-images.githubusercontent.com/62337596/189137255-79783101-5ca2-40ee-b799-e18745b1c9f3.gif)

**Comment by Veykril** [comment] 2022-09-08 13:52
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/6070

**Closed by Veykril** 2022-09-08 13:52 UTC
