### ISSUE TITLE
rust-analyzer failed to discover workspace: Sounds like wrong assumptions being made about human behaviour

### ISSUE THREAD

**Issue by cottrell** [rust-lang/rust-analyzer#13371] opened 2022-10-09 09:34 UTC
VSCode shows old rust-lang extensions is deprecated. Pushes everyone towards this one. When this one is installed you get errors about "failed to discover workspace" and click through (to def) doesn't work. I suspect this is due to wrong assumptions being made that humans will open one vscode window per rust project. This is not how vscode is used. You open a top level folder with many projects in it and use vscode to search and work on all of them.

The extension should search for "nearest" Cargo.toml to the file being viewed and maintain scopes. Typically one is in src/ somewhere and ../Cargo.toml is good guess. Not sure if there is an option for that but it should be default.

**Comment by cottrell** [comment] 2022-10-09 09:41
Ongoing stuff https://users.rust-lang.org/t/rust-analyzer-failed-to-discover-workspace/47457/4

**Comment by cottrell** [comment] 2022-10-09 09:42
This thread indicates it is not enabled. https://www.reddit.com/r/rust/comments/n1crnt/rustanalyzer_doesnt_want_to_work/

If it is in alpha state it definitely should not be the recommended extension in vscode. If there is a fix, we should try to bump it up in the search results.

**Comment by cottrell** [comment] 2022-10-09 09:44
This *might* be a workaround but is not obvious (5 s) https://rust-analyzer.github.io/manual.html#non-cargo-based-projects

**Comment by cottrell** [comment] 2022-10-09 09:46
Related https://users.rust-lang.org/t/working-on-bigger-projects-using-vscode-with-rust-analyzer/54628

**Comment by flodiebold** [comment] 2022-10-09 10:03
Duplicate of #13226 and others. (If you need a workaround and don't want to just open the project folder, setting `rust-analyzer.linkedProjects` as described in your first link is the way to go.)

**Closed by flodiebold** 2022-10-09 10:03 UTC
