### ISSUE TITLE
Can I set proxy for rust-analyzer ? 

### ISSUE THREAD

**Issue by q2333gh** [rust-lang/rust-analyzer#15869] opened 2023-11-11 09:54 UTC
Due to my vscode stuck at rust-analyzer: Fetching metadata . 
China network firewall may block some networking from rust-analyzer.So i want to use proxy to fetch info.

I use local  win11 vscode-client . the rust-analyzer both on win11-vscode-clinet  and Extension is enabled on 'SSH: ubuntu_vmware_btwl'-vscode-server   where should I set proxy ? and how ? 

this is what i have do: 
![image](https://github.com/rust-lang/rust-analyzer/assets/32679742/df41c624-c3b8-453a-8dea-907ef57e8cff)
It works when i download some extension in vscode . but dont work in rust-analyzer.

**Comment by lnicola** [comment] 2023-11-11 10:27
rust-analyzer just runs `cargo`, see https://doc.rust-lang.org/cargo/reference/config.html#configuration-format.

**Comment by lnicola** [comment] 2023-11-11 10:42
Duplicate of #9448.

**Closed by lnicola** 2023-11-11 10:42 UTC
Labels: C-support
