### ISSUE TITLE
glibc version requirement jumped with the current release past the Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by kamulos** [rust-lang/rust-analyzer#13082] opened 2022-08-22 10:44 UTC
I am deveoping in a Ubuntu 18.04 container. With the newest release of the VSCode extension (0.3.1178) it fails to start:

```
INFO [8/22/2022, 10:22:57 AM]: Using server binary at /home/build/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/server/rust-analyzer
ERROR [8/22/2022, 10:22:57 AM]: Bootstrap error [Error: Failed to execute /home/build/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/server/rust-analyzer --version
	at IS (/home/build/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/out/main.js:85:2328)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async kS (/home/build/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/out/main.js:84:1060)
	at async pv (/home/build/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/out/main.js:84:891)
	at async v._activate (/home/build/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:85:8180)
	at async v._waitForDepsThenActivate (/home/build/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:85:8122)
	at async v._initialize (/home/build/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:85:7486)]
```
The reason is displayed, when I try to execute it manually:

```
uild@1c38b786d96f:/cmcloud$ /home/build/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/server/rust-analyzer --version
/home/build/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/server/rust-analyzer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /home/build/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/server/rust-analyzer)
/home/build/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/server/rust-analyzer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/build/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/server/rust-analyzer)
```

The available version in Ubuntu 18.04 LTS seems to be 2.27:

```
build@1c38b786d96f:/cmcloud$ ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27
```

**Comment by lnicola** [comment] 2022-08-22 10:46
Duplicate of #13081

**Closed by lnicola** 2022-08-22 10:46 UTC
