### ISSUE TITLE
`include!` macro can't include files outside of project's directory.

### ISSUE THREAD

**Issue by DiscreteTom** [rust-lang/rust-analyzer#17507] opened 2024-06-28 08:03 UTC
**rust-analyzer version**: VSCode 0.3.2011-standalone (2fd803cc1 2024-06-22)

**rustc version**: rustc 1.78.0 (9b00956e5 2024-04-29)

**editor or extension**: VSCode

**repository link (if public, optional)**: 
https://github.com/DiscreteTom/rust-analyzer-include-issue

**code snippet to reproduce**: 
```rust
// see the repo above for more details
include!("../../snippet.rs");

fn main() {
    println!("{}", snippet());
}
```

Got error: 

```
failed to load file `../../snippet.rs`rust-analyzer[macro-error](https://rust-analyzer.github.io/manual.html#macro-error)
```

However this is compile-able and runable by `cargo build` or `cargo run`.

**Comment by davidbarsky** [comment] 2024-06-28 13:48
Unfortunately a known issue. I'll close this as a dupe of https://github.com/rust-lang/rust-analyzer/issues/17040.

**Closed by davidbarsky** 2024-06-28 13:48 UTC
Labels: C-bug
