### ISSUE TITLE
Pre-compiled binary does not work on CentOS 7

### ISSUE THREAD

**Issue by marlls1989** [rust-lang/rust-analyzer#12585] opened 2022-06-19 19:40 UTC
When using rust-analyser with either Coc.nvim or a remote visual studio session on a CentOS 7 remote machine, I have to manually compile from source and point to the executable because the version automatically downloaded requires a too newer version of GLIBC.

I would suggest compiling the binary distribution on an older distro, e.g. Centos 7, to guarantee greater compatibility.

**Comment by lnicola** [comment] 2022-06-19 19:42
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/11434 and others.

**Closed** 2022-06-19 19:42 UTC
