### ISSUE TITLE
Incorrect mismatched-arg-count in rustc

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-analyzer#13631] opened 2022-11-18 10:04 UTC
To reproduce, check out rustc and navigate to [this line](https://github.com/rust-lang/rust/blob/83356b78c4ff3e7d84e977aa6143793545967301/compiler/rustc_middle/src/mir/mod.rs#L1128). RA reports an incorrect-arg-count there, but that is wrong -- the `index` function being called here is [defined via a macro here](https://github.com/rust-lang/rust/blob/83356b78c4ff3e7d84e977aa6143793545967301/compiler/rustc_middle/src/mir/mod.rs#L1562-L1565). I have proc macros disabled so I am not surprised it cannot find that type, but it still should not report incorrect diagnostics. The type of `field` shows as `&{unknown}`, and when a method is called on an unknown type, RA shouldn't assume it knows which method that is and how many arguments it has.

**Comment by Veykril** [comment] 2022-11-18 10:13
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/6975
r-a assumes it's implementing `Index` as that is in scope.

Curious but why do you have proc-macros disabled on rustc? They should work nowadays

**Closed by Veykril** 2022-11-18 10:13 UTC

**Comment by RalfJung** [comment] 2022-11-18 10:15
The comment in my vscode config says "These just make everything way too slow". The extra full check build that is required for proc macros to work just makes quickly editing some parts of rustc too annoying.

**Comment by lnicola** [comment] 2022-11-18 10:20
It's not a full check, we have that RUSTC_WRAPPER hack. But of course, you can disable the diagnostic.

**Comment by Veykril** [comment] 2022-11-18 10:22
I assume the wrapper doesn't affect the `x.py` script too much

**Comment by RalfJung** [comment] 2022-11-18 10:23
That hack caused quite a few problems in the past so I disabled it (globally). I usually want a check build anyway so I'd rather RA share the results of that with its proc macro support, than go over the code twice (with and without the wrapper). It's just in rustc where even check builds take several minutes that I am looking for ways to cut down startup time.

**Comment by lnicola** [comment] 2022-11-18 10:25
Have you tried the option to disable cache warming?

**Comment by RalfJung** [comment] 2022-11-18 10:27
I did, for a bit. Then it seemed like tooltips with type information don't work reliably any more, so I went back to the default.

**Comment by RalfJung** [comment] 2022-11-18 10:29
Maybe I should try no cache warming + wrapper + proc macros in rustc again one day. But for now, disabling proc macros gets me pretty far and avoids many potential sources of bugs.^^

**Comment by lnicola** [comment] 2022-11-18 10:30
That's shouldn't be the case AFAICT. They might be delayed at times, but still work. I hope Code doesn't time them out.

**Comment by Veykril** [comment] 2022-11-18 10:33
Ye that sounds like a bug to me. Fwiw, we hopefully get rid of the wrapper hack in the (near 🤞) future https://github.com/rust-lang/rfcs/pull/3344
