### ISSUE TITLE
[VSCode] rust-analyzer will be triggered when meson plugin is used

### ISSUE THREAD

**Issue by kands-code** [rust-lang/rust-analyzer#18271] opened 2024-10-09 05:50 UTC
**rust-analyzer version**: rust-analyzer 1.83.0-nightly (6f4ae0f3 2024-10-08)

**rustc version**: rustc 1.83.0-nightly (6f4ae0f34 2024-10-08)

**editor or extension**: v0.3.2137

**steps to reproduction**:

- start a meson project
- click meson tabs
- run whatevver
- then rust-analyzer is triggered

**videos**:

https://github.com/user-attachments/assets/9f401827-ea2b-4636-9f1b-f61720627755

**Comment by davidbarsky** [comment] 2024-10-09 16:03
This is a bug in VS Code (https://github.com/rust-lang/rust-analyzer/issues/15068, https://github.com/rust-lang/rust-analyzer/issues/14231), where listing building tasks _activates_ extensions as well. I'll close this issue as a duplicate of those.

**Closed by davidbarsky** 2024-10-09 16:03 UTC
Labels: C-bug
