### ISSUE TITLE
Unit tests in lib/core workspace parsed abnormally

### ISSUE THREAD

**Issue by Banyc** [rust-lang/rust-analyzer#12282] opened 2022-05-17 06:47 UTC
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)

rust-analyzer version: 94fa8a653 2022-05-12 nightly

**rustc version**: (eg. output of `rustc -V`)

rustc 1.60.0 (7737e0b5c 2022-04-04)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

none

# File structure

- A
  - core
    - src/
    - Cargo.toml
  - B 
    - src/
    - Cargo.toml
  - C
    - src/
    - Cargo.toml
  - Cargo.lock
  - Cargo.toml

`A/Cargo.toml`:

```toml
[workspace]
members = [
    "core",
    "B",
    "C",
]

```

`A/core/Cargo.toml`:

```toml
[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```

`A/B/Cargo.toml`:

```toml
[package]
name = "B"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "../core" }
```

`A/C/Cargo.toml`:

```toml
[package]
name = "C"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "../core" }
```

# Issues

Unit tests written in files under `core/src` do not have `CodeLen` features like `Run Test | Debug` buttons. Worse still, the suggestions make little sense.

In comparisons, the unit tests in `B/src` work as expected. None of the issues happens here.

**Comment by jonas-schievink** [comment] 2022-05-17 14:09
This happens because `cfg(test)` is unset by default for `core`, since otherwise the whole libcore disappears

**Comment by Banyc** [comment] 2022-05-18 06:04
@jonas-schievink Thanks! But im a bit confused about the inside logic. Is it an expected behavior? If so, how to get around this issue?

**Comment by bjorn3** [comment] 2022-05-18 06:09
Try renaming your crate from core to something else. Even if it doesn't give problems for rustc at the moment naming one of your own crates core is bound to give problems if some code wants to use the core crate of the standard library.

**Comment by Banyc** [comment] 2022-05-18 06:18
@bjorn3 Besides `core`, is there any more taboo name?

**Comment by bjorn3** [comment] 2022-05-18 07:02
core, alloc, std, proc_macro and test are the only public facing standard library crates. Test is unstable right now, but overriding it may break `#[test]` tests. Other than those five everything should be fine I think.

**Comment by Veykril** [comment] 2023-02-08 12:07
Closing as this is expected behavior

**Closed by Veykril** 2023-02-08 12:07 UTC
Labels: C-bug, A-ide
