### ISSUE TITLE
thread 'Worker' panicked at 'index out of bounds

### ISSUE THREAD

**Issue by kzhui125** [rust-lang/rust-analyzer#15676] opened 2023-09-28 07:12 UTC
**rust-analyzer version**: rust-analyzer version: 0.3.1673-standalone (862a3004e 2023-09-24)

**rustc version**: rustc 1.72.1 (d5c2e9c34 2023-09-13)

extension panic and crash, vscode output is here:

[panic_context.txt](https://github.com/rust-lang/rust-analyzer/files/12746636/panic_context.txt)

Will try to reproduce if I meet this issue again.

**Comment by lnicola** [comment] 2023-09-28 07:14
Duplicate of #5366.

**Closed by lnicola** 2023-09-28 07:14 UTC
Labels: C-bug
