### ISSUE TITLE
Option for toggling autoclose of angle brackets

### ISSUE THREAD

**Issue by aftix** [rust-lang/rust-analyzer#12332] opened 2022-05-20 16:36 UTC
The current `editor.autoClosingBrackets` effects all brackets like `()` and `{}`. I'd like to specifically opt out of closing `<` since `<` is used for comparisons and shift operations.

**Comment by jonas-schievink** [comment] 2022-05-20 17:54
We don't register `<>` as an auto-closing bracket pair:

https://github.com/rust-lang/rust-analyzer/blob/11823872240d83aa5075575056414cd7d29eba3f/editors/code/language-configuration.json#L16-L22

This might be an issue with your configuration. Do you have other Rust plugins installed that could interfere?

**Comment by aftix** [comment] 2022-05-20 22:04
Huh, setting a rust language specific option `editor.autoClosingBrackets` to `languageDefined` gives me all of those but doesn't auto close `>` anymore. In fact, I can't get any setting to recreate the behavior now, despite the fact someone else said they had the same problem.

**Comment by lnicola** [comment] 2022-05-25 14:17
Closing since you can't reproduce it, but you might want to keep an eye on https://github.com/rust-lang/rust-analyzer/issues/12379.

**Closed by lnicola** 2022-05-25 14:17 UTC
Labels: S-unactionable, C-support
