### ISSUE TITLE
Panic in HIR when processing tinyvec macros

### ISSUE THREAD

**Issue by alexrudy** [rust-lang/rust-analyzer#14608] opened 2023-04-19 03:35 UTC
**rust-analyzer version**: 0.3.1481-standalone (bab80dae4 2023-04-16)

**rustc version**: (eg. output of `rustc -V`) rustc 1.69.0-beta.8 (f18236dcd 2023-04-13)

**relevant settings**: possibly `"rust-analyzer.procMacro.enable": true,`

I haven't minimized this bug. `rust-analyzer analysis-stats` doesn't reproduce the bug, and from what I'm reading in the panic, it looks like the bug is somewhere in the generation of InlayHints. I would like to provide a better minimization, but I'm not sure where to start, so pointers are most welcome!

What I've got so far:

Rust Analyzer ends up in a panic loop with this panic:
```
> DefMap Idx::<CrateData>(86) crate_name=Some(CrateDisplayName { crate_name: CrateName("tinyvec_macros"), canonical_name: "tinyvec_macros" }) block=None path=Sealed

thread 'Worker' panicked at 'index out of bounds: the len is 1 but the index is 5', crates/hir-def/src/nameres/path_resolution.rs:390:33
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro_single
   4: hir_def::resolver::Resolver::resolve_path_in_type_ns
   5: hir_ty::lower::TyLoweringContext::lower_trait_ref_from_path
   6: hir_ty::lower::TyLoweringContext::lower_type_bound
   7: hir_ty::lower::TyLoweringContext::lower_where_predicate
   8: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
   9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  10: hir_ty::lower::generic_predicates_query
  11: salsa::runtime::Runtime::execute_query_implementation
  12: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  13: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  14: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  15: salsa::derived::slot::MemoRevisions::validate_memoized_value
  16: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  17: salsa::derived::slot::Slot<Q,MP>::read
  18: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  19: <DB as hir_ty::db::HirDatabase>::trait_datum::__shim
  20: <chalk_ir::UCanonical<chalk_ir::InEnvironment<chalk_ir::Goal<I>>> as chalk_solve::coinductive_goal::IsCoinductive<I>>::is_coinductive
  21: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  22: chalk_recursive::fulfill::Fulfill<I,Solver>::prove
  23: chalk_recursive::fulfill::Fulfill<I,Solver>::solve
  24: chalk_recursive::solve::SolveIteration::solve_iteration
  25: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  26: chalk_recursive::fulfill::Fulfill<I,Solver>::prove
  27: chalk_recursive::fulfill::Fulfill<I,Solver>::solve
  28: chalk_recursive::solve::SolveIteration::solve_iteration
  29: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  30: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  31: hir_ty::traits::trait_solve_query
  32: salsa::runtime::Runtime::execute_query_implementation
  33: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  34: salsa::derived::slot::Slot<Q,MP>::read
  35: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  36: salsa::QueryTable<Q>::get
  37: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  38: hir_ty::db::trait_solve_wait
  39: <DB as hir_ty::db::HirDatabase>::trait_solve
  40: hir_ty::infer::unify::InferenceTable::register_obligation_in_env
  41: hir_ty::infer::unify::InferenceTable::resolve_obligations_as_possible
  42: hir_ty::infer::pat::<impl hir_ty::infer::InferenceContext>::infer_pat
  43: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  44: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  45: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_return
  46: hir_ty::infer::infer_query
  47: salsa::runtime::Runtime::execute_query_implementation
  48: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  49: salsa::derived::slot::Slot<Q,MP>::read
  50: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  51: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  52: <DB as hir_ty::db::HirDatabase>::infer_query
  53: hir_ty::db::infer_wait
  54: <DB as hir_ty::db::HirDatabase>::infer
  55: hir::DefWithBody::diagnostics
  56: hir::ModuleDef::diagnostics
  57: hir::Module::diagnostics
  58: hir::Module::diagnostics
  59: ide_diagnostics::diagnostics
  60: salsa::Cancelled::catch
  61: ide::Analysis::diagnostics
  62: rust_analyzer::handlers::publish_diagnostics
  63: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  64: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Veykril** [comment] 2023-04-19 05:17
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/10084

**Closed by Veykril** 2023-04-19 05:17 UTC
Labels: C-bug
