### ISSUE TITLE
MonoRepo - linkedProjects ERROR FetchWorkspaceError

### ISSUE THREAD

**Issue by grahamsmallenroly** [rust-lang/rust-analyzer#17752] opened 2024-07-31 15:16 UTC
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
rust-analyzer version: 0.3.2053-standalone (fd74511f3 2024-07-28)

**rustc version**: (eg. output of `rustc -V`)
rustc 1.80.0 (051478957 2024-07-21)

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable)
VSCode rust-analyzer v0.3.2053

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
  "rust-analyzer.linkedProjects": [
    "rust/lambdas/[some project name]/Cargo.toml",
    ...
  ]
}
**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))

**code snippet to reproduce**: 
```rust
// add your code here

```

Experiencing the following error
2024-07-31T15:04:55.390885Z ERROR failed to find any projects in [AbsPathBuf("/Users/*********/my-dev/*******")]
2024-07-31T15:04:55.401650Z ERROR FetchWorkspaceError:
rust-analyzer failed to discover workspace
2024-07-31T15:04:55.402082Z ERROR FetchWorkspaceError:
rust-analyzer failed to discover workspace

We are a mono-repo, there is no .toml file in root. We have a .vscode/settings.json file with values for rust-analyzer.linkedProjects being the project roots of rust projects. 

This has been working. 

I can see the extension has been updated today: Last released 2024-07-31, 01:32:43

**Comment by davidbarsky** [comment] 2024-07-31 16:36
The workaround, at least until https://github.com/rust-lang/rust-analyzer/pull/17750 is in a build, is to use absolute paths. Closing as a duplicate of https://github.com/rust-lang/rust-analyzer/issues/17664.

**Closed by davidbarsky** 2024-07-31 16:36 UTC
Labels: C-bug

**Comment by lnicola** [comment] 2024-07-31 17:33
https://github.com/rust-lang/rust-analyzer/pull/17750 is now available in a pre-release build.

**Comment by grahamsmallenroly** [comment] 2024-08-01 07:55
Lovely. Thank you.

**Comment by grahamsmallenroly** [comment] 2024-08-01 08:00
I can confirm the pre-release version has fixed thee issue I was experiencing. 💪
