### ISSUE TITLE
Parantheses not removed when completing a function pointer (e.g. map(String::from_str))

### ISSUE THREAD

**Issue by tom-anders** [rust-lang/rust-analyzer#14187] opened 2023-02-21 21:44 UTC
**rust-analyzer version**: rust-analyzer 0.0.0 (16ba5dd77 2023-02-20)

**rustc version**: rustc 1.67.1 (d5a82bbd2 2023-02-07)

For example: 

```
fn main() {
    let strs = vec!["foo", "bar"];
    strs.iter().map(String::fr^); 
}
```

Triggering completion at ^ suggests `from_str(...)`, but it should be `from_str` instead.

Interestingly, when you type `from` and trigger completion, it works, but then once you get to `from_` it stops working again.

Here's an asciinema recording from neovim, but I could also reproduce this in VsCode, so it should not be an editor issue: https://asciinema.org/a/rvZb7zDIrv9YFodTj7SgCJa8c

I tried adding some debugging output to `params()` in `render/function.rs`. When printing `ctx.expected_type`, the `ty` field is displayed as `{error}`, this corresponds to the parantheses not being removed. This is my very first time working with the code base, so I'm kinda stuck at this point and don't know where to look next. If someone can guide me into the right direction, maybe I can investigate a bit more.

Thanks for this great piece of software! Let me know if anything is unclear.

**Comment by flodiebold** [comment] 2023-02-22 08:00
Duplicate of #3148; in #8676 there's an explanation why this is complicated :sweat_smile:

**Closed** 2023-02-22 08:00 UTC
Labels: C-bug
