### ISSUE TITLE
Trait bounds for specific types, type inference failed.

### ISSUE THREAD

**Issue by A4-Tacks** [rust-lang/rust-analyzer#16855] opened 2024-03-16 11:49 UTC
**rust-analyzer version**: `rust-analyzer 1.76.0 (07dca48 2024-02-04)`

**rustc version**: `rustc 1.76.0 (07dca489a 2024-02-04)`

**relevant settings**: NONE

**repository link (if public, optional)**: NONE

**code snippet to reproduce**: 
```rust
use std::borrow::Borrow;

fn f<T>()
where u32: Borrow<T>,
{
    let _x = 1u32.borrow(); // ra: let _x: &{unknown} // size = 8, align = 0x8
    println!("{}", core::any::type_name_of_val(&_x)); // &u32
}
fn main() { f() }
```

**Comment by lnicola** [comment] 2024-03-16 15:15
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/5514.

**Closed by lnicola** 2024-03-16 15:15 UTC
Labels: C-bug
