### ISSUE TITLE
Expanding proc macros fail in the latest rust nightly

### ISSUE THREAD

**Issue by tamasfe** [rust-lang/rust-analyzer#12495] opened 2022-06-08 16:58 UTC
Expanding proc macros in the [following codebase](https://github.com/tamasfe/taplo) seem to fail with the messages:

```
memory allocation of 140637737325848 bytes failed
[ERROR rust_analyzer::reload] proc macro server crashed: server exited
[ERROR rust_analyzer::reload] proc macro server crashed: failed to write request: Broken pipe (os error 32)
...
```

Unfortunately I don't have an MRE for this.

Possible workaround could be installing ~130 TiB RAM which I haven't tried.

**rust-analyzer version**: rust-analyzer version: ad6810e90 2022-06-06 stable
**rustc version**: rustc 1.63.0-nightly (5435ed691 2022-06-07)

**Comment by lnicola** [comment] 2022-06-08 16:59
Dupe of #12489

**Closed by lnicola** 2022-06-08 16:59 UTC
