### ISSUE TITLE
snake_case Quick Fix should refactor symbol

### ISSUE THREAD

**Issue by tevoinea** [rust-lang/rust-analyzer#17413] opened 2024-06-13 14:18 UTC
```rust
fn demo() {
  let notSnakeCase = 1;                 <---- applying the Quick Fix here
  println!("{}", notSnakeCase);        <---- should also update this line
}

**Comment by lnicola** [comment] 2024-06-13 14:21
Duplicate of #7742. We rename it just fine, it's the `rustc` suggestion that's incorrect. Try this one instead:

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/cf7f6e01-0632-48d3-8ff0-f85c79369140)

**Closed by lnicola** 2024-06-13 14:21 UTC
Labels: C-feature
