### ISSUE TITLE
VS Code extension assumes workspace uses `/` path separator for debugging

### ISSUE THREAD

**Issue by Toby222** [rust-lang/rust-analyzer#16025] opened 2023-12-05 11:19 UTC
**rust-analyzer version**: rust-analyzer 0.3.1756-standalone (e402c494b 2023-12-01)

Trying to debug anything using the VS Code rust-analyzer brings up the following error:
![Error window with text "Invalid 'cwd' value 'C:\Users\Berger\Documents\repos\AdventOfCode\rust\Cargo.toml. The directory name is invalid."](https://github.com/rust-lang/rust-analyzer/assets/14962962/14057853-04b6-480c-8a93-576e9e4d29d8)

After some debugging, I found that [this](https://github.com/rust-lang/rust-analyzer/blob/2d66f6df252896cfbd7bd24be6ee0c124369b1b7/editors/code/src/toolchain.ts#L77) is supposed to remove the trailing "`Cargo.toml`", but assumes the path separator at that point is `/`, instead of Windows' `\`.

**Comment by lnicola** [comment] 2023-12-05 11:23
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/16010.

**Closed by lnicola** 2023-12-05 11:23 UTC
Labels: C-bug
