### ISSUE TITLE
Feature request: prefer using type alias in inlay hints

### ISSUE THREAD

**Issue by jkelleyrtp** [rust-lang/rust-analyzer#12194] opened 2022-05-09 05:20 UTC
I use a lot of Type Aliases in my libraries, but inlay hints gets really messy when trying to print out the concrete type.

In my opinion, RA should try to use the type alias, especially if the signature of a method or function is using it.

If I have the type `Element = Option<Node>` and the function
```rust
fn create() -> Element {}
```

I would expect the inlay hint

```rust
let node = create();
```

to be Element, not `Option<Node>`.

The heuristics here don't have to be 100%, but for the obvious cases where hints are coming from functions that explicitly opt into aliases, then the inlay hint should show an alias.

**Comment by flodiebold** [comment] 2022-05-09 08:07
Duplicate of #1666.

**Closed by flodiebold** 2022-05-09 08:07 UTC
