### ISSUE TITLE
Auto complete doesn't work properly in a function completion

### ISSUE THREAD

**Issue by BlankParticle** [rust-lang/rust-analyzer#14660] opened 2023-04-26 10:03 UTC
**rust-analyzer version**: `0.3.1489-standalone`
**rustc version**: `rustc 1.69.0 (84c898d65 2023-04-16)`
**relevant settings**:  Nothing different, default config provided by rustup 

I am using the Rust Analyzer VSCode Extension, when autocompleting a function the arguments of that function are also added with their default name. When I am trying to pass my argument, auto complete suggest options. But I can't insert those with `Enter` or `Tab`.

My guess is that the variables being selected while auto completing is cause of the issue.
I attached a video showcasing the problem.

PS: I would love to work on the issue, if I can get help about where to look for the function that is responsible for providing the auto complete suggestions.

[Screencast_20230426_151446.webm](https://user-images.githubusercontent.com/130567419/234542405-f678bf70-6b2c-4775-b0ab-f40756d51dfd.webm)

**Comment by Ddystopia** [comment] 2023-04-28 09:28
To me it looks like a VSCode configuration issue

**Comment by BlankParticle** [comment] 2023-04-28 09:31
This is a new empty profile with latest version of vs code and rust analyzer. But It is still same.

Can you try it on your machine?

If it works on your  machine then can you send your `settings.json` file with personal information removed

**Comment by antonilol** [comment] 2023-05-02 18:26
i have this problem as well, i dont think it is a vs code configuration issue because this feature works normally out of the box with for example typescript (native support) and c (using clangd extension)

**Comment by Veykril** [comment] 2023-05-03 07:09
You'll most likely have to set `editor.suggest.snippetsPreventQuickSuggestions` to `false` in your settings

**Comment by antonilol** [comment] 2023-05-04 16:38
> You'll most likely have to set `editor.suggest.snippetsPreventQuickSuggestions` to `false` in your settings

i am pretty sure it worked but testing now with c (clangd) it doesn't work anymore. it turns out they changed the default value for this setting to `false`. setting this value to `true` gave me the expected behavior back, thank you!

**Comment by MariaSolOs** [comment] 2023-05-05 03:16
> You'll most likely have to set `editor.suggest.snippetsPreventQuickSuggestions` to `false` in your settings, or set `rust-analyzer.completion.callable.snippets` to `"none"`/`"add_parentheses"`

That setting [was removed recently though](https://github.com/microsoft/vscode/pull/181098).

**Comment by MariaSolOs** [comment] 2023-05-05 03:51
Also we might want to take this discussion to the existing VS Code issue: https://github.com/microsoft/vscode/issues/181573

**Comment by Veykril** [comment] 2023-08-12 05:08
Closing this since if this is still an issue its a client behavior, not something r-a is in control of

**Closed by Veykril** 2023-08-12 05:08 UTC
Labels: A-vscode, C-bug
