### ISSUE TITLE
file names in src/bin seems to have some weird case-sensetive behaviors

### ISSUE THREAD

**Issue by tionway** [rust-lang/rust-analyzer#18177] opened 2024-09-24 05:30 UTC
**rust-analyzer version**: 0.4.2122-standalone (3d0343251 2024-09-23)

**rustc version**: 1.81.0 (eeb90cda1 2024-09-04)

**editor or extension**: vscode, rust-analyzer v0.4.2122 (pre-release)

**relevant settings**: none

---

In src/bin, creating a file with any name and then changing the case of some letters will prevent ra from including it in the module tree. Each name can only be recognized by ra in the original case it was created in, even when creating new files in src/bin.

here for `iter1.rs` and `Iter1.rs` (`iter1.rs` works
![Image](https://github.com/user-attachments/assets/caf5aba6-e2d7-4833-ab7b-3b86167c547e)
![Image](https://github.com/user-attachments/assets/938815cc-1fc5-4568-b77b-f2ccba7e64cd)

here for `baSe1.rs` and `base1.rs` (`baSe1.rs` works
![Image](https://github.com/user-attachments/assets/468b06fb-b490-4a72-885f-0517cb25e494)
![Image](https://github.com/user-attachments/assets/b8693061-4767-4711-aa9e-23d57ff0dfff)

**Most important** thing is, this won't be reset by `cargo clean` or reloading editor. I "fixed" it by creating a new crate and copy files to this crate with correct name.

```

**Comment by lnicola** [comment] 2024-09-24 08:18
Duplicate of #9947, this is a VS Code bug, supposedly fixed.

**Closed by lnicola** 2024-09-24 08:18 UTC
Labels: C-bug
