### ISSUE TITLE
ternary izip! from itertools makes rust-analyzer take the second type from the third value

### ISSUE THREAD

**Issue by schuelermine** [rust-lang/rust-analyzer#14460] opened 2023-03-31 23:12 UTC
Example code:
```rs
use itertools::izip;

pub struct A<const N: usize> {
    chunks: [u64; N],
}

impl<const N: usize> A<N> {
    pub fn foo(self, rhs: Self) {
        let mut chunks = [0; N];
        let mut iter = izip!(self.chunks, rhs.chunks, &mut chunks);
        let (_a, _b, _c) = iter.next().unwrap();
    }
}
```

Example screenshot:
![image](https://user-images.githubusercontent.com/48802534/229248353-75ceb006-6de7-4160-b316-e5605df29787.png)

**rust-analyzer version**: rust-analyzer version: 2023-03-27

**rustc version**: rustc 1.70.0-nightly (ec2f40c6b 2023-03-30)

**relevant settings**: None

**Comment by Veykril** [comment] 2023-04-01 05:17
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/11681

**Closed by Veykril** 2023-04-01 05:17 UTC
Labels: C-bug
