### ISSUE TITLE
Cyclic dependency detected when running analysis-stats on future-rs

### ISSUE THREAD

**Issue by edwin0cheng** [rust-lang/rust-analyzer#2414] opened 2019-11-26 15:50 UTC
When running `analysis-stats` (4d753fa) on `futures-rs`:

```
C:\sandbox\rust-root\rust-analyzer (master -> origin)
λ cargo run --release -p ra_cli -- analysis-stats -q ..\futures-rs
    Finished release [optimized] target(s) in 1.33s
     Running `target\release\ra_cli.exe analysis-stats -q ..\futures-rs`
ERROR [ra_project_model] cyclic dependency futures -> futures-channel
ERROR [ra_project_model] cyclic dependency futures -> futures-core
ERROR [ra_project_model] cyclic dependency futures -> futures-task
ERROR [ra_project_model] cyclic dependency futures -> futures-test
ERROR [ra_project_model] cyclic dependency futures-util -> futures
ERROR [ra_project_model] cyclic dependency futures-util -> futures-channel
ERROR [ra_project_model] cyclic dependency futures-util -> futures-core
ERROR [ra_project_model] cyclic dependency futures-util -> futures-task
ERROR [ra_project_model] cyclic dependency futures-util -> futures-test
ERROR [ra_project_model] cyclic dependency futures-executor -> futures
ERROR [ra_project_model] cyclic dependency futures-executor -> futures-core
ERROR [ra_project_model] cyclic dependency futures-executor -> futures-task
Database loaded, 92 roots, 2.2761003s
Crates in this dir: 64
Total modules found: 304
Total declarations: 7893
Total functions: 1689
Item Collection: 7.6418828s, 0b allocated 0b resident
Total expressions: 40920
Expressions of unknown type: 5394 (13%)
Expressions of partially unknown type: 6398 (15%)
Type mismatches: 1824
Inference: 21.2589651s, 0b allocated 0b resident
Total: 28.9012308s, 0b allocated 0b resident
```

**Comment by edwin0cheng** [comment] 2019-12-03 03:34
I think the reason of cycle dependencys is similar to https://github.com/rust-lang/cargo/issues/4242

And #1282

**Comment by matklad** [comment] 2019-12-03 15:16
Yeah, the problem is that a crate can have a dev-dep onto itself:

```rust
[package]
name = "foo"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
foo = { path = "." }
```

The solution here is to start "duplicating" crates when lowering `cargo-metada` output to `CrateGraph`. In the above example, we should construct two `foo` crates, one with `cfg(test)` and one without, and make the required depednency edge.

**Comment by djc** [comment] 2021-01-20 10:18
I'm seeing something similar to this in Cargo, where cargo has a dev-dep on cargo-test-support while cargo-test-support depends on cargo.

```
[Error - 11:10:15 AM] Registering progress handler for token rustAnalyzer/fetching failed.
Error: Progress handler for token rustAnalyzer/fetching already registered
	at Object.onProgress (/Users/djc/.vscode/extensions/matklad.rust-analyzer-0.3.446-nightly/out/src/main.js:5366:23)
	at LanguageClient.onProgress (/Users/djc/.vscode/extensions/matklad.rust-analyzer-0.3.446-nightly/out/src/main.js:13386:45)
	at new ProgressPart (/Users/djc/.vscode/extensions/matklad.rust-analyzer-0.3.446-nightly/out/src/main.js:11405:41)
	at createHandler (/Users/djc/.vscode/extensions/matklad.rust-analyzer-0.3.446-nightly/out/src/main.js:14710:34)
	at handleRequest (/Users/djc/.vscode/extensions/matklad.rust-analyzer-0.3.446-nightly/out/src/main.js:4896:41)
	at processMessageQueue (/Users/djc/.vscode/extensions/matklad.rust-analyzer-0.3.446-nightly/out/src/main.js:4777:17)
	at Immediate._onImmediate (/Users/djc/.vscode/extensions/matklad.rust-analyzer-0.3.446-nightly/out/src/main.js:4767:13)
	at processImmediate (internal/timers.js:439:21)
[ERROR project_model::workspace] cyclic deps: cargo_test_support(CrateId(59)) -> cargo(CrateId(49))
[Error - 11:11:48 AM] Registering progress handler for token rustAnalyzer/fetching failed.
Error: Progress handler for token rustAnalyzer/fetching already registered
	at Object.onProgress (/Users/djc/.vscode/extensions/matklad.rust-analyzer-0.3.446-nightly/out/src/main.js:5366:23)
	at LanguageClient.onProgress (/Users/djc/.vscode/extensions/matklad.rust-analyzer-0.3.446-nightly/out/src/main.js:13386:45)
	at new ProgressPart (/Users/djc/.vscode/extensions/matklad.rust-analyzer-0.3.446-nightly/out/src/main.js:11405:41)
	at createHandler (/Users/djc/.vscode/extensions/matklad.rust-analyzer-0.3.446-nightly/out/src/main.js:14710:34)
	at handleRequest (/Users/djc/.vscode/extensions/matklad.rust-analyzer-0.3.446-nightly/out/src/main.js:4896:41)
	at processMessageQueue (/Users/djc/.vscode/extensions/matklad.rust-analyzer-0.3.446-nightly/out/src/main.js:4777:17)
	at Immediate._onImmediate (/Users/djc/.vscode/extensions/matklad.rust-analyzer-0.3.446-nightly/out/src/main.js:4767:13)
	at processImmediate (internal/timers.js:439:21)
```

**Comment by KalitaAlexey** [comment] 2021-03-18 14:35
We see this issue because our packages have [dev-dependencies] on each other. Does it break anything?

**Comment by Veykril** [comment] 2023-02-16 08:59
Closing in favor of https://github.com/rust-lang/rust-analyzer/issues/14167

**Closed by Veykril** 2023-02-16 08:59 UTC
Labels: S-actionable
