### ISSUE TITLE
"Go to definition" not working for some types

### ISSUE THREAD

**Issue by zhiqiangxu** [rust-lang/rust-analyzer#14744] opened 2023-05-05 12:26 UTC
The "Go to definition" function doesn't work for the `cmp` [here](https://github.com/zcash/halo2/blob/main/halo2_proofs/src/plonk/circuit.rs#L50), saying "No definition found for 'cmp'".

**rust-analyzer version**: 0.3.1498-standalone (3a27518fe 2023-04-30)
**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)

**Comment by lowr** [comment] 2023-05-05 13:38
This is a duplicate of #5514; we are having trouble identifying the type of `self.column_type.into()` when `self.column_type` is bound by `Into<Any>`. Closing as a duplicate, thanks for the report though!

**Closed by lowr** 2023-05-05 13:38 UTC
Labels: A-ty, C-bug
