### ISSUE TITLE
Version 0.3.2045 - latest version on VSCode seems to ignore the linkedProjects setting

### ISSUE THREAD

**Issue by justinasfour04** [rust-lang/rust-analyzer#17673] opened 2024-07-22 18:57 UTC
**rust-analyzer version**: 0.3.2045

**rustc version**: rustc 1.79.0 (129f3b996 2024-06-10)  

**editor or extension**: VsCode

**relevant settings**: rust-analyzer.linkedProjects

On the latest version available to vscode the following happens. I have linkedProjects defined and it works fine in **version 0.3.2037**. Seems like there is a bug in **v0.3.2045**
![image](https://github.com/user-attachments/assets/28cfd345-f591-4ec5-a5aa-cfdf4f5734d6)

**Comment by lnicola** [comment] 2024-07-22 19:05
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/17664.

**Closed by lnicola** 2024-07-22 19:05 UTC
Labels: C-bug
