### ISSUE TITLE
treats nalgebra::DVector::zeros(any number) as "expexted 0 arguments, found 1"

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [rust-lang/rust-analyzer#13033] opened 2022-08-15 20:31 UTC
stable version of extension

**Comment by lnicola** [comment] 2022-08-15 20:55
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/5441. You can disable the warning using `rust-analyzer.diagnostics.disabled.

**Closed by lnicola** 2022-08-15 20:55 UTC

**Comment by H-A-M-G-E-R** [comment] 2022-08-15 21:14
a false positive

**Comment by H-A-M-G-E-R** [comment] 2022-08-16 01:04
i found the cause in #5441
