### ISSUE TITLE
rust-analyzer cannot go to definition of a type that inside of body of macro

### ISSUE THREAD

**Issue by Mingun** [rust-lang/rust-analyzer#13554] opened 2022-11-05 16:26 UTC
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
0.4.1273-standalone (66900a7e0 2022-11-04)

**rustc version**: (output of `rustc -V`)
rustc 1.65.0 (897e37553 2022-11-02)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
Set `"rust-analyzer.cargo.features": "all"` in VSCode config. Otherwise nothing unusual, never change the defaults.

When I try to go to definition of the `ParseState::ClosedTag` in that line
https://github.com/tafia/quick-xml/blob/a54f6c2211e4fd6541c7191992e451ed47831b74/src/reader/mod.rs#L214

nothing happens. RLS allowed me to go to definition here. I can't remember for sure, but it seems RLS also allowed me to go to fields/methods, such as `read_bang_element()`, etc. here.

**Comment by flodiebold** [comment] 2022-11-05 18:37
Duplicate of #7890. In general the tokens inside the macro definition don't have any particular meaning, though it might be nice to have a heuristic anyway.

**Closed by flodiebold** 2022-11-05 18:37 UTC
Labels: A-macro, C-bug, A-ide

**Comment by Mingun** [comment] 2022-11-05 19:35
That situation is slightly different from #7890, because part of code that I referenced is not dependent on macro at all. In addition, rust-analyzer is already somehow analyzing macros. If you intentionally make an error in it, or pass incorrect parameters at the call point, then error markers will appear inside the macro body. That says, that rust-analyzer can have information about context in which macro is called and therefore have information about tokens inside a macro.
