### ISSUE TITLE
"Debug" button fails with "No such file or directory ...Cargo.toml"

### ISSUE THREAD

**Issue by stefnotch** [rust-lang/rust-analyzer#16052] opened 2023-12-08 12:15 UTC
### Error, with steps to reproduce
I created a new Rust project `cargo new t`. The path is `C:\Coding\GitHub\School\t`
Then I opened it in VSCode and pressed the "Debug" button

![image](https://github.com/rust-lang/rust-analyzer/assets/10220080/cdf2870c-66a5-4e8a-9e28-540e672217fc)

It started by showing me a weird error message, with a "Open 'launch.json'" button.
![image](https://github.com/rust-lang/rust-analyzer/assets/10220080/22017d0c-45a8-41aa-8e1a-a4872e195891)

So I pressed that button, it said "Cargo.toml has been detected in this workspace.
Would you like to generate launch configurations for its targets?". 

It generated a sensible looking config
![image](https://github.com/rust-lang/rust-analyzer/assets/10220080/027c74aa-2eb9-42bb-9e04-a9f9f3c93d88)

And then I pressed the Debug button again. And the error message still popped up.
```
No such file or directory: C:\Coding\GitHub\School\t\Cargo.toml
```
![image](https://github.com/rust-lang/rust-analyzer/assets/10220080/0f357b6d-24e4-49a5-a3fa-45a4e5d82615)

### Workaround

Pressing F5 to start the debugger works.

### Extra Info
**rust-analyzer version**: rust-analyzer version: 0.3.1756-standalone (e402c494b 2023-12-01)

**rustc version**: rustc 1.76.0-nightly (0e2dac837 2023-12-04)
(Should also be reproducible with a stable compiler)

**relevant settings**:
- Windows 11 or Windows 10
- VSCode version 1.85
- CodeLLDB is installed (v1.10.0, should be the latest one)

**reproduction info**: A colleague of mine was able to reproduce the same error on his Windows machine.

**Comment by lnicola** [comment] 2023-12-08 12:30
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/16010.

**Closed by lnicola** 2023-12-08 12:30 UTC
Labels: C-bug
