### ISSUE TITLE
rust-analyzer service panics

### ISSUE THREAD

**Issue by l3utterfly** [rust-lang/rust-analyzer#13170] opened 2022-09-02 08:53 UTC
**rust-analyzer version**: 0.3.1186-standalone (e8e598f64 2022-08-28)

**rustc version**: rustc 1.65.0-nightly (e1b28cd2f 2022-08-19)

**relevant settings**: VSCode install

Rust analyser stops working randomly in my project with the following panic message:

````
thread 'Worker' panicked at 'assertion failed: start <= end', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\text-size-1.1.0\src\range.rs:48:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:142
   2: core::panicking::panic
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:48
   3: rust_analyzer::from_proto::text_range
   4: rust_analyzer::from_proto::file_range
   5: rust_analyzer::handlers::handle_inlay_hints_resolve
   6: std::panicking::try
   7: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
````

Unfortunately it happens in a big project of mine which I cannot share the source code.

**Comment by lnicola** [comment] 2022-10-10 15:04
Do you know if this happens in specific situations like switching `git` branches?

**Comment by Veykril** [comment] 2022-10-10 15:12
Oh this was already reported here, I didn't see that. I wrote down the *likely* cause here https://github.com/rust-lang/rust-analyzer/issues/13372

**Comment by Veykril** [comment] 2022-11-07 15:52
Closing as a duplicate of #13372

**Comment by Veykril** [comment] 2022-11-07 16:24
Actually this is not a dupe, the explanation I gave in #13372 is relevant for this one, I misinterpreted #13372 😅

**Comment by Veykril** [comment] 2023-02-09 11:48
No longer relevant as we got rid of the resolve calls

**Closed by Veykril** 2023-02-09 11:48 UTC
Labels: Broken Window, A-inlay-hints, I-panic
