### ISSUE TITLE
Rename doesn't alter links in rustdoc

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust-analyzer#15475] opened 2023-08-17 20:10 UTC
**rust-analyzer version**: rust-analyzer 1 (baee6b338b 2023-08-06)

**rustc version**: rustc 1.73.0-nightly (1b198b3a1 2023-08-13)

**relevant settings**: N/A

When renaming a symbol, links in rustdoc are totally unaffected. For example, take this example:

```rust
/// See also: [mutable version](IterMut)
pub struct Iter { /* ... */ }

/// Mutable version of [`Iter`].
pub struct IterMut { /* ... */ }
```

If renaming `Iter` to `MyIter`, I would expect the following result:

```rust
/// See also: [mutable version](IterMut)
pub struct MyIter { /* ... */ }

/// Mutable version of [`MyIter`].
pub struct IterMut { /* ... */ }
```

Similarly, anchors for links should also work. For example, if renaming `IterMut` to `MyIterMut`:

```rust
/// See also: [mutable version](MyIterMut)
pub struct MyIter { /* ... */ }

/// Mutable version of [`MyIter`].
pub struct MyIterMut { /* ... */ }
```

I noticed a few mentions of rust-analyzer not taking into account doc comments, but I didn't see this particular bug reported, so, I decided to file a new issue. Perhaps there could be a specific setting to only change the destination of links, not the actual names in the case of shorthands (e.g. [\`Iter\`] might become [\`Iter\`][MyIter] instead of [\`MyIter\`]) although I would in general not expect `rust-analyzer` to leave behind invalid links when renaming items.

**Comment by lnicola** [comment] 2023-08-18 03:48
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/12583.

**Closed by lnicola** 2023-08-18 03:48 UTC
Labels: C-bug
