### ISSUE TITLE
can't resolve local deps

### ISSUE THREAD

**Issue by HomyeeKing** [rust-lang/rust-analyzer#15485] opened 2023-08-20 15:32 UTC
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

0.4.1629-standalone (83b3ba1b8 2023-08-19)

**rustc version**: (eg. output of `rustc -V`)  

rustc 1.71.1 (eb26296b5 2023-08-03)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

here's  reproduce [repo](https://github.com/HomyeeKing/gito/blob/repro/packages/cli/Cargo.toml#L22)

![image](https://github.com/rust-lang/rust-analyzer/assets/49113249/ba443e2e-f4fc-4419-89dd-7107c39a9949)

![image](https://github.com/rust-lang/rust-analyzer/assets/49113249/68799377-909a-45c2-bd6c-137946b4335a)

**Comment by lnicola** [comment] 2023-08-20 16:37
Does it work if you open `..` instead of `.`?

**Comment by HomyeeKing** [comment] 2023-08-21 02:22
nope, wrong path will cause RA failed.
I haven't touch this project for months, don't remember have this issue before

**Comment by lnicola** [comment] 2023-08-23 13:51
Your project seems to build fine for me. In addition, the errors in your second screenshot aren't reported by rust-analyzer, so they're out of scope for us.

Maybe try a fresh clone?

**Comment by lnicola** [comment] 2023-08-23 14:06
Looks like this is caused by `crate-type = ["cdylib"]`.

**Comment by Veykril** [comment] 2023-08-29 06:00
isn't this a rustc issue given the diagnostics screenshot?

**Comment by lnicola** [comment] 2023-08-29 06:06
It is. And it happens because you can't link to cdylib crates like this.

**Closed** 2023-08-29 06:09 UTC
Labels: C-support
