### ISSUE TITLE
`incorrect-ident-case` should honor `#[allow(non_snake_case)]` and others

### ISSUE THREAD

**Issue by tgeoghegan** [rust-lang/rust-analyzer#14080] opened 2023-02-02 16:25 UTC
**rust-analyzer version**: 2023-01-16

**rustc version**: rustc 1.67.0 (fc594f156 2023-01-24)

**relevant settings**: n/a

I have a fragment of code that uses a non-standard variable identifier:

```
    #[allow(non_snake_case)]
    let A = -two * a + auth;
```

We did this on purpose to match the variables names in the paper this code implements. We can opt out of `rustc/clippy`'s warning about identifier case with an `#[allow]`, but this line still trips `rust-analyzer`'s independent `incorrect-ident-case` warning:

```
  621:9   hint    Variable `A` should have snake_case name, e.g. `a` ​rust-analyzer
```

While `incorrect-ident-case` covers more cases than just `non_snake_case`, I think the programmer's intent here is clear and should be honored by suppressing the warning.

**Comment by tgeoghegan** [comment] 2023-02-02 16:26
#9803 would also fix this for me, but I filed a new issue since this suggests a different strategy for solving a more specific problem.

**Comment by lowr** [comment] 2023-02-03 07:51
Closing in favor of #6541. The problem is that we currently don't handle attributes on statements/expressions. I know it's not really the same thing, but you can apply the attribute on the containing item as a workaround.

**Closed by lowr** 2023-02-03 07:51 UTC

**Comment by tgeoghegan** [comment] 2023-02-03 15:58
Thanks for the swift response and workaround! I'll follow #6541.
