### ISSUE TITLE
Regression: "proc macro not found"

### ISSUE THREAD

**Issue by maxnoel** [rust-lang/rust-analyzer#12598] opened 2022-06-20 17:42 UTC
Hi,

As of the most recent version of rust-analyzer, I'm running into problems where proc macro use is always highlighted as an error with an error message of this form:

```
proc macro `main` not expanded: proc macro not foundrust-analyzer[unresolved-proc-macro](https://rust-analyzer.github.io/manual.html#unresolved-proc-macro)
```

A "simple" Tokio hello-world program can trigger the bug:

![image](https://user-images.githubusercontent.com/1538011/174654434-5f364381-afec-4c33-8598-dfb7ad1d7fb1.png)

(this is the full source code of the example program, whose sole dependency is `tokio = { version = "1.19.2", features = ["full"] }`. `cargo run` compiles and executes it as expected)

**rust-analyzer version**: rust-analyzer version: 0.0.0 (427061da1 2022-06-19)

**rustc version**: rustc 1.61.0 (fe5b13d68 2022-05-18)

I'm running `stable-x86_64-pc-windows-msvc (default)` on Windows 10, with Visual Studio Code as my IDE and the normal rust-analyzer extension. Nothing exotic. Let me know if there's any info I can give you to help.

**Comment by bjorn3** [comment] 2022-06-20 17:44
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/12450 I think.

**Comment by flodiebold** [comment] 2022-06-20 19:48
Indeed.

**Closed by flodiebold** 2022-06-20 19:48 UTC
