### ISSUE TITLE
Configured tasks not showing up in `v0.3.1896`

### ISSUE THREAD

**Issue by Barugon** [rust-lang/rust-analyzer#16950] opened 2024-03-25 22:19 UTC
Configured tasks in vscode are not showing up using rust-analyzer `v0.3.1896`. They work fine in the previous version, `v0.3.1885`

**rust-analyzer version**: 0.3.1896-standalone

**rustc version**: 1.77.0

**Comment by brogdonm** [comment] 2024-03-27 17:59
I am seeing the same thing. I am unable to run any cargo-based tasks from VS Code with version `v0.3.1896`. Reverting to `v0.3.1885` allows me to run cargo-based tasks from VS Code again.

**Comment by lnicola** [comment] 2024-03-28 07:28
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/16949.

**Closed by lnicola** 2024-03-28 07:28 UTC
Labels: C-bug
