### ISSUE TITLE
Hide a specific trait in autocomplete

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/rust-analyzer#18024] opened 2024-09-01 23:22 UTC
I love `color-eyre` but the `OwoColorize` trait adds a lot of noise to autocomplete.
![image](https://github.com/user-attachments/assets/5c079db3-9c3c-4ddc-af20-029f5c433cf2)

Could we get a way to hide some specific traits?
I'd personally also use it for `Any`

**Comment by lnicola** [comment] 2024-09-02 17:24
Duplicate of #17477 and possibly others, too.

**Closed by lnicola** 2024-09-02 17:25 UTC
Labels: A-completion, C-feature
