### ISSUE TITLE
Incorrect macro coercion behavior

### ISSUE THREAD

**Issue by JessterP** [rust-lang/rust-analyzer#14429] opened 2023-03-28 22:38 UTC
**rust-analyzer version**: rust-analyzer version: 0.3.1451-standalone (b99d5eb97 2023-03-26)

**rustc version**: rustc 1.68.0-nightly (ad8ae0504 2022-12-29)

**relevant settings**: 

Macro expansion handles coercion differently than rustc

originally discovered in Intellij-rust, same bug exists in Rust-Analyzer
https://github.com/intellij-rust/intellij-rust/issues/10300

```rust
macro_rules! __ide_check_2 {
    (1) => { 0u32 /* IDE */};
    ($number:literal) => { "RustC" }
}

macro_rules! __ide_check_1 {
    ($number:literal) => {
        __ide_check_2!($number)
    }
}

macro_rules! ide_check {
    () => {__ide_check_1!(1)}
}

pub fn main() {
    let a = ide_check!();
    println!("{}", a);
}
```

**Comment by lowr** [comment] 2023-03-29 10:20
Thanks for the report, this is a known issue that we don't know how to handle properly yet. Closing as a duplicate of #12603.

**Closed by lowr** 2023-03-29 10:20 UTC
Labels: A-macro, C-bug
