### ISSUE TITLE
Rust analyzer fails to recognize impl<T:Any + Debug> with error "expected &dyn AnyDebug, found &T"

### ISSUE THREAD

**Issue by codecnotsupported** [rust-lang/rust-analyzer#17334] opened 2024-06-02 17:10 UTC
**rust-analyzer version**: 
rust-analyzer version: 0.4.1981-standalone
**rustc version**:
rustc 1.80.0-nightly (bdbbb6c6a 2024-05-26)
**editor or extension**:
VSCodium
**relevant settings**:
N/A
**repository link (if public, optional)**:
N/A
**code snippet to reproduce**: 
This compiles without warning. But Gives a error in rust-analyzer.
```rust
use std::any::Any;
use std::fmt::Debug;


pub trait AnyDebug: Any + Debug {}
impl<T:Any + Debug> AnyDebug for T {}

fn main(){
    
    let variable: &dyn AnyDebug = &1; // expected &dyn AnyDebug, found &i32 rust-analyzer[E0308]
    dbg!(variable);

}
```

**Comment by codecnotsupported** [comment] 2024-06-02 17:21
As a temporary workaround, the error goes away if you write redundantly:

```rust
variable: &dyn AnyDebug = &1 as &dyn AnyDebug;
```

**Comment by lnicola** [comment] 2024-06-02 17:25
Probably a duplicate of #11847.

**Closed by lnicola** 2024-06-02 17:25 UTC
Labels: C-bug
