### ISSUE TITLE
Running a quickfix (rename) does not rename all occurences

### ISSUE THREAD

**Issue by JDuchniewicz** [rust-lang/rust-analyzer#7936] opened 2021-03-09 13:16 UTC
Transferred from [coc-rust-analyzer](https://github.com/fannheyward/coc-rust-analyzer/issues/637)
When renaming variables using quickfix, not all of them are renamed.
Example before is:
```rust
const aspect_ratio: f64 = 16.0 / 9.0;
const viewport_height: f64 = 2.0;
const viewport_width: f64 = aspect_ratio * viewport_height;
```

After:
```rust
const ASPECT_RATIO: f64 = 16.0 / 9.0;
const viewport_height: f64 = 2.0;
const viewport_width: f64 = aspect_ratio * viewport_height;
```

when renamed (capitalized) the aspect_ratio, it did not rename the occurrence on the right hand side of the assignment but was able to do it for in-function parameters. It had somehow troubles with the `*` operator neighboring occurence.

**Comment by bjorn3** [comment] 2021-03-09 13:35
The uses of `aspect_ratio` and `viewport_height` are not capitalized, but the `const`s are. This means that they are distinct identifiers and as such not treated as one when renaming.

**Comment by JDuchniewicz** [comment] 2021-03-09 14:41
Hmm I used coc-rust-analyzer quickfix and it did rename just this one occurrence.

**Comment by flodiebold** [comment] 2021-03-09 16:25
I guess only the (not so great) suggestion from rustc is marked as a quickfix for the diagnostic coming from rustc. We should merge the two and hide the quickfix from rustc when we know we've got a better one.

**Comment by DropDemBits** [comment] 2024-07-01 05:04
Duplicate of #7742 since it's dealing with the same quickfix and mentions the same solution.

**Closed by DropDemBits** 2024-07-01 05:04 UTC
Labels: S-actionable, A-diagnostics
