### ISSUE TITLE
Rename doesn't work on asm! macro

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/rust-analyzer#17437] opened 2024-06-17 09:15 UTC
```rs
let x: *const *u8;
asm!("mov {:e}, RAX", out(reg) x);
```
Renaming x doesn't affect the code in the macro.

**Comment by Veykril** [comment] 2024-06-17 10:57
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/11621

**Closed by Veykril** 2024-06-17 10:57 UTC
Labels: C-bug
