### ISSUE TITLE
Proc macros do not expand on latest nightly

### ISSUE THREAD

**Issue by SkyfallWasTaken** [rust-lang/rust-analyzer#13373] opened 2022-10-09 10:23 UTC
**rust-analyzer version**: rust-analyzer version: 0.3.1229-standalone

**rustc version**: rustc 1.66.0-nightly (8796e7a9c 2022-10-08)

**relevant settings**: n/a I think?

RA no longer works with today's nightly when it comes to proc macros:

This can be reproduced with the following code:
```rust
#[tokio::main]
async fn main() {
    println!("Hello world");
}

fn f1() {}
```

The error is:

```
proc macro `main` not expanded: Cannot create expander for /home/skyfall/Projects/custard/target/debug/deps/libtokio_macros-a5c4f94b46da1247.so: UnsupportedABIrust-analyzer[unresolved-proc-macro](https://rust-analyzer.github.io/manual.html#unresolved-proc-macro)
```

The rest of RA works, so in the example it'd warn about `f1` not being used.

**Comment by fasterthanlime** [comment] 2022-10-09 11:02
Am also experiencing issues with completion in `tokio::main` right now (cf. #13355, maybe also #13322),

Although I am able to use the "Expand macro recursively" functionality to expand it:

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/7998310/194753153-c3bf7e40-59e6-42b1-9449-308890fb50b6.png">

And I do have this in my "Rust Analyzer Language Server" output:

```
[INFO rust_analyzer::reload] Loaded proc-macros for /home/amos/bearcove/promac/target/debug/deps/libtokio_macros-789c7494be924096.so: ["main", "main_rt", "test", "test_rt", "main_fail", "test_fail", "select_priv_declare_output_enum", "select_priv_clean_pattern"]
```

I wasn't seeing any completion in `tokio::main` for rustc 1.64.0 either, will investigate some more.

**Comment by fasterthanlime** [comment] 2022-10-09 11:08
Are you using bazel, or buck, or any other non-cargo build system? If so, your issue is a duplicate of #13322 and unrelated to #13355.

**Comment by SkyfallWasTaken** [comment] 2022-10-09 11:09
> Are you using bazel, or buck, or any other non-cargo build system? If so, your issue is a duplicate of #13322 and unrelated to #13355.

Nope, just cargo.

**Comment by fasterthanlime** [comment] 2022-10-09 11:42
> Nope, just cargo.

Is that in vscode? How is rust-analyzer installed? How is rustc/cargo installed?

**Comment by SkyfallWasTaken** [comment] 2022-10-09 12:17
> Is that in vscode?
Yep.

> How is rust-analyzer installed?
I'm _pretty_ sure I got it from the prompt after installing the VS Code RA extension. Not 100% sure, though.

> How is rustc/cargo installed?
With Linux rustup

**Comment by Veykril** [comment] 2023-02-09 13:32
Do you still experience this problem?

**Comment by fasterthanlime** [comment] 2023-02-09 19:13
> Do you still experience this problem?

I know you're probably asking @SkyfallWasTaken, but because I confirmed that issue back when it was opened, I can confirm I'm no longer able to reproduce it (even with an era-appropriate tokio version).

**Comment by Veykril** [comment] 2023-02-09 19:32
Ye I think we can close this then.

**Closed by Veykril** 2023-02-09 19:32 UTC
Labels: C-support

**Comment by SkyfallWasTaken** [comment] 2023-02-09 19:57
> Do you still experience this problem?

Nah, I haven't had the issue in a while
