### ISSUE TITLE
Extend Support

### ISSUE THREAD

**Issue by Padmanabh82** [rust-lang/rust-analyzer#12888] opened 2022-07-27 13:16 UTC
Please also support raspberry pis

**Comment by bjorn3** [comment] 2022-07-27 13:24
You can install rust-analyzer from rustup using `rustup component add --toolchain nightly rust-analyzer`. This version supports arm.

**Comment by jonas-schievink** [comment] 2022-07-28 19:15
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/9670

**Closed by jonas-schievink** 2022-07-28 19:15 UTC
Labels: C-support
