### ISSUE TITLE
Borrow/BorrowMut auto importing completions are confusing for newcomers

### ISSUE THREAD

**Issue by kotauskas** [rust-lang/rust-analyzer#8468] opened 2021-04-11 09:13 UTC
A realistic use case which *sometimes* reproduces the issue:
```rust
use std::{rc::Rc, cell::RefCell};

let my_thing = Rc::new(RefCell::new(None));
send_it_somewhere(Rc::clone(&my_thing));
*my_thing.borrow_mut() = Some("Sample data!");
```

Here, typing out the `.borrow_mut()` will import `std::borrow::BorrowMut`, which will try to use the implementation of `BorrowMut` on `Rc<RefCell<Option<&'static str>>>` because it'd take priority over deref coercion of `Rc` down to the `RefCell` with its own `.borrow_mut()`, thus mutably borrowing the variable storing the `Rc` rather than its content. Assigning to that fails with a type mismatch (expects you to put a new `Rc` there but finds an `Option<&'static str>` which should itself be wrapped in an `Rc`).

This does not reliably reproduce if you encounter the issue and remove the import (typing out the same code won't trigger the `BorrowMut` auto import again), but one thing I noticed is that this happens only when hovering over the `.borrow_mut()` you just typed out shows the documentation from the `BorrowMut` trait rather than the method. However, even when you remove the import it added and it doesn't add it again (the bug essentially disappears), *hovering over `.borrow_mut()` will still show the `BorrowMut` documentation, even though `BorrowMut` isn't in scope and the method call refers to `RefCell::borrow_mut()`.*

I'm using the VSCode extension (`matklad.rust-analyzer`, not the official one) if that matters at all.

**Comment by kornelski** [comment] 2021-12-17 14:07
I've ran into the exact same issue, and it's been bewildering.

I don't think it should simply be closed in favor of #10454, because the problem here is auto-import of traits, not method suggestion. Suggesting `borrow_mut()` on an "unknown" `RefCell` is perfectly fine — it will compile and work. But auto-import of `BorrowMut` unexpectedly breaks `RefCell`s, and that is problematic in its own way.

**Comment by flodiebold** [comment] 2021-12-17 14:21
Hmm @kornelski I think it would be helpful if you could provide a simple reproduction of the problem.

**Comment by kornelski** [comment] 2021-12-17 16:10
I've had a struct like:

```rust
struct Foo {
   cell: RefCell<i32>.
}
```

and I wrote:

```
self.cell.borrow_mu <tab>
```

rust-analyzer auto-completed `borrow_mut()`, but not did not understand it as `RefCell::borrow_mut()`, but as `BorrowMut::borrow_mut()` and inserted `use std::borrow::BorrowMut` automatically for me at the top of the file (which I didn't notice).

Instead of `RefMut<i32>` I've ended up with `&mut RefCell` and was totally confused why `RefCell` doesn't seem to do anything.

**Comment by mejrs** [comment] 2022-10-24 20:26
Can this issue be reopened? I'm very active teaching people rust, and this pain point comes up almost daily. It has not been solved.

**Comment by Veykril** [comment] 2022-10-24 20:41
Do you have a minimal reproduction? It looks fixed to me 
![image](https://user-images.githubusercontent.com/3757771/197625007-f797af90-60a0-4b5c-a83b-282911feace3.png)

**Comment by mejrs** [comment] 2022-10-24 20:56
> Do you have a minimal reproduction? It looks fixed to me ![image](https://user-images.githubusercontent.com/3757771/197625007-f797af90-60a0-4b5c-a83b-282911feace3.png)

That is the reproduction. People click on the second option, and then they get weird errors everywhere.

I think we just have a difference of opinion about what "fixed" means. What I see is that people (especially newcomers) still get confused by accidentally importing `BorrowMut`. You can see this for yourself: go to the rust community discord and search for "BorrowMut". You'll find about a hundred results, many of which are something like "Remove the `use std::borrow::BorrowMut;` you have at the top of your file.`

To me the correct fix seems to be to special-case `Rc<RefCell<..>>` to not suggest using `BorrowMut`.

**Comment by Veykril** [comment] 2022-10-24 21:08
That does not sound like a fix to me, special casing one specific case here that is. There are probably more occasions where this could occur, `BorrowMut` is just one of the more common ones. I'm open for suggestions on how to prevent people from making this mistake or making it less likely for them, but I am not too happy about special casing like this.

(On an unrelated note, I am also surprised as to why especially newcomers jump the gun with Rc and RefCell 😕)

**Comment by mejrs** [comment] 2022-10-24 21:29
`borrow_mut` seems to be uniquely confusing like this. I can't off the top of my head recall any other cases where someone got confused by trait vs inherent methods.

**Comment by Veykril** [comment] 2022-10-24 21:32
Well, why do people only get confused here? It's in no way special in regards to other inherent vs trait method collisions really.

One thing that came to mind right now though, since I assume part of the confusion for newcomers at least could come from them not understanding what the `(use path::to::Trait)` part means. We have plans to do a pop up on install of the extension, we could probably explain the few completion gimmicks there. Would that help?

**Comment by kornelski** [comment] 2022-10-24 22:31
People won't read a random popup. 

Installation time is wrong time to explain a problem users haven't run into yet, without relevant context. Even if you make users read it, there's very little chance they will recall this when they run into the problem.

You could show the warning when users select the BorrowMut trait for the first time, but it's not as good as never suggesting the trap in the first place.

**Comment by Veykril** [comment] 2022-10-26 16:35
Well from the looks of it people either don't read what completions say either or they don't know what the `(use path::to::Trait)` part in completions mean.  I am not saying we should describe the concrete issue in that page, I am saying we should describe what the different completions mean. I mean there has to be a reason why people pick the wrong one here right?

**Comment by mejrs** [comment] 2022-10-31 10:51
> We have plans to do a pop up on install of the extension, we could probably explain the few completion gimmicks there. Would that help?

I agree with @kornelski here; a popup listing some gotchas is a bad idea, especially when you can avoid having that gotcha in the first place.

> I mean there has to be a reason why people pick the wrong one here right?

The main reason, I think, is that in general people tend to not read things.

**Comment by tvallotton** [comment] 2022-12-03 14:46
Well, if you think about it, the `BorrowMut` auto-completion is always wrong, it instead should use universal function call syntax. So I think there are two reasonable options: remove the suggestion, or refactor the code to use UFCS. It would look something like this:
```rust
shared_cell.borrow_m<tab>
```
And it'd be transformed into
```rust
BorrowMut::borrow_mut(shared_cell)
```
Which would probably be annoying, but it would prevent those confusing ambiguity errors.

**Comment by Veykril** [comment] 2022-12-16 21:59
`BorrowMut::borrow_mut(shared_cell)` would imply that `BorrowMut` is in scope which is the cause of the problem here so that wouldn't work.

**Comment by Veykril** [comment] 2022-12-16 22:01
Let's move the discussions over to https://github.com/rust-lang/rust-analyzer/issues/13786, this issue wasn't about the confusion per se (the issue was about the inherent completion not appearing at all)

**Closed** 2022-12-16 22:00 UTC
Labels: A-assists
