### ISSUE TITLE
Consider adopting VS Code testing API instead of code lenses

### ISSUE THREAD

**Issue by connor4312** [rust-lang/rust-analyzer#13440] opened 2022-10-19 19:18 UTC
A while ago, we added the [testing API](https://code.visualstudio.com/api/extension-guides/testing) to VS Code. It would be be a nice and more consistent experience if `rust-analyzer` adopted this API instead of its custom code lenses; I constantly try to use the native keybindings when testing Rust code.

Here's an extension with screenshots to show what the native testing experience looks like: https://marketplace.visualstudio.com/items?itemName=ZixuanChen.vitest-explorer

**Comment by flodiebold** [comment] 2022-10-19 21:24
Duplicate of #3601

**Closed by flodiebold** 2022-10-19 21:24 UTC
Labels: A-vscode, C-feature
