### ISSUE TITLE
Failed to discover workspace after upgrading to version v0.3.2045

### ISSUE THREAD

**Issue by spektom** [rust-lang/rust-analyzer#17746] opened 2024-07-30 13:21 UTC
Workspace containing Rust projects doesn't load anymore after upgrading rust-analyzer to version v0.3.2045.

Version v0.3.2037 works just fine.

Workspace configuration has the following section defined:

````json
{
    "rust-analyzer.linkedProjects": [
        "project1/src/Cargo.toml",
        "path/to/project2/Cargo.toml",
        "path/to/project3/Cargo.toml",
    ]
}
````

The error is:

```
[ERROR rust_analyzer::config] failed to find any projects in [AbsPathBuf("/home/michael/Dev/App1")]
[ERROR rust_analyzer::main_loop] FetchWorkspaceError:
rust-analyzer failed to discover workspace
[ERROR rust_analyzer::main_loop] FetchWorkspaceError:
rust-analyzer failed to discover workspace
```

**Comment by lnicola** [comment] 2024-07-30 13:23
Can you try the workaround in https://github.com/rust-lang/rust-analyzer/issues/17664#issuecomment-2243570442?

**Comment by spektom** [comment] 2024-07-30 13:45
> Can you try the workaround in [#17664 (comment)](https://github.com/rust-lang/rust-analyzer/issues/17664#issuecomment-2243570442)?

The workaround works. Thank you!

**Comment by lnicola** [comment] 2024-07-30 13:46
Duplicate of #17664.

**Closed by lnicola** 2024-07-30 13:46 UTC
Labels: C-bug
