### ISSUE TITLE
Rust analyser mistakenly highlights the rest of file as a string after using a single quotation mark 

### ISSUE THREAD

**Issue by Leonard-Pat** [rust-lang/rust-analyzer#14016] opened 2023-01-24 10:43 UTC
**rust-analyzer version**: rust-analyzer version: 0.3.1377-standalone

**rustc version**: rustc 1.66.1 (90743e729 2023-01-10)

Bug:
For some reason rust-anaylzer identifies everything after the use of a single quotation mark as a string. As seen here:
![image](https://user-images.githubusercontent.com/106159231/214271133-0617acb5-b57d-444a-82e9-d9904dceed0b.png)
Even though it was successfully closed (see the assert line)

![image](https://user-images.githubusercontent.com/106159231/214271297-5ae498a0-9ce2-4e91-8a21-534f0f737341.png)
If i add a third one, it recognises it as closed  (see the assert line)

**Comment by Veykril** [comment] 2023-01-24 10:57
rust doesn't have single quotation mark strings, single quotes designated character literals, not strings

**Comment by jonas-schievink** [comment] 2023-01-27 16:18
Closing. Not a bug.

**Closed by jonas-schievink** 2023-01-27 16:18 UTC
