### ISSUE TITLE
unresolved-field error in interdependent workspace crates

### ISSUE THREAD

**Issue by martijnarts** [rust-lang/rust-analyzer#14296] opened 2023-03-09 11:20 UTC
I'm seeing an unresolved-field error on a field that definitely exists and compiles just fine. I think the problem is actually the weird dependencies I've introduced into my workspace modules though. I've reproduced it here: https://github.com/martijnarts/ra-unresolved-field-repro

I haven't tried to fully minimise the reproduction. It might be the case that this happens even without all the interdependencies and such, this is just the scenario that I see in my production code.

Here's what it looks like when breaking:

<img width="478" alt="how-it-breaks" src="https://user-images.githubusercontent.com/54749/224006155-15f73356-075b-4efe-ba89-a08f006d4b12.png">

**rust-analyzer version**: 0.3.1426-standalone (0a956ec93 2023-03-05)

**rustc version**: rustc 1.66.0 (69f9c33d7 2022-12-12)

**relevant settings**: happens in a basic, unconfigured rust/rust-analyzer setup.

**Comment by lnicola** [comment] 2023-03-09 14:15
Probably a dupe of #14167.

**Closed** 2023-03-09 14:21 UTC
Labels: A-ty, C-bug

**Comment by martijnarts** [comment] 2023-03-09 15:13
Ah yes it's definitely a dupe of that!
