### ISSUE TITLE
Recursive macro expansion mismatch between rustc and r-a

### ISSUE THREAD

**Issue by jprochazk** [rust-lang/rust-analyzer#14675] opened 2023-04-28 17:48 UTC
**rust-analyzer version**: 0.3.1489-standalone

**rustc version**: rustc 1.71.0-nightly (f5559e338 2023-04-24)

**relevant settings**: probably none

Given the following macro:
```rust
macro_rules! get {
    ($list:ident; ) => (
        None
    );
    ($list:ident; (Marker)) => (
        Some($list[0])
    );
    ($list:ident; (Marker) $(($tail:ty))*) => (
        Some($list[0])
    );
    ($list:ident; ($head:ty) $(($tail:ty))*) => (
        get!($list; $(($tail))*)
    );
}
```

The output of the following snippet will be `None`:
```rust
fn main() {
    let test = &["test"];
    let v: Option<&'static str> = get!(test; (Test) (Marker));
    println!("{v:?}");
}
```

But `rust-analyzer`'s expansion outputs `Some(test[0])`, which should print `Some("test")`.

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f7e4d5acbb2e43b5068d53cad4f8cd4c)

For more context, `cargo-expand` expands the above snippet to:

```rust
fn main() {
    let test = &["test"];
    let v: Option<&'static str> = None;
    {
        ::std::io::_print(format_args!("{0:?}\n", v));
    };
}
```

If the designator of `$tail` is changed from `ty` to `ident`:

```rust
macro_rules! get {
    ($list:ident; ) => (
        None
    );
    ($list:ident; (Marker)) => (
        Some($list[0])
    );
    ($list:ident; (Marker) $(($tail:ident))*) => (
        Some($list[0])
    );
    ($list:ident; ($head:ident) $(($tail:ident))*) => (
        get!($list; $(($tail))*)
    );
}
```

Then `rustc`, `cargo-expand`, and `rust-analyzer` all agree that the expansion of the macro is `Some(test[0])`, which will print `Some("test")`.

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=74685d07d0cd18e0842a41dd038f1051)

**Comment by lowr** [comment] 2023-04-29 16:40
Thanks for the report! This is a known issue we haven't figured out how to resolve. Closing as a duplicate of #12603.

**Closed by lowr** 2023-04-29 16:40 UTC
Labels: A-macro, C-bug
