### ISSUE TITLE
rust-analyzer handles git merge conflicts than rls (VSCodium extension) (stable release)

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [rust-lang/rust-analyzer#13137] opened 2022-08-28 23:48 UTC
rust-analyzer treats conflicts as actual code

**Comment by bjorn3** [comment] 2022-08-29 07:02
Unlike rustc (which rls internally uses), rust-analyzer has a parser which is designed to keep producing somewhat useful results even in the face of incomplete or entirely incorrect syntax. This includes merge conflict markers.

**Comment by flodiebold** [comment] 2022-08-29 07:58
Duplicate of #7127

**Closed by flodiebold** 2022-08-29 07:58 UTC
Labels: A-parser
