### ISSUE TITLE
lifetime param variance method in Hover Doc

### ISSUE THREAD

**Issue by A4-Tacks** [rust-lang/rust-analyzer#17183] opened 2024-05-04 05:58 UTC
Can an optional feature be added:
when viewing HoverDoc of struct, etc., display whether the variance method of their lifetime param is covariant invariant or contravariant

**Example**
---

```rust
struct Foo<'a>(fn(&'a ()));
struct Bar<'a>(fn() -> &'a ());
struct Baz<'a>(fn(&'a ()) -> &'a ());
```

Hover Doc Output

```rust
struct Foo<'a> // size = 8, align = 0x8

---
'a: contravariant
```
```rust
struct Bar<'a> // size = 8, align = 0x8

---
'a: covariant
```
```rust
struct Baz<'a> // size = 8, align = 0x8

---
'a: invariant
```

**Comment by Veykril** [comment] 2024-05-04 06:50
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/13073

**Closed by Veykril** 2024-05-04 06:50 UTC
Labels: C-feature
