### ISSUE TITLE
rust-analyzer fails to display comment generated during nested macro expansion

### ISSUE THREAD

**Issue by 0rphon** [rust-lang/rust-analyzer#13190] opened 2022-09-04 20:01 UTC
possibly related to #13075 

the following has a macro that generates documentation for `A` and for `B`. Rust-Anaylzer displays the documentation just fine for `B`, but shows no documentation for `A`.

```rust
macro_rules! tester {
    ($x:expr, $n:ident) => {
        tester! {@inner concat!("This is ", $x), $n}
    };
    (@inner $x:expr, $n:ident) => {
        #[doc = $x]
        const $n: u8 = 1u8;
    };
}

tester!("A", A);
tester!(@inner "This is B", B);

fn main() {
    A;
    B;
}
```

![image](https://user-images.githubusercontent.com/59403052/188331315-81248e69-1386-4c2c-b1ab-df1c32ce3695.png)
![image](https://user-images.githubusercontent.com/59403052/188331323-ca60a4e5-0104-4338-8b4d-a8123dcb9371.png)

just to confirm that the docs exist, here's the output of `cargo expand` (`cargo doc` also confirms a doc string exists for A)

```rust
#![feature(prelude_import)]
#[prelude_import]
use std::prelude::rust_2021::*;
#[macro_use]
extern crate std;
///This is A
const A: u8 = 1u8;
///This is B
const B: u8 = 1u8;
fn main() {
    A;
    B;
}
```

but using `rust-analyzer: Expand Macro Recursively` shows that the 'A' doc has parentheses around it, which would be considered a syntax error

```rust
// Recursive expansion of tester! macro
// =====================================

#[doc = ("This is A")]
const A: u8 = 1u8;
```

```rust
// Recursive expansion of tester! macro
// =====================================

#[doc = "This is B"]
const B: u8 = 1u8;
```

**rust-analyzer version**: both the release version `0.3.1186-standalone (e8e598f64 2022-08-28)` and pre-release version `0.4.1192-standalone (8ddb8b7e8 2022-09-03)`

**rustc version**: both `rustc 1.63.0 (4b91a6ea7 2022-08-08)` and `rustc 1.65.0-nightly (84f0c3f79 2022-09-03)`

**relevant settings**: None

**Comment by 0rphon** [comment] 2022-09-04 20:20
i messed around with this some more and i found a similar example where rust-analyzer manages to generate the correct syntax for the doc string but still fails to show documentation for it

code: 
```rust
macro_rules! tester {
    ($n:ident) => {
        #[doc = concat!("This is ", stringify!($n))]
        const $n: u8 = 1u8;
    };
}

tester!(A);

fn main() {
    A;
}
```

cargo expand:
```rust
#![feature(prelude_import)]
#[prelude_import]
use std::prelude::rust_2021::*;
#[macro_use]
extern crate std;
///This is A
const A: u8 = 1u8;
fn main() {
    A;
}
```

rust-analyzer expansion:
```rust
// Recursive expansion of tester! macro
// =====================================

#[doc = "This is A"]
const A: u8 = 1u8;
```

on hover:
![image](https://user-images.githubusercontent.com/59403052/188331924-1c48b11f-d3e0-4d39-af8c-05585590badf.png)

**Comment by jonas-schievink** [comment] 2022-09-05 10:49
We don't support macros in attribute values at the moment

**Comment by Veykril** [comment] 2022-09-07 11:39
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/8092

**Closed by Veykril** 2022-09-07 11:39 UTC
