### ISSUE TITLE
Feat req: Organise imports and adapt references when code is moved to another file / module

### ISSUE THREAD

**Issue by gitmalong** [rust-lang/rust-analyzer#12774] opened 2022-07-16 10:33 UTC
Hi!

I would like to move a function `fn` or code block to another file / module and let rust analyzer take care about:

* updating references to that function call
* adapting imports within the target file / module
* removing unused imports from source file / module

Rust analyzer currently supports to extract code blocks to a new module within the same file. Within that module one can find the necessary imports. RA also supports renaming functions and adapting references to it. So I guess most building blocks are already in place for such a feature.

Concrete cases when RA (vscode extension) should execute the refactor tasks:
* Select code block, right click -> refactor -> extract to file
* Copy code block / fn -> paste into new file

Reasoning: Refactoring code is a common task but very time consuming and error prone if one has to execute the tasks from above manually. This leads generally to less refactoring and worsens the overall code quality within projects. From personal experience it is also a feature that most people coming from Java world are missing.

Thanks

**Comment by flodiebold** [comment] 2022-07-16 11:09
Duplicate of #2178

**Closed** 2022-07-18 10:48 UTC
