### ISSUE TITLE
Destructured tuple types not inferred correctly

### ISSUE THREAD

**Issue by yngwi** [rust-lang/rust-analyzer#12819] opened 2022-07-19 20:27 UTC
When using a [query](https://docs.rs/bevy/latest/bevy/ecs/system/struct.Query.html) in a [Bevy](https://bevyengine.org/) system, destructured tuple values are not correctly infered but shown as `{unknown}`.

```rust
fn test_system(query: Query<(&Position, &Archetype)>) {
    for(pos, arch) in query.iter() {
        println!("{:?} {:?}", pos, arch);
    } 
}
```
Screenshot where `{unknown}` is shown:
![image](https://user-images.githubusercontent.com/963440/179841379-cbe0fb7c-0d95-46f0-bcb2-c90939648afe.png)

**rust-analyzer version**:rust-analyzer version: 0.3.1131-standalone (897a7ec4b 2022-07-17)

**rustc version**: rustc 1.64.0-nightly (46b8c23f3 2022-07-01)

**Comment by Veykril** [comment] 2022-07-19 20:57
From the looks of it the problem is the `Archetype`, using it causes us to not longer infer the appropriate methods for WorldQuery. I am a bit confused though, `Archetype` is clearly not a `WorldQuery` as it doesn't implement `Component`, so how does this even compile...?

**Comment by Veykril** [comment] 2022-07-19 21:04
Actually your snippet doesn't compile for me at all as `Archetype` is not a `Component`, so there is no bug here it seems.

**Comment by yngwi** [comment] 2022-07-19 21:42
Sorry I have included a more extensive code example. Position and archetype are both custom component strictly that I defined elsewhere. The code compiles and runs just fine on my system, it's just the type inference that is off. Inference also works if the query includes just a single component instead of a tuple.

**Comment by ostwilkens** [comment] 2022-07-21 10:58
I had this issue on w10 after updating vscode, rust-analyzer and rustc. 

![image](https://user-images.githubusercontent.com/5286600/180190551-8ae109ed-e23c-4bec-af68-b68d673f8b88.png)


Reverting to an older nightly toolchain fixed it for me. 

#### **`rust-toolchain.toml`**
``` 
[toolchain]
channel = "nightly-2022-04-25"
```

**Comment by Veykril** [comment] 2022-07-21 11:08
A reproducible snippet would be welcome, @yngwi is your problem also dependent on the toolchain, that is does the toolchain that was posted here fix the problem for you?

**Comment by yngwi** [comment] 2022-07-21 15:21
Hi, I have set the rust toolchain in my project folder as suggested and now see the correct types in VSCode. So this indeed seems to be the cause of the problem.

**Comment by Veykril** [comment] 2022-07-21 15:25
Alright, will investigate then, I assume some lang items/unstable traits changed in nightly that are relevant here

**Comment by flodiebold** [comment] 2022-07-21 15:27
It might just be proc macro expansion? @yngwi does it still work with the older toolchain if you set `rust-analyzer.procMacro.enable` to `false`?

**Comment by Veykril** [comment] 2022-07-21 15:27
Oh right, that is most likely it 🤦

**Comment by flodiebold** [comment] 2022-07-22 10:19
Yeah, that means this is just caused by proc macro support currently being broken on nightly. This should be fixed with the next stable release of rust-analyzer, or you could try the pre-release version.

**Closed by flodiebold** 2022-07-22 10:19 UTC
Labels: A-ty

**Comment by yngwi** [comment] 2022-07-22 15:06
Ok, thank you.
