### ISSUE TITLE
`unresolved-module` when using a `#[path]` attribute with a file outside of the current crate

### ISSUE THREAD

**Issue by negamartin** [rust-lang/rust-analyzer#14230] opened 2023-03-01 19:41 UTC
**rust-analyzer version**: `0.3.1418-standalone`

**rustc version**: `rustc 1.67.1 (d5a82bbd2 2023-02-07)`

**relevant settings**: All default as far as I know.

**platform**: `rust-analyzer` extension on VSCode, on Linux Mint 21 Cinnamon.

Hello,

I ran into an issue using the `#[path]` attribute to point to a file outside the crate.
This makes rust-analyzer run into an `unresolved-module` error, while `cargo build` and `cargo run` work fine.

Directory structure to reproduce the issue:

```
/bug/Cargo.toml
/bug/src/main.rs
/foo.rs
```

```toml
# /bug/Cargo.toml

[package]
name = "bug"
version = "0.1.0"
edition = "2021"
```

```rust
//! /bug/src/main.rs

#[path = "../../foo.rs"]
mod foo;

fn main() {
    foo::hello();
}
```

```rust
//! /foo.rs

pub fn hello() {
    println!("hello world!");
}
```

This directory structure confuses `rust-analyzer` but `cargo` itself builds and runs fine.

**Comment by lnicola** [comment] 2023-03-02 11:29
I think this is a dupe of https://github.com/rust-lang/rust-analyzer/issues/3898 and maybe other issues too.

**Closed by lnicola** 2023-03-02 11:29 UTC
Labels: C-bug

**Comment by negamartin** [comment] 2023-03-03 20:12
Sorry, for some reason I couldn't find that issue.
