### ISSUE TITLE
Support Question Mark Operator in Control Flow Highlighting

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust-analyzer#18147] opened 2024-09-19 11:21 UTC
rust-analyzer can nicely highlight which control flow relevant pieces of the code relate to each other, such as shown here:

![Image](https://github.com/user-attachments/assets/9dc6941d-8955-405f-8ed7-b03e3618cbe2)

This currently does not extend to the question mark operator:

![Image](https://github.com/user-attachments/assets/72cebce4-02fb-4e5d-add1-80e33269a337)

However, while writing this issue, I did notice that it actually works perfectly fine already if you are on the `fn` itself:

![Image](https://github.com/user-attachments/assets/4e656aa9-e1bc-4f57-a04d-41b89b29dfa8)

**Comment by ChayimFriedman2** [comment] 2024-09-19 11:34
That is really really weird... We have code for highlighting when on `->` or `?`, we have tests for them, the tests pass, yet this does not work!

**Comment by CryZe** [comment] 2024-09-19 11:39
That sounds plausible at least.

**Comment by Veykril** [comment] 2024-09-19 13:23
This is a known VSCode issue

**Comment by Veykril** [comment] 2024-09-19 13:24
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/9395

**Closed by Veykril** 2024-09-19 13:24 UTC
Labels: C-feature

**Comment by CryZe** [comment] 2024-09-19 14:00
A case that definitely does not work atm is the following:
![Image](https://github.com/user-attachments/assets/17a9fe10-23f5-4dd4-9fd6-2131fad2562a)

The cursor is on the `async` but only the `return` is marked, not the implicit return or the question mark operator.
