### ISSUE TITLE
rust-analyzer deletes line comments

### ISSUE THREAD

**Issue by elpablete** [rust-lang/rust-analyzer#14399] opened 2023-03-24 20:20 UTC
I'm finding that runing rust-analyzer on save (in VSCode) deletes comments in my files.

Example:

before save
```
def hello(name: str):
    #name = f"{name}!"
    print(f"hello {name}")
```

after save
```
def hello(name: str):
    print(f"hello {name}")
```

- rust-analyzer version: 0.3.1443-standalone (825833c26 2023-03-19)
- rustc 1.67.1 (d5a82bbd2 2023-02-07)

**Comment by bjorn3** [comment] 2023-03-24 21:04
Rust-analyzer doesn't operate on Python code. Are you sure this is caused by rust-analyzer?

**Comment by elpablete** [comment] 2023-03-24 22:02
my mistake, this is so embarrassing, I meant to report this bug to ruff. Sorry, please close (or even delete) this issue.

**Comment by bjorn3** [comment] 2023-03-24 22:15
No worries. I don't have permission to delete this issue, but I can close it for you.

**Closed by bjorn3** 2023-03-24 22:15 UTC
Labels: C-bug
