### ISSUE TITLE
'failed to find any projects' with a project that is not Rust related

### ISSUE THREAD

**Issue by adamrybak** [rust-lang/rust-analyzer#14237] opened 2023-03-03 00:10 UTC
I am running into an error from rust analyzer when I am working on a project not even related to rust.
The problem is annoying at most.

To replicate:
 - Clone the minimal repo.
 - Load directory into VS Code.
 - Press F5 to debug.

**rust-analyzer version**: rust-analyzer version: 0.4.1421-standalone (32424d0ab 2023-03-01)
**rustc version**: rustc 1.67.1 (d5a82bbd2 2023-02-07)
**relevant settings**: N/A
**Link to minimal repo**: https://github.com/adamrybak/ra-issue

Rust Analyzer Language Server Response:
> [ERROR rust_analyzer::config] failed to find any projects in [AbsPathBuf("c:\\ra-issue")]
> [ERROR rust_analyzer::lsp_utils] rust-analyzer failed to discover workspace
> [ERROR rust_analyzer::lsp_utils] rust-analyzer failed to discover workspace

**Comment by lnicola** [comment] 2023-03-03 05:48
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/14231.

**Closed by lnicola** 2023-03-03 05:48 UTC
Labels: C-bug
