### ISSUE TITLE
Rename Symbol doesn't work in function annotated with `#[tokio::main]`

### ISSUE THREAD

**Issue by gimmi** [rust-lang/rust-analyzer#13958] opened 2023-01-15 16:50 UTC
https://github.com/rust-analyzer/rust-analyzer.github.io/issues/195

**Comment by gimmi** [comment] 2023-01-15 16:54
@lnicola is right, rename work when removing the `#[tokio::main]` attribute:

![RenameBug](https://user-images.githubusercontent.com/6589/212554613-1e5c8fa3-d015-46e7-8ed8-06d3f088a1f6.gif)

**Comment by lowr** [comment] 2023-01-16 12:42
Duplicate of #12362 (cc #13614).

**Closed by lowr** 2023-01-16 12:42 UTC
Labels: C-bug, A-ide
