### ISSUE TITLE
calling `.into()` on a `Into<Box<...>>` resolving to `{unknown}`

### ISSUE THREAD

**Issue by vivax3794** [rust-lang/rust-analyzer#15675] opened 2023-09-27 17:11 UTC
**rust-analyzer version**: 0.3.1673-standalone
**rustc version**: rustc 1.72.1 (d5c2e9c34 2023-09-13)

The follow code: 
```rs
fn bar(_: &str) {}

fn foo<T: Into<Box<str>>>(x: T) {
    let y = x.into();
    bar(&y);
}
``` 
compiles fine, and of course the type of `y` is `Box<str>`, but the inlay hints (and hover) are saying something else:
![image](https://github.com/rust-lang/rust-analyzer/assets/51753506/8353b9e2-9198-4ed7-8c21-0f530be1df42)

this isnt just happening with `Box<str>` but seems to happen to any `Into<Box<_>>`, and it look to just pick up whatever it guesses based on the usage (like above it saw `&y` when a `&str` is expected to guessed `y` must be a `str`), so you can get some pretty strange stuff:

![image](https://github.com/rust-lang/rust-analyzer/assets/51753506/fbd63ccc-8f92-435f-b552-9c595e62650b)
(of course in this case it wont compile, but it shows that rust analyzer is just picking up what ever you use it as)

**Comment by lnicola** [comment] 2023-09-27 17:14
Duplicate of #5514.

**Closed by lnicola** 2023-09-27 17:14 UTC
Labels: C-bug
