### ISSUE TITLE
rust-analyzer hangs when having `&dyn Fn...` as one of the parameter to another `Fn`

### ISSUE THREAD

**Issue by chomosuke** [rust-lang/rust-analyzer#13293] opened 2022-09-25 10:39 UTC
**rust-analyzer version**: rust-analyzer 0.3.1194-standalone (67920f797 2022-09-04)

**rustc version**: rustc 1.64.0 (a55dd71d5 2022-09-19)

**relevant settings**: None, all default

When analyzing the following code, rust analyzer hangs at around 45% of CPU with no stderr output:
```rust
fn main() {}

mod memoize {
    use core::hash::Hash;
    use std::collections::HashMap;

    pub struct Memoize<P, R, F> {
        mem: HashMap<P, R>,
        f: F,
    }
    impl<Par: Hash, Ret, F: Fn(Par, &dyn Fn(Par) -> Ret) -> Ret> Memoize<Par, Ret, F> {
        pub fn new(f: F) -> Self {
            Self {
                mem: HashMap::new(),
                f,
            }
        }
    }

    #[cfg(test)]
    mod test {
        use super::*;

        #[test]
        fn coins() {
            let solve = Memoize::new(|target: usize, rec| {
            });
        }
    }
}
```
If the file is changed and saved after that, the diagnostics does not update to reflect the new code.

If I run cargo check, everything seems correct:
![image](https://user-images.githubusercontent.com/38484873/192139332-c4a95d64-c9c4-452d-be80-8a043a54d058.png)

**Comment by lowr** [comment] 2023-02-13 11:47
Duplicate of #11063.

**Closed by lowr** 2023-02-13 11:47 UTC
Labels: A-ty, C-bug, I-hang
