### ISSUE TITLE
Try_blocks feature does not work properly

### ISSUE THREAD

**Issue by swwind** [rust-lang/rust-analyzer#12479] opened 2022-06-06 07:13 UTC
![image](https://user-images.githubusercontent.com/26316494/172112906-997f6ba1-658a-4bea-afc7-31c9d392e780.png)

The code should be valid due to <https://doc.rust-lang.org/unstable-book/language-features/try-blocks.html>

Adding a `Ok()` wrapper does not compile neither.

**Comment by mvolfik** [comment] 2022-06-06 16:38
Just ran into this as well: the code (in the version showed) **does compile** and `cargo check`, it's just rust analyzer that flags it incorrectly

**Comment by mvolfik** [comment] 2022-06-06 16:39
Duplicate of #11843

**Closed** 2022-06-06 16:43 UTC
