### ISSUE TITLE
vscode: Reindent lines does not ignore braces in comments

### ISSUE THREAD

**Issue by wlinna** [rust-lang/rust-analyzer#12814] opened 2022-07-19 05:26 UTC
When using vscode's `reindent lines` command in Rust, reindentation is done incorrectly when there are braces `{` in comments. For example this:
```
// if (current_vertex_i == 9869) {
// if (current_vertex_i == 9904) {
// if (current_vertex_i == 1873) {
// if (current_vertex_i == 9842) {
// if (current_vertex_i == 2607) {
// if (current_vertex_i == 2173) {
if (current_vertex_i == 1234) {
    
}
```
after `reindent lines` turns into this:
```
// if (current_vertex_i == 9869) {
    // if (current_vertex_i == 9904) {
        // if (current_vertex_i == 1873) {
            // if (current_vertex_i == 9842) {
                // if (current_vertex_i == 2607) {
                    // if (current_vertex_i == 2173) {
                        if (current_vertex_i == 1234) {
                            
                        }
```
The same doesn't happen if I change language to JavaScript, so it seems like the problem originates from Rust Analyzer. EDIT: `Format document` works fine as well.

**rust-analyzer version**: rust-analyzer version: 0.3.1131-standalone (897a7ec4b 2022-07-17)

**rustc version**: rustc 1.61.0 (fe5b13d68 2022-05-18)

**relevant settings**: None

**Comment by lnicola** [comment] 2022-07-19 05:34
That's not a LSP command, Code just sends us a `textDocument/didChange` with whatever it likes.

**Comment by wlinna** [comment] 2022-07-19 05:50
Okay, thanks for the quick reply. Does this mean that the problem should be reported to `vscode` repo directly?

**Comment by lnicola** [comment] 2022-07-19 05:55
It's kind of been reported, but formatting requires language-specific knowledge that Code does not have. It works for JavaScript because of the obvious reasons, but I think it's just a bunch of regexes in the end.

**Comment by jonas-schievink** [comment] 2022-07-28 23:30
Closing this issue, as this is not a bug on our end

**Closed by jonas-schievink** 2022-07-28 23:30 UTC
Labels: S-unactionable, C-support
