### ISSUE TITLE
Do not show runtime errors in the editor

### ISSUE THREAD

**Issue by dnut** [rust-lang/rust-analyzer#15183] opened 2023-06-30 17:39 UTC
If I run the code with the code lens in vscode, and everything compiles perfectly fine, but my compiled program has an error after it starts running, the line of code that panicked is highlighted in the editor as an error. It constantly says I have an error on this line of code. The file becomes red in the explorer. This never goes away no matter how many changes I make to the code. It continues to highlight that line number, regardless of what is there.

I hate this feature. It is extremely distracting. Error highlighting needs to be reserved exclusively for problems that would cause compilation errors. Is there a way to turn this off?

**Comment by HKalbasi** [comment] 2023-06-30 17:57
Duplicate of #14977

**Closed by HKalbasi** 2023-06-30 17:57 UTC
Labels: C-support
