### ISSUE TITLE
rust-analyzer confuses Option::take and Iterator::take when checking arguments

### ISSUE THREAD

**Issue by Wilfred** [rust-lang/rust-analyzer#16516] opened 2024-02-09 00:18 UTC
Given the code:

```
fn my_example(
    _x: impl IntoIterator<Item = impl AsRef<str>>,
    _y: impl IntoIterator<Item = impl AsRef<str>>,
) {
    let mut cmd = std::process::Command::new("foo");

    let mut child = cmd.spawn().unwrap();
    child.stdin.take();
}

fn main() {}
```

rust-analyzer complains about the `.take()` call, saying it needs an argument:

<img width="393" alt="Screenshot 2024-02-08 at 16 16 02" src="https://github.com/rust-lang/rust-analyzer/assets/70800/9a257fa0-0f66-4f46-bc5b-7cd613db6b0a">

However, this is incorrect. The program compiles fine, because it's actually calling `Option::take` which takes no arguments.

**rust-analyzer version**: rust-analyzer 1.75.0 (82e1608d 2023-12-21), but also reproduces on 2024-01-22.

**rustc version**: rustc 1.75.0 (82e1608df 2023-12-21)

**Comment by davidbarsky** [comment] 2024-02-09 00:38
I'll mark this as a duplicate of https://github.com/rust-lang/rust-analyzer/issues/15027, but this _is_ the smallest reproduction of the underlying issue, which is neat!

**Closed** 2024-02-09 00:38 UTC
Labels: A-ty, C-bug
