### ISSUE TITLE
Hover information doesn't include doc comments created with `concat!`

### ISSUE THREAD

**Issue by Wilfred** [rust-lang/rust-analyzer#17345] opened 2024-06-04 20:56 UTC
**rust-analyzer version**: rust-analyzer version: 0.3.1983-standalone (7852a4c77 2024-06-02)

**rustc version**: 1.78.0

**code snippet to reproduce**: 
```rust
fn main() {
    let x: usize = 1;
    let _ = x.saturating_add(123);
}
```

Hovering over `saturating_add` does not include the example:

<img width="711" alt="Screenshot 2024-06-04 at 1 41 02 PM" src="https://github.com/rust-lang/rust-analyzer/assets/70800/853e3779-99ee-436c-90e3-5c43eeab265a">

This seems to be because the doc comment looks like this: https://github.com/rust-lang/rust/blob/master/library/core/src/num/int_macros.rs#L1599

        /// Saturating integer addition. Computes `self + rhs`, saturating at the numeric
        /// bounds instead of overflowing.
        ///
        /// # Examples
        ///
        /// Basic usage:
        ///
        /// ```
        #[doc = concat!("assert_eq!(100", stringify!($SelfT), ".saturating_add(1), 101);")]
        #[doc = concat!("assert_eq!(", stringify!($SelfT), "::MAX.saturating_add(100), ", stringify!($SelfT), "::MAX);")]
        #[doc = concat!("assert_eq!(", stringify!($SelfT), "::MIN.saturating_add(-1), ", stringify!($SelfT), "::MIN);")]
        /// ```

Would it be possible to support this in rust-analyzer?

**Comment by Veykril** [comment] 2024-06-05 07:20
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/8092

**Closed by Veykril** 2024-06-05 07:20 UTC
Labels: C-bug
