### ISSUE TITLE
BUG - v0.3.1877

### ISSUE THREAD

**Issue by Cheban1996** [rust-lang/rust-analyzer#16809] opened 2024-03-11 12:46 UTC
Today i update rust-analyzer to last version(v0.3.1877) - and define bug. Nothing working if in code exists error. If i use cargo clippy or check manual in console i see error. But in vscode nothing
As resolve i updated to v0.3.1868 and that resolve my trouble
I don't know how get log -  because in Output nothing has

**Comment by ThomasMiz** [comment] 2024-03-12 16:36
I'm having the same issue, I'm getting absolutely nothing since I updated to `0.3.1877-standalone (574e23ec5 2024-03-09)`.

I make an empty project with nothing but these three lines:
```rust
fn hello(thing: NonExistType) {
    return this_doesnt_exist;
}
```
I should get an error that `NonExistType` doesn't exist, or that `this_doesnt_exist` doesn't exist, or trying to return a value in a `()` function

**Comment by Veykril** [comment] 2024-03-13 08:47
Can you check the server logs for any info? Does the status bar (in vscode) show a yellow or red icon?

**Comment by ThomasMiz** [comment] 2024-03-17 15:05
> Can you check the server logs for any info? Does the status bar (in vscode) show a yellow or red icon?

Hello! Today I updated to `rust-analyzer version: 0.4.1883-standalone (5ecace48f 2024-03-16)` and `rustc 1.78.0-nightly (766bdce74 2024-03-16)` and the issue is not present anymore.

If you want, I can roll back to the problematic version and see if I can extract any info, otherwise I guess we can close this

**Closed** 2024-03-17 15:08 UTC
Labels: C-bug
