### ISSUE TITLE
Chains of tuple access are incorrectly typed unless broken up

### ISSUE THREAD

**Issue by kythyria** [rust-lang/rust-analyzer#10560] opened 2021-10-17 01:38 UTC
VSCode: 1.61.1
OS: Windows 10
Rust-analyser: 0.2.776

This code compiles, but is handled incorrectly by RA:
```rs
use std::rc::Rc;
use std::collections::HashMap;

struct DocumentData {
    tables: Vec<TableData>
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct TableId(usize);

struct TableData {
    everything_else_hash: HashMap<String, String>
}

pub struct TableRef(Rc<DocumentData>, TableId);
impl TableRef {
    pub fn get_item_bug(&self, item: &String) -> Option<String> {
        let tid = self.1.0;
        self.0.tables[tid].everything_else_hash.get(item).map(Clone::clone)
    }

    pub fn get_item_correct(&self, item: &String) -> Option<String> {
        let ti = self.1;
        let tid = ti.0;
        self.0.tables[tid].everything_else_hash.get(item).map(Clone::clone)
    }
}
```
Specifically, in `get_item_bug`:
* Tooltip of `tid` reads `let tid: Rc<DocumentData>` (should be `usize`)
* `everything_else_hash` and `get` are displayed with the "nonexistent item" formatting (should be field and method respectively)
* Their tooltips read `{unknown}` and highlight the entire line up to that point.
* `map` is incorrectly listed as being `Iterator::map` rather than `Option::map`

None of `get_item_correct` has this, nor does rustc itself report any errors

**Comment by Veykril** [comment] 2021-10-17 08:20
Probably a dupe of https://github.com/rust-analyzer/rust-analyzer/issues/1109

**Closed** 2022-05-05 15:45 UTC
Labels: C-bug
