### ISSUE TITLE
`failed to load workspace` in projects with Rust nested more than one directory deep

### ISSUE THREAD

**Issue by KyleMiles** [rust-lang/rust-analyzer#13048] opened 2022-08-17 20:09 UTC
`rust-lang.rust`'s default behavior allowed for the discovery of Rust projects nested at any depth in large projects.

Now that `rust-analyzer` is the default for Rust in VSCode, I no longer get **_any Rust integration_** in my IDE for folders nested more than one level deep.

The year is 2022, and I should not need to populate configuration files or change settings for my IDE to provide support for the language I'm using.  I feel strongly enough about this to assert that `rust-analyzer` is unusable for my (and many others') day-to-day use case and consider using a different IDE with reasonable default behavior.

I see the `linkedProjects` workaround provided in #7268 as well as the performance considerations in #2533, but unfortunately I don't think that `rust-analyzer` is a viable replacement for `rust-lang.rust` until I can just:
1. Open my project's root directory
2. Have support for all the Rust code in my project

**rust-analyzer version**: `rust-analyzer version: 0.3.1170-standalone (b6d59f2bb 2022-08-14)`
**rustc version**: `rustc 1.63.0 (4b91a6ea7 2022-08-08)`
**relevant settings**: All default settings, fresh install.  Using VSCode.

**Comment by flodiebold** [comment] 2022-08-17 20:44
Duplicate of #8622

**Closed by flodiebold** 2022-08-17 20:44 UTC
