### ISSUE TITLE
`tokio::test` doesn't trigger the test runner

### ISSUE THREAD

**Issue by nitnelave** [rust-lang/rust-analyzer#14197] opened 2023-02-23 14:34 UTC
Similar to https://github.com/rust-lang/rust-analyzer/issues/10768:

In neovim, I can run `:RustTest` on a function marked with `#[test]`, but not with `#[tokio::test]`.

**rust-analyzer version**: rust-analyzer 1.69.0-nightly (fdbc432 2023-02-22)

**rustc version**: rustc 1.67.1 (d5a82bbd2 2023-02-07)

**relevant settings**: using tokio 1.17, all features.

**Comment by nitnelave** [comment] 2023-02-23 14:39
Also tried with tokio 1.25, not working either.

**Comment by lnicola** [comment] 2023-02-23 14:43
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/12362 and/or https://github.com/rust-lang/rust-analyzer/issues/11396.

**Closed by lnicola** 2023-02-23 14:43 UTC
Labels: C-bug
