### ISSUE TITLE
`generate_derive` loses indent

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#14674] opened 2023-04-28 16:02 UTC
![image](https://user-images.githubusercontent.com/308347/235197072-ce9921ca-a1a2-4064-8682-f8d75d293c30.png)

https://github.com/rust-lang/rust-analyzer/blob/816f7fe/crates/ide-assists/src/handlers/generate_derive.rs#L45

**Comment by ponyii** [comment] 2023-05-06 18:19
just for the sake of clarity:

`generate_derive` being called on a snippet like this eats an indent.
```
mod module {
    enum Enum {      // this indent will be lost
        Whatever,<|>
    }
}
```

**Comment by ponyii** [comment] 2023-05-06 18:24
I've found some other assists that doesn't taking into account indentation and, consequently, produce incorrectly indented code (e.g. `toggle_ignore`, `generate_deref`). It's worth checking them all.

Another problem is that each assist deal with indentation by itself ([an example](https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide-assists/src/handlers/generate_documentation_template.rs#L455)). It might be more convenient to write a single function for the generated code indentation.

I think I can fix it within this issue, could you assign it to me?

**Comment by ponyii** [comment] 2023-05-11 18:13
I've written a few _ad hoc_ patches and some new tests (PR https://github.com/rust-lang/rust-analyzer/pull/14752), but there're still too many assists that can break indentation, so some general solution is required.

As far as I understand, all the assists eventually pass a closure to `Assists::add` that changes the source code using different methods of `SourceChangeBuilder`. None of these methods checks if the code addition / replacement / whatever breaks the indentation, and I suppose it's the root cause of the bug. 
It doesn't seem to me convenient to introduce such a check in these methods (one reason: their arguments are `impl Into<String>`, but not easy-to-reindent syntax trees). The general solution I'd suggest is to call some `fix_indentation` function after each usage of an assist; though it's in no way brilliant - for instance, it will break any user's unconventional indentation.

(I believe this issue is no longer _actionable_ and requires a discussion of the general solution - and whether it's important to implement it at all)

**Closed** 2023-05-24 19:13 UTC
Labels: S-actionable, A-assists, C-bug
