### ISSUE TITLE
Autocompletion doesn't work for implemented traits for `rusymbols::Expression`

### ISSUE THREAD

**Issue by Andrew15-5** [rust-lang/rust-analyzer#15708] opened 2023-10-04 08:13 UTC
**rust-analyzer version**: `0.3.1681-standalone`

**rustc version**: `1.72.1 (d5c2e9c34 2023-09-13)`

**relevant settings**: `"workspace.ignoredFolders": ["$HOME", "$HOME/.cargo/**", "$HOME/.rustup/**"]`

I'm not sure how this is possible, but only methods of implemented (std) traits are not shown in autocompletion list:

<details><summary>screenshot</summary>

![image](https://github.com/rust-lang/rust-analyzer/assets/37143421/36c4bd2e-3958-4424-b19a-245a0717b0e9)

</details>

But methods of struct implementation are present:

<details><summary>screenshot</summary>

![image](https://github.com/rust-lang/rust-analyzer/assets/37143421/63f94351-c68e-47c1-96ec-5b8b3a1acd65)

</details>

And after using non-present method, its methods are also won't exist (return type is `Expression`):

<details><summary>screenshot</summary>

![image](https://github.com/rust-lang/rust-analyzer/assets/37143421/5fa26516-bcac-41cc-8c39-eeaefd0759ff)

</details>

<details><summary>example</summary>

```rust
fn main() {
    use rusymbols::Expression;
    use std::collections::HashMap;

    let x = Expression::new_var("x");
    let two = Expression::new_val(2.0);
    let polynomial = x.clone().pow(two.clone()) - x + two;

    let mut args: HashMap<&str, f64> = HashMap::new();
    args.insert("x", 1.0);

    assert_eq!(polynomial.to_string(), "x**2 - x + 2");
    assert_eq!(polynomial.eval_args(&args).unwrap(), 2.0);
}
```

</details>

OnHover event also doesn't work on `clone()` or on any methods after `clone()`. When hovering on `polynomial` server can't detect the type of `Expression`: `let polynomial: {unknown}`

I don't think that it is somehow linked to my rust-analyzer setup or `coc.nvim` plugin (but I guess everything is possible). I'm also new to Rust (idk if this is relevant). I'm also not sure if this is a bug in [this specific crate](https://docs.rs/rusymbols/latest/rusymbols/) or is this a known issue.

**Comment by lnicola** [comment] 2023-10-04 08:28
Confirmed, we don't resolve `clone()`:

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/c1051ce8-aea6-4d99-b01e-a3726d5d66c0)

Which is quite surprising, as the following works fine:

```rust
#[derive(Debug, Clone)]
pub enum Actions {
    Var(String),
}

#[derive(Clone, Debug, Default)]
pub struct Expression {
    args: Vec<Expression>,
    kind: Actions,
}

impl Expression {
    pub fn new(left: Expression, right: Expression, kind: Actions) -> Expression {
        Expression{ args: vec![left, right], kind}
    }

    pub fn new_var(literal: &str) -> Expression {
        Expression { args: vec![], kind: Actions::Var(String::from(literal)) }
    }
}

fn main() {
    let x = Expression::new_var("x");
    let polynomial = x.clone();
}
```

**Comment by lnicola** [comment] 2023-10-04 08:31
Duplicate of #13600.

**Closed by lnicola** 2023-10-04 08:31 UTC
Labels: C-bug
