### ISSUE TITLE
Issue with tree structure debugging

### ISSUE THREAD

**Issue by ButuzGOL** [rust-lang/rust-analyzer#13644] opened 2022-11-19 14:06 UTC
**rust-analyzer version**: v0.3.1285
**rustc version**: rustc 1.65.0 (897e37553 2022-11-02)
**relevant settings**: 

Here code example
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d96b0ee0d9b0ac090f085d66b92b05dd
<img width="1140" alt="Screenshot 2022-11-19 at 16 06 06" src="https://user-images.githubusercontent.com/196564/202854569-740dd5be-2607-46e3-8b05-62033942bb6d.png">

**Comment by bjorn3** [comment] 2022-11-19 14:10
Rust-analyzer itself doesn't provide the debugger integration. You should probably configure your debugger extension to use rust-gdb/rust-lldb or load the pretty printers another way. I don't know which debugger extension and which debugger you are using, so I can't help with configuring this.

**Comment by jonas-schievink** [comment] 2023-01-30 12:25
Closing, this is not a bug on our end.

**Closed by jonas-schievink** 2023-01-30 12:25 UTC
Labels: C-support
