### ISSUE TITLE
VSCode: Rust Analyzer Activating in Non-Rust Workspaces

### ISSUE THREAD

**Issue by rspeir** [rust-lang/rust-analyzer#15488] opened 2023-08-20 20:01 UTC
I'm working on an embedded C project, and I have created VSCode tasks to run 'make' and 'make clean' commands. Every time I press CTRL+Shift+B to run one of these commands, Rust Analyzer starts running, complaining that it's "Failed to discover workspace".

There are only .c, .h, .s, and makefiles in my workspace. There are NO .rs or Cargo.toml files anywhere, so I don't know why Rust Analyzer is triggering in the first place. 

This is under VSCode 1.81.1 running on Windows 10.0.19045, Rust Analyzer v0.3.1623

Any ideas?

**Comment by lnicola** [comment] 2023-08-23 12:18
Duplicate of #14231.

**Closed by lnicola** 2023-08-23 12:18 UTC
Labels: C-bug
