### ISSUE TITLE
RA runs into an endless build loop with the windows-rs repo

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-analyzer#16250] opened 2024-01-04 10:59 UTC
- clone https://github.com/microsoft/windows-rs
- open that folder in vscode, with RA installed

Half an hour later, the IDE is still in an endless loop of check builds. Something seems to be going wrong. Note that I am on Linux, but I need to grep for some stuff in the windows-sys crate.

The "rust-analyzer" thing in the status bar is brown, indicating a warning. It switches between the "warning" triangle symbol and the "loading" spinner.

"output" shows one error:
```
[ERROR rust_analyzer::main_loop] FetchBuildDataError:
error: environment variable `windir` not defined at compile time
 --> crates/tests/component/build.rs:3:61
  |
3 |     let metadata_dir = format!("{}\\System32\\WinMetadata", env!("windir"));
  |                                                             ^^^^^^^^^^^^^^
  |
  = help: use `std::env::var("windir")` to read the variable at run time
  = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)


error: aborting due to previous error


error: could not compile `test_component` (build script) due to 2 previous errors
```
This is also what I get from `cargo check`. But that finishes in a few seconds, whereas RA just keeps going forever.

**rust-analyzer version**: rust-analyzer version: 0.3.1791-standalone

**rustc version**: rustc 1.74.1 (a28077b28 2023-12-04)

**relevant settings**: none

**Comment by Veykril** [comment] 2024-01-04 14:00
Doesnt hang on windows at least, will check whats up with my linux machine later

**Comment by Veykril** [comment] 2024-01-06 11:15
So there is something funny going on in this repo, its build scripts consistently touch rust files in a weird which causes us to reload the workspace and restart from the beginning.

**Comment by Veykril** [comment] 2024-01-06 11:21
Now interestingly enough, it doesn't hang for me, it just reloads the workspace for a good minute, but at some point it stops. Anyways, the cause is https://github.com/microsoft/windows-rs/blob/7219668f80a459b47097bc524af304073c69ec4b/crates/tests/standalone/build.rs is deleting and re-creating the files in the `src` folder of the crate which will require r-a to attempt to reload the workspace which will potentially retrigger the build scripts. Bit odd I'm not observing this on windows. I don't think we can do anything on the r-a side here.

**Comment by RalfJung** [comment] 2024-01-06 11:28
Yeah I also see changes in `git diff` after opening vscode in that repo.

**Comment by lnicola** [comment] 2024-01-06 11:30
Why are we reloading the workspace if it only touches Rust files (on phone, can't really follow the code now)?

**Comment by RalfJung** [comment] 2024-01-06 11:32
> Does disabling --all-targets fix it?

I am not setting `--all-targets` anywhere. I am confused by the question.

**Comment by lnicola** [comment] 2024-01-06 11:34
It's set by default, see the extension settings.

**Comment by RalfJung** [comment] 2024-01-06 11:37
I have now set this but it doesn't help
```
{
    "rust-analyzer.check.allTargets": false,
    "rust-analyzer.cargo.buildScripts.enable": false
}
```

**Comment by lnicola** [comment] 2024-01-06 11:41
You're disabling build scripts only for RA, they still get run by `cargo check` (different setting for that). But I guess you did answer my question.

**Comment by RalfJung** [comment] 2024-01-06 11:42
Yeah `buildScripts.enable` was just another experiment, it makes no difference as you say.

**Comment by Veykril** [comment] 2024-01-06 13:34
> Why are we reloading the workspace if it only touches Rust files (on phone, can't really follow the code now)?
> 
> Does disabling `--all-targets` fix it?

The build script deletes and then creates the files in that directory again one by one, a creation / deletion event triggers a workspace reload (not a mere modify). I don't recall why we do that, but I believe there is a good reason for that.

**Comment by RalfJung** [comment] 2024-01-06 16:49
Strangely, I see a change in `git diff` when opening the repo in RA, but so far I didn't find a way to cause a direct `cargo` invocation to cause a similar issue.

**Comment by lnicola** [comment] 2024-01-06 17:08
Yeah, weird. `cargo build --keep-going --tests` (and even `check`) does seem to delete and re-create some test files. Loading it form RA seems to have a similar effect.

**Comment by ChrisDenton** [comment] 2024-01-06 17:11
I used rust-analyzer on the windows-rs crate and don't remember encountering this issue. Although now that I look at my rust-analyzer config it seems like I was trying to work around *something* even if I no longer remember it:

```json
"rust-analyzer.cargo.buildScripts.enable": false,
"rust-analyzer.cachePriming.enable": false,
```

**Comment by riverar** [comment] 2024-01-06 18:42
Ditto here, have never experienced the aforementioned loop. That said, the workspace is always in a perpetual need-reload state, of which I just ignore. Only preference I have (aside from inlay hints) is:

```json
"rust-analyzer.checkOnSave": false,
```

**Comment by lnicola** [comment] 2024-08-18 14:07
Fixed in `widnows-rs`.

**Closed by lnicola** 2024-08-18 14:07 UTC
Labels: C-Architecture, C-bug, A-vfs
