### ISSUE TITLE
Regression(?): proc macro not expanded since v0.3.1091

### ISSUE THREAD

**Issue by andrew-sol** [rust-lang/rust-analyzer#12525] opened 2022-06-13 16:35 UTC
I use NEAR Rust SDK crate (https://docs.rs/near-sdk/latest/near_sdk).
I see "proc macro not expanded" errors everywhere after the update to v0.3.1091.

v0.3.1083 works fine.

**rust-analyzer version**: 0.3.1091
**rustc version**: rustc 1.61.0 (fe5b13d68 2022-05-18)
**relevant settings**: `CARGO`, `RUSTUP_HOME`, `RUSTUP_HOME` are empty

**Comment by bjorn3** [comment] 2022-06-13 16:40
You will need to update rustc. Between the rustc version you are using and the latest one there has been an abi breaking change in the proc_macro implementation. Rust-analyzer 0.3.1091 updated for the new abi and thus broke support for the old abi (on nightly rustc at least) Rust-analyzer doesn't attempt to support nightlies other than the latest.

**Comment by lnicola** [comment] 2022-06-13 16:40
There was a change affecting 1.63 nightlies, but it shouldn't have any effect on 1.61.

**Comment by bjorn3** [comment] 2022-06-13 16:43
Right, misread the rustc version.

**Comment by Veykril** [comment] 2022-06-13 16:46
The latest release upgraded the diagnostic to warning from weak-lint since we now properly detect whether proc-macros are disabled or not. So these errors might not be new for your project, they are just more visible now.

This usually indicates some other build problem for r-a in your project. The easy way out is to disable the specific diagnostic via the settings, though that might give you a worse experience overall for other IDE features still.

**Comment by arnolddevos** [comment] 2022-06-14 02:17
Same problem here but with yew macros.  Versions as above:

rust-analyzer version: 0.3.1091
rustc version: rustc 1.61.0 (fe5b13d68 2022-05-18)

ra shows an error unresolved-proc-macro for yew's `Properties`, `function_component` and `html` macros. There was no warning or error with the previous ra version and cargo builds the project without warnings or errors.

**Comment by andrew-sol** [comment] 2022-06-14 07:43
Will clarify a bit. In my case (NEAR SDK) the error appears only for attribute macroses and derive macroses:
```
#[near_bindgen]
#[ext_contract(...)]
#[derive(BorshDeserialize, BorshSerialize, PanicOnDefault)]
```
Some of them are from this crate: https://docs.rs/borsh/latest/borsh.

Log (Extension Host) doesn't show any errors.

**Comment by lnicola** [comment] 2022-06-14 07:54
(sneaky little macroses :sweat_smile:)

The log channel is called `Rust Analyzer Language Server`.

![image](https://user-images.githubusercontent.com/308347/173523729-7f29871f-1611-451f-a8e8-0d4344576de8.png)

**Comment by sumerman** [comment] 2022-06-14 08:08
Same problem with [pgx macroses](http://github.com/tcdi/pgx/). 
- `rustc 1.61.0`
- `pgx 0.3.1`

**Comment by lnicola** [comment] 2022-06-14 08:10
@sumerman do you have some public code showing this problem?

**Comment by Veykril** [comment] 2022-06-14 08:46
And for those that either do not want to investigate why their proc-macro's don't get resolved by r-a, or want to get around this since they want to work before investigating it, you can set `"rust-analyzer.diagnostics.disabled": ["unresolved-proc-macro"]` which should hide these errors. Note though that all the proc-macros that error aren't being expanded and as such will degrade your overall experience most likely.

**Comment by lnicola** [comment] 2022-06-15 09:02
After setting up `cargo pgx`, expanding `#[pg_extern]` seems to work for me, both in stable and beta:

![image](https://user-images.githubusercontent.com/308347/173787656-bb80f40e-07f2-4152-85a3-971b9f844742.png)

**Comment by sumerman** [comment] 2022-06-15 09:59
After switching rust version back and forth with rustup it suddenly works for me too 🤔

**Comment by Veykril** [comment] 2022-06-15 16:11
I'll hide the resolved comments here so we don't lose track of the different people here, @sumerman if you can't seem to figure out your new problem feel free top open a new issue for that.

**Comment by sumerman** [comment] 2022-06-16 07:40
> I'll hide the resolved comments here so we don't lose track of the different people here, @sumerman if you can't seem to figure out your new problem feel free top open a new issue for that.

It was my setup. I had x86_64 leftovers after migrating to aarch64 system.

**Comment by flodiebold** [comment] 2022-06-16 13:18
@andrew-sol @arnolddevos Please try the current pre-release version; it should show a more detailed error message.

**Comment by Veykril** [comment] 2022-06-18 22:39
Heads up, https://github.com/rust-lang/rust-analyzer/pull/12584 fixed an issue where we potentially did misdiagnose *derive helpers* as being unresolved specifically. Please let us know if your issues were due to *derive helpers* erroring or not (so we know whose issues may have been fixed by that here).

**Comment by andrew-sol** [comment] 2022-06-20 09:10
Updated to the pre-release version. Now the error says (paths are shortened):
```
proc macro `near_bindgen` not expanded: Cannot create expander for /.../path-to-the-project-
dir/target/debug/deps/libnear_sdk_macros-7d99f10f2e6fc575.dylib: Io(Custom { kind: InvalidData, error: DlOpen { desc:
"dlopen(/.../path-to-the-project-dir/target/debug/deps/libnear_sdk_macros-7d99f10f2e6fc575.dylib, 0x000A): tried:
\'/.../path-to-the-project-dir/target/debug/deps/libnear_sdk_macros-7d99f10f2e6fc575.dylib\' (mach-o file, but is an
incompatible architecture (have \'x86_64\', need \'arm64e\'))" } })
```

I'm on Apple M1.

**Comment by lnicola** [comment] 2022-06-20 09:41
CC @cloutiertyler via https://github.com/rust-lang/rust-analyzer/issues/10894.

@andrew-sol what do you get in Code / Help / About, and did you set `rust-analyzer.server.path`?

**Comment by lnicola** [comment] 2022-06-20 10:03
@andrew-sol what about `rustup toolchain list`? Did you switch recently from an x64 to an M1 Mac?

**Comment by andrew-sol** [comment] 2022-06-20 10:10
`rustup toolchain list` shows this:
```
stable-aarch64-apple-darwin
stable-x86_64-apple-darwin (default)
1.56.0-x86_64-apple-darwin
1.58.1-x86_64-apple-darwin
1.61.0-x86_64-apple-darwin (override)
```

I switched some time ago back and forth, but not recently.

My `rust-toolchain` file contains:
```
1.61.0
```

**Comment by lnicola** [comment] 2022-06-20 10:11
> stable-x86_64-apple-darwin (default)

Yeah, I don't think you want that.

**Comment by flodiebold** [comment] 2022-06-20 11:06
> Given the comment that is probably something we'll have to fix somehow, but I don't know anything about that.

I think #12579 will fix that problem if/when we implement it.

**Comment by flodiebold** [comment] 2022-06-20 11:13
> stable-aarch64-apple-darwin
> stable-x86_64-apple-darwin (default)

Hmm but that's the *target* architecture, right? Like when I install a wasm toolchain, it compiles to wasm, but runs on x86_64. Can you have a toolchain built for aarch64 that compiles to x86_64, or vice versa? How does rustup choose the host architecture of the toolchain on M1 Macs? :thinking:

**Comment by lnicola** [comment] 2022-06-20 11:16
> Can you have a toolchain built for aarch64 that compiles to x86_64, or vice versa?

Umm, yes? I think the problem is that @andrew-sol is using the Aarch64 RA with an `x64` toolchain, so we can't load the proc macro library in the server process.

I'm curious if this is a new install or a cloned drive. And can you use e.g. an x64 Firefox or Chrome to download an x64 `rustup` and get an `x64` toolchain?

**Comment by andrew-sol** [comment] 2022-06-20 11:17
I did:
```
rustup default stable-aarch64-apple-darwin
```
removed the `target` folder and recompiled.

The error has gone.

When I did this the previous time some project dependencies didn't compile for arch64, but now they do.

**Comment by lnicola** [comment] 2022-06-20 11:19
I suppose you need to install the x64 version of Code if you want to build your project for x64.

**Comment by flodiebold** [comment] 2022-06-20 11:22
> Umm, yes? I think the problem is that @andrew-sol is using the Aarch64 RA with an x64 toolchain, so we can't load the proc macro library in the server process.

Right, but what I'm trying to say is that just because rustup says `stable-x86_64-apple-darwin (default)`, that wouldn't automatically mean the *host* architecture is x86_64? Like, the *target* architecture shouldn't matter, you should be able to cross-compile from aarch64 to x86_64, in which case rustc should build proc macros for aarch64.

Unless rustup on M1 Mac installs aarch64 builds for compiling to aarch64, and x86 builds for compiling to x86. Which I guess would make some sense.

> I suppose you need to install the x64 version of Code if you want to build your project for x64.

Or just point `rust-analyzer.server.path` to an x86_64 build of rust-analyzer.

**Comment by bjorn3** [comment] 2022-06-20 11:24
> that wouldn't automatically mean the host architecture is x86_64?

Yes it would. The triple in the toolchain name is the triple for which the compiler itself is built and is thus the host triple.

**Comment by flodiebold** [comment] 2022-06-20 11:25
Ah right, I was confusing toolchains with targets :sweat_smile:

**Comment by flodiebold** [comment] 2022-06-20 11:34
Well, the original issue is clarified, so let's close this ticket.

**Closed by flodiebold** 2022-06-20 11:34 UTC
Labels: C-support, A-proc-macro

**Comment by andrew-sol** [comment] 2022-06-20 11:49
Yeah, thanks for your help.
