### ISSUE TITLE
proc macro `async_trait` not expanded: failed to write request: The pipeline is being closed. (os error 232)

### ISSUE THREAD

**Issue by Rick9622092** [rust-lang/rust-analyzer#14992] opened 2023-06-06 07:23 UTC
In VSCode, Error Messages as:
proc macro `async_trait` not expanded: failed to write request: The pipeline is being closed. (os error 232)
proc macro `Deserialize` not expanded: failed to write request: The pipeline is being closed. (os error 232)
....

In terminal, run "Cargo build": pass!

**rust-analyzer version**: v0.3.1541

**rustc version**: rustc 1.72.0-nightly (e6d4725c7 2023-06-05)
![cargo_build_result](https://github.com/rust-lang/rust-analyzer/assets/116558673/ffde5c23-5280-494b-9a0a-b7990946f22c)
![err_msg](https://github.com/rust-lang/rust-analyzer/assets/116558673/6e0af489-30ba-4b99-bc62-4e46e8d33aa6)

**Comment by lnicola** [comment] 2023-06-06 07:25
Duplicate of #14991

**Closed by lnicola** 2023-06-06 07:25 UTC
Labels: C-bug

**Comment by lnicola** [comment] 2023-06-08 10:18
#14991 is still open.
