### ISSUE TITLE
Flyimport completion sometimes won't suggest std::iter::once

### ISSUE THREAD

**Issue by johnw42** [rust-lang/rust-analyzer#10112] opened 2021-09-01 17:09 UTC
Using VS Code completion, I can't get anything to complete to `std::iter::once`. When there are no imports and the word before the point is `onc` or `once`, the suggestions I get are `std::iter::once_with` (twice!), `FnOnce`, and `std::lazy::SyncOnceCell`. I'm testing using a brand-new crate created with `cargo init --lib`.

rust-analyzer d15f646ff 2021-08-30 stable
code 1.58.0 2d23c42a936db1c7b3b06f918cde29561cc47cd6 x64
Extension version: 0.2.727

**Comment by lnicola** [comment] 2021-09-01 17:26
Hmm, it does seem to work for me:

![image](https://user-images.githubusercontent.com/308347/131716308-5b6b2ae0-7655-4ea0-a543-4a8fbf1f91a3.png)

It even includes the module, which it probably shouldn't.

**Comment by flodiebold** [comment] 2021-09-01 19:14
What rustc version are you using?

**Comment by flodiebold** [comment] 2021-09-01 19:17
Oh, I think this is about autoimport completions? I.e. just typing `on<|>` and getting `once (use std::iter::once)`. I indeed don't see that, even with `onc<|>`. The autoimport code action works on `once` though, and 'qualify' is even suggested twice for some reason :confused:

**Comment by Veykril** [comment] 2021-09-01 19:55
The qualify one gives two options because of the module with the same name(which we currently find when searching for some reason), we fixed that for auto-import but not for qualiy_path it seems, fixed that now https://github.com/rust-analyzer/rust-analyzer/pull/10114

I do see the completion for `onc` though 
![image](https://user-images.githubusercontent.com/3757771/131735398-4e25bd04-0ce5-4d75-998b-b941f41603ab.png)
For `o` and `on` we don't flyimport the completion as we only apply it for more than 2 characters.

**Comment by Veykril** [comment] 2021-09-01 19:59
I'm not sure whether its intentional that we discard the flyimport for an item if its name is fully typed out though, feels like we shouldn't discard it since the import is still of interest.

**Comment by johnw42** [comment] 2021-09-02 15:40
I definitely agree with you there. It feels weird having to scroll up and
manually add an import when it happens automatically 95% of the time, and
I'd much prefer it be automated so the time so I don't have to think about
things like how to group the imports to be consistent with the existing
style.

Would making that and change allow me to do something like expand the
suggestions for "iter" and get an option to add an import for "std::iter"?
I see a lot of examples where names are qualified by a module name in std,
and I wish rust-analyzer made it easier to use that style.

**Comment by Veykril** [comment] 2021-09-02 15:52
You can flyimport modules, so (with this bug? fixed) you could type out `iter` and then get a completion that would add the import for `std::iter` for you.

**Comment by Veykril** [comment] 2022-01-04 09:27
So this is interesting, depending on your crate graph typing `onc` will show the completion for `std::iter::once`, but typing `once` will not(due to reaching the query limit in this case). The cause for this I believe is https://github.com/rust-analyzer/rust-analyzer/blob/989c06b25d7e9d5c10ce77831952cab7359d6ab2\crates\hir_def\src\import_map.rs#L417
effectively making the order of how we traverse the query results "random", replacing this with `FxIndexSet` unfortunately effectively causes us to not show `std::iter::once` at all, probably due to std ending up at the far bottom somehow.

**Comment by Veykril** [comment] 2024-07-21 10:52
I will close this, the limit here might be lifted in the future, it might not. There were a bunch of improvements here though which should make this less likely to run into.

**Closed by Veykril** 2024-07-21 10:52 UTC
Labels: A-completion, S-actionable
