### ISSUE TITLE
proc macro not expanded: failed to write request (os error 232) on Windows

### ISSUE THREAD

**Issue by zjp-CN** [rust-lang/rust-analyzer#16306] opened 2024-01-08 02:31 UTC
**rust-analyzer version**: rust-analyzer version: 0.3.1791-standalone (9db515503 2024-01-01)

**rustc version**: rustc 1.77.0-nightly (595bc6f00 2024-01-05)

**relevant settings**: none

![](https://github.com/rust-lang/rust-analyzer/assets/25300418/9fa3c39c-bce1-4242-bf2e-85b12d78d5cb)

> proc macro `Serialize` not expanded: failed to write request: 管道正在被关闭。 (os error 232)
> rust-analyzer [unresolved-proc-macro](https://rust-analyzer.github.io/manual.html#unresolved-proc-macro)

OS: Windows11

Reproduce:
```shell
cargo new test-ra
cd test-ra
cargo add serde -F derive
```

```rust
// src/main.rs
use serde::Serialize;
#[derive(Serialize)]
pub struct A {}
fn main() {}
```

Found a related but closed issue: https://github.com/rust-lang/rust-analyzer/issues/14991

**Comment by Veykril** [comment] 2024-01-08 07:52
We really need to improve the `pipe closed` error somehow

**Comment by Veykril** [comment] 2024-01-08 09:51
Though generally that means the server crashed I think, which has me worried that the upstream server is now built without the sysroot abi after the trouble i had there last week ...

**Comment by Veykril** [comment] 2024-01-08 09:57
Yup, I broke the sysroot server last week ...

**Comment by Veykril** [comment] 2024-01-08 10:23
Gonna give it a quick attempt at fixing and if that fails I'll disable the in-rust-tree stuff fully, I'm fed up with rustc's bootstrapping shenanigans.

**Comment by Veykril** [comment] 2024-01-08 10:42
After some debugging, ![image](https://github.com/rust-lang/rust-analyzer/assets/3757771/531a8a21-c909-4c9a-867a-cd99081eafb3)
apparently I managed to dynamically link the server against rustc internals? 🤨

**Comment by Veykril** [comment] 2024-01-08 10:44
@onur-ozkan apologies for the cross-repo ping, but do you have an idea what could be going wrong here? Do I need to tell bootstrap to do static linking here somehow?

**Comment by Veykril** [comment] 2024-01-08 10:51
Oh, nvm now I see whats going on. We changed the tool mode to `Rustc` which is expected to dynamically link, but the proc-macro server lives in `libexec`, not `bin` so we fail to find the dylib! Well that is annoying ...

**Comment by Veykril** [comment] 2024-01-08 13:03
Started a discussion on zulip: https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/rust-analyzer-proc-macro-srv.20dynamically.20links.20rustc_driver

**Comment by nevercast** [comment] 2024-01-11 06:10
Any updates to this? I'm seeing this with `wasm_bindgen`

**Comment by zjp-CN** [comment] 2024-01-11 07:16
From zulip thread above, the issue may result from [this PR](https://github.com/rust-lang/rust/pull/118861#issuecomment-1878177138) merged on 2024-01-05, so I tried pinning the nightly toolchain before that date, and with latest rust-analyzer  v0.3.1799 released on 2024-01-08, it turns out to work without the error. 
And if your toolchain is on stable, you may not see this error, since that landed before 2024-01-05 (I've tested it on stable toolchain with latest nightly RA). 

```TOML
# rust-toolchain.toml
[toolchain]
channel = "nightly-2024-01-04"
```

**Comment by nevercast** [comment] 2024-01-11 07:29
Thank you @zjp-CN. I will try that on my Windows machine. If the issue is not present on Linux I may also use that until it lands in latest nightly. Thanks for the quick and detailed response!

**Comment by Veykril** [comment] 2024-01-11 08:02
Yes, to add context. This issue only exists on the windows toolchain because windows does not support `rpath`s and the the proc-macro server is now dynamically linked to something outside of its own directory. Latest nightly r-a and next week's stable r-a should just work again.

This was fixed by https://github.com/rust-lang/rust-analyzer/pull/16312

**Closed by Veykril** 2024-01-11 08:02 UTC
Labels: Broken Window, C-bug, A-proc-macro

**Comment by spooky-th-ghost** [comment] 2024-02-18 22:13
Don't know if this is 100% related but I'm running the `stable-x86_64-unknown-linux-gnu` toolchain and using `rustup update` to update to rust 1.76 yesterday introduced this error using the built in LSP in nvim
![image](https://github.com/rust-lang/rust-analyzer/assets/30451500/b819dce8-1d82-4544-b0b9-f145227cedbe)

**Comment by arnfaldur** [comment] 2024-02-19 02:24
I have also encountered this issue on linux. I managed to mitigate it by using an older toolchain (from around last october) but I can't use the old toolchain anymore, reintroducing the problem.

**Comment by zjp-CN** [comment] 2024-02-19 02:57
@spooky-th-ghost I've tested 2024-02-12 nightly RA with 1.76 stable toolchain (released on 2024-02-04) for proc macros, nothing goes wrong.
IIUC the error says your proc-macro server (from toolchain) is newer than RA. What's the verion of your RA?

**Comment by Veykril** [comment] 2024-02-19 08:18
As was said you'll need to update your rust-analyzer to a newer version./

**Comment by spooky-th-ghost** [comment] 2024-02-19 20:03
> @spooky-th-ghost I've tested 2024-02-12 nightly RA with 1.76 stable toolchain (released on 2024-02-04) for proc macros, nothing goes wrong. IIUC the error says your proc-macro server (from toolchain) is newer than RA. What's the verion of your RA?

I pulled the source yesterday and built and it looks like it's version 0.0.0

**Comment by spooky-th-ghost** [comment] 2024-02-19 20:18
Just downloaded the release of rust-analyzer from today and i'm still getting the same issue on proc-macros

**Comment by Veykril** [comment] 2024-02-19 20:47
Then it seems like you are still somehow running an outdated server as the release build has the latest server version running.

> I pulled the source yesterday and built and it looks like it's version 0.0.0

source builds always have version 0.0.0

**Comment by benfaerber** [comment] 2024-03-15 01:18
I'm having the same issue on Neovim. 
rustc 1.76.0 (07dca489a 2024-02-04)
rust-analyzer 1.76.0 (07dca48 2024-02-04)

proc macro `Serialize` not expanded: Failed to run proc-macro server from path /home/ben/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/libexec/rust-analyzer-proc-macro-srv, error: Custom { kind: Other, error: "proc-macro server's api version (3) is newer than rust-analyzer's (2)" }

I've tried everything, reinstalling, rebooting, replacing the rust-analyzer binary with the latest release.

**Comment by zjp-CN** [comment] 2024-03-15 01:29
@benfaerber FYI if you use LSP plugins in neovim that install RA (say mason),  it's likely not to use RA installed from rustup, which also cause outdated RA with newer toolchain.

**Comment by benfaerber** [comment] 2024-03-15 01:34
> @benfaerber FYI if you use LSP plugins in neovim that install RA (say mason), it's likely not to use RA installed from rustup, which also cause outdated RA with newer toolchain.

OMG I didn't realize that! Thanks for the tip, it fixed it!

**Comment by 790944715** [comment] 2024-04-17 14:04
Is this issue been fixed?
I still encounter this issue with the stable version:
**PS F:\workspace\rust\test-ra> rustup update
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: checking for self-update

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.77.2 (25ef9e3d8 2024-04-09)

info: cleaning up downloads & tmp directories**

Here's the error message, how can I fix this issue in vscode, currently can't find a useful way.
**proc macro `Parser` not expanded: failed to write request: 管道正在被关闭。 (os error 232)**

**Comment by TheRealSmeddy** [comment] 2024-04-24 10:03
Updated rust version, restarted the workspace and extensions, seems to be fixed

**Comment by Zerowalker** [comment] 2024-07-17 04:17
I still get this issue:

```
stable-x86_64-pc-windows-msvc (default)
rustc 1.79.0 (129f3b996 2024-06-10)
---
Version 0.4.2039, Server Version 0.4.2039-standalone (26747bd1e 2024-07-16)
or
Version 0.3.2037, Server Version 0.3.2037-standalone (e9afba57a 2024-07-14)
```

Have updated rust and reloaded the workspace, even restarted vscode to no avail.

**Comment by KiSetsuFu-PuLiN** [comment] 2024-08-26 03:17
Fixed after update VSCode
