### ISSUE TITLE
unresolved macro call on standard library macro.

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust-analyzer#9352] opened 2021-06-21 05:18 UTC
The following code triggers an unresolved macro problem with RA nightly 2021-06-20:

```rust
// main.rs
fn main() {
  println!("sse2: {}", cfg!(target_feature = "sse2"));
  println!("sse3: {}", cfg!(target_feature = "sse3"));
  println!("ssse3: {}", cfg!(target_feature = "ssse3"));
  println!("sse4.1: {}", cfg!(target_feature = "sse4.1"));
  println!("sse4.2: {}", cfg!(target_feature = "sse4.2"));
  println!("runtime rdrand: {}", std::is_x86_feature_detected!("rdrand"));
  println!("runtime rdseed: {}", std::is_x86_feature_detected!("rdseed"));
}
```

Given that I'm building for x86_64 windows, the macro should be in the standard library just fine. Indeed, the program compiles and runs perfectly with `cargo run`, only RA itself is having the hiccup.

**Comment by Veykril** [comment] 2021-06-21 10:33
The macro re-export is gated behind a `simd_x86`, https://github.com/rust-lang/rust/blob/6b354a13820a444f834a33365ae4a8d97d7d27ce/library/std/src/lib.rs#L541-L542.

When is this supposed to be set? Querying the cfg via `rustc --print cfg` for my windows target doesn't list it.

**Comment by bjorn3** [comment] 2021-06-21 11:31
That is a stability marker, not a cfg.

**Comment by Veykril** [comment] 2021-06-21 11:34
Wasn't quite awake yet I suppose 🤦

**Comment by Veykril** [comment] 2021-06-21 11:34
So ye the problem is we can't resolve `std_detect` in `std` it seems.

**Comment by bjorn3** [comment] 2021-06-21 12:24
It probably needs to be added to the list of sysroot crates.

**Comment by jonas-schievink** [comment] 2021-06-21 13:21
stdarch is full of `cfg_if!`, so it probably won't work even then

**Comment by jonas-schievink** [comment] 2021-06-22 12:03
With #9357 the crate is now loaded correctly.

cc https://github.com/rust-analyzer/rust-analyzer/issues/7637 for the `cfg_if!` issue

**Comment by Veykril** [comment] 2022-07-02 17:37
Since this seems to work fine and the `cfg_if!` part is tracked in another issue I believe we can close this.

**Closed by Veykril** 2022-07-02 17:37 UTC
Labels: A-macro
