### ISSUE TITLE
Request textDocument/hover failed.  - request handler panicked: index out of bounds: the len is 1 but the index is 1

### ISSUE THREAD

**Issue by VorpalBlade** [rust-lang/rust-analyzer#14564] opened 2023-04-13 20:01 UTC
As of this week I keep getting an error popup with a reference to look at the rust-analyzer plugin output in VS Code. This happens while I'm editing and doing other stuff. While it is reproducible (I have seen it 10s of times) I'm not sure *what* I'm doing to trigger it, I have not been able to pin it down to any specific action. I *think* it might be happening more often while I scroll the document, but not always.

```
[Error - 21:53:31] Request textDocument/hover failed.
  Message: request handler panicked: index out of bounds: the len is 1 but the index is 1
  Code: -32603 
Panic context:
> 
version: 0.3.1472-standalone
request: textDocument/hover HoverParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/arvid/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/path.rs",
            query: None,
            fragment: None,
        },
    },
    position: Position(
        Position {
            line: 1167,
            character: 11,
        },
    ),
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
}

> impl_trait_query(ImplId(52154) -> ItemLoc { container: ModuleId { krate: Idx::<CrateData>(205), block: None, local_id: Idx::<ModuleData>(1) }, id: ItemTreeId { tree: TreeId { file: HirFileId(2980), block: None }, value: Idx::<Impl>(0) } } -> ImplData { target_trait: None, self_ty: Path(Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("SecretService"))] }, generic_args: Some([Some(GenericArgs { args: [Lifetime(LifetimeRef { name: Name(Text("'a")) })], has_self_type: false, bindings: [], desugared_from_fn: false })]) }), items: [FunctionId(FunctionId(68246)), FunctionId(FunctionId(68247)), FunctionId(FunctionId(68248)), FunctionId(FunctionId(68249)), FunctionId(FunctionId(68250)), FunctionId(FunctionId(68251)), FunctionId(FunctionId(68252))], is_negative: false, attribute_calls: None })

> impl_self_ty_query(ImplId(52154) -> ItemLoc { container: ModuleId { krate: Idx::<CrateData>(205), block: None, local_id: Idx::<ModuleData>(1) }, id: ItemTreeId { tree: TreeId { file: HirFileId(2980), block: None }, value: Idx::<Impl>(0) } } -> ImplData { target_trait: None, self_ty: Path(Normal { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("SecretService"))] }, generic_args: Some([Some(GenericArgs { args: [Lifetime(LifetimeRef { name: Name(Text("'a")) })], has_self_type: false, bindings: [], desugared_from_fn: false })]) }), items: [FunctionId(FunctionId(68246)), FunctionId(FunctionId(68247)), FunctionId(FunctionId(68248)), FunctionId(FunctionId(68249)), FunctionId(FunctionId(68250)), FunctionId(FunctionId(68251)), FunctionId(FunctionId(68252))], is_negative: false, attribute_calls: None })

> DefMap Idx::<CrateData>(205) crate_name=Some(CrateDisplayName { crate_name: CrateName("scopeguard"), canonical_name: "scopeguard" }) block=None path=SecretService

thread 'Worker' panicked at 'index out of bounds: the len is 1 but the index is 1', crates/hir-def/src/nameres/path_resolution.rs:390:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_bounds_check
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:159:5
   3: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro_single
   4: hir_def::resolver::ModuleItemMap::resolve_path_in_type_ns
   5: hir_def::resolver::Resolver::resolve_path_in_type_ns
   6: hir_ty::lower::TyLoweringContext::lower_ty_ext
   7: hir_ty::lower::impl_self_ty_query
   8: salsa::runtime::Runtime::execute_query_implementation
   9: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  10: salsa::derived::slot::Slot<Q,MP>::read
  11: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  12: salsa::QueryTable<Q>::get
  13: <DB as hir_ty::db::HirDatabase>::impl_self_ty
  14: hir_ty::lower::impl_trait_query
  15: salsa::runtime::Runtime::execute_query_implementation
  16: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  17: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  18: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  19: salsa::derived::slot::MemoRevisions::validate_memoized_value
  20: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  21: salsa::derived::slot::Slot<Q,MP>::read
  22: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  23: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate::__shim
  24: hir::Impl::all_for_type
  25: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  26: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  27: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  28: ide::goto_implementation::goto_implementation
  29: std::panicking::try
  30: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  31: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  32: rust_analyzer::handlers::handle_hover
  33: std::panicking::try
  34: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 21:54:07] Request textDocument/hover failed.
  Message: request handler panicked: index out of bounds: the len is 1 but the index is 1
  Code: -32603 
```

**rust-analyzer version**: 0.3.1472-standalone

**rustc version**: rustc 1.68.2 (9eb3afe9e 2023-03-27)

* VSCode 1.77.3-1 (Microsoft official binary release)
* Distro: Arch Linux

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

Not sure: I'm working in a small workspace (3 packages). 

```console
$ cat ~/.cargo/config.toml
[build]
rustc-wrapper = "/usr/bin/sccache"

[net]
git-fetch-with-cli = true

[registries.crates-io]
protocol = "sparse"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]
```

**Comment by Veykril** [comment] 2023-04-13 20:02
Duplicate of #10084

**Comment by Veykril** [comment] 2023-04-13 20:03
Just as a note, if you encounter this specific out of bounds, restarting the server should fix it. (This sometimes happens when youadd new dependencies to your project)

**Closed by Veykril** 2023-04-13 20:02 UTC
Labels: C-bug

**Comment by VorpalBlade** [comment] 2023-04-13 20:07
Ah thanks, that could be it. It is never the same line from panic to panic. Is there anything I can do to help get to the bottom of this weird issue? From skimming the bug you mentioned (that is quite a long thread!) it seems that people are unclear on what the underlying cause is? Is there anything I can do to help with this? Not that I seem to be able to reproduce it right now...

**Comment by Veykril** [comment] 2023-04-13 20:09
We believe it to be a bug in [salsa](https://github.com/salsa-rs/salsa) which is currently being reworked, so not much actionable there
