### ISSUE TITLE
Doc in macro with `concat!` and `stringify!` won't show up

### ISSUE THREAD

**Issue by rodrigocfd** [rust-lang/rust-analyzer#14684] opened 2023-04-29 13:01 UTC
**rust-analyzer version**: 0.3.1489-standalone (bc78ebd9d 2023-04-23)

**rustc version**: 1.69.0 (84c898d65 2023-04-16)

I'm trying to use [this method](https://stackoverflow.com/a/68783193/6923555) for generating dynamic doc within macros:

```rust
macro_rules! my_func {
  ($method:ident, $name:tt) => {
    #[doc = concat!("This is ", stringify!($name), ".")]
    pub fn $method() {}
  };
}

my_func!(foo, "foo");

/// This documentation shows up.
fn another() {}

fn main() {
  foo();
  another();
}
```

Notice the use of [`concat!`](https://doc.rust-lang.org/std/macro.concat.html) and [`stringify!`](https://doc.rust-lang.org/std/macro.stringify.html) to generate the documentation dynamically.

Screenshot 1:

![no-show](https://user-images.githubusercontent.com/1283868/235303692-38d9effe-111c-4e8e-945f-279ad73f0995.png)

Screenshot 2:

![yes-show](https://user-images.githubusercontent.com/1283868/235303712-b3f868b4-c911-4422-ac3c-49a9bd7f7884.png)

**Comment by Veykril** [comment] 2023-04-29 16:36
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/8092

**Closed by Veykril** 2023-04-29 16:36 UTC
Labels: A-macro, C-bug, A-ide
