### ISSUE TITLE
Code action - fill match arm with enum named via "Self" generates already-covered match arm

### ISSUE THREAD

**Issue by RuijieYu** [rust-lang/rust-analyzer#13168] opened 2022-09-02 00:21 UTC
The following is the code snippet I am having the issue.

Before code action:

```rust
#![allow(dead_code)]
enum Enum {
    First,
    Second,
}

impl Enum {
    pub const fn f(&self) -> u8 {
        match self {
            Self::First => 1, // Cursor here
        }
    }
}

fn main() {
    println!("{}", Enum::First.f())
}
```

After code action: 

```rust
#![allow(dead_code)]
enum Enum {
    First,
    Second,
}

impl Enum {
    pub const fn f(&self) -> u8 {
	match self {
            Self::First => 1,
            Enum::First => todo!(), // added by RA
	    Enum::Second => todo!(), // added by RA
	}
    }
}

fn main() {
    println!("{}", Enum::First.f())
}
```

As seen above, the cursor is at the end of `Self::First` line before running the code action.  When I run Code Action > Fill Match Arm, the two match arms in the following two lines are generated by RA.  The expected behavior is to only generate a `Enum::Second` arm, or preferably, a `Self::Second` arm. 

For the record, the code snippet after code action executes successfully, with the warning that the `Enum::First` line is unreachable. 

---

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

```console
$ rust-analyzer --version
rust-analyzer 0.0.0 (e8e598f64 2022-08-28)
```

**rustc version**: (eg. output of `rustc -V`)

```console
$ rustc --version
rustc 1.63.0 (4b91a6ea7 2022-08-08)
```

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
Emacs + lsp, reproducible on a machine with no settings.

**Comment by flodiebold** [comment] 2022-09-02 08:55
Duplicate of #4650

**Closed by flodiebold** 2022-09-02 08:55 UTC
Labels: S-actionable, A-assists, C-bug
