### ISSUE TITLE
`type-mismatch` triggers in macro expansion whenever an input identifier is the same as a hardcoded one and types differ

### ISSUE THREAD

**Issue by repnop** [rust-lang/rust-analyzer#12733] opened 2022-07-09 22:45 UTC
**rust-analyzer version**: rust-analyzer version: 0.0.0 (5342f47f4 2022-07-09)

**rustc version**: rustc 1.62.0 (a8314ef7d 2022-06-27)

**relevant settings**:  none

Reproducing code:
```rust
macro_rules! qux {
    ($n:ident: $t:ty) => {{
        let mut $n: Option<$t> = None;
        Some(1).map(|test| match test {
            0 => $n = None,
            _ => (),
        });

        println!("{:?}", $n);
    }};
}

fn main() {
    qux!(test: String);
}
```
r-a generates `Expected i32, found Option<{unknown}>` yet the code is able to be built and run
```
repnop@snek /t/foo (master)> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
     Running `target/debug/foo`
None
```

I expect this is because `rustc` is tracking the `$n` identifier and is able to properly resolve it to the correct binding, whereas r-a expands the macros and is unable to differentiate between the two

**Comment by flodiebold** [comment] 2022-07-10 11:15
Duplicate of #11681, I think.

**Closed by flodiebold** 2022-07-10 11:15 UTC
