### ISSUE TITLE
'0 implementations' on type nested in fn

### ISSUE THREAD

**Issue by TyPR124** [rust-lang/rust-analyzer#3739] opened 2020-03-27 01:02 UTC
I have the following:

```rust
#[derive(Clone)]
struct Foo;
fn bar() {
    #[derive(Clone)]
    struct Bar;
}
````

which shows '1 implementation' on `Foo` but '0 implementations' on `Bar`. I'm using version 0.2.100 as listed in VSCode.

**Comment by lnicola** [comment] 2020-03-27 06:09
Might be a duplicate of #1559.

**Comment by lnicola** [comment] 2021-01-25 17:47
Blocked on #1559.

**Closed** 2024-03-19 13:27 UTC
Labels: S-actionable
