### ISSUE TITLE
Inlay hint (type is displayed as unknown) do not work for .into() for generics bound to Into<..>

### ISSUE THREAD

**Issue by xvbcfj** [rust-lang/rust-analyzer#17776] opened 2024-08-03 06:58 UTC
<img width="387" alt="Screenshot 2024-08-03 at 12 23 41" src="https://github.com/user-attachments/assets/8d0ebad6-9dd3-4aac-883d-668a10c510b2">

---

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

rust-analyzer version: 0.3.2053-standalone (fd74511f3 2024-07-28)

**rustc version**: (eg. output of `rustc -V`)

rustc 1.82.0-nightly (8e86c9567 2024-08-01)

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable)

v0.3.2053

**code snippet to reproduce**: 
```rust
fn test2<A>(str: A)
where
    A: Into<String>, // does not work
{
    let str = str.into();
    println!("{str}");
}
```

**Comment by flodiebold** [comment] 2024-08-03 07:45
Duplicate of #5514

**Closed by flodiebold** 2024-08-03 07:45 UTC
Labels: C-bug
