### ISSUE TITLE
Bad "Replace match with if let" code action

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust-analyzer#11547] opened 2022-02-25 02:18 UTC
input:

```rust
match chars.next()? {
    '{' => (),
    _ => return None,
};
```

output:

```rust
if let _ = chars.next()? {
    return None
};
```

This changes the code semantics. (In this example, `mut chars: std::str::Chars`.)

**rust-analyzer version**: rust-analyzer version: 02904e99a 2022-02-14 nightly

**rustc version**: rustc 1.60.0-nightly (6abb6385b 2022-01-26)

**relevant settings**: (none relevant)

**Comment by Veykril** [comment] 2022-02-25 09:47
Problem seems to be this part here https://github.com/rust-analyzer/rust-analyzer/blob/f6901c952ec3847ca522c69d4c854e9e0e51d5fe/crates/ide_assists/src/handlers/replace_if_let_with_match.rs#L260
This should say `(pat2, expr2, expr)`

**Comment by hi-rustin** [comment] 2022-03-16 13:01
I am working on this.

**Comment by erhuve** [comment] 2022-06-19 16:12
> Problem seems to be this part here https://github.com/rust-analyzer/rust-analyzer/blob/f6901c952ec3847ca522c69d4c854e9e0e51d5fe/crates/ide_assists/src/handlers/replace_if_let_with_match.rs#L260 This should say `(pat2, expr2, expr)`

I believe the `pat` in `(pat, expr2, expr)` is the shadowed `pat` from the match arm, so it's actually correct. Please correct me if I'm wrong.

I'm unable to reproduce this bug anyways. This is my output:
```
if let '{' = chars.next()? {
        ()
    } else {
        return None
    };
```

**Comment by Veykril** [comment] 2022-06-19 16:26
Oh, this was fixed in https://github.com/rust-lang/rust-analyzer/pull/12467 actually!

**Closed by Veykril** 2022-06-19 16:26 UTC
Labels: E-has-instructions, A-assists, C-bug
