### ISSUE TITLE
Strange semantic hl bug, from recent update.

### ISSUE THREAD

**Issue by OneKnightOnly** [rust-lang/rust-analyzer#12222] opened 2022-05-12 07:43 UTC
**rust-analyzer version**: v0.2.1048

**rustc version**: 1.60.0

Developer: Inspect Editor in vscode shows incorrect semantic tokens with the code below. eg inspect editor thinks the purple 'p'  is a keyword, and the green equals sign is a number.

![SemanticMess](https://user-images.githubusercontent.com/96325194/168017364-1b32e85e-8f27-4f9b-a2d9-c7e127f67e73.png)

Strangely the semantic highlighting works, if you comment out the attribute.

![SemanticWorks](https://user-images.githubusercontent.com/96325194/168017440-adf36040-4b21-4322-992f-ebd030a2e12e.png)

https://github.com/microsoft/vscode/issues/149321

**Comment by flodiebold** [comment] 2022-05-12 08:50
Duplicate of #12216 (though this is a simpler reproduction).

**Closed by flodiebold** 2022-05-12 08:50 UTC
Labels: S-actionable, C-bug, A-proc-macro

**Comment by OneKnightOnly** [comment] 2022-05-14 00:08
This issue still hasn't been resolved, even with the new rust analyzer version v0.3.1051
![random](https://user-images.githubusercontent.com/96325194/168402885-08147fa1-4393-491b-8f1e-c552023e9437.png)

**Comment by Veykril** [comment] 2022-05-14 00:26
That is not the new version, the new nightly is building right now and should be published in roughly in an hour assuming the publish doesn't fail spontaneously
