### ISSUE TITLE
println!() inline variables don't work with 'rename symbol'

### ISSUE THREAD

**Issue by 1Dragoon** [rust-lang/rust-analyzer#11503] opened 2022-02-19 02:29 UTC
The new inline variable references for println!() and format!() do not appear to show up as symbols in vscode, so when you right click on the variable name elsewhere and click 'rename symbol', it doesn't rename it inside of the println line. For example:

```rust
let hello_world = "Hello World";
println!("{hello_world}");
```

Renaming hello_world to hello ends up like this:

```rust
let hello = "Hello World";
println!("{hello_world}");
```

Where it should end up like this:

```rust
let hello = "Hello World";
println!("{hello}");
```

**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
rust-analyzer version: 02904e99a 2022-02-14 stable

**rustc version**: (eg. output of `rustc -V`)
rustc 1.58.1 (db9d1b20b 2022-01-20)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
N/A

**Comment by jhgg** [comment] 2022-02-19 04:23
Dupe of #11296

**Closed as completed** 2022-02-19 04:26 UTC
