### ISSUE TITLE
Rust-Analyzer suggesting import in wrong position.

### ISSUE THREAD

**Issue by DasLixou** [rust-lang/rust-analyzer#16686] opened 2024-02-26 18:01 UTC
**rust-analyzer version**: rust-analyzer version: 0.4.1859-standalone (5346002d0 2024-02-25)

**rustc version**: rustc 1.76.0 (07dca489a 2024-02-04)

**code snippet to reproduce**: 
```rust
// lib.rs
type Test = u32;
type Other = u32;
// other.rs
#[cfg(debug)]
fn test() -> Result<(), Test> {
    use crate::Other;
    Ok(())
}
```
Note that `Test` is not imported yet.
When you now use the import on Test, it autofills to:
```rs
#[cfg(debug)]
fn test() -> Result<(), Test> {
    use crate::{Test, Other};
    Ok(())
}
```
where it still can't find `Test`

**Comment by lnicola** [comment] 2024-02-26 20:52
Duplicate of #9391.

**Closed by lnicola** 2024-02-26 20:52 UTC
Labels: C-bug
