### ISSUE TITLE
Incorrect `type-mismatch` in certain code involving trait objects

### ISSUE THREAD

**Issue by brennanvincent** [rust-lang/rust-analyzer#12980] opened 2022-08-08 20:55 UTC
Rust-analyzer emits a `type-mismatch` error for this code, which is accepted by `rustc`:

```
pub fn f(mut client: postgres::Client, stmt: postgres::Statement) {
    client.query_one(&stmt, &[&0]).unwrap();
}
``` 

`query_one` takes `&[&(dyn ToSql + Sync)]`, and `i32` is indeed both `ToSql` and `Sync`, so this should be allowed, but r-a reports `expected &(dyn ToSql + Sync), found &i32 [type-mismatch]`.

Note that you must have `postgres = "0.19.3"` in Cargo.toml to reproduce this. I do not know how to reproduce this without depending on the postgres crate. I tried creating a similar thing without dependencies but the issue did not reproduce.

**rust-analyzer version**: rust-analyzer 0.0.0 (a02b042ae 2022-08-03)

**rustc version**: rustc 1.62.0 (a8314ef7d 2022-06-27)

**relevant settings**: emacs lsp-mode with `'(lsp-rust-analyzer-proc-macro-enable t)`

**Comment by flodiebold** [comment] 2022-08-08 21:28
Duplicate of #11847

**Closed by flodiebold** 2022-08-08 21:28 UTC
