### ISSUE TITLE
Imports inserted inside of `cfg`ed function when that scope is too small

### ISSUE THREAD

**Issue by kpreid** [rust-lang/rust-analyzer#16215] opened 2023-12-30 04:15 UTC
Given this code:

```rust
mod foo {
    pub struct Foo {}
}

mod bar {
    #[cfg(feature = "enabled_feature")]
    fn use_foo(_: Foo) {} // cannot find type `Foo` in this scope
}
```

Activating the "Import `crate::foo::Foo`" assist produces this code:

```rust
mod bar {
    #[cfg(feature = "enabled_feature")]
    fn use_foo(_: Foo) {
        use crate::foo::Foo;
    }
}
```

This import is in the wrong place to help since imports in the function body do not apply to its parameter list. A better fix would be:

```rust
mod bar {
    #[cfg(feature = "enabled_feature")]
    use crate::foo::Foo;

    #[cfg(feature = "enabled_feature")]
    fn use_foo(_: Foo) {}
}
```

**rust-analyzer version**: 0.3.1782-standalone (85fb463fc 2023-12-24)

**rustc version**: rustc 1.75.0 (82e1608df 2023-12-21)

**Comment by Veykril** [comment] 2024-01-01 14:34
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/9391

**Closed by Veykril** 2024-01-01 14:34 UTC
Labels: C-bug
