### ISSUE TITLE
Type inference issues with IntoIterator 

### ISSUE THREAD

**Issue by cynecx** [rust-lang/rust-analyzer#11242] opened 2022-01-09 20:57 UTC
```rust
#[test]
fn double_into_iter() {
    check_types(
        r#"
//- /main.rs crate:main deps:core
use core::iter::IntoIterator;

fn intoiter_issue<A, B>(foo: A)
where
    A: IntoIterator<Item = B>,
    B: IntoIterator<Item = usize>,
{
    for x in foo {
    //  ^ B
        for m in x {
        //  ^ usize
        }
    }
}

//- /core.rs crate:core
pub mod iter {
    pub trait Iterator {
        type Item;
    }

    pub trait IntoIterator {
        type Item;
        type IntoIter: Iterator<Item = Self::Item>;
        // #[lang = "into_iter"]
        fn into_iter(self) -> Self::IntoIter;
    }

    // Uncomment this impl and type inference/test works/passes.
    impl<I: Iterator> IntoIterator for I {
        type Item = I::Item;
        type IntoIter = I;

        fn into_iter(self) -> I {
            self
        }
    }
}
"#,
    );
}
```
**rust-analyzer version**: 0f8c96c92689af8378dbe9f466c6bf15a3a27458 (current master)

**rustc version**: rustc 1.60.0-nightly (a7e2e3396 2022-01-08)

```
thread 'tests::traits::double_into_iter' panicked at 'assertion failed: `(left == right)`
  left: `"{unknown}"`,
 right: `"B"`',
```

Something weird is going on here because it works without the `impl<I: Iterator> Iterator for I` impl.

**Comment by jhgg** [comment] 2022-01-10 05:56
Dupe of #10653 / #9990

**Comment by flodiebold** [comment] 2024-02-15 19:05
Yeah, duplicate of #10653

**Closed by flodiebold** 2024-02-15 19:05 UTC
Labels: A-ty, C-bug
