### ISSUE TITLE
Variable Type Derivation Bug

### ISSUE THREAD

**Issue by A4-Tacks** [rust-lang/rust-analyzer#15063] opened 2023-06-16 13:27 UTC
**rust-analyzer version**: `rust-analyzer 1.70.0 (90c54180 2023-05-31)` and `rust-analyzer 1.72.0-nightly (114fb86c 2023-06-15)`

**rustc version**: `rustc 1.70.0 (90c541806 2023-05-31)` and `rustc 1.72.0-nightly (114fb86ca 2023-06-15)`

**relevant settings**: NO_SETTINGS

```rust
fn _foo<I, I1>(source: I)
where I: IntoIterator<Item = char>,
      I1: IntoIterator<Item = usize>
{
    for _ch in source {
        // _ch: {unknown}
    }
}
fn _bar<I, I1>(source: I)
where I: IntoIterator<Item = char>,
{
    for _ch in source {
        // _ch: char
    }
}
fn _moo<I, I1>(source: I)
where I: IntoIterator<Item = char>,
      I1: IntoIterator<Item = usize>
{
    for _ch in source {
        let _: char = _ch;
        // _ch: char
    }
}
```

**Comment by lowr** [comment] 2023-06-16 14:38
Thanks for the report -- this is a duplicate of #10653 that needs to be solved in an upstream library: rust-lang/chalk#750. Closing as a duplicate.

**Closed by lowr** 2023-06-16 14:38 UTC
Labels: C-bug
