### ISSUE TITLE
From version `2024-02-19` VS Code hangs on `building proc-macros: app_name`

### ISSUE THREAD

**Issue by frederikhors** [rust-lang/rust-analyzer#16605] opened 2024-02-19 16:50 UTC
After upgrading from 2024-02-12 version to 2024-02-19 on my Windows PC and after a `cargo clean` VS Code hangs on:

`building proc-macros: app_name`

**rustc version**: `rustc 1.76.0 (07dca489a 2024-02-04)`

**Comment by Veykril** [comment] 2024-02-19 17:17
This will need more info to be reproducible. Anything interesting in the logs? Any specific crates that this happens with?

**Comment by Veykril** [comment] 2024-02-20 14:13
Closing as duplicate of https://github.com/rust-lang/rust-analyzer/issues/16614

**Closed by Veykril** 2024-02-20 14:13 UTC
Labels: C-bug
