### ISSUE TITLE
associated type is unresolved when trait path is qualified.

### ISSUE THREAD

**Issue by jhgg** [rust-lang/rust-analyzer#11973] opened 2022-04-13 06:46 UTC
```rust
fn main() {}

trait T1 {
    type Bar;
    type Baz;
}

struct Foo;

mod t2 {
    pub trait T2 {
        type Bar;
    }
}

use t2::T2;

impl T2 for Foo {
    type Bar = String;
}

impl T1 for Foo {
    type Bar = <Foo as t2::T2>::Bar;
    //                          ^^^ unresolvedReference
    type Baz = <Foo as T2>::Bar;
    //                      ^^^ typeAlias
}
```

When `T2` is used as `t2::T2`, `Bar` is unresolved, but when using `T2` directly by getting it in scope w/ `use t2::T2;`, it is resolved properly. 

rust-analyzer version: 14c86d5d3 2022-04-13 dev
rustc 1.60.0 (7737e0b5c 2022-04-04)

**Comment by lnicola** [comment] 2022-04-13 06:48
Probably dupe of #8282.

**Comment by jhgg** [comment] 2022-04-13 06:49
I swear I searched 🤣

**Comment by jhgg** [comment] 2022-04-13 06:51
I don't think this is the same issue though, because 8282 has the trait in scope, where as this issue refers to it having a qualified path for the trait. I'll reopen but feel free to close  if it is indeed dupe.

**Comment by bitgaoshu** [comment] 2022-04-24 13:54
I think the two is same. the both try to resolve a path fully. and the last segment is a assoc of trait.

**Comment by bitgaoshu** [comment] 2022-04-24 14:04
the diff is need to fix different method

**Closed** 2022-04-25 11:15 UTC
Labels: S-actionable, A-nameres, C-bug
