### ISSUE TITLE
Rust Analyzer "show references" fails to display as link when there are a LOT of references.

### ISSUE THREAD

**Issue by laundmo** [rust-lang/rust-analyzer#12087] opened 2022-04-26 15:45 UTC
When Rust-Analyzer in VSCode tries to show a lot of references in the hover popup, the formatting breaks leading to a enourmous block of url-encoded string.

![image](https://user-images.githubusercontent.com/24855949/165339159-dd24a440-e113-42cc-b290-70c2583e387f.png)

https://user-images.githubusercontent.com/24855949/165339346-53dd9552-2a08-4042-a066-f5954ae4c53a.mp4

dependencies used in example: [bevy](https://crates.io/crates/bevy), though any crate with a sufficiently large amount of references for something should work.

example code used, this was the easiest way to get this issue to show up, i am aware that the code would not run.
```rust
fn main() {
    let s: String = vec![0.0, 0.0].into();
}
```

**rust-analyzer version**: rust-analyzer version: b5d7a712e 2022-04-25 stable

**rustc version**: rustc 1.62.0-nightly (34a6c9f26 2022-04-13)

**Comment by Veykril** [comment] 2022-04-26 17:56
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/9926

**Closed by Veykril** 2022-04-26 17:56 UTC
