### ISSUE TITLE
Type inference regression with `TryFrom` bounds.

### ISSUE THREAD

**Issue by Greatness7** [rust-lang/rust-analyzer#17783] opened 2024-08-04 10:00 UTC
The iterator method below used to work fine, but recently type inference began to fail. Now it only shows `value: &{unknown}` and autocomplete/highlighting/etc are not available. It is making working with certain crates very unpleasant.

The method takes an iterator over enum values and uses `filters_map` and `try_into` to yield only those of a specific variant.

The last version of rust-analyzer where the type inference worked was `v0.3.2020`.

---

**rust-analyzer version**: `rust-analyzer version: 0.3.2053-standalone (fd74511f3 2024-07-28)`

**rustc version**: `rustc 1.80.0 (051478957 2024-07-21)`

**editor or extension**: `VSCode`

**code snippet to reproduce**: 
```rust
enum Value {
    Char(char),
    // Additional variants omitted for brevity.
}

impl<'a> TryFrom<&'a Value> for &'a char {
    type Error = ();

    fn try_from(value: &'a Value) -> Result<Self, Self::Error> {
        match value {
            Value::Char(value) => Ok(value),
        }
    }
}

struct Data {
    values: Vec<Value>,
}

impl Data {
    fn values_of_type<'a, T>(&'a self) -> impl Iterator<Item = &'a T>
    where
        &'a T: 'a + TryFrom<&'a Value>,
    {
        self.values.iter().filter_map(|value| value.try_into().ok())
    }
}

fn main() {
    let data = Data {
        values: vec![Value::Char('a')],
    };

    for value in data.values_of_type::<char>() {
        // rust analyzer fails to infer the type of `value`
        println!("{value}");
    }
}
```

**Comment by flodiebold** [comment] 2024-08-04 12:46
Works for me, I think this is a duplicate of #17734 which got fixed by #17747.

**Closed by flodiebold** 2024-08-04 12:46 UTC
Labels: A-ty, C-bug, A-chalk
