### ISSUE TITLE
Please bring back decimal format for memory layout numbers

### ISSUE THREAD

**Issue by KSXGitHub** [rust-lang/rust-analyzer#14928] opened 2023-05-30 04:44 UTC
When I hover my mouse over a type definition of a non-generic type, the following text appear:

```
// size = 0xC8, align = 0x8
```

The problem is, I don't understand how much is `0xC8` without typing it to a calculator.

## Suggestion

The enum variants show both, so should the memory layout numbers:

```
// size = 200 (0xC8), align = 8 (0x8)
```

**Comment by lnicola** [comment] 2023-05-30 05:54
Dupe of #14918.

**Closed by lnicola** 2023-05-30 05:54 UTC
Labels: C-feature
