### ISSUE TITLE
core::intrinsics::size_of is suggested instead of core::mem::sizeof

### ISSUE THREAD

**Issue by giluis** [rust-lang/rust-analyzer#16172] opened 2023-12-20 22:55 UTC
When `size_of::<u128>()` is typed, code suggestions /intellisense show `core::intrinsics::size_of` is shown before `core::mem::size_of`. Since the former is unstable and requires adding `!#[feature (...)]` and the latter is stable and, generally, a better choice for most programmers,  I believe `core::intrinsics::size_of`should be second in the code suggestions / intellisense pane, yielding the first place to `core::mem::size_of`.
The same thing happens for `size_of_val::<u128>()`. The type provided as generic argument seems to *not* interfere with the observed behaviour

Thank you and let me know if there is anything I can do to improve this bug report :)

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

The command suggested above shows nothing in any panel I can check on VS-Code. However, my version seems to be v0.3.1774
![image](https://github.com/rust-lang/rust-analyzer/assets/52404649/d651c002-03e5-43b5-babf-7b93301e203b)

**rustc version**: (eg. output of `rustc -V`)
rustc 1.75.0-nightly (1c05d50c8 2023-10-21)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
None relevant, I think

**Comment by lnicola** [comment] 2023-12-21 07:03
Duplicate of #14077

**Closed by lnicola** 2023-12-21 07:03 UTC
Labels: C-bug
