### ISSUE TITLE
How to get real time cargo check editing experience without "manually check on save"?

### ISSUE THREAD

**Issue by Wyvern** [rust-lang/rust-analyzer#10119] opened 2021-09-02 11:00 UTC
Hi, I previously used rust official extension, it could always check / watch my editing .rs files and give results immediately.

After switch to rust-analyzer I lost this capability, always need "check on save"; it's not good for general users.

Is there  a way to get always check function, or how to config/set to activate it?

**Comment by bjorn3** [comment] 2021-09-02 11:11
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/3107

tl;dr: rls used an unstable compiler api to provide rustc with the contents of the files as provided by the editor. Rust-analyzer doesn't use unstable api's, so it has to use `cargo check`, which requires the files to be saved on the disk.

**Comment by lnicola** [comment] 2021-09-02 11:12
Syntax errors and other diagnostics are already refreshed during editing. If you want the full `rustc` diagnostics set, you can save periodically, or you can [configure your editor](https://github.com/rust-analyzer/rust-analyzer/issues/6591#issuecomment-781353173) to save the files automatically (at the cost of some CPU usage).

Full on-the-fly diagnostics are tracked in #3107.

**Closed as completed by bjorn3** 2021-09-02 11:11 UTC
