### ISSUE TITLE
rust-analyzer.check.workspace = false is ignored on server startup

### ISSUE THREAD

**Issue by BaxHugh** [rust-lang/rust-analyzer#18141] opened 2024-09-18 17:53 UTC
`"When rust-analyzer.check.workspace" : false` is set I expect that cargo check should only be run on the rust crate which I have open in vs code. However, rust-analyzer runs cargo check across all workspace members [[edit] when the server is first started. After which saving a file shows that check is only run on the crate which is opened.]
This is a problem as I am working in a mono repo which has many member crates: when I'm working in one, where VS Code is only open at the member crate's manifest directory, the rust-analyzer is slow [[edit] to start] as it is unnecessarily checking all the workspace crates.

I have reproduced this problem in a simple toy workspace.

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
rust-analyzer 0.3.2112-standalone

**rustc version**: (eg. output of `rustc -V`)
rustc 1.77.0 (aedd173a2 2024-03-17)

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable)
VSCode version 1.93.1 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40 x64
rust-analyzer extension: v0.3.2112

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`) 
in .vscode/settings.json for the workspace (user level settings.json file removed)
"rust-analyzer.check.workspace": false,

**code example to reproduce**: 
To reproduce, please see the zipped demo project: [ra-workspace-issue-demo.zip](https://github.com/user-attachments/files/17048216/ra-workspace-issue-demo.zip)

This has the structure
```
./
├── bar
│   ├── Cargo.toml
│   └── src
│       └── lib.rs
├── Cargo.lock
├── Cargo.toml
└── foo
    ├── Cargo.toml
    └── src
        └── lib.rs
```
i.e. a Cargo workspace with two workspace.member crates which do not depend on each other.
In both lib.rs files, I have called a non existent function such that `cargo check` reports an error.

If I open, say, the foo crate: `code ./foo` in the problems panel, I can clearly see that rust-analyzer has reported problems in the foo crate which is not open in VS Code. (similarly I can confirm by introducing a build.rs file with panics, and the rust-analyzer output shows the error when it has built the crate it should not be running check on).

![Image](https://github.com/user-attachments/assets/53296330-bc81-4939-8d3f-dceacb06bf13)
**Screenshot showing that problems from both the foo and bar crate are being reported, despite only foo being open**

[edit]
![Image](https://github.com/user-attachments/assets/1d8e9817-f24a-44f1-8663-18ef310b29dc)
**Screenshot showing that after a save, only problems from the open crate are reported**

**Comment by ChayimFriedman2** [comment] 2024-09-18 19:30
I cannot reproduce. Initially rust-analyzer indeed checks all packages, but when editing and saving it checks only one.

**Comment by BaxHugh** [comment] 2024-09-18 22:52
Thanks for the feedback @ChayimFriedman2. When you say initially rust-analyzer checks all packages. Do you agree that, that is not the desired behaviour?
check.workspace = false specifies that the --workspace flag is not passed, but instead -p=crate is. If the -p argument is passed all along, then cargo check should never be run on anything but the single crate which is opened. That is how I understand it.

**Comment by BaxHugh** [comment] 2024-09-19 08:02
@ChayimFriedman2 I can confirm that I see the same behaviour as you. The screenshot showing both problems is after first restarting the RA server. Once I save a file, the problems listed reduce to just the crate that is open.

I'll update the original post to reflect this.

However, RA checking the whole workspace on startup is still a problem for me, as there are a lot of crates and deps in the workspace, and starting the server takes a long time, after opening the project in VSCode.

**Comment by alibektas** [comment] 2024-10-10 21:47
@afroozeh  Yes, we did it exactly like you describe. See #17912 

> In very deep crates, it takes quite some time to check things on each save

If this wasn't the case before, then it indicates that we did something wrong.

**Comment by alibektas** [comment] 2024-10-10 22:22
You may want to make sure that you have your rust-analyzer up-to-date. There was previously an issue with which crates we ran our flycheck on but #18197 hopefully resolved. If your rust-analyzer is indeed a more recent version, I will check if there are other cases where this issue persists but I highly doubt that.

**Comment by alibektas** [comment] 2024-10-10 23:21
> [@alibektas](https://github.com/alibektas) my RustAnalyzer is up to date. if you're now running cargo check on the current crate and all dependent crates, it's going to be slow for live editing for very deep crates in the dependency graph. I want an option that runs `cargo check` just for a single crate, i.e., `cargo check -p <current_crate>`. 

Let me get back to you with this in a few days. I am rewriting most of the `cargo check` logic. 

> Again to double check, Is this the case when `rust-analyzer.check.workspace` is `false`? Or `false` means check the current crate and all dependent crates?

`true` : Add `--workspace` to `cargo check`
`false` : Add `-p <package_name>`

**Comment by davidbarsky** [comment] 2024-10-11 16:29
> And pardon my ignorance but I thought that RustRover uses IntellijRust or is it now possible to use both of them?

Not without some active work: while it is possible to configure a classic, non-Fleet JetBrains IDE to use an arbitrary LSP server, I'm not sure why folks would want to point RustRover at rust-analyzer.

**Comment by alibektas** [comment] 2024-11-12 16:56
@afroozeh hey sorry for the late reply. Honestly, I totally forgot that I wanted to resolve this issue but now the team lead is away and I definitely  want to check with him first before I do it because something doesn't seem right. Sorry for the inconvenience! I made a separate issue you can check it out the updates

**Comment by TheColorRed** [comment] 2024-11-26 16:02
I am not sure if this is related, but I have the following in my `settings.json`:

```json
{
  "rust-analyzer.check.workspace": false
}
```

When I save a file, in a large project (e.g. `packages/packages-a/main.rs`), it takes a few minutes to run the check.

However, if I run the following in the command line for that same project, it takes one second or less:

```sh
cargo check -p packages-a
```

**Comment by ChayimFriedman2** [comment] 2024-11-26 16:15
Did you run the commands one after the other?

**Comment by TheColorRed** [comment] 2024-11-26 16:18
I did the following:

- Save same file two times in a row (both times ran 1+ minutes)
- Run save (ran 1+ minutes) then run in terminal (ran under 1 second)
- Run save in the terminal two times in a row (both ran under 1 second)

**Comment by alibektas** [comment] 2024-11-26 16:38
I am waiting for the project leas to be online again which will happen either tomorrow or the day after. After that it will be resolved in no time. Once again terribly sorry for the inconvenience.

**Comment by ChayimFriedman2** [comment] 2024-11-26 16:39
Ah it's probably https://github.com/rust-lang/rust-analyzer/pull/18197, you don't have a target set (like the default). @alibektas I get a headache every time I try to think if we should have `&&` or `||`, but are you sure `&&` is the correct call?

**Comment by alibektas** [comment] 2024-11-26 16:42
> Ah it's probably https://github.com/rust-lang/rust-analyzer/pull/18197, you don't have a target set (like the default). @alibektas I get a headache every time I try to think if we should have `&&` or `||`, but are you sure `&&` is the correct call?

I was sure back then can't say I am sure now. Let me have a look again.

**Comment by ChayimFriedman2** [comment] 2024-11-26 17:01
@afroozeh Save a bin file (or test (integration)/example/bench).

**Comment by ChayimFriedman2** [comment] 2024-11-26 17:19
@afroozeh Yeah, `[lib]` is where this doesn't work. Add a `[bin]` target and save it.

**Comment by ChayimFriedman2** [comment] 2024-11-26 17:21
Given that this is not the same problem as OP's, I opened a new issue about this: #18562, please use it for discussions.

**Comment by ChayimFriedman2** [comment] 2024-11-26 17:25
@afroozeh Please discuss this in the new issue.

**Comment by mhnap** [comment] 2024-12-20 13:18
> The current `"rust-analyzer.check.workspace": false` is broken in the sense that it does not do `cargo check -p`. To me it seems like it checks the current package and all dependent ones, and that's why it takes a long time in a large project. This was working fine a couple of months ago, so something has changed. [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/20956650?s=64&amp;u=4c72516b19de7bcf401b6f4618e4f5a8d8410511&amp;v=4">@alibektas](https://github.com/alibektas) Is there any plan to fix this? You created a new issue but that seems to be just there without any activity.

I still have the same issue on `v0.3.2220`. @afroozeh @TheColorRed Maybe someone also tried to update to the latest release and check this again?

**Comment by mhnap** [comment] 2024-12-20 14:59
> Recently, I'm also observing issues with `rust-analyzer.check.workspace" : false`. It just checks the current crate and all the dependent crates on it. In very deep crates, it takes quite some time to check things on each save. Before, it was just changing the current crate. Has something changed recently in the behavior of this setting?

@afroozeh Do you remember the version you used when it was working as expected?

**Comment by mhnap** [comment] 2024-12-20 15:22
> Not exactly, but it was some times in September 2024...

Hmm, I've switched 4 months back, but I still have the same problem (it checks the current crate and all the dependent crates on it). Or maybe I have wrong config 🤔
```
	"rust-analyzer.cargo.allTargets": false,
	"rust-analyzer.check.allTargets": false,
	"rust-analyzer.check.workspace": false,
	"rust-analyzer.checkOnSave": false,
```

**Closed** 2024-12-22 12:25 UTC
Labels: C-bug
