### ISSUE TITLE
Assist: Add return type to existing tuple return type

### ISSUE THREAD

**Issue by Jesse-Bakker** [rust-lang/rust-analyzer#15339] opened 2023-07-26 12:45 UTC
When writing or refactoring functions, I often realize mid-way through that I need an extra return type. It would be great if there was an assist for this.

Example:

```rust
fn foo() -> (u32,) {
    (2u32, 3u32)
//         ^^^^ ---- Mismatched types
}
```
->

```rust
fn foo() -> (u32, u32) {
    (2u32, 3u32)
}
```

This is especially useful when working with complex types. Currently, this can be worked around by removing the return type from the function signature and then applying the `add_return_type` assist to re-add the return type with the additional type.

**Comment by lnicola** [comment] 2023-07-26 13:15
I guess this could more generally be "update return type to match expression".

**Comment by lowr** [comment] 2023-07-27 07:34
Duplicate of #14616?

**Closed** 2023-07-27 07:45 UTC
Labels: A-diagnostics, C-feature
