### ISSUE TITLE
Auto Closing Angle Brackets inserts a literal '$0'

### ISSUE THREAD

**Issue by rdxdkr** [rust-lang/rust-analyzer#16093] opened 2023-12-11 17:03 UTC
When trying out the new setting for auto closing angle brackets in VS Code, as soon as I type a '<' the extension writes '$0>' and the caret is moved to the right of the '>', which is not what I would be expecting.

Example: just write `Vec::<` and it gets completed to `Vec::<$0>`.

**rust-analyzer version**: `0.3.1766-standalone (457b966b1 2023-12-10)`

**rustc version**: `1.74.1 (a28077b28 2023-12-04)`

**VS Code version**: `1.85.0 af28b32d7e553898b2a91af498b1fb666fdebe0c x64`

**relevant settings**: `"rust-analyzer.typing.autoClosingAngleBrackets.enable": true`

**Comment by Veykril** [comment] 2023-12-11 17:08
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/14054

**Closed by Veykril** 2023-12-11 17:08 UTC
Labels: C-bug
