### ISSUE TITLE
thread 'Worker' panicked at 'invalid offset'

### ISSUE THREAD

**Issue by xxshady** [rust-lang/rust-analyzer#14792] opened 2023-05-12 21:08 UTC
Error `Request textDocument/inlayHint failed` appears immediately after opening rs file: https://github.com/xxshady/panic-repro

**rust-analyzer version**: 0.3.1506-standalone (833d5301d 2023-05-07)

**rustc version**: 1.69.0

**relevant settings**: happens without any extensions installed in VSCode

Full error from log:
```
[Error - 12:11:08 AM] Request textDocument/inlayHint failed.
  Message: request handler panicked: invalid offset
  Code: -32603 
Panic context:
> 
version: 0.3.1506-standalone (833d5301d 2023-05-07)
request: textDocument/inlayHint InlayHintParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/c%3A/dev/rust/altv-rust/example_resource/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 15,
            character: 0,
        },
    },
}

thread 'Worker' panicked at 'invalid offset', lib\line-index\src\lib.rs:148:35
stack backtrace:
   0:     0x7ff781389314 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff781389314 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff781389314 - std::sys_common::backtrace::_print_fmt
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\sys_common\backtrace.rs:65
   3:     0x7ff781389314 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\sys_common\backtrace.rs:44
   4:     0x7ff77ff7b72b - core::fmt::write
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\fmt\mod.rs:1232
   5:     0x7ff7813832f1 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\io\mod.rs:1684
   6:     0x7ff78138904b - std::sys_common::backtrace::_print
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\sys_common\backtrace.rs:47
   7:     0x7ff78138904b - std::sys_common::backtrace::print
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\sys_common\backtrace.rs:34
   8:     0x7ff78138cc97 - std::panicking::default_hook::closure$1
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\panicking.rs:271
   9:     0x7ff78138c927 - std::panicking::default_hook
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\panicking.rs:290
  10:     0x7ff78139d31c - std::thread::local::LocalKey<T>::with::h43dc39a522223d23
  11:     0x7ff78138d560 - alloc::boxed::impl$47::call
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\alloc\src\boxed.rs:2001
  12:     0x7ff78138d560 - std::panicking::rust_panic_with_hook
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\panicking.rs:696
  13:     0x7ff78138d2b6 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\panicking.rs:583
  14:     0x7ff78138a8a9 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\sys_common\backtrace.rs:150
  15:     0x7ff78138cf54 - std::panicking::begin_panic_handler
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\panicking.rs:579
  16:     0x7ff781452a15 - core::panicking::panic_fmt
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\panicking.rs:64
  17:     0x7ff77ff78c60 - core::panicking::panic_display<ref$<str$> >
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\panicking.rs:147
  18:     0x7ff77ff78c0b - core::panicking::panic_str
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\panicking.rs:131
  19:     0x7ff7814529d9 - core::option::expect_failed
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\option.rs:2045
  20:     0x7ff781053ec1 - rust_analyzer::to_proto::position::h65a28963eaa9ce13
  21:     0x7ff78105eac4 - rust_analyzer::to_proto::location::h8cb00423ac34b2e3
  22:     0x7ff781228a07 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::hff365fa599a2b4d0
  23:     0x7ff7810e03d2 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::hce7488ae834f208d
  24:     0x7ff78108835d - core::iter::adapters::try_process::hbbb30cc54f4be886
  25:     0x7ff78105c4c1 - rust_analyzer::to_proto::inlay_hint::h93dc2b0d3d733c87
  26:     0x7ff7810c99b1 - alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter::hc2169c9cb51c0325
  27:     0x7ff781087ff5 - core::iter::adapters::try_process::h2b6a466558d6cf1e
  28:     0x7ff7811df0bc - rust_analyzer::handlers::request::handle_inlay_hints::haee54c37a9a3e596
  29:     0x7ff78113e1a5 - std::panicking::try::h9bbdcb2fe10f31d2
  30:     0x7ff780fecd85 - <F as threadpool::FnBox>::call_box::hd4c229b668edb66b
  31:     0x7ff7813f7faf - std::sys_common::backtrace::__rust_begin_short_backtrace::h5b5b955995361fb6
  32:     0x7ff7813fa49a - std::thread::Builder::spawn::hace45a994920b741
  33:     0x7ff78139a57c - alloc::boxed::impl$45::call_once
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\alloc\src\boxed.rs:1987
  34:     0x7ff78139a57c - alloc::boxed::impl$45::call_once
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\alloc\src\boxed.rs:1987
  35:     0x7ff78139a57c - std::sys::windows::thread::impl$0::new::thread_start
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\sys\windows\thread.rs:56
  36:     0x7fff2d4126ad - BaseThreadInitThunk
  37:     0x7fff2df8a9f8 - RtlUserThreadStart
```

**Comment by xxshady** [comment] 2023-05-12 21:12
Updated full error log with `RUST_BACKTRACE=full`

**Comment by MarkSwanson** [comment] 2023-05-13 03:42
Dupe of #14637

**Comment by xxshady** [comment] 2023-05-13 09:37
@MarkSwanson by backtrace its not looks like it is the same, is it?

**Comment by Veykril** [comment] 2023-05-13 10:13
Most likely caused by https://github.com/rust-lang/rust-analyzer/pull/14733

**Comment by Veykril** [comment] 2023-05-13 10:19
@MarkSwanson your comment in the linked issue is in fact this issue. The original report there is a different panic though.

**Comment by MarkSwanson** [comment] 2023-05-13 22:58
Is hiding people's comments the best way to work through issues? 
All I said was <quote>Dupe of #14637 </quote>

**Comment by androxylo** [comment] 2023-05-30 14:42
```
thread 'Worker' panicked at 'invalid offset', lib/line-index/src/lib.rs:148:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:147:5
   3: core::panicking::panic_str
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:131:5
   4: core::option::expect_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/option.rs:2045:5
   5: rust_analyzer::to_proto::position
   6: rust_analyzer::to_proto::location
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   9: core::iter::adapters::try_process
  10: rust_analyzer::to_proto::inlay_hint
  11: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  12: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  13: core::iter::adapters::try_process
  14: rust_analyzer::handlers::request::handle_inlay_hints
  15: std::panicking::try
  16: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 2:39:16 PM] Request textDocument/inlayHint failed.
  Message: request handler panicked: invalid offset
  Code: -32603 
```

**Comment by Veykril** [comment] 2023-05-30 17:25
The repro of OP does not reproduce for me. I looked through all the relevant parts where we construct LocationLinks and they all seem fine so this needs a reproduction. Additionally, for people that run into this, if you can't manage to make a minimal reproduction please share the inlay hint kinds you have enabled and if possible, try to minimize those to the offending kind at least. That would help in figuring this out.

**Comment by xxshady** [comment] 2023-05-31 23:51
Here is the minimal repro i can get for this: https://github.com/xxshady/panic-repro
Additional info: when expanding all the proc macros used there and pasting the result directly into the code everything works fine without any panic

**Comment by Veykril** [comment] 2023-06-01 07:38
Yup, that helped figure out the cause, thanks!

**Closed** 2023-06-01 09:34 UTC
Labels: Broken Window, C-bug, I-panic

**Comment by xxshady** [comment] 2023-06-01 13:14
What about https://github.com/rust-lang/rust-analyzer/issues/14637?

**Comment by Veykril** [comment] 2023-06-01 13:29
That could be the same cause (as it was opened a week after the include token mapping changes)

**Comment by xxshady** [comment] 2023-06-01 17:03
Tho it's also reproducable on the panic-repro repository I did
