### ISSUE TITLE
type-mismatch false positives in `rust-lang/rust`: expected &dyn Display, found &i32

### ISSUE THREAD

**Issue by Zalathar** [rust-lang/rust-analyzer#14724] opened 2023-05-03 04:55 UTC
When I open the Rust compiler's `compiler/rustc_mir_transform/src/coverage/debug.rs` in VSCode with rust-analyzer, I see two type errors that don't appear when building normally at the command-line:

- expected &dyn Display, found &i32 _rust-analyzer (type-mismatch) [Ln 642, Col 68]_
- expected &dyn Display, found &i32 _rust-analyzer (type-mismatch) [Ln 743, Col 67]_

These appear to be false positives, since `&i32` should convert to `&dyn Display` automatically.

I can work around the problem locally by manually changing the source code from `&0` to `&0 as _`.

----

**rust-analyzer version**: 0.3.1498-standalone (3a27518fe 2023-04-30)

**rustc version**: Bootstrap compiler provided by `x.py`

**relevant settings**: Using the compiler's `rust_analyzer_settings.json`, modified with `--build-dir=_build-rust-analyzer`

**Comment by Zalathar** [comment] 2023-05-03 05:19
The affected lines:

https://github.com/rust-lang/rust/blob/71af5c4074cf1993551c10d8e4a1d6da9c27ce33/compiler/rustc_mir_transform/src/coverage/debug.rs#L642-L643

https://github.com/rust-lang/rust/blob/71af5c4074cf1993551c10d8e4a1d6da9c27ce33/compiler/rustc_mir_transform/src/coverage/debug.rs#L743-L744

`create_dump_file` is defined here:

https://github.com/rust-lang/rust/blob/71af5c4074cf1993551c10d8e4a1d6da9c27ce33/compiler/rustc_middle/src/mir/pretty.rs#L245-L262

**Comment by lnicola** [comment] 2023-05-03 05:25
Duplicate of #11847

**Closed by lnicola** 2023-05-03 05:25 UTC
Labels: A-ty, C-bug
