### ISSUE TITLE
Incorrect signature in documentation tooltip of Option::and_then()

### ISSUE THREAD

**Issue by vincentisambart** [rust-lang/rust-analyzer#12084] opened 2022-04-26 10:34 UTC
As you can see on the screenshot below, when the cursor is on the parameter of [`Option::and_then()`](https://doc.rust-lang.org/std/option/enum.Option.html#method.and_then), the tooltip says the parameter is `f: Option<T>` even though it's `f: F` (`F` being a template parameter with `F: FnOnce(T) -> Option<U>`).
<img width="574" src="https://user-images.githubusercontent.com/34704/165279924-b2120a74-5653-4f2c-9355-3b2b00e47124.png">

Note that the `and_then` completion says `const fn(self, F) -> Option<U>`, with is better (at least you can guess the parameter is a callable and not an `Option`.

**rust-analyzer version**: rust-analyzer version: b5d7a712e 2022-04-25 stable

**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

**Comment by flodiebold** [comment] 2022-04-26 11:19
Duplicate of #12079.

**Closed by flodiebold** 2022-04-26 11:19 UTC
