### ISSUE TITLE
Error `cannot mutate immutable variable` when using itertools

### ISSUE THREAD

**Issue by art-den** [rust-lang/rust-analyzer#16994] opened 2024-04-02 07:37 UTC
**rust-analyzer version**: 0.4.1907-standalone

**rustc version**: rustc 1.77.0 (aedd173a2 2024-03-17)

**editor or extension**: VSCodium

**code snippet to reproduce**: 
```rust
fn main() {
    // [dependencies]
    // itertools = "0.12"

    use itertools::*;

    for (m1, m2, (s1, s2))
    in izip!(&mut [1; 10], &mut [1; 10], [1; 10].iter().tuples()) {
        *m1 = *s1;
        *m2 = *s2; // cannot mutate immutable variable `m2` rust-analyzer (E0384)
    }
}
```

**Comment by Veykril** [comment] 2024-04-02 07:49
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/11681

**Closed by Veykril** 2024-04-02 07:48 UTC
Labels: C-bug
