### ISSUE TITLE
Crashes when parsing enum variants

### ISSUE THREAD

**Issue by wangtz0607** [rust-lang/rust-analyzer#15644] opened 2023-09-21 06:06 UTC
**rust-analyzer version**: 0.3.1665-standalone

**rustc version**: 1.72.1 (d5c2e9c34 2023-09-13)

**relevant settings**: None

![Recording 2023-09-21 at 14 05 07](https://github.com/rust-lang/rust-analyzer/assets/25856391/9b304ba2-fb68-42d3-9f69-b75b965a92d0)

```rust
enum Gender {
    Male,
    Female
}

fn main() {
    Gender::Male;
}
```

```
Panic context:
> 
version: 0.3.1665-standalone
request: textDocument/completion CompletionParams {
    text_document_position: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/home/wtz/Desktop/project/src/main.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 6,
            character: 12,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    context: Some(
        CompletionContext {
            trigger_kind: TriggerCharacter,
            trigger_character: Some(
                ":",
            ),
        },
    ),
}

thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chalk-solve-0.92.0/src/clauses/builtin_traits/fn_family.rs:90:55
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:117:5
   3: chalk_solve::clauses::builtin_traits::fn_family::add_fn_trait_program_clauses
   4: chalk_solve::clauses::builder::ClauseBuilder<I>::push_binders
   5: chalk_solve::clauses::program_clauses_that_could_match
   6: chalk_recursive::solve::SolveIteration::solve_iteration
   7: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
   8: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
   9: hir_ty::traits::solve::{{closure}}
  10: hir_ty::traits::trait_solve_query
  11: salsa::runtime::Runtime::execute_query_implementation
  12: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  13: salsa::derived::slot::Slot<Q,MP>::read
  14: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  15: salsa::QueryTable<Q>::get
  16: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  17: hir_ty::db::trait_solve_wait
  18: <DB as hir_ty::db::HirDatabase>::trait_solve
  19: hir_ty::method_resolution::iterate_method_candidates_dyn
  20: hir::Type::iterate_path_candidates_dyn
  21: hir::Type::iterate_path_candidates
  22: ide_completion::context::CompletionContext::iterate_path_candidates
  23: ide_completion::completions::expr::complete_expr_path
  24: ide_completion::completions::complete_name_ref
  25: ide_completion::completions
  26: std::panicking::try
  27: rust_analyzer::handlers::request::handle_completion
  28: std::panicking::try
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 2:03:29 PM] Request textDocument/completion failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
```

**Comment by Veykril** [comment] 2023-09-21 11:16
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/13531

**Closed by Veykril** 2023-09-21 11:16 UTC
Labels: C-bug
