### ISSUE TITLE
Incorrect inlay type hint when using `itertools::izip!`

### ISSUE THREAD

**Issue by vmalloc** [rust-lang/rust-analyzer#13613] opened 2022-11-13 13:57 UTC
**rust-analyzer version**:  0.3.1277-standalone (d03c1c87d 2022-11-05)
**rustc version**: rustc 1.65.0 (897e37553 2022-11-02)

Below is a code snippet that reproduces the issue:

```rust
use itertools::izip;

fn main() {
    let nums1 = vec![0f64];
    let nums2 = vec![0f64];
    let bools = vec![false];

    let _x =
        izip!(nums1.iter(), nums2.iter(), bools.iter(),).fold(0f64, |res, (num_1, num_2, boolean)| res);
}
```

The above code is processed by RA, but the type inlay hint provided for `boolean` is incorrect:
![Screenshot 2022-11-13 at 15 56 52](https://user-images.githubusercontent.com/28710/201525548-85d00af7-d5bf-413a-9165-c242ebcaadb2.png)

It is deduced as `&f64` whereas it should be deduced as `&bool`

**Comment by lnicola** [comment] 2022-11-13 14:35
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/11681.

**Closed by lnicola** 2022-11-13 14:35 UTC

**Comment by vmalloc** [comment] 2022-11-13 14:40
@lnicola thanks! Sorry for spamming
