### ISSUE TITLE
Missing impls for tuples?

### ISSUE THREAD

**Issue by cynecx** [rust-lang/rust-analyzer#16154] opened 2023-12-18 18:38 UTC
**rust-analyzer version**: [current master 0ed815fa](https://github.com/rust-lang/rust-analyzer/tree/0ed815faca2c408803cb2724c288ca8a2094e58b)

**rustc version**:

```
rustc 1.76.0-nightly (6a6287132 2023-12-17)
binary: rustc
commit-hash: 6a62871320e262661bb1a0ea7f8aec9d3abeddf2
commit-date: 2023-12-17
host: aarch64-apple-darwin
release: 1.76.0-nightly
LLVM version: 17.0.6
```

```rust
trait Boba {
    type Foo;
}

impl<T: Eq + std::hash::Hash> Boba for T {
    type Foo = String;
}

fn test() {
    let a: <(bool, bool) as Boba>::Foo;
    //  ^ currently: <(isize, isize) as Boba>::Foo. This should've been `String`.
    let a: <isize as Boba>::Foo;
    //  ^ currently: String
}
```

I could've sworn that this worked before but I might be wrong.

**Comment by Veykril** [comment] 2023-12-18 21:57
Might've been https://github.com/rust-lang/rust-analyzer/pull/15970? Only thing I can think of that looks relevant and that has been merged recently (assuming this used to work)

**Comment by cynecx** [comment] 2023-12-19 02:03
Okay, I might have imagined things because I can reproduce this with a build from early November 🤷‍♂️.

**Comment by Veykril** [comment] 2023-12-19 09:47
Actually, this isn't a rust-analyzer regression. It's a core library change that trips over r-a https://github.com/rust-lang/rust/pull/117050.

The impl macro makes use of nightly features (surprise surprise ...), and the behavior of those features has changed, which now breaks tuple impls for r-a because the expansion is wrong.

**Closed** 2023-12-20 10:41 UTC
Labels: A-ty, Broken Window, C-bug
