### ISSUE TITLE
Separate goto pattern references and goto constructors references

### ISSUE THREAD

**Issue by zetanumbers** [rust-lang/rust-analyzer#17038] opened 2024-04-09 14:27 UTC
Currently when you execute "goto references" for an enum variant you get a list of references both to usages of this variant as a pattern and as a enum constructor:

```rust
enum Foo {
    Bar(i32), // from there goto references
}

let foo = Foo::Bar(42); // goes there to the constructor

if let Foo::Bar(_) = foo { // and goes there to the pattern
// ...
}
```

There are some common situations, where I would search just for constructions of a variant and have to manually filter through many pattern references instead.

**Comment by Nadrieril** [comment] 2024-05-21 12:45
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/14873

**Closed by Nadrieril** 2024-05-21 12:45 UTC
Labels: C-feature
