### ISSUE TITLE
rust-analyser not working for rustc modules while working on clippy

### ISSUE THREAD

**Issue by akshay1992kalbhor** [rust-lang/rust-analyzer#13364] opened 2022-10-08 08:57 UTC
I want to contribute to clippy but while setting up rust-analyser for the rustc modules I am getting an error. I am using neovim + coc.nvim + rust-analyser. The error says "Connection to server got closed. Server will not be restarted". The rustc source has been set to "discover" in the nvim/coc-settings.json. The Workspace output file has been included. 
[rust-analyser-error.txt](https://github.com/rust-lang/rust-analyzer/files/9738807/rust-analyser-error.txt)

active toolchain
----------------

nightly-2022-10-06-x86_64-apple-darwin (overridden by '/Users/akshaykalbhor/rust-clippy/rust-toolchain')
rustc 1.66.0-nightly (c97d02cdb 2022-10-05)

**Comment by Veykril** [comment] 2022-10-08 09:06
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/13343
which is fixed in the upcoming release

**Closed by Veykril** 2022-10-08 09:06 UTC

**Comment by akshay1992kalbhor** [comment] 2022-10-08 10:33
Thanks for the quick update. Changed my update channel to "nightly" and got the latest version and now its working
