### ISSUE TITLE
Struct tuples cause IntelliSense problems on VSCode

### ISSUE THREAD

**Issue by gruszkakarol** [rust-lang/rust-analyzer#5429] opened 2020-07-18 12:10 UTC
Hello!

VSCode version: 1.46.1
Rust analyzer plugin version: 0.2.240
Active toolchain: nightly-x86_64-unknown-linux-gnu
Code: https://gist.github.com/Sniadekk/a7ee128f6f27805f96eccf26a8efdaec
Screenshots of the problem: https://imgur.com/a/WJCDsgA

I stumbled upon a bug while solving one of the Advent of Code problems.
The Object tuple struct contains `String` and `Option<Box<Object>>` inside.
While working on the `tree_size` function and trying to access the node.1 I have the same IntelliSense as with the node.0 which is a String, but there should be tips for the `Option` type instead.
Seems like the error isn't gone after I reload the VSCode.

I will be more than happy to provide more information to you to reproduce the bug.

Have a great day and thank you for your work.

**Comment by Veykril** [comment] 2022-11-11 12:42
Caused by https://github.com/rust-lang/rust-analyzer/issues/1109 so closing as resolving that willr esolve this issue as well.

**Closed by Veykril** 2022-11-11 12:42 UTC
Labels: S-actionable
