### ISSUE TITLE
Type Inference Failure on Cyclic Associated Types

### ISSUE THREAD

**Issue by ZhennanWu** [rust-lang/rust-analyzer#14174] opened 2023-02-19 06:44 UTC
# Minimal Reproducible Example
```rust
trait A {
    type B: B<A=Self>;
}
trait B {
    type A: A<B=Self>;
}
struct C<T: A> {
    b: T::B
}
fn func<T:A>(c: C<T>) {
    let unknown: T::B = c.b;
}
```
![image](https://user-images.githubusercontent.com/38578020/219933279-63a0363f-ddea-45df-a1fd-df6cf8ed06e9.png)

Breaking the cycle by removing one `Self` bound would solve ths issue.

**rust-analyzer version**: 0.3.1402-standalone

**rustc version**: rustc 1.67.0-nightly (c1a859b25 2022-11-10)

**relevant settings**

**Comment by lowr** [comment] 2023-02-19 07:56
Duplicate of #12897, which is closed but tracked in upstream issue rust-lang/chalk#773.

**Closed by lowr** 2023-02-19 07:56 UTC
Labels: C-bug
