### ISSUE TITLE
type-mismatch Error Misattributed

### ISSUE THREAD

**Issue by kierankasha** [rust-lang/rust-analyzer#14936] opened 2023-05-31 15:06 UTC
**rust-analyzer version**:  0.3.1533-standalone

**rustc version**: rustc 1.67.1

I'm working on a library that includes a function that converts various input data into `String` format. I encountered a type-mismatch error in the VsCode plugin between `&ToString` and any type that is not already `String`/ `&str`. The Quick Fix recommendation is to add a reference. Doing so just perpetuates the error and the suggestion remains the same ad infinitum. Here is a minimal reproducible example where this issue occurs:

```rust
fn main() {
    convert_to_string(&0.02)
}

fn convert_to_string(argument: &dyn ToString) {
    let argument = argument.to_string();
    println!("{argument}");
}
```
![image](https://github.com/rust-lang/rust-analyzer/assets/79289747/e97ba08e-f631-4eeb-b951-9dce7bc620e0)

When I build, run this example, or run clippy on this, no errors are identified by the compiler and I get the output that I want:
![image](https://github.com/rust-lang/rust-analyzer/assets/79289747/cc7514fe-80d8-4a1a-8d9b-b82604c920e6)

What's even stranger is this error was not identified by rust-analyzer yesterday. I tried disabling and re-enabling the plugin, uninstalling and reinstalling the plugin, and reverting to a pre-release version to no success.

**Comment by lnicola** [comment] 2023-05-31 15:19
This is a duplicate of https://github.com/rust-lang/rust-analyzer/issues/11847, an old issue.

**Comment by lowr** [comment] 2023-07-15 12:41
Closing as a duplicate of #11847. Thanks for the report though!

**Closed by lowr** 2023-07-15 12:41 UTC
Labels: C-bug
