### ISSUE TITLE
No completions in vec macro: `let s: Vec<String> = vec![]`

### ISSUE THREAD

**Issue by kzhui125** [rust-lang/rust-analyzer#16667] opened 2024-02-25 06:59 UTC
```rs
fn main() {
    let s: Vec<String> = vec!["1".];
}
```

expect completion: `"1".to_string()`

**rust-analyzer version**: 
rust-analyzer version: 0.3.1850-standalone (68c506fd6 2024-02-19)

**rustc version**:

rustc 1.76.0 (07dca489a 2024-02-04)

**Comment by flodiebold** [comment] 2024-02-25 09:08
Duplicate of #13231

**Closed by flodiebold** 2024-02-25 09:08 UTC
Labels: C-bug
