### ISSUE TITLE
dependencies rebuilding

### ISSUE THREAD

**Issue by amitamitamitamit** [rust-lang/rust-analyzer#16658] opened 2024-02-24 11:28 UTC
**rust-analyzer version**: 0.3.1850-standalone (68c506fd6 2024-02-19)

**rustc version**: rustc 1.76.0 (07dca489a 2024-02-04)

**relevant settings**: on mac, everything is default.

Every time I save a file the extension running full dependencies fetching and building even if nothing changed.

I tried to run cargo check via shell twice and in the second time it didn't rebuild it.
If I am trying to run this from the extension the dependencies getting rebuilt every time.

Cargo.toml

```
[package]
name = "test"  
version = "0.1.0"
edition = "2021"
[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
```

main.rs
```
fn main() {
    println!("Hello, world!");
}
```

**Comment by Young-Flash** [comment] 2024-02-24 11:49
duplicate of https://github.com/rust-lang/rust-analyzer/issues/16640

**Closed by Young-Flash** 2024-02-24 11:49 UTC
Labels: C-bug
