### ISSUE TITLE
Unresolved reference, but compiles anyway.

### ISSUE THREAD

**Issue by bluelightzero** [rust-lang/rust-analyzer#12287] opened 2022-05-17 11:36 UTC
This happened while analyzing example code for vulkano: https://github.com/vulkano-rs/vulkano/blob/v0.28.0/examples/src/bin/image/main.rs

When using clion with the rust plugin, I get this error in the problem checker:

    Unresolved reference: `Format`

It is on any line that is using a format such as this: 

    Format::R8G8B8A8_SRGB

I have the correct use:

    use vulkano::format::Format;

It is unable to pull docs for `Format`, probably because it is auto generated.

Despite incorrectly showing a problem while editing, the code compiles just fine.

**Comment by Rua** [comment] 2022-05-17 11:39
I can confirm this using rust-analyzer with VSCode. It does not autocomplete `Format` when I type `use vulkano::format::` first. When I enter `Format` manually, there is usually no error, but in some rare cases I have seen errors happen there too.

**Comment by flodiebold** [comment] 2022-05-17 11:54
The build scripts take a long time to run, but once everything is finished everything works for me. You need to have `rust-analyzer.cargo.buildScripts.enable` turned on, of course.

@bluelightzero IntelliJ Rust does not use rust-analyzer, so you should report this there.

**Comment by flodiebold** [comment] 2022-05-29 13:32
Closing since it's not reproducible.

**Closed by flodiebold** 2022-05-29 13:32 UTC
