### ISSUE TITLE
vscode use f2 rename has a bug

### ISSUE THREAD

**Issue by fwc-git** [rust-lang/rust-analyzer#12941] opened 2022-08-04 16:28 UTC
![image](https://user-images.githubusercontent.com/52595007/182901598-b2c7cec2-bc1d-4380-8e47-37214519cd98.png)
![image](https://user-images.githubusercontent.com/52595007/182902500-13889241-c652-4883-93dc-8c227f1156c5.png)

change process_in_job name but  has a  not changed

**rust-analyzer version**: v0.4.1157

**rustc version**: (rustc 1.64.0-nightly (23e21bdd2 2022-07-15)

**relevant settings**:

**Comment by lnicola** [comment] 2022-08-04 16:30
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/11296.

**Closed by lnicola** 2022-08-04 16:30 UTC
