### ISSUE TITLE
VSCode Tooltip Hiding/moving on mouseover

### ISSUE THREAD

**Issue by SetheenDev** [rust-lang/rust-analyzer#12713] opened 2022-07-07 14:41 UTC
[discord chatter](https://discordapp.com/channels/273534239310479360/273541522815713281/994611088672948324)
![rust development](https://user-images.githubusercontent.com/93453706/177801193-2442f1bc-991e-46c7-9007-a426f1766a08.gif)

**Comment by Veykril** [comment] 2022-07-07 19:50
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/12436

**Closed as completed by Veykril** 2022-07-07 19:50 UTC
