### ISSUE TITLE
Wrong hint for "Expected 2 arguments, found 1"

### ISSUE THREAD

**Issue by shenhunluo** [rust-lang/rust-analyzer#6390] opened 2020-10-28 07:22 UTC
when:
  use serde::{Serialize, Deserialize};
  use crate::schema::{blog,user,friend};
  use diesel::prelude::*;
  use diesel::result::Error;
  use diesel::{QueryDsl, ExpressionMethods, update};
  use log::debug;
hint: Expected 2 arguments, found 1

**Comment by bjorn3** [comment] 2020-10-28 09:44
What is the code for which there is an error? You only show your imports, not the function call, nor the context around it.

**Comment by martskins** [comment] 2020-10-28 21:22
I'm seeing the same issue with this line:

`let active_signature_index = help.active_signature.unwrap_or(0).max(0) as usize;`

Where `active_signature` is an `Option<i64>`.

Going to definition on that `max` in the code takes me to `std::iter::Iterator::max`, as opposed to `std::cmp::Ord::max`.

**Comment by bjorn3** [comment] 2020-10-28 22:25
What is the type of `help` in reality and according to rust-anayzer?

**Comment by martskins** [comment] 2020-10-28 22:36
```rust
pub struct SignatureHelp {
    pub signatures: Vec<SignatureInformation>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active_signature: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active_parameter: Option<i64>,
}
```

**Comment by bjorn3** [comment] 2020-10-28 22:54
Where and how is `help` defined?

**Comment by martskins** [comment] 2020-10-29 00:07
`let help = SignatureHelp::deserialize(result)?;`

Probably this will be easier if I link the file 😁 

Defined here: https://github.com/autozimu/LanguageClient-neovim/blob/15fd62fad3c0260f63aa904621332ec68c9d7b00/src/language_server_protocol.rs#L1671

Error shows here: https://github.com/autozimu/LanguageClient-neovim/blob/15fd62fad3c0260f63aa904621332ec68c9d7b00/src/language_server_protocol.rs#L1678

**Comment by bjorn3** [comment] 2020-10-29 09:08
Rust-analyzer doesn't seem to recognize that `SignatureHelp` implements `Deserialize` even when enabling proc-macro support.

**Comment by happycoder97** [comment] 2020-11-10 16:53
> I'm seeing the same issue (except it expects 0 arguments and it found 1) with this line:
> 
> `let active_signature_index = help.active_signature.unwrap_or(0).max(0) as usize;`
> 
> Where `active_signature` is an `Option<i64>`.
> 
> Going to definition on that `max` in the code takes me to `std::iter::Iterator::max`, as opposed to `std::cmp::Ord::max`.
> 
> The code compiles and checks just fine, but `rust-analyzer` is sending that error diagnostic.

@martskins I think #6418 and this are related

**Comment by flodiebold** [comment] 2020-11-10 16:56
They're related in that both are wrong method resolutions. The actual reasons may be different.

**Comment by lnicola** [comment] 2021-04-08 10:33
CC #8418 for the `LanguageClient-neovim` problem.

**Comment by flodiebold** [comment] 2022-08-27 09:57
Closing this since we don't have a reproduction for the original report.

**Closed by flodiebold** 2022-08-27 09:57 UTC
Labels: A-ty, S-unactionable
