### ISSUE TITLE
False "unresolved import" error for chrono_tz

### ISSUE THREAD

**Issue by sbrocket** [rust-lang/rust-analyzer#10068] opened 2021-08-28 20:55 UTC
After some time using rust-analyzer in VSCode, I start getting "unresolved import" errors for my `use chrono_tz::Tz;` lines. They go away temporarily if I either "Reload Window" or even if I just "Rust Analyzer: Restart server" and wait for any indexing or checking to finish. I can hover over the `chrono_tz` at that point and get the crate docs, which I believe should mean RA correctly resolved the import?

I've seen the closed #7233, but I already have RA's proc-macro support enabled and the other option mentioned there (`rust-analyzer.cargo.loadOutDirsFromCheck`) no longer exists. I tried also enabling experimental attribute proc-macro support but the same thing happens.

I haven't yet been able to figure out what steps lead to the errors reoccurring after restarting the RA server since I usually notice that it has popped up after editing for a bit, but I'll keep a look out and see if I can gather any other info. 

Version: rust-analyzer version: 996300f4a 2021-08-23 stable

RA options in my settings.json:

```
    "rust-analyzer.updates.askBeforeDownload": false,
    "rust-analyzer.cargo.allFeatures": true,
    "rust-analyzer.rustfmt.extraArgs": [
        "+nightly"
    ],
    "rust-analyzer.cargo.unsetTest": [
        "core",
        "derivative"
    ],
    "rust-analyzer.experimental.procAttrMacros": true,
```

**Comment by jonas-schievink** [comment] 2021-08-28 21:13
Works fine for me. Is `rust-analyzer.cargo.runBuildScripts` enabled (by default, it should be)? Can you post the "Rust Analyzer Client" logs, they should contain the configuration that is actually in use.

**Comment by sbrocket** [comment] 2021-08-28 22:18
Like I mentioned, it works fine for a while and then the errors pop up after some time. It hasn't yet reoccured since I posted this, though I'm not doing any heavy editing at the moment.

Yes, `rust-analyzer.cargo.runBuildScripts` is enabled; the above was all of my RA options (with the addition of `extraEnv` for `RA_LOG` now).

Rust Analyzer Client logs: https://gist.github.com/sbrocket/821b714d32640b0aa6a40b0fb78a81e3

**Comment by lxdlam** [comment] 2021-08-30 19:41
Sames for me when use [ed25519_dalek](https://doc.dalek.rs/ed25519_dalek) package. Just copy any example in package will trigger this issue.

Running rust-analyzer 0.2.727 with VSCode 1.59.1.

**Comment by SevenO2** [comment] 2021-08-30 21:46
I'm also seeing this problem with [angular_units](https://crates.io/crates/angular-units). I've noticed with all of these, the crate name uses '-' (hyphen) while the package name has '_' (underscore)

**Comment by jonas-schievink** [comment] 2021-08-30 21:51
@lxdlam That's https://github.com/rust-analyzer/rust-analyzer/issues/7243

@SevenO2 which imports specifically are unresolved there? The crate is working fine for me

**Comment by SevenO2** [comment] 2021-08-30 22:21
> @SevenO2 which imports specifically are unresolved there? The crate is working fine for me

Oops, I just had to restart the server 🤦

**Comment by Veykril** [comment] 2021-12-14 12:57
Is this still an issue?

**Comment by lavinder** [comment] 2021-12-23 01:28
I had same issue as soon as i referened TZ_VARIANTS, the issue seems to be that documentation is pointing to version 0.4 in cargo.toml but it seems this is defined in version later than that. Once i updated my cargo.toml to use 0.6 version of chrono_tz, the TZ_VARIANTS resolved correctly.

**Comment by jcdc404** [comment] 2021-12-25 12:15
> Is this still an issue?

Yes, still an issue with Ed25519_dalek. Although I'm not sure it's exactly the same. With Ed25519_dalek the error never goes away and it does prevent Intellisense from working correctly. I get a popup window (as I should) if I hover over "use ed25519_dalek", but not if I hover over anything after the ::, just the error message unresolved import.

**Comment by lnicola** [comment] 2021-12-25 12:24
`ed25519_dalek` is tracked in #7243 and possibly some other dupes.

**Comment by flodiebold** [comment] 2022-06-28 17:08
Closing since the original issue is not reproducible.

**Closed by flodiebold** 2022-06-28 17:08 UTC
