### ISSUE TITLE
Feature request: destructure parameter code action/refactor

### ISSUE THREAD

**Issue by adsick** [rust-lang/rust-analyzer#13104] opened 2022-08-24 16:51 UTC
so basically if you have
```rust
struct Vector {
    x: f32,
    y: f32,
    z: f32,
}

fn length(vector: Vector) -> f32 {
    let Vector { x, y, z } = vector;
    (x * x + y * y + z * z).sqrt()
}
```
the line 
```rust
let Vector { x, y, z } = vector;
```
could be auto-generated by performing a code action on `vector` parameter, I think it would be handy for many devs out there so maybe add this functionality to RA?

**Comment by adsick** [comment] 2022-08-24 16:59
upd: it also could be "destructure parameter inplace"... whoa, RA is already capable of it, cool!
I mean this:
```rust
fn length(Vector { x, y, z }: Vector) -> f32 {
    (x * x + y * y + z * z).sqrt()
}
```

**Comment by flodiebold** [comment] 2022-08-24 17:25
Duplicate of #8673 -- note that this already works for tuples, e.g. if you have `fn length(v: (f32, f32, f32))`.

**Closed by flodiebold** 2022-08-24 17:25 UTC
