### ISSUE TITLE
VSCode Extension - Code Foldings will always reopen after VSCode restart

### ISSUE THREAD

**Issue by rtdietrich** [rust-lang/rust-analyzer#16201] opened 2023-12-27 09:49 UTC
When programming, I am used to VSCode remembering which parts of my source code I have hidden via code folding and displaying this status unchanged after a restart of VSCode.

However, as soon as I install the rust-analyzer extension in VSCode (WIN10), this no longer works. When reopening VSCode, you can see for 1/10 of a second that the code is displayed correctly with the closed code foldings, but is then automatically unfolded.

Since I initially assumed this to be the case, I looked in the settings for how to deactivate the unpleasant behavior, but found nothing of the sort.

I therefore assume that this is a bug

**Comment by lnicola** [comment] 2023-12-27 09:52
This matches the behaviour of the Python extension. I think VS Code might remember the folding state only if no language server is available.

**Comment by lnicola** [comment] 2023-12-27 09:57
Duplicate of https://github.com/microsoft/vscode/issues/165266#issuecomment-1302374847.

**Closed by lnicola** 2023-12-27 09:57 UTC
Labels: C-bug
