### ISSUE TITLE
"Expand macros" differs from rustc behavior by reparsing variables

### ISSUE THREAD

**Issue by Kyuuhachi** [rust-lang/rust-analyzer#14179] opened 2023-02-20 01:44 UTC
```rs
macro_rules! test {
	(@aaaa) => { "Yes" };
	(@$t:ty) => { "No" };
	($t:ty) => { test!(@$t) }
}

fn main() {
	let a = test!(aaaa);
	println!("{a}");
}
```

In this example, compiling and running the program will print `No`, but expanding the macro (in this case via [rust-tools.nvim](https://github.com/simrat39/rust-tools.nvim)'s `:RustExpandMacro`) will say `"Yes"`.

I believe that once an argument has been parsed as for example a `:ty` or `:expr`, it it not supposed to be reparsed as an `:ident` or literal token, which seems to be what is happening here.

`rust-analyzer --version` ⇒ rust-analyzer 1 (daa0138e4 2023-01-21)\
`rustc --version` ⇒ rustc 1.69.0-nightly (7aa413d59 2023-02-19)

**Comment by lowr** [comment] 2023-02-20 06:23
Duplicate of #12603.

**Closed by lowr** 2023-02-20 06:23 UTC
Labels: A-macro, C-bug
