### ISSUE TITLE
Import trait not suggested

### ISSUE THREAD

**Issue by tamasfe** [rust-lang/rust-analyzer#16989] opened 2024-04-01 20:33 UTC
**rust-analyzer version**: rust-analyzer version: 0.4.1905-standalone
**rustc version**: rustc 1.76.0 (07dca489a 2024-02-04)

**editor or extension**: vscode

**issue**:

We have an example trait somewhere:

```rs
trait NotInScope {
  fn not_in_scope(&self) {}
}

impl<T> NotInScope for T {}
```

When calling a trait function on a variable (`foo.not_in_scope()`) and the trait is not in scope, import of the trait is not offered anymore. rustc correctly fails with `the following trait is implemented but not in scope; perhaps add a `use` for it: ...`.

**Comment by tamasfe** [comment] 2024-04-01 21:03
The bad commit after a bisect turned out to be c246a930465b32176dcd2f01ece81996606544eb.
I could not produce an MCVE unfortunately, as it only happens in a large-ish private repo with a lot of generated code.

I can only guess what is required to repro:

- generated code that is `include!()`-d
- workspace with path dependencies
- ???

Hopefully now that it is known which commit causes the issue, someone more knowledgeable than me can figure why it causes the issue.

**Comment by tamasfe** [comment] 2024-04-02 18:35
I just checked it out, the structure looks something like this:

```
/
├── completion-here/
│   └── Cargo.toml
├── common/
│   ├── Cargo.toml
│   └── ...
├── proto/
│   ├── Cargo.toml
│   ├── build.rs
│   └── ...
├── proto-derive/
│   └── Cargo.toml
└── Cargo.toml
```

The plot is the following, and contains several twists:

- Code is generated in `proto/build.rs`, the generated code lives in `OUT_DIR` and is included via tonic's [`include_proto`](https://docs.rs/tonic/latest/tonic/macro.include_proto.html).
- The trait itself is generated by a derive macro that lives in `proto-derive` inside the generated code (the only way to hook into tonic's code generation)
- There's yet another trait that is generated by a `macro_rules!` macro in `common` and acts as a wrapper such as `trait Wrapper { type Foo: NotInScope; fn foo(&self) -> Self::Foo; }`, this macro is also used via derive where the other trait was generated, so this wrapper trait is generated by a macro that is generated by a macro inside generated code

The trait is used via the wrapper trait that is bound to a generic type:

```
fn foo<T: Wrapper>(t: T) {
  t.foo().not_in_scope();
         ^^^^^^^^^^^^^
}
```

So there are several layers of macroception as well as generics, I'm not surprised no one else has run into this.

I'll try to get an MCVE sometime this week based on this setup.

**Comment by tamasfe** [comment] 2024-04-07 11:18
I set up an MCVE here: https://github.com/tamasfe/ra-completion-repro/blob/master/crates/completion-here/src/lib.rs

It seems that adding the "wrapper" trait is what breaks completion:

```
pub trait Wrapper {
    type Inner: NotInScope;
    fn inner(&self) -> Self::Inner;
}
```

So far it doesn't seem to matter where this trait is defined, via macro, `include!` or any other means, completion does not seem to work even if it is defined in the same crate.

**Comment by tamasfe** [comment] 2024-05-08 19:48
@Veykril @davidbarsky sorry to bother, it seems my knowledge is rather limited here and I won't have enough time to dive into the issue anytime soon.

Would it be possible to (partially?) revert the changes in the linked commit until this is solved, as the codebase I'm working with relies heavily on the patterns outlied in this issue and we have to maintain a separate older RA version.

**Comment by davidbarsky** [comment] 2024-05-08 21:22
> @Veykril @davidbarsky sorry to bother, it seems my knowledge is rather limited here and I won't have enough time to dive into the issue anytime soon.
> 
> Would it be possible to (partially?) revert the changes in the linked commit until this is solved, as the codebase I'm working with relies heavily on the patterns outlied in this issue and we have to maintain a separate older RA version.

I didn't see your update with the reproduction, sorry! I don't think I will revert it, but I'll work on reproducing it tomorrow.

**Comment by davidbarsky** [comment] 2024-05-08 21:37
If I don't make sufficient progress tomorrow, I can add a config option to disable the filtering I introduced in that PR: is that okay?

**Comment by tamasfe** [comment] 2024-05-08 22:37
> If I don't make sufficient progress tomorrow, I can add a config option to disable the filtering I introduced in that PR: is that okay?

Yeah, thank you, much appreciated!

**Comment by davidbarsky** [comment] 2024-05-17 19:40
Commenting to link to https://github.com/rust-lang/rust-analyzer/pull/16555, since I couldn't find this issue be linked from the PR.

**Comment by davidbarsky** [comment] 2024-05-17 20:38
You may have alluded to this already, but the reproduction can be even more minimal. Writing the following in a single crate:

```rust
pub trait NotInScope {
    fn not_in_scope(&self);
}

pub trait Wrapper {
    type Inner: NotInScope;
    fn inner(&self) -> Self::Inner;
}

pub struct Whatever {
    pub id: i32,
}

impl NotInScope for Whatever {
    fn not_in_scope(&self) {
        todo!()
    }
}
```

...and in another crate, trying to do completions on:

```rust
// No completion here for generic type
fn no_completion<T: Wrapper>(whatever: T) {
    whatever.inner().$0
}
```

...results in no completions. Something about the associated type isn't being recorded in `hir_ty::method_resolution::TraitImpls`. Commenting out [bit of code](https://github.com/rust-lang/rust-analyzer/blob/4da6dbfc246717fd088323439c3b691800f91c00/crates/ide-db/src/imports/import_assets.rs#L536-L560), however, results in completions returning.

**Comment by davidbarsky** [comment] 2024-05-20 16:54
My conclusions is that `TraitImpls` isn't aware of any associated types. I'll see what I can do to make it aware, but if there isn't anything I can do easily, I'll build something atop of https://github.com/rust-lang/rust-analyzer/pull/17252 with a configuration option.

**Comment by flodiebold** [comment] 2024-05-20 17:15
Why would `TraitImpls` need to be aware of associated types?

**Comment by flodiebold** [comment] 2024-05-20 17:19
I think probably the fix rather needs to be to adapt the logic in `import_assets.rs` to not do this filtering for associated types (and placeholder types).

**Comment by flodiebold** [comment] 2024-05-21 08:32
Yeah, if I understand correctly that's because the filtering logic is incorrect for these kinds of receiver types -- it's based on the assumption that the type can only implement traits for which a possibly matching impl exists, but for an associated type it can also implement traits through implied bounds. The assumption also doesn't work for placeholder types, like in this case:
```rust
fn foo<T: SomeTrait>(t: T) { t.<|> }
```
but here it doesn't matter since any such trait will be in scope automatically already, so we don't need to care about it in autoimport.
`TraitImpls` just gives you actual impls. There is no `impl` for the associated type, so it's correct that it returns nothing.

**Comment by davidbarsky** [comment] 2024-05-21 16:23
thanks for the tip! this should fix it: https://github.com/rust-lang/rust-analyzer/pull/17270

**Comment by tamasfe** [comment] 2024-05-21 16:51
Just checked the PR out, works great indeed, thank you!

**Closed** 2024-05-22 20:50 UTC
Labels: C-bug
