### ISSUE TITLE
Offer download and settings to access documentation offline

### ISSUE THREAD

**Issue by Wilker-uwu** [rust-lang/rust-analyzer#14640] opened 2023-04-23 03:35 UTC
hello!

sometimes i won't have internet connection available to program and build things, but the links offered during errors are only accessible online.

![pictured: current behaviour. a mouse cursor pointing at `IteratorRandom` inside a hovering text for `rand::seq`, revealing a URL to `https://rust-random.github.io/rand/rand/rngs/struct.ThreadRng.html`](https://user-images.githubusercontent.com/10854855/233811202-b0a8d435-ce08-48b0-a49d-92114a236e1f.png)

it would be best if instead it calls for a command to execute  `cargo doc --no-deps --package --open ${the_package_name}` on any documentation link clicked, as well as offer downloads for the pages from the [user manual](https://rust-analyzer.github.io/manual.html) to be accessible without internet.

what do you think?

**Comment by lnicola** [comment] 2023-04-24 12:37
Duplicate of #12867, except for the user manual part, which I'm not too keen on because we'd have to bundle all the images with the extension. Please file another issue is that's really important.

**Closed by lnicola** 2023-04-24 12:37 UTC
Labels: C-feature
