### ISSUE TITLE
Autocomplete for functions used as first class objects inappropriately populates parameter list

### ISSUE THREAD

**Issue by alice-i-cecile** [rust-lang/rust-analyzer#13497] opened 2022-10-27 13:57 UTC
**rust-analyzer version**: v0.4.1261

**rustc version**: rustc 1.66.0-nightly (1898c34e9 2022-10-26)

When passing in functions as first-class objects (such as when adding systems in Bevy), we do not want to call them. As a result, brackets or parameter names to be autocompleted.

Small example of this in practice: https://github.com/bevyengine/bevy/blob/latest/examples/hello_world.rs

Tiny example:
```rust
fn accepts_function<F: FnOnce(u8, u8) -> u8>(function: F) {}

fn add(a: u8, b: u8) -> u8 {
    a + b
}

fn main(){
    accepts_function(
}
```

Completing the call to `accepts_function` suggests `add(...)   fn(u8, u8) -> u8`, which fills the parameters inappropriately. If you type the whole function name, it is accepted as an appropriate value with the correct type.

**Comment by Veykril** [comment] 2022-10-27 14:13
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/3148

**Closed by Veykril** 2022-10-27 14:13 UTC
Labels: A-completion, S-actionable

**Comment by alice-i-cecile** [comment] 2022-10-27 15:15
Thanks! I spent a while looking but couldn't find an existing issue.
