### ISSUE TITLE
linkedProjects don't support relative path

### ISSUE THREAD

**Issue by DLillard0** [rust-lang/rust-analyzer#17692] opened 2024-07-25 07:42 UTC
**rust-analyzer version**: 0.3.2045-standalone (4afe0d539 2024-07-21)

**rustc version**: 1.78.0 (9b00956e5 2024-04-29)

**editor or extension**: VSCode
**relevant settings**: None
**repository link (if public, optional)**: [rust-analyzer](https://github.com/rust-lang/rust-analyzer)

**code snippet to reproduce**: 
```rust
{
    "rust-analyzer.linkedProjects": [
        "./packages/core/Cargo.toml"
    ]
}
```
In the past, this kind of relative path was supported, but after the latest update, only absolute paths can be used.

**Comment by lnicola** [comment] 2024-07-25 08:09
Duplicate of #17664.

**Closed by lnicola** 2024-07-25 08:09 UTC
Labels: C-bug
