### ISSUE TITLE
rust-analyzer only error for `{integer}` store to `&dyn Debug`

### ISSUE THREAD

**Issue by A4-Tacks** [rust-lang/rust-analyzer#17730] opened 2024-07-28 10:43 UTC
**rust-analyzer version**: rust-analyzer 1.80.0 (05147895 2024-07-21)

**rustc version**: rustc 1.80.0 (051478957 2024-07-21)

**code snippet to reproduce**: 
```rust
use std::fmt::Debug;

fn main() {
    let x: &dyn Debug = &2;
}
```
`cargo check` 0 errors
ra: `expected &dyn Debug, found &i32 (rust-analyzer E0308)`

**Comment by lnicola** [comment] 2024-07-28 14:24
Duplicate of #11847.

**Closed by lnicola** 2024-07-28 14:24 UTC
Labels: C-bug
