### ISSUE TITLE
Proc macro generating `include!` or `include_str!` is not expanded correctly if including files from the target folder

### ISSUE THREAD

**Issue by tomasol** [rust-lang/rust-analyzer#16343] opened 2024-01-10 15:05 UTC
**rust-analyzer version**: rust-analyzer version: 0.4.1801-standalone
**rustc version**: rustc 1.75.0 (82e1608df 2023-12-21)

Reproducer: https://github.com/tomasol/ra-proc-macro-including-target

I want to use a proc macro which `include!`s some generated rust files from the `target` directory. RA cannot expand the macro properly, but only when the included file resides in the target directory. Needed for fixing [this issue in cargo-component](https://github.com/bytecodealliance/cargo-component/issues/196)

[Comment](https://github.com/bytecodealliance/cargo-component/issues/196#issuecomment-1826256558) from the issue:
> From the output of RA:
> 
> ```
> File with cargo diagnostic not found in VFS: file not found: /Users/peterhuene/demo/target/bindings/proxy/bindings.rs
> ```
> 
> It seems, for whatever reason when loaded in a workspace, the VFS isn't populated with the bindings file, which I think means RA will give it an empty file to the proc-macro, ultimately resulting in an empty bindings macro.

When reproducing the issue there was no difference between the project being part of a workspace or not.

**Comment by Veetaha** [comment] 2024-01-11 00:49
This definitely worked for me in the past, so this must be a regression after some commit in rust-analuzer. I'm sure, because suddenly big percentage of our code that uses code generation in build.rs with `prost` is entirely unanalyzed.

**Comment by Veykril** [comment] 2024-01-11 08:09
Yes this is a known regression (can't find the concrete issue right now) since https://github.com/rust-lang/rust-analyzer/pull/15959

**Comment by lnicola** [comment] 2024-01-11 08:11
#16109

**Comment by Veykril** [comment] 2024-01-11 08:31
That's the one, I thought I left a comment on the issue but I guess I didn't. Closing as duplicate.

**Closed by Veykril** 2024-01-11 08:31 UTC
Labels: C-bug, A-proc-macro
