### ISSUE TITLE
Rust analyzer reports `missing structure fields` when field is an `Option`

### ISSUE THREAD

**Issue by githubsands** [rust-lang/rust-analyzer#14200] opened 2023-02-23 18:34 UTC
<!--
Troubleshooting guide: https://rust-analyzer.github.io/manual.html#troubleshooting
Forum for questions: https://users.rust-lang.org/c/ide/14
'
**1. on-the-fly diagnostics are mostly unimplemented:** 

**rust-analyzer version**: [version from homebrew ](https://formulae.brew.sh/formula/rust-analyzer)

**rustc version**: 1.66.1  
 
`func missing_fields` ([code](
https://github.com/rust-lang/rust-analyzer/blob/27239fbb58a115915ffc1ce65ededc951eb00fd2/crates/ide-diagnostics/src/handlers/missing_fields.rs#L31)) should check if field is wrapped in an `Option` before assuming a field is missing.

**Comment by lnicola** [comment] 2023-02-23 18:37
Dupe of #14201.

**Closed by lnicola** 2023-02-23 18:37 UTC
Labels: C-bug
