### ISSUE TITLE
`include!` macro gives `failed to load file` error

### ISSUE THREAD

**Issue by Barugon** [rust-lang/rust-analyzer#17828] opened 2024-08-07 23:56 UTC
Use of the `include!` macro always gives an error that reads `failed to load file` even though the program builds and runs fine. I believe this started sometime after v0.3.1992.

See this very simple attached project.
[include_values.zip](https://github.com/user-attachments/files/16535755/include_values.zip)

**Comment by eval-exec** [comment] 2024-08-08 09:31
I'm using `rust-analyzer 0.4.2064-standalone`, and I couldn’t reproduce the issue. Could you set the environment variable `export RA_LOG=rust_analyzer=debug` to provide more detailed log information?

**Comment by Veykril** [comment] 2024-08-08 09:35
This issue should be fixed, your r-a v0.3.1992 is a bit old so likely does not yet contain that fix

**Comment by lnicola** [comment] 2024-08-08 09:37
This is a known limitation, we only load Rust files. You can rename the file to `src_values.rs` and it will work fine.

**Closed** 2024-08-08 09:41 UTC
Labels: C-bug

**Comment by Barugon** [comment] 2024-08-08 16:08
> This is a known limitation, we only load Rust files. You can rename the file to `src_values.rs` and it will work fine.

But why? This is not a compiler limitation.

**Comment by 8de2fdb0** [comment] 2025-03-16 00:53
just as a note for everyone coming here:

if the file is outside your crate folder, let's say in a workspace root folder for example rust-analyzer will show the same error.

**Comment by mjohnsonengr** [comment] 2025-03-16 12:23
I have this issue with a generated file;

I see the error in:
`workspace/crates/db/src/lib.rs`

The generated file is in `workspace/target/debug/build`

**Comment by Avi-D-coder** [comment] 2025-03-16 21:23
The above seems to be a rust-analyzer bug, can this get reopened?

**Comment by DennisJensen95** [comment] 2025-04-16 05:15
> I have this issue with a generated file;
> 
> I see the error in: `workspace/crates/db/src/lib.rs`
> 
> The generated file is a `.rs` file in `workspace/target/debug/build`

I am experiencing the same.
