### ISSUE TITLE
RHEL 8 no longer supported?

### ISSUE THREAD

**Issue by dominikwerder** [rust-lang/rust-analyzer#13085] opened 2022-08-22 13:07 UTC
rust-analyzer requires now glibc 2.29, so does that mean rust-analyzer no longer supports RHEL 8 ?

**Comment by lnicola** [comment] 2022-08-22 13:09
Duplicate of #13081

**Closed by lnicola** 2022-08-22 13:09 UTC

**Comment by dominikwerder** [comment] 2022-08-22 13:12
Seeing that #13081 is "closed" as well, does that mean that redhat 8 is not supported by rust-analyzer? Isn't redhat 8 quite widely used?

**Comment by lnicola** [comment] 2022-08-22 13:14
If you read the discussion, you can find an explanation and three workarounds (using `rustup`, installing the `musl` variant or staying on an older version of RA).

**Comment by dominikwerder** [comment] 2022-08-22 13:17
Of course, I see the workarounds, it just got me wonder why it seems to be a no-goal to maintain the good user experience on such a widely used target..

**Comment by lnicola** [comment] 2022-08-22 13:23
The release binaries are built on GitHub. We don't have the infrastructure for cross-compilation set up, and the GHA workflows are already pretty complicated right now. If someone sends a PR for this, we might merge it, but it's probably not going to be a priority otherwise.

We generally avoid adding workarounds for older software versions (we update to new toolchains relatively soon, we don't try to support older releases of Code etc.). Users who need (or want) to keep using older distros have some workarounds, at least.

**Comment by dominikwerder** [comment] 2022-08-22 13:44
Ok, thank you for the explanation!

**Comment by lnicola** [comment] 2022-08-22 13:48
@dominikwerder if you can use a beta toolchain, can you install the [MUSL version](https://github.com/rust-lang/rust-analyzer/releases/download/2022-08-22/rust-analyzer-alpine-x64.vsix) and see if it works for you?

**Comment by bjorn3** [comment] 2022-08-22 14:15
The musl version is dynamically linked, so you need musl libc.so installed locally: https://github.com/rust-lang/rust-analyzer/blob/fdc28b4333c7fccafbb85af7ccddbbf6f96df9a0/.github/workflows/release.yaml#L132

**Comment by dominikwerder** [comment] 2022-08-23 06:08
@lnicola same for [this musl executable](https://github.com/rust-lang/rust-analyzer/releases/download/2022-08-22/rust-analyzer-x86_64-unknown-linux-musl.gz) it's not a static.

The workaround using the RA from nightly seems the easiest so far.
