### ISSUE TITLE
Type mismatch when aliasing Fn trait

### ISSUE THREAD

**Issue by dbofmmbt** [rust-lang/rust-analyzer#13957] opened 2023-01-15 15:07 UTC
In my codebase, when I alias a Fn trait, although rustc compiles it fine, R-A complains about type mismatch:

> expected bool, found <dyn Alias as FnOnce<(bool,)>>::Output

I extracted a short example based on what I implemented:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=75d946a49d2296d3defd525590b366b5

I couldn't find any related issue. It looks like R-A doesn't know that the Output is actually a bool.

rust-analyzer version: 0.3.1361-standalone
rustc: 1.66.1 (90743e729 2023-01-10)

**Comment by lowr** [comment] 2023-01-16 12:27
This is a duplicate of #13169. Chalk has some problems when trait objects interact with supertraits and unfortunately we can only wait for upstream to fix the underlying problem.

**Closed by lowr** 2023-01-16 12:27 UTC
Labels: A-ty, C-bug
