### ISSUE TITLE
Not working at all in mio

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/rust-analyzer#13514] opened 2022-10-29 06:26 UTC
**rust-analyzer version**: 0.3.1258-standalone
**rustc version**: rustc 1.64.0 (a55dd71d5 2022-09-19)

RA not working in [mio](https://github.com/tokio-rs/mio) for some modules. It works fine for most of the library, but almost everything under `src/sys/` and `src/net` doesn't work. (I think it's all platform specific stuff)

**Comment by lnicola** [comment] 2022-10-29 06:29
Does it work for the code specific to your OS?

**Comment by dev-ardi** [comment] 2022-10-29 07:00
No. Nothing works, even types like Result...

**Comment by lnicola** [comment] 2022-10-29 11:52
I think the code is disabled. RA starts working for me in `src/sys/unix/pipe.rs` if I enable `default = ["os-ext"]` in `Cargo.toml`. You can also use `rust-analyzer.cargo.features` for that.

**Comment by lnicola** [comment] 2022-11-08 18:24
@dev-ardi did you try that setting?

**Comment by jonas-schievink** [comment] 2023-01-30 17:22
I've confirmed that the `unix` module works fine while on a Linux host, as long as the `os-ext` feature is enabled (by setting `"rust-analyzer.cargo.features": ["os-ext"]`). The `net` module is behind a different feature though. You can enable all Cargo features by setting `"rust-analyzer.cargo.features": "all"`. On other hosts the target triple also has to be set.

Closing, since this is working as expected. If it still doesn't work for you, please provide more information about your environment.

**Closed by jonas-schievink** 2023-01-30 17:22 UTC
Labels: C-support
