### ISSUE TITLE
No longer possible to insert inlay hints

### ISSUE THREAD

**Issue by mikenunan** [rust-lang/rust-analyzer#15604] opened 2023-09-13 13:36 UTC
Prior to the latest release 2 days ago (0.3.1657 versus 0.3.1649 in Marketplace, or tags [2023-09-11](https://github.com/rust-lang/rust-analyzer/releases/tag/2023-09-11) vs [2023-09-04](https://github.com/rust-lang/rust-analyzer/releases/tag/2023-09-04)), inlay hints carried a "Double-click to insert" capability in VSCode:

![image](https://github.com/rust-lang/rust-analyzer/assets/8653660/ef8b2cfb-7b27-4a58-b155-9355f81ab3b0)

I recognise this had an issue anyway as the default gesture conflicts with code's [hardwired](https://stackoverflow.com/questions/43428264/use-ctrlclick-to-select-word-in-vs-code) `ctrl+click` mapping for go to definition, but the feature was not entirely unusable. The gesture for the inlay insert however _is_ assignable I believe, so could we have the feature back with a non-conflicting binding possibly?

**Comment by Veykril** [comment] 2023-09-13 14:16
Probably regressed with https://github.com/rust-lang/rust-analyzer/pull/15522

**Comment by SomeoneToIgnore** [comment] 2023-09-14 06:39
I can confirm that it's due to resolution, if we stop resolving edits it gets back to normal, this patch fixes it:

```diff
diff --git a/crates/rust-analyzer/src/lsp/to_proto.rs b/crates/rust-analyzer/src/lsp/to_proto.rs
index 23074493a..6943c10ec 100644
--- a/crates/rust-analyzer/src/lsp/to_proto.rs
+++ b/crates/rust-analyzer/src/lsp/to_proto.rs
@@ -446,7 +446,7 @@ pub(crate) fn inlay_hint(
     let needs_resolve = inlay_hint.needs_resolve;
     let (label, tooltip, mut something_to_resolve) =
         inlay_hint_label(snap, fields_to_resolve, needs_resolve, inlay_hint.label)?;
-    let text_edits = if needs_resolve && fields_to_resolve.resolve_text_edits {
+    let text_edits = if false && needs_resolve && fields_to_resolve.resolve_text_edits {
         something_to_resolve |= inlay_hint.text_edit.is_some();
         None
     } else {
```

Now the question is — why VSCode cannot handle resolved edits? It does send us textEdits in the client hit resolve capabilities

```
 resolve_support: Some(
            InlayHintResolveClientCapabilities {
                properties: [
                    "tooltip",
                    "textEdits",
                    "label.tooltip",
                    "label.location",
                    "label.command",
                ],
            },
        ),
```

and edits json that r-a sends back does not contain anything that might get obsolete (in the context of hint resolution, where we just hover on the established hint) :

```
"textEdits":[{"range":{"start":{"line":3,"character":10},"end":{"line":3,"character":10}},"newText":": Vec<String>"}]
```

So I do not see what exactly r-a does wrong, could it be VSCode bug? Would be nice to follow and discuss with them I presume.
As a workaround, we can introduce extra settings to ignore certain client hint resolve capabilities, but does it make any sense? 
Are there better alternatives to solve this?

**Comment by Veykril** [comment] 2023-09-14 07:05
Might very well be a vscode bug. To work around we can just check if the client is vscode instead of adding a setting I think. The LSP initialization should name the client (at least VSCode names itself)

**Comment by mikenunan** [comment] 2023-09-14 17:56
Thanks to you all here for picking this up. Any thoughts around the gesture conflict and whether it can be fixed? Or should I open a separate issue for that once the feature is working again perhaps?

**Comment by SomeoneToIgnore** [comment] 2023-09-19 18:39
Hey @mikenunan , sorry, I have no good understanding of gesture conflict, but can stub the hint resolution the proposed way: https://github.com/rust-lang/rust-analyzer/pull/15635

Double click starts to work after the PR lands, so technically the issue would be closed 🙂 
I would propose to create a separate issue for the conflict itself, if you think it will break eventually, and I am still not sure I follow why would double click stop working later, so more context inside the new issue would be great.

**Closed** 2023-09-19 20:51 UTC
Labels: C-bug, A-inlay-hints
