### ISSUE TITLE
Regression in v0.3.2045

### ISSUE THREAD

**Issue by levino** [rust-lang/rust-analyzer#17681] opened 2024-07-24 08:42 UTC
I am using `rust-analyzer` in vscode with the `rust-analyzer.linkedProjects` feature in the `.vscode/settings.json`. It used to work fine. With `v0.3.2045` I get the "cannot find workspace" error again. I assume that this regression has to do with https://github.com/rust-lang/rust-analyzer/pull/17246. I downgraded to `v0.3.2037` and everything works fine again.

Maybe the behaviour is expected. However I would expect a major release for such a breaking change. Also it would be nice to find some docs on how to configure the project via the `rust-project.json`, as I assume this is how one should configure things in the future.

Thank you for your time.

**Comment by lnicola** [comment] 2024-07-24 09:04
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/17664, there's a potential workaround there.

**Closed by lnicola** 2024-07-24 09:04 UTC
Labels: C-bug

**Comment by levino** [comment] 2024-07-24 09:24
The workaround is
```diff
"rust-analyzer.linkedProjects": [
-        "my-workspace/Cargo.toml",
+        "${workspaceFolder}/my-workspace/Cargo.toml",
]
```
