### ISSUE TITLE
About two IntoIterator Generic param type error

### ISSUE THREAD

**Issue by A4-Tacks** [rust-lang/rust-analyzer#16354] opened 2024-01-12 20:50 UTC
```rust
pub fn assert_equal<T: PartialEq<U> + std::fmt::Debug, U: std::fmt::Debug>(
    a: impl IntoIterator<Item = T>,
    b: impl IntoIterator<Item = U>,
) {
    let (a, b) = (a.into_iter(), b.into_iter());
    let a_size: usize = a.size_hint().0;
    let b_size: usize = b.size_hint().0;
    let mut elems = Vec::with_capacity(usize::min(a_size, b_size));
    for (a, b) in a.zip(b) {
        assert_eq!(a, b, "left != right, elems: {:?}", elems);
        elems.push(a);
    }
}
```
cargo check: 0 errors, 0 warnings
`elems: Vec<{unknown}>`
open doc from `usize::min`, output: `core::iter::traits::iterator::Iterator::min`

**rust-analyzer version**: rust-analyzer 1.77.0-nightly (bf8716f1 2023-12-24)

**rustc version**: rustc 1.77.0-nightly (bf8716f1c 2023-12-24)

**relevant settings**: NONE

**Comment by Austaras** [comment] 2024-02-10 12:03
Possibly duplicate of #15027

**Comment by A4-Tacks** [comment] 2024-02-10 12:41
Possibly duplicate of #10653

**Comment by flodiebold** [comment] 2024-02-15 19:01
It's a duplicate of #10653, yes (there might also be even older reports of this...)

**Closed** 2024-02-15 19:09 UTC
Labels: C-bug
