### ISSUE TITLE
Breakage on Zalgo

### ISSUE THREAD

**Issue by Kixiron** [rust-lang/rust-analyzer#4841] opened 2020-06-11 03:39 UTC
I was writing this totally normal string in a unit test today, and for some reason it really broke RA. It refused to rustfmt (even though `cargo fmt` worked), froze up and wouldn't report errors and flung about a few random red squiggles that wouldn't go away until I restarted VSCode entirely. 

<details>
<summary>The string in question</summary>

where is your utf8 now

</details>

Note that I attempted to shove this into multiple pastebin services, but for *some* reason they all returned 422's, whoops. Since even GitHub decided to do some "editing" of the source string, the only way to perfectly recreate that I can think of is going to https://zalgo.org/ and typing in `where is your utf8 now` (or your preferred string, don't think it really matters) and then cranking up the `Craziness Level` slider on the right all the way up

Edit: It seems that [hastebin works](https://hastebin.com/oyafowaxoc), but is *really* weird, it's almost like this shouldn't be done

**Comment by lnicola** [comment] 2020-06-11 05:28
Do you mean like this?

![image](https://user-images.githubusercontent.com/308347/84348404-81055380-abbd-11ea-91c4-5e0087440848.png)

**Comment by lnicola** [comment] 2020-06-11 05:36
I did get a panic in `LineIndex`, but I'm not able to reproduce it. Might be related to incremental sync.

**Comment by lnicola** [comment] 2021-01-17 13:56
@Kixiron this now works for me, can you please re-test?

**Comment by lnicola** [comment] 2021-01-17 13:56
Actually no, it still happens.

**Comment by lnicola** [comment] 2022-05-25 13:27
I still can:

```
thread '<unnamed>' panicked at 'Bad offset: range 0..52835 offset 52836', /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/rowan-0.15.4/src/cursor.rs:751:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/core/src/panicking.rs:142:14
   2: rowan::cursor::SyntaxNode::token_at_offset
   3: ide::references::find_all_refs
   4: ide::annotations::resolve_annotation
   5: std::panicking::try
   6: ide::Analysis::resolve_annotation
   7: rust_analyzer::handlers::handle_code_lens_resolve
   8: std::panicking::try
   9: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 16:27:34] Request codeLens/resolve failed.
  Message: request handler panicked: Bad offset: range 0..52835 offset 52836
```

**Comment by lnicola** [comment] 2022-05-25 13:32
Uploading zalgo.mp4…

**Comment by lnicola** [comment] 2022-05-25 13:32
https://user-images.githubusercontent.com/308347/170274405-e69e4f44-46cf-4c8c-8084-13ea0d618bd4.mp4

**Comment by lnicola** [comment] 2022-07-08 04:51
Closing in favour of #12718 because it appears to happen even without the Zalgo text.

**Closed by lnicola** 2022-07-08 04:51 UTC
Labels: E-unknown, S-actionable

**Comment by Kixiron** [comment] 2022-07-08 05:33
Are you sure they're the same issue, that one seems centered around codelense and not freezing/crashing

**Comment by lnicola** [comment] 2022-07-08 05:36
Did/does it (still) freeze for you? The problem is that the only way I managed to reproduce this in the last two years was related to a code lens, like in my video above.
