### ISSUE TITLE
VSCode|VSCodium Extension 'rust-lang.rust-analyzer' not found.

### ISSUE THREAD

**Issue by adrianovieira** [rust-lang/rust-analyzer#12750] opened 2022-07-12 23:42 UTC
Hi!

I am trying to install this vscode[^codium] extension 'rust-lang.rust-analyzer', but it is not found.

```bash
$ codium --install-extension rust-lang.rust-analyzer
```

```texinfo
Installing extensions...
Extension 'rust-lang.rust-analyzer' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
Failed Installing Extensions: rust-lang.rust-analyzer
```

But if I download a VSIX release file from this repository it works like a charm.

```bash
$ codium --install-extension ~/Downloads/rust-analyzer-linux-x64.vsix
```

```texinfo
Installing extensions...
(node:33244) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `codium --trace-deprecation ...` to show where the warning was created)
Extension 'rust-analyzer-linux-x64.vsix' was successfully installed.
```

```bash
$ codium --list-extensions --show-versions
```

```texinfo
rust-lang.rust-analyzer@0.3.1123
```

[^codium]: VSCodium https://github.com/VSCodium/vscodium

**Comment by adrianovieira** [comment] 2022-07-13 04:03
Maybe this is an *OpenVSX Gallery* issue. 
So I just opened an issue there https://github.com/eclipse/openvsx/issues/488, too.

**Comment by lnicola** [comment] 2022-07-13 04:17
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/11080.

**Closed by lnicola** 2022-07-13 04:17 UTC
