### ISSUE TITLE
Error due to cyclic deps

### ISSUE THREAD

**Issue by sehz** [rust-lang/rust-analyzer#13009] opened 2022-08-13 04:44 UTC
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

```
rust-analyzer version: 0.3.1162-standalone (634cfe3d7 2022-08-07)
```

**rustc version**: (eg. output of `rustc -V`)
```
rustc -V
rustc 1.63.0 (4b91a6ea7 2022-08-08)
```

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
```

```

Rust analyzer crashes due to loop.  This is from server log
```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /Users/sehyo/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.61/src/lib.rs:214:32
    |
214 | #![cfg_attr(backtrace, feature(backtrace))]
    |                                ^^^^^^^^^


error: aborting due to previous error


For more information about this error, try `rustc --explain E0554`.

error: could not compile `anyhow` due to 2 previous errors


[ERROR project_model::workspace] cyclic deps: fluvio_dataplane_protocol(CrateId(168)) -> fluvio_dataplane_protocol(CrateId(168)), alternative path: fluvio_dataplane_protocol(CrateId(168))
[ERROR project_model::workspace] cyclic deps: fluvio_protocol(CrateId(177)) -> fluvio_protocol(CrateId(177)), alternative path: fluvio_protocol(CrateId(177))
[ERROR project_model::workspace] cyclic deps: fluvio_protocol_derive(CrateId(191)) -> fluvio_protocol(CrateId(177)), alternative path: fluvio_protocol(CrateId(177)) -> fluvio_protocol_derive(CrateId(191))
[ERROR project_model::workspace] cyclic deps: fluvio_storage(CrateId(214)) -> fluvio_storage(CrateId(214)), alternative path: fluvio_storage(CrateId(214))
```

Steps to reproduce:

1.  Clone repo
```
git clone https://github.com/infinyon/fluvio.git
```

2.  Run Rust Analyzer

**Comment by lnicola** [comment] 2022-08-13 04:46
Duplicate of #12973

**Closed by lnicola** 2022-08-13 04:46 UTC
