### ISSUE TITLE
Unable to resolve traits correctly in fns with two IntoIterator type parameters

### ISSUE THREAD

**Issue by TetroGem** [rust-lang/rust-analyzer#16878] opened 2024-03-18 16:31 UTC
**rust-analyzer version**: 0.3.1885-standalone (b6d1887bc 2024-03-17)

**rustc version**: rustc 1.76.0 (07dca489a 2024-02-04)

**relevant settings**: n/a

**repository link (if public, optional)**: n/a

**code snippet to reproduce**: 
```rust
// example trait to reproduce
pub trait Map {
    fn map(&self, x: u32, y: u32) -> Self;
}

impl Map for u32 {
    fn map(&self, x: u32, _y: u32) -> Self {
        x
    }
}

fn main() {
    one_into_iter([1]);
    two_iterators([1].iter(), [1.].iter());
    two_into_iters([1], [1.]);
}

fn one_into_iter(_a: impl IntoIterator<Item = u32>) -> u32 {
    0.map(1, 2) // resolves correctly with one IntoIterator...
}

fn two_iterators<A: Iterator<Item = u32>, B: Iterator<Item = f64>>(_a: A, _b: B) -> u32 {
    0.map(1, 2) // resolves correctly with two Iterators...
}

fn two_into_iters<A: IntoIterator<Item = u32>, B: IntoIterator<Item = f64>>(_a: A, _b: B) -> u32 {
    0.map(1, 2) // with two IntoIterators, doesn't resolve to correct method -- errors...
    // (expected 1 argument, found 2) -- resolving it as Iterator::map, not Map::map
}

```

This only happens if there are two type parameters which are both IntoIterator as far as I've seen, having one IntoIterator or 2+ type parameters of other types both work fine, it's just IntoIterator

**Comment by ShoyuVanilla** [comment] 2024-03-19 03:16
Might be related to trait bounds with associated types. I'll check this few hours later.

**Comment by lnicola** [comment] 2024-03-19 07:01
Duplicate of #10653.

**Closed by lnicola** 2024-03-19 07:01 UTC
Labels: C-bug

**Comment by ShoyuVanilla** [comment] 2024-03-19 08:11
It's sad that the original issue is unactionable 😢
