### ISSUE TITLE
Allow excluding traits from auto-completion

### ISSUE THREAD

**Issue by GyrosOfWar** [rust-lang/rust-analyzer#17922] opened 2024-08-18 09:55 UTC
Some crates (e.g.`owo_colors`) have traits that add a bunch of methods to every type (e.g. [OwoColorize](https://docs.rs/owo-colors/latest/owo_colors/trait.OwoColorize.html)). This can pollute the auto-completions for types quite a lot. An example for a type from `aws_sdk_s3` in VSCode:

![image](https://github.com/user-attachments/assets/c9306810-8cbc-45f2-ad24-0cd44d54a136)

I looked for existing issues and found #7449, which would help, but it would be nice to have a more granular way to do this. I also wouldn't be opposed to try my hand at implementing this myself, but it'd be cool if someone could assess whether this is a feasible issue for a beginner in this codebase (like myself).

**Comment by lnicola** [comment] 2024-08-18 10:28
I think this has a bunch of dupes, including https://github.com/rust-lang/rust-analyzer/issues/17477 and possibly others.

**Comment by lnicola** [comment] 2024-09-02 17:26
Closing as a duplicate of #17477

**Closed** 2024-09-02 17:26 UTC
Labels: A-completion, C-feature
