### ISSUE TITLE
Installing Bun breaks rust-analyser in Tauri projects.

### ISSUE THREAD

**Issue by Dylan-B-D** [rust-lang/rust-analyzer#17382] opened 2024-06-10 19:58 UTC
**rust-analyzer version**: (rust-analyzer version: 0.3.1992-standalone, also tried pre-release)

**rustc version**: rustc 1.78.0

**editor**: VSCode (latest version), Tested with clean reinstall.

**Steps taken to troubleshoot**:
1. Install Bun
2. Open any Tauri project with the rust-analyser extension.
3. Replicated the issue on Windows 10, Windows 11, and Garuda Linux.
4. The issue occurs specifically with Tauri projects, as other Rust projects work with rust-analyser.
5. Running the bun uninstall script does not resolve the issue but causes the error when hovering over Rust code. Before uninstalling rust-analyser showed no errors but would not provide any errors, or information on hover.

**Error Details**:
```
Panic context:

version: 0.4.1991-standalone (b427d460e 2024-06-09)
request: textDocument/inlayHint InlayHintParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/c%3A/.../src/commands/fractals.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 111,
            character: 0,
        },
        end: Position {
            line: 252,
            character: 1,
        },
    },
}

thread 'Worker' panicked at crates\hir\src\semantics.rs:1516:13:

Failed to lookup NAME@7961..7966 in this Semantics.
Make sure to use only query nodes, derived from this instance of Semantics.
root node:   SOURCE_FILE@0..8206
known nodes: SOURCE_FILE@0..140694, SOURCE_FILE@0..8206, MACRO_ITEMS@0..2211

stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:645
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:72
   2: hir::semantics::SemanticsImpl::find_file
   3: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   4: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
   5: ide::inlay_hints::param_name::hints
   6: ide::inlay_hints::hints
   7: ide::inlay_hints::inlay_hints
   8: std::panicking::try
   9: rust_analyzer::handlers::request::handle_inlay_hints
  10: std::panicking::try
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 7:23:12 PM] Request textDocument/inlayHint failed.
  Message: request handler panicked:

Failed to lookup NAME@7961..7966 in this Semantics.
Make sure to use only query nodes, derived from this instance of Semantics.
root node:   SOURCE_FILE@0..8206
known nodes: SOURCE_FILE@0..140694, SOURCE_FILE@0..8206, MACRO_ITEMS@0..2211

  Code: -32603
```
**Additional Information**:
After having issues on both my Garuda and Windows 10 when using rust-analyser specifically in my Tauri projects after testing out Bun, I tried to see if bun would also break rust-analyser on my windows 11 install on my laptop.  
I made sure it worked first, and then as soon as I ran the command to install bun and restarted VSCode rust-analyser no longer did anything. Sometimes it would work for the first item I would hover, but then seem to crash with no error output. After running the Bun uninstall script, it did not fix the issue, but now I got the error message above the after rust-analyser finishes indexing.

I have tried to reinstall VSCode with no extensions, as well as including the line `"rust-analyzer.linkedProjects": ["src-tauri/Cargo.toml",]` in my settings.JSON but nothing seems to fix the issue.

**Comment by hamster0523** [comment] 2024-06-11 01:51
you need downgrade the rust-analyzer version

**Comment by lnicola** [comment] 2024-06-11 04:38
@Dylan-B-D can you try the nightly? This is a dupe of #17376.

**Comment by samrg472** [comment] 2024-06-11 06:55
> @Dylan-B-D can you try the nightly? This is a dupe of #17376.

I have a similar setup (Tauri + Bun) and this issue is fixed for me in the nightly build.

**Closed** 2024-06-11 06:56 UTC
Labels: C-bug

**Comment by Dylan-B-D** [comment] 2024-06-11 14:09
The `v0.3.1995` update to rust-analyser seems to have fixed the issue.
