### ISSUE TITLE
Intellisense created some sort of unknown expression

### ISSUE THREAD

**Issue by eitan07** [rust-lang/rust-analyzer#17330] opened 2024-06-02 13:10 UTC
**rust-analyzer version**: rust-analyzer version: 0.3.1975-standalone (71a816a90 2024-05-26)

**rustc version**: rustc 1.76.0-beta.5 (f732c37b4 2024-01-12)

**editor or extension**: VSCode - ext ver: 0.3.1975

**relevant settings**: none

I know it's not such of a big deal but intellisense suggests a unknown expression in the top of the list.

![image](https://github.com/rust-lang/rust-analyzer/assets/74129652/67f9ee7d-158f-4908-80ec-bd415bbabd3f)

(The 2 digits in the end are varying by the line and parameter location)

**Comment by lnicola** [comment] 2024-06-02 13:59
Duplicate of #15626

**Closed by lnicola** 2024-06-02 13:59 UTC
Labels: C-bug
