### ISSUE TITLE
RA reports "expected &dyn Debug, found &i32", rustc is fine with it

### ISSUE THREAD

**Issue by djc** [rust-lang/rust-analyzer#17997] opened 2024-08-29 10:20 UTC
**rust-analyzer version**: rust-analyzer version: 0.3.2089-standalone (0f7f68dad 2024-08-27)

**rustc version**: rustc 1.80.0 (051478957 2024-07-21)

**editor or extension**: VS Code

**relevant settings**: N/A

**repository link (if public, optional)**: https://github.com/tokio-rs/tracing

**code snippet to reproduce**: 
```rust
struct FmtBitset(u64);

impl fmt::Debug for FmtBitset {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let mut set = f.debug_set();
        for bit in 0..64 {
            // if the `bit`-th bit is set, add it to the debug set
            if self.0 & (1 << bit) != 0 {
                set.entry(&bit);
            }

        }
        set.finish()
    }
}
```

<img width="747" alt="Screenshot 2024-08-29 at 12 20 01" src="https://github.com/user-attachments/assets/877270f2-b8c0-4950-85c4-cd61acf64a00">

**Comment by lnicola** [comment] 2024-08-29 10:22
Duplicate of #11847.

**Closed by lnicola** 2024-08-29 10:22 UTC
Labels: C-bug
