### ISSUE TITLE
thread 'Worker' panicked at 'Bad offset: range 0..923 offset 934'

### ISSUE THREAD

**Issue by antonilol** [rust-lang/rust-analyzer#14637] opened 2023-04-22 13:16 UTC
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
0.3.1463-standalone

**rustc version**: (eg. output of `rustc -V`)
rustc 1.67.1 (d5a82bbd2 2023-02-07)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
None

log:
```
Panic context:
> 
version: 0.3.1463-standalone
request: textDocument/hover HoverParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/antoni/rs/threads/src/main.rs",
            query: None,
            fragment: None,
        },
    },
    position: Position(
        Position {
            line: 38,
            character: 19,
        },
    ),
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
}

thread 'Worker' panicked at 'Bad offset: range 0..923 offset 934', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/rowan-0.15.11/src/cursor.rs:751:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: rowan::cursor::SyntaxNode::token_at_offset
   3: ide::hover::hover
   4: std::panicking::try
   5: rust_analyzer::handlers::handle_hover
   6: std::panicking::try
   7: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 12:15:51 PM] Request textDocument/hover failed.
  Message: request handler panicked: Bad offset: range 0..923 offset 934
  Code: -32603 
```

rust analyzer crashed after using auto format (code oss 'Format Document' option)

code oss version: `code 1.77.3-1`
archlinux

main.rs: (923 bytes, ends on EOL)
```rust
use std::{sync::mpsc, thread, time::Duration};

fn main() {
    let (tx, rx) = mpsc::channel();

    {
        let tx = tx.clone();
        thread::spawn(move || {
            let vals = vec![
                String::from("hi"),
                String::from("from"),
                String::from("the"),
                String::from("thread"),
            ];

            for val in vals {
                tx.send(val).unwrap();
                thread::sleep(Duration::from_secs(1));
            }
        });
    }

    thread::spawn(move || {
        let vals = vec![
            String::from("more"),
            String::from("messages"),
            String::from("for"),
            String::from("you"),
        ];

        for val in vals {
            tx.send(val).unwrap();
            thread::sleep(Duration::from_secs(1));
        }
    });

    for received in rx {
        println!("Got: {}", received);
    }
}
```

**Comment by strideynet** [comment] 2023-05-07 14:56
Also experiencing this on `rustc 1.69.0 (84c898d65 2023-04-16)`

**Comment by MarkSwanson** [comment] 2023-05-08 21:30
Yes, I'm also experiencing the hover panic on latest stable and nightly.
This hover panic occurs in the rust-analyzer stable and pre-release version that are installable from vscode.

**Comment by lnicola** [comment] 2023-05-09 04:50
I can't reproduce the panic reported by @antonilol.

@MarkSwanson (or anyone else) can you bisect this to find when it was introduced in RA?

**Comment by MarkSwanson** [comment] 2023-05-10 14:03
bisect results: v0.3.1506 fails.
v0.3.1498 works fine (hover works great).

**Comment by MarkSwanson** [comment] 2023-05-10 14:07
In case it helps, here's my log:
(Note: the hover function always fails - it doesn't matter if the target fn has comments or not.)

Panic context:
> 
version: 0.3.1506-standalone
request: textDocument/inlayHint InlayHintParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/me/src/pm/project/src/calculations.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 680,
            character: 0,
        },
        end: Position {
            line: 840,
            character: 0,
        },
    },
}

thread 'Worker' panicked at 'invalid offset', lib/line-index/src/lib.rs:148:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:147:5
   3: core::panicking::panic_str
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:131:5
   4: core::option::expect_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/option.rs:2045:5
   5: rust_analyzer::to_proto::position
   6: rust_analyzer::to_proto::location
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   9: core::iter::adapters::try_process
  10: rust_analyzer::to_proto::inlay_hint
  11: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  12: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  13: core::iter::adapters::try_process
  14: rust_analyzer::handlers::request::handle_inlay_hints
  15: std::panicking::try
  16: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 10:04:25 AM] Request textDocument/inlayHint failed.
  Message: request handler panicked: invalid offset
  Code: -32603

**Comment by Veykril** [comment] 2023-05-10 14:25
Does this happen for all hovers for you? Or odes it require a specific setup/file where you could provide a minimal reproduction?

**Comment by MarkSwanson** [comment] 2023-05-10 19:32
Ok, I created a tiny crate that shows the problem. I think small enough to just paste here.
(the hover errors are on: electron_uncertainty_momentum_ev, new, radius (hovering over either 'radius' fails)

STEP_ONE: cargo new --library hover_tmp
STEP_TWO: Cargo.toml
[dependencies]
qd = { version = "0.2.0-alpha", git = "https://github.com/Barandis/qd.git" }
dimensioned = { version = "0.8.0", features = ["oibit"] }
lazy_static = "*"

STEP_THREE: src/calculations.rs
use std::{str::FromStr, f64::consts::PI, ops::{Mul, Sub, Add, Neg}};
use qd::{Quad, qd};
use dimensioned::{
    derived,
    si::{self, Meter, Joule, Unitless}, Dimensioned,
};
use crate::dimensioned::Dimensionless; // so unitless check will work
use crate::consts::*;

pub fn electron_uncertainty_momentum_ev(radius: Meter<Quad>) -> Joule<Quad> {
    // todo: 
    (*HBAR_EV * *LIGHT_SPEED) / (Unitless::new(qd!(2)) * radius)
}

STEP_FOUR: consts.rs
use qd::{Quad, qd};
use dimensioned::{
    derived,
    si::{self, JouleSecond, MeterPerSecond}, Dimensioned,
};
use lazy_static::lazy_static;

lazy_static! {
    pub static ref PLANCK: JouleSecond<Quad> = JouleSecond::new(qd!(6.626068E-34));
    pub static ref HBAR_EV: JouleSecond<Quad> = JouleSecond::new(qd!(6.582_119_569e-16));
    pub static ref LIGHT_SPEED: MeterPerSecond<Quad> = MeterPerSecond::new(qd!(299_792_458));
}

STEP_FIVE: lib.rs
#![allow(unused_imports)]
#![allow(non_snake_case)]
#![allow(clippy::excessive_precision)]
#![recursion_limit = "256"] // for consts.rs

pub mod calculations;
pub mod consts;

#[macro_use]
extern crate dimensioned;

**Comment by androxylo** [comment] 2023-05-12 13:49
```

thread 'Worker' panicked at 'invalid offset', lib/line-index/src/lib.rs:148:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:147:5
   3: core::panicking::panic_str
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:131:5
   4: core::option::expect_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/option.rs:2045:5
   5: rust_analyzer::to_proto::position
   6: rust_analyzer::to_proto::location
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   9: core::iter::adapters::try_process
  10: rust_analyzer::to_proto::inlay_hint
  11: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  12: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  13: core::iter::adapters::try_process
  14: rust_analyzer::handlers::request::handle_inlay_hints
  15: std::panicking::try
  16: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 1:47:51 PM] Request textDocument/inlayHint failed.
  Message: request handler panicked: invalid offset
  Code: -32603 
```
for me

**Comment by xxshady** [comment] 2023-06-01 19:20
@Veykril seems like it was fixed with https://github.com/rust-lang/rust-analyzer/issues/14792 or?

https://github.com/rust-lang/rust-analyzer/assets/54737754/eaf23bca-9776-493d-bd99-359d4c47662f

**Comment by Veykril** [comment] 2023-06-02 04:06
Looks like it, thanks for checking :)

**Closed by Veykril** 2023-06-02 04:06 UTC
Labels: Broken Window, C-bug, I-panic
