### ISSUE TITLE
`some` completion doesn't work in Column Selection Mo

### ISSUE THREAD

**Issue by CGMossa** [rust-lang/rust-analyzer#13710] opened 2022-12-02 20:21 UTC
**rust-analyzer version**: rust-analyzer version: 0.4.1305-standalone (398a71aff 2022-11-29)

**rustc version**: rustc 1.67.0-nightly (c090c6880 2022-12-01)

Using `.some` completion in VSCode doesn't work when you're in Column Selection Mode.
Here is a screenshot:

![image](https://user-images.githubusercontent.com/1063624/205378553-18c198c7-92d2-420b-9f0b-68ca421de259.png)

![image](https://user-images.githubusercontent.com/1063624/205378505-3d12658c-4118-4087-b64c-ee222dcd2de2.png)

Note that the completion does work if done on individual lines.

**Comment by jonas-schievink** [comment] 2022-12-03 03:01
Approximately nothing works if you have multiple cursors, but I think that's often a VS Code bug or LSP limitation

**Comment by flodiebold** [comment] 2022-12-04 10:58
Duplicate of #11841, though it's questionable whether there's anything to do for us.

**Closed by flodiebold** 2022-12-04 10:58 UTC
