### ISSUE TITLE
Rename refactoring in async fn main not function correctly

### ISSUE THREAD

**Issue by c5soft** [rust-lang/rust-analyzer#14172] opened 2023-02-18 04:44 UTC
rust-analyzer version: rust-analyzer version: 0.3.1402
rustc version: rustc 1.67.1 
relevant settings: N/A

Consider following code:
```
#[tokio::main]
async fn main() {
    let word ="world";
    println!("hello {}", word);
}
```
If I'm trying to rename local variable "word" to "word1" in line 3, we expect the variable referenced in line 4 should be renamed, but nothing happened .

code that we expected:
```
#[tokio::main]
async fn main() {
    let word1 ="world";
    println!("hello {}", word1);
}
```
but code that we got:
```
#[tokio::main]
async fn main() {
    let word1 ="world";
    println!("hello {}", word);
}
```

**Comment by Veykril** [comment] 2023-02-18 07:21
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/13388

**Closed by Veykril** 2023-02-18 07:21 UTC
Labels: C-bug
