### ISSUE TITLE
Import completion inserts a local use statement for function parameters on #[cfg(...)] functions

### ISSUE THREAD

**Issue by hasali19** [rust-lang/rust-analyzer#12782] opened 2022-07-17 08:09 UTC
When using the import completion feature on a function parameter where the function has a cfg attribute, ra inserts the use statement within the function body when it should be in the global scope.

![image](https://user-images.githubusercontent.com/10169241/179389678-d391acbd-e389-4ee3-99af-5df3aa9d9807.png)

**rust-analyzer version**: 0.4.1129-standalone (766c5f086 2022-07-16)

**rustc version**: rustc 1.62.0 (a8314ef7d 2022-06-27)

**Comment by lnicola** [comment] 2022-07-17 08:19
This is intentional, in order to avoid putting a `#[cfg]` on the import.

**Comment by hasali19** [comment] 2022-07-17 08:19
That makes sense for completions within the function, but it doesn't work for parameters since they can't see the imports within the body.

**Comment by lnicola** [comment] 2022-07-17 08:20
Yeah, dupe of #9391.

**Closed by lnicola** 2022-07-17 08:20 UTC
